# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-24 22:26
from __future__ import unicode_literals

from django.db import migrations


def set_required_false(apps, schema_editor):
    CustomField = apps.get_model('infrastructure', 'CustomField')
    cfs = CustomField.objects.filter(type='BOOL', required=True)
    cfs.update(required=False)


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0012_resourcepoolvalueset_service'),
    ]

    operations = [
        migrations.RunPython(set_required_false),
    ]
