# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-13 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0016_remove_oracle_ssh_keys_cf'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScheduledTime',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hour', models.IntegerField(choices=[(1, '1:00'), (2, '2:00'), (3, '3:00'), (4, '4:00'), (5, '5:00'), (6, '6:00'), (7, '7:00'), (8, '8:00'), (9, '9:00'), (10, '10:00'), (11, '11:00'), (12, '12:00'), (13, '13:00'), (14, '14:00'), (15, '15:00'), (16, '16:00'), (17, '17:00'), (18, '18:00'), (19, '19:00'), (20, '20:00'), (21, '21:00'), (22, '22:00'), (23, '23:00'), (24, '24:00')])),
                ('day_of_week', models.IntegerField(choices=[(0, 'Monday'), (1, 'Tuesday'), (2, 'Wednesday'), (3, 'Thursday'), (4, 'Friday'), (5, 'Saturday'), (6, 'Sunday')], verbose_name='Day of Week')),
            ],
        ),
        migrations.AddField(
            model_name='server',
            name='power_off_scheduled_times',
            field=models.ManyToManyField(blank=True, help_text='ScheduledTimes at which the Server should be powered off.', related_name='servers_to_power_off', to='infrastructure.ScheduledTime'),
        ),
        migrations.AddField(
            model_name='server',
            name='power_on_scheduled_times',
            field=models.ManyToManyField(blank=True, help_text='ScheduledTimes at which the Server should be powered on.', related_name='servers_to_power_on', to='infrastructure.ScheduledTime'),
        ),
    ]
