# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-07-06 23:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0011_installpodorderitem_custom_field_values'),
        ('infrastructure', '0019_migrate_power_control_modeling'),
    ]

    operations = [
        migrations.CreateModel(
            name='ControlValue',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('custom_field_options', models.ManyToManyField(blank=True, help_text='The options for the dependent field when the control field is set to this value.', to='orders.CustomFieldValue')),
                ('custom_field_value', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='behavior_for_value', to='orders.CustomFieldValue')),
            ],
        ),
        migrations.CreateModel(
            name='FieldDependency',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('maximum', models.DecimalField(blank=True, decimal_places=2, help_text='For string types, the max length. For integers & decimals, the maximum value.  For dates, the maximum number of days from today.', max_digits=10, null=True)),
                ('minimum', models.DecimalField(blank=True, decimal_places=2, help_text='For string types, the min length. For integers & decimals, the maximum value.', max_digits=10, null=True)),
                ('regex', models.CharField(default='', max_length=250)),
                ('controlling_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_dependency_dependent_set', to='infrastructure.CustomField')),
                ('custom_field_options', models.ManyToManyField(blank=True, through='infrastructure.ControlValue', to='orders.CustomFieldValue')),
                ('dependent_field', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='field_dependency_controlling_set', to='infrastructure.CustomField')),
            ],
        ),
        migrations.AddField(
            model_name='controlvalue',
            name='field_dependency',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.FieldDependency'),
        ),
    ]
