# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 14:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0020_auto_20170706_2320'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='placeholder',
            field=models.CharField(blank=True, help_text='May be used to provide a sample of the expected input value. Only available to string or text type parameters.', max_length=255, null=True),
        ),
    ]
