# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 18:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0021_customfield_placeholder'),
    ]

    operations = [
        migrations.AlterField(
            model_name='fielddependency',
            name='minimum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For string types, the min length. For integers & decimals, the minimum value.', max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='resourcepoolvalueset',
            name='applications',
            field=models.ManyToManyField(blank=True, to='externalcontent.Application', verbose_name='Applications'),
        ),
        migrations.AlterField(
            model_name='server',
            name='applications',
            field=models.ManyToManyField(blank=True, to='externalcontent.Application', verbose_name='Applications'),
        ),
        migrations.AlterField(
            model_name='server',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='server',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.UserProfile', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='server',
            name='status',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('DECOM', 'Deleting'), ('HISTORICAL', 'Historical'), ('MODIFY', 'Modifying'), ('PROVFAILED', 'Provision Failed'), ('PROV', 'Provisioning')], default='ACTIVE', help_text='Changing the status is useful if a server gets stuck in the wrong state. Setting status to historical is like deleting a server except that history is retained.', max_length=10, verbose_name='Status'),
        ),
    ]
