# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-09 19:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0023_customfield_allow_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='servernetworkcard',
            name='additional_ips',
            field=models.TextField(blank=True, default=''),
        ),
    ]
