# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 21:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontent', '0005_auto_20170325_1506'),
        ('infrastructure', '0024_servernetworkcard_additional_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='relevant_osfamilies',
            field=models.ManyToManyField(
                related_name='dependent_fields',
                to='externalcontent.OSFamily',
                verbose_name='Relevant OS Families',
                help_text='This parameter will only be shown on forms when the OS Family matches one specified, or any of their children (ie. selecting "Linux" will cover all Linux flavors).',
            ),
        ),
    ]
