# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 16:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0025_customfield_relevant_osfamilies'),
    ]

    operations = [
        migrations.RenameField(
            model_name='server',
            old_name='service',
            new_name='resource',
        ),
    ]
