# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 12:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0025_customfield_relevant_osfamilies'),
    ]

    operations = [
        migrations.AddField(
            model_name='fielddependency',
            name='dependency_type',
            field=models.CharField(choices=[('SHOWHIDE', 'Show/hide'), ('REGENOPTIONS', 'Regenerate Options')], default='SHOWHIDE', max_length=250),
        ),
    ]
