# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 17:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0026_auto_20180108_1634'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resourcepoolvalueset',
            old_name='service',
            new_name='resource',
        ),
    ]
