# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-12 14:44
from __future__ import unicode_literals

from django.db import migrations


def update_cf_descriptions(apps, schema_editor):
    """
    Updating the auto-scaling CFs to reference resources rather than services.
    They aren't entirely out-of-the-box, rather defined in a special
    initialize/cloud_bursting.py, but some customers may have already run that
    and have existing objects that need updating. Update their descriptions here
    so that users don't have to perform that manual step again (even tho doing so
    could make the desired changes instead).
    """
    CustomField = apps.get_model("infrastructure", "CustomField")

    cf_names = ['auto_scaling_config', 'simulated_cpu_load']
    for name in cf_names:
        cf = CustomField.objects.filter(name=name).first()
        if cf:
            cf.description = cf.description.replace(
                'service', 'resource')
            cf.save()


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0027_auto_20180108_1720'),
    ]

    operations = [
        migrations.RunPython(update_cf_descriptions,
                             migrations.RunPython.noop),
    ]
