# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-29 19:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0026_fielddependency_dependency_type'),
        ('infrastructure', '0028_scaling_cfs_update_descriptions_20180112_1444'),
    ]

    operations = [
    ]
