# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-27 18:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0031_add_auto_delete_ebs_volumes_parameter_to_aws_envs_20180328_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='name',
            field=models.CharField(max_length=1024),  # previous length was 55
        ),
    ]
