# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 17:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0034_auto_20180516_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='placeholder',
            field=models.CharField(blank=True, help_text='May be used to provide a sample of the expected input value. Only available to string, password or text type parameters.', max_length=255, null=True),
        ),
    ]
