# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-06 00:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0034_auto_20180516_2007'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatssample',
            name='sample_period',
            field=models.CharField(choices=[('LAST_YEAR', 'last_year'), ('LAST_MONTH', 'last_month'), ('LAST_WEEK', 'last_week'), ('LAST_DAY', 'last_day'), ('LAST_HOUR', 'last_hour')], max_length=30),
        ),
    ]
