# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-06 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0035_auto_20180606_0039'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverstats',
            name='avg_cpu_last_week',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Last week's average CPU utilization (%)"),
        ),
    ]
