# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-19 15:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0036_serverstats_avg_cpu_last_week'),
        ('infrastructure', '0035_auto_20180619_1726'),
    ]

    operations = [
    ]
