# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-25 21:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0037_merge_20180619_1557'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverstats',
            name='avg_disk_last_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Last day's average Disk utilization"),
        ),
        migrations.AddField(
            model_name='serverstats',
            name='avg_disk_last_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Last hour's average Disk utilization"),
        ),
        migrations.AddField(
            model_name='serverstats',
            name='avg_disk_last_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Last month's average Disk utilization"),
        ),
        migrations.AddField(
            model_name='serverstats',
            name='avg_disk_last_week',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Last week's average Disk utilization"),
        ),
        migrations.AddField(
            model_name='serverstats',
            name='avg_disk_last_year',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Last year's average Disk utilization"),
        ),
        migrations.AddField(
            model_name='serverstats',
            name='avg_mem_last_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name='Last 24 hours average Memory utilization (%)'),
        ),
        migrations.AddField(
            model_name='serverstats',
            name='avg_mem_last_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Last hour's average Memory utilization (%)"),
        ),
        migrations.AddField(
            model_name='serverstats',
            name='avg_mem_last_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Last month's average Memory utilization (%)"),
        ),
        migrations.AddField(
            model_name='serverstats',
            name='avg_mem_last_week',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Last week's average Memory utilization (%)"),
        ),
        migrations.AddField(
            model_name='serverstats',
            name='avg_mem_last_year',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=5, null=True, verbose_name="Last year's average Memory utilization (%)"),
        ),
        migrations.AddField(
            model_name='serverstats',
            name='avg_net_last_day',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Last day's average Network utilization"),
        ),
        migrations.AddField(
            model_name='serverstats',
            name='avg_net_last_hour',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Last hour's average Network utilization"),
        ),
        migrations.AddField(
            model_name='serverstats',
            name='avg_net_last_month',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Last month's average Network utilization"),
        ),
        migrations.AddField(
            model_name='serverstats',
            name='avg_net_last_week',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Last week's average Network utilization"),
        ),
        migrations.AddField(
            model_name='serverstats',
            name='avg_net_last_year',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=8, null=True, verbose_name="Last year's average Network utilization"),
        ),
    ]
