# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-03 23:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0038_auto_20180625_2145'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servernetworkcard',
            name='ip',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='servernetworkcard',
            name='private_ip',
            field=models.CharField(blank=True, default='', max_length=50, null=True),
        ),
    ]
