# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-23 10:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0039_auto_20190503_2313'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='type',
            field=models.CharField(choices=[('STR', 'String'), ('INT', 'Integer'), ('IP', 'IP Address'), ('DT', 'Date & Time'), ('TXT', 'Multi-line Text'), ('ETXT', 'Encrypted Text'), ('CODE', 'Code'), ('BOOL', 'Boolean'), ('DEC', 'Decimal'), ('NET', 'Network'), ('PWD', 'Password'), ('TUP', 'Tuple'), ('LDAP', 'LDAPUtility'), ('URL', 'URL'), ('NSXS', 'NSX Scope'), ('NSXE', 'NSX Edge'), ('STOR', 'DiskStorage'), ('FILE', 'Upload File')], max_length=6),
        ),
    ]
