# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-12 17:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containerorchestrators', '0008_auto_20190325_2121'),
        ('infrastructure', '0043_auto_20190702_2254'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='container_orchestrator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='containerorchestrators.ContainerOrchestrator'),
        ),
    ]
