# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-04 20:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0044_environment_container_orchestrator'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='allow_multiple',
            field=models.BooleanField(default=False, verbose_name='Allow multiple values'),
        ),
    ]
