# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-14 23:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0044_environment_container_orchestrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='rate_currency_unit',
            field=models.CharField(default=None, help_text='Ex. ¥, €, £, SEK, CHF, R$, $, etc', max_length=10, null=True),
        ),
    ]
