# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-21 23:43
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0045_environment_rate_currency_unit'),
    ]

    operations = [
        migrations.AlterField(
            model_name='environment',
            name='rate_currency_unit',
            field=models.CharField(default=None, help_text='Ex. JPY, EUR, GBP, SEK, CHF, BRL, USD, etc', max_length=10, null=True),
        ),
    ]
