# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-15 22:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0047_set_env_global_ids_20190919_0941'),
        ('infrastructure', '0045_environment_rate_currency_unit'),
    ]

    operations = [
    ]
