# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-17 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0048_merge_20191015_2227'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfield',
            name='description',
            field=models.TextField(blank=True, help_text='May be used to explain the purpose of a custom field and offer guidance to users.  If set, will be shown on order form and elsewhere in order to improve the user experience.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='label',
            field=models.CharField(max_length=50, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='name',
            field=models.CharField(help_text='Alphanumeric characters, starting with a letter, with optional underscores.', max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='placeholder',
            field=models.CharField(blank=True, help_text='May be used to provide a sample of the expected input value. Only available to string, password or text type parameters.', max_length=255, null=True, verbose_name='Placeholder'),
        ),
        migrations.AlterField(
            model_name='customfield',
            name='type',
            field=models.CharField(choices=[('STR', 'String'), ('INT', 'Integer'), ('IP', 'IP Address'), ('DT', 'Date & Time'), ('TXT', 'Multi-line Text'), ('ETXT', 'Encrypted Text'), ('CODE', 'Code'), ('BOOL', 'Boolean'), ('DEC', 'Decimal'), ('NET', 'Network'), ('PWD', 'Password'), ('TUP', 'Tuple'), ('LDAP', 'LDAPUtility'), ('URL', 'URL'), ('NSXS', 'NSX Scope'), ('NSXE', 'NSX Edge'), ('STOR', 'DiskStorage'), ('FILE', 'File Upload')], max_length=6, verbose_name='Type'),
        ),
    ]
