# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-28 14:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0049_auto_20191017_0101'),
        ('infrastructure', '0046_auto_20191021_2343'),
    ]

    operations = [
    ]
