# Generated by Django 2.2.10 on 2020-01-09 18:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0050_merge_20191028_1439'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverstatssample',
            name='value',
            field=models.BigIntegerField(),
        ),
    ]
