# Generated by Django 2.2.16 on 2021-02-11 14:26

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('infrastructure', '0052_auto_20201019_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='environment',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant'),
        ),
    ]
