# Generated by Django 2.2.16 on 2021-04-07 21:56

import common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0054_auto_20210218_1007'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfield',
            name='global_id',
            field=models.CharField(default=common.mixins.get_global_id_chars, help_text='Identifier that can be used to access this object through the API across instances.', max_length=16, verbose_name='Global ID'),
        ),
    ]
