# Generated by Django 3.2.3 on 2021-08-13 05:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0059_replace_global_key_name_with_key_name_20210630_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='servernetworkcard',
            name='name',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
