# Generated by Django 3.2.3 on 2021-07-21 15:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0040_remove_customfieldvalue_tenant'),
        ('infrastructure', '0059_replace_global_key_name_with_key_name_20210630_1352'),
    ]

    operations = [
        migrations.AddField(
            model_name='disk',
            name='custom_field_values',
            field=models.ManyToManyField(blank=True, to='orders.CustomFieldValue'),
        ),
    ]
