# Generated by Django 3.2.3 on 2021-08-23 00:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0060_disk_custom_field_values'),
        ('infrastructure', '0060_servernetworkcard_name'),
    ]

    operations = [
    ]
