# Generated by Django 3.2.5 on 2021-11-19 13:46

from django.db import migrations, models
from django.conf import settings


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0063_auto_20211104_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='scheduledtime',
            name='timezone',
            field=models.CharField(default=settings.TIME_ZONE, max_length=255),
        ),
    ]
