# Generated by Django 3.2.5 on 2022-01-14 21:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0062_update_internet_max_bandwidth_out_20211213_1835'),
        ('infrastructure', '0064_scheduledtime_timezone'),
    ]

    operations = [
    ]
