# Generated by Django 2.2.10 on 2020-03-02 11:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('ipam', '0006_auto_20191107_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarWindsIPAM',
            fields=[
                ('ipam_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ipam.IPAM')),
            ],
            options={
                'abstract': False,
            },
            bases=('ipam.ipam',),
        ),
    ]
