# Generated by Django 2.2.10 on 2020-03-06 16:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0006_auto_20191107_0049'),
        ('solarwindsipam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarWindsIPAMNetwork',
            fields=[
                ('ipamnetwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ipam.IPAMNetwork')),
                ('subnet_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('ipam.ipamnetwork',),
        ),
    ]
