# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 14:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0003_auto_20160829_2059'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loadbalancer',
            old_name='service',
            new_name='resource',
        ),
    ]
