# Generated by Django 3.2.3 on 2021-09-13 23:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('networks', '0005_auto_20180202_1944'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NetscalerLoadBalancer',
        ),
    ]
