# Generated by Django 3.2.3 on 2021-09-20 22:09

from django.db import migrations


class Migration(migrations.Migration):

    def delete_netscaler_load_balancer_technology(apps, schema_editor):
        netscaler_load_balancer_technology = apps.get_model("networks", "LoadBalancerTechnology")
        netscaler_load_balancer_technology.objects.filter(name="Netscaler").delete()

    dependencies = [
        ('networks', '0006_delete_netscalerloadbalancer'),
    ]

    operations = [
        migrations.RunPython(delete_netscaler_load_balancer_technology,  migrations.RunPython.noop)
    ]
