# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-23 14:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0007_userprofile_recently_viewed_items'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='last_activity_time',
            field=models.DateTimeField(blank=True, help_text='Time stamp of last activity through the CloudBolt UI or API.', null=True),
        ),
    ]
