# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-29 19:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0008_userprofile_last_activity_time'),
    ]

    operations = [
        migrations.CreateModel(
            name='CBPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional. Explain purpose or details about this permission.', null=True)),
            ],
        ),
        migrations.CreateModel(
            name='GroupRoleMembership',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Group')),
                ('profile', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.UserProfile')),
            ],
        ),
        migrations.CreateModel(
            name='Role',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('description', models.TextField(blank=True, help_text='Optional. Explain purpose or details about this role.', null=True)),
                ('permissions', models.ManyToManyField(blank=True, to='accounts.CBPermission')),
            ],
        ),
        migrations.AddField(
            model_name='grouprolemembership',
            name='role',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Role'),
        ),
    ]
