# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-20 00:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0009_auto_20170329_1933'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cbpermission',
            options={'verbose_name': 'Permission'},
        ),
        migrations.AddField(
            model_name='role',
            name='assignable_to_users',
            field=models.BooleanField(default=True),
        ),
    ]
