# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-28 23:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0011_auto_20170428_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='server_actions',
            field=models.ManyToManyField(blank=True, help_text='Server Actions that this role should have permission to run', related_name='roles', to='cbhooks.ServerAction'),
        ),
        migrations.AlterField(
            model_name='role',
            name='service_actions',
            field=models.ManyToManyField(blank=True, help_text='Service Actions that this role should have permission to run', related_name='roles', to='cbhooks.ServiceAction'),
        ),
    ]
