# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-01 19:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_auto_20170428_2320'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='server_actions',
            field=models.ManyToManyField(blank=True, help_text='Server Actions that this role should have permission to run. Note: if this role has the server.all_actions permission, it will override this list.', related_name='roles', to='cbhooks.ServerAction'),
        ),
        migrations.AlterField(
            model_name='role',
            name='service_actions',
            field=models.ManyToManyField(blank=True, help_text='Service Actions that this role should have permission to run. Note: if this role has the service.all_actions permission, it will override this list.', related_name='roles', to='cbhooks.ServiceAction'),
        ),
    ]
