# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-02 22:59
from __future__ import unicode_literals

from django.db import migrations


def add_permission(apps, schema_editor):
    """
    Add the new server.all_actions permission to an existing Server Owners role
    because create_objects doesn't update it.

    This only affects customers who upgraded to  7.2-alpha1 and got a Server
    Owners role without this permissions.
    """
    Role = apps.get_model('accounts', 'Role')
    CBPermission = apps.get_model('accounts', 'CBPermission')

    # Copied from cb_minimal because this runs first so we need to get_or_create
    perm_dict = {'name': 'server.all_actions',
                 'label': 'Run All Server Actions',
                 'description': 'Allows the user to execute any Server Action available on the server'}

    if Role.objects.filter(name='server_owners').exists():
        role = Role.objects.filter(name='server_owners').first()
        perm, _ = CBPermission.objects.get_or_create(name=perm_dict['name'],
                                                     defaults=perm_dict)
        role.permissions.add(perm)
        role.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170501_1903'),
    ]

    operations = [
        migrations.RunPython(add_permission),
    ]
