# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 19:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0013_auto_20170505_0019'),
        ('accounts', '0014_auto_20170502_2259'),
    ]

    operations = [
    ]
