# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-08 17:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0015_merge_20170505_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='approvers',
        ),
        migrations.RemoveField(
            model_name='group',
            name='requestors',
        ),
        migrations.RemoveField(
            model_name='group',
            name='resource_admins',
        ),
        migrations.RemoveField(
            model_name='group',
            name='user_admins',
        ),
        migrations.RemoveField(
            model_name='group',
            name='viewers',
        ),
    ]
