# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0016_remove_old_roles'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='role',
            options={'ordering': ('label',)},
        ),
        migrations.AlterField(
            model_name='role',
            name='label',
            field=models.CharField(help_text='This is what users see. E.g. "QA Tester"', max_length=255),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text='Internal identifier for this role. Names must be unique. E.g. "qa_tester"', max_length=255, unique=True),
        ),
    ]
