# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 21:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_power_schedule_perms'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cbpermission',
            name='description',
            field=models.TextField(blank=True, help_text='Optional. Explain purpose or details about this permission.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='cbpermission',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='cbpermission',
            name='name',
            field=models.CharField(max_length=255, unique=True, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='description',
            field=models.TextField(blank=True, help_text='Optional. Explain purpose or details about this group.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='group',
            name='levels_to_show',
            field=models.IntegerField(blank=True, default=None, help_text="How many levels of ancestors' names to show when this name is shown outside the context of the group hierarchy.", null=True, verbose_name='Levels to show'),
        ),
        migrations.AlterField(
            model_name='group',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='group',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Group', verbose_name='Parent'),
        ),
        migrations.AlterField(
            model_name='group',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.GroupType', verbose_name='Type'),
        ),
        migrations.AlterField(
            model_name='grouptype',
            name='group_type',
            field=models.CharField(max_length=20, verbose_name='Group Type'),
        ),
        migrations.AlterField(
            model_name='role',
            name='label',
            field=models.CharField(help_text="This is what users see. E.g. 'QA Tester'", max_length=255),
        ),
        migrations.AlterField(
            model_name='role',
            name='name',
            field=models.CharField(help_text="Internal identifier for this role. Names must be unique. E.g. 'qa_tester'", max_length=255, unique=True),
        ),
    ]
