# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 18:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20171027_1226'),
        ('accounts', '0020_auto_20171004_2104'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='custom_field_values',
            field=models.ManyToManyField(blank=True, to='orders.CustomFieldValue'),
        ),
    ]
