# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-21 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0021_userprofile_custom_field_values'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='service_actions',
            field=models.ManyToManyField(blank=True, help_text='Service Actions that this role should have permission to run. Note: if this role has the resource.all_actions permission, it will override this list.', related_name='roles', to='cbhooks.ServiceAction'),
        ),
    ]
