# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 12:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0022_auto_20171229_1623'),
        ('accounts', '0023_permissions_and_role_service_to_resource_20171221_1849'),
    ]

    operations = [
    ]
