# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-12 18:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0024_merge_20180111_1234'),
    ]

    operations = [
        migrations.AlterField(
            model_name='role',
            name='service_actions',
            field=models.ManyToManyField(blank=True, help_text='Resource Actions that this role should have permission to run. Note: if this role has the resource.all_actions permission, it will override this list.', related_name='roles', to='cbhooks.ServiceAction'),
        ),
    ]
