# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 11:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0023_userprofile_api_access'),
        ('accounts', '0026_auto_20180115_1337'),
    ]

    operations = [
    ]
