# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-06 20:28
from __future__ import unicode_literals

from django.db import migrations


def add_permissions(apps, schema_editor):
    """
    Add the new resource.view_power_schedule and resource.manage_power_schedule
    permissions to existing default and special roles (Viewer for view only,
    Resource Admin, Resource Owner) because create_objects doesn't update them.
    """
    Role = apps.get_model('accounts', 'Role')
    CBPermission = apps.get_model('accounts', 'CBPermission')

    # Copied from cb_minimal because this runs first so we need to get_or_create
    view_perm_dict = {
        'name': 'resource.view_power_schedule',
        'label': "View Resource's Power Schedule",
        'description': 'Allows the user the see the schedule for recurring '
                       'power control on the resource'
    }
    manage_perm_dict = {
        'name': 'resource.manage_power_schedule',
        'label': "Manage Resource's Power Schedule",
        'description': 'Allows the user the edit the schedule for recurring '
                       'power control on the resource'
    }

    if Role.objects.filter(name__in=['viewer', 'resource_admin', 'resource_owner']).exists():
        view_perm, _ = CBPermission.objects.get_or_create(
            name=view_perm_dict['name'], defaults=view_perm_dict)
        manage_perm, _ = CBPermission.objects.get_or_create(
            name=manage_perm_dict['name'], defaults=manage_perm_dict)

        role_with_view_only = Role.objects.filter(name='viewer').first()
        if role_with_view_only:
            role_with_view_only.permissions.add(view_perm)
            role_with_view_only.save()

        roles_with_both_perms = Role.objects.filter(name__in=['resource_admin',
                                                              'resource_owner'])
        for role in roles_with_both_perms:
            role.permissions.add(view_perm)
            role.permissions.add(manage_perm)
            role.save()


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0027_merge_20180219_1124'),
    ]

    operations = [
        migrations.RunPython(add_permissions,
                             migrations.RunPython.noop),
    ]
