# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-08 12:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0028_fix_role_resource_actions_col_name_20180307_1619'),
        ('accounts', '0028_add_resource_power_schedule_perms'),
    ]

    operations = [
    ]
