# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-21 19:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0029_combine_cb_and_super_admin_20180319_2048'),
        ('accounts', '0029_merge_20180308_1255'),
    ]

    operations = [
    ]
