# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-24 20:06
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0035_globalpreferences_cit_default_owner'),
        ('accounts', '0030_merge_20180321_1947'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExternalUserAttributeMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_attribute', models.CharField(help_text='Attribute name in the external system.', max_length=255)),
                ('cloudbolt_attribute', models.CharField(help_text='Attribute name in CloudBolt.', max_length=255)),
                ('ldap_utility', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.LDAPUtility')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
