# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-25 19:34
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_merge_20180321_1947'),
    ]

    operations = [
        migrations.AddField(
            model_name='grouprolemembership',
            name='group_inherited_from',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='grms_inherited_from', to='accounts.Group'),
        ),
    ]
