# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 13:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_externaluserattributemapping'),
        ('accounts', '0031_grouprolemembership_group_inherited_from'),
    ]

    operations = [
    ]
