# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-29 16:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0033_clean_up_duplicate_grms_20180529_1608'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='grouprolemembership',
            unique_together=set([('group', 'role', 'profile')]),
        ),
    ]
