# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-17 12:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0034_auto_20180529_1631'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='global_viewer',
            field=models.BooleanField(default=False, help_text='A global role that grants the user permission to view, but only view, everything in the UI, with documented exceptions. The user has no edit capabilities unless they are provided by other roles, but may be able to view sensitive information such as user details and portals.'),
        ),
    ]
