# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-14 20:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0037_passwordhistory'),
    ]

    operations = [
        migrations.AddField(
            model_name='group',
            name='approval_groups',
            field=models.ManyToManyField(blank=True, help_text='List of Groups that can approve orders submitted by this Group.', related_name='_group_approval_groups_+', to='accounts.Group', verbose_name='Approval Groups'),
        ),
    ]
