# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-18 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0038_group_approval_groups'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='group',
            name='approval_groups',
        ),
        migrations.AddField(
            model_name='group',
            name='can_approve',
            field=models.ManyToManyField(blank=True, help_text='List of additional Groups whose orders can be approved by this Group.', related_name='approved_by', to='accounts.Group', verbose_name='Group Approval Permission'),
        ),
        migrations.AlterField(
            model_name='group',
            name='allow_auto_approval',
            field=models.BooleanField(default=False, help_text='Approve all orders for this group automatically. If not set, only orders for super admins and users with the order.approve permission will be auto approved. Note: Auto-Approval will override any Approval Actions configured below.', verbose_name='Auto approve all orders'),
        ),
    ]
