# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-05 02:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20190618_2147'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='catalog_viewing_mode',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
