# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-06 19:06
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0040_userprofile_catalog_viewing_mode'),
        ('accounts', '0040_userprofile_view_initial_tour'),
    ]

    operations = [
    ]
