# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-20 20:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0041_userprofile_server_table_columns'),
        ('accounts', '0041_merge_20190806_1906'),
    ]

    operations = [
    ]
