# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-19 22:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0045_set_group_global_ids_20190917_1314'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_answer',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='password_reset_question',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
