# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-26 16:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0046_auto_20190919_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='temp_user_email',
            field=models.EmailField(blank=True, max_length=254, null=True, verbose_name='temporary email address storage'),
        ),
    ]
