# Generated by Django 2.2.12 on 2020-05-26 01:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20200323_1456'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='grouprolemembership',
            options={'ordering': ['id']},
        ),
    ]
