# Generated by Django 2.2.10 on 2020-10-19 17:22

import accounts.models
from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0054_auto_20201019_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='widgets_json',
            field=django_extensions.db.fields.json.JSONField(default=accounts.models.widgets_json_default, help_text='JSON representation of dashboard widgets'),
        ),
    ]
