# Generated by Django 2.2.16 on 2021-02-07 11:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('accounts', '0055_userprofile_widgets_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='user_profiles', to='tenants.Tenant'),
        ),
        migrations.AddField(
            model_name='userprofile',
            name='tenant_roles',
            field=models.ManyToManyField(blank=True, related_name='user_profiles', to='tenants.TenantRole'),
        ),
    ]
