# Generated by Django 2.2.16 on 2021-03-01 23:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0056_auto_20210207_1142'),
        ('accounts', '0056_add_bp_any_group_can_deploy_if_manage_20210225_1434'),
    ]

    operations = [
    ]
