# Generated by Django 2.2.16 on 2021-03-02 17:18

import common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0057_merge_20210301_2303'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='global_id',
            field=models.CharField(default=common.mixins.get_global_id_chars, help_text='Identifier that can be used to access this object through the API across instances.', max_length=16, verbose_name='Global ID'),
        ),
    ]
