# Generated by Django 2.2.16 on 2021-03-12 15:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0059_set_global_id_for_userprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='role',
            name='group_types',
            field=models.ManyToManyField(blank=True, help_text='The Types of Group that this Role should be available to. If not set, the Role will only be available to Groups whose type does not have custom Roles configured.', to='accounts.GroupType'),
        ),
    ]
