# Generated by Django 2.2.16 on 2021-05-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_role_group_types'),
    ]

    operations = [
        migrations.AddField(
            model_name='userprofile',
            name='legal_notice_seen',
            field=models.DateTimeField(blank=True, help_text='Time stamp of when this User (last) saw any configured Legal Notice Text. Used as an indicator of whether they need to see it when the feature is configured to only show once per User.', null=True),
        ),
    ]
