# Generated by Django 3.2.5 on 2021-10-22 00:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_move_workspace_creator_to_super_admin'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='userprofile',
            name='configuration_admin',
        ),
        migrations.RemoveField(
            model_name='userprofile',
            name='workspace_creator',
        ),
    ]
