# Generated by Django 3.2.5 on 2021-11-02 21:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0062_new_delegate_server_owner_role_20211013_2358'),
        ('accounts', '0063_auto_20211022_0010'),
    ]

    operations = [
    ]
