# Generated by Django 3.2.5 on 2021-11-15 22:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0063_alter_userprofile_tenant'),
        ('accounts', '0064_merge_20211102_2159'),
    ]

    operations = [
    ]
