# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-08 18:15
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('externalcontent', '0012_duplicate_osbas_in_multiple_rhs'),
        ('resourcehandlers', '0010_auto_20180523_1626'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCDBaseImage',
            fields=[
                ('osbuildattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='externalcontent.OSBuildAttribute')),
                ('description', models.CharField(max_length=1024)),
                ('total_disk_size', models.DecimalField(blank=True, decimal_places=4, help_text='Total size of all disks on this image in GB', max_digits=10, null=True)),
                ('uuid', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Image',
                'abstract': False,
            },
            bases=('externalcontent.osbuildattribute',),
        ),
        migrations.CreateModel(
            name='VCDHandler',
            fields=[
                ('resourcehandler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resourcehandlers.ResourceHandler')),
                ('networks', models.ManyToManyField(blank=True, to='resourcehandlers.ResourceNetwork')),
                ('os_build_attributes', models.ManyToManyField(blank=True, to='vcloud_director.VCDBaseImage')),
            ],
            options={
                'verbose_name': 'Acropolis resource handler',
                'abstract': False,
            },
            bases=('resourcehandlers.resourcehandler',),
        ),
    ]
