# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-20 22:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0034_auto_20180516_2007'),
        ('vcloud_director', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCDServerInfo',
            fields=[
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='infrastructure.Server')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
