# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-28 23:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloud_director', '0002_vcdserverinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcdbaseimage',
            name='org_uuid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
