# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-03 21:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloud_director', '0003_vcdbaseimage_org_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcdserverinfo',
            name='href',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vcdserverinfo',
            name='mo_ref',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AddField(
            model_name='vcdserverinfo',
            name='org_href',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vcdserverinfo',
            name='vcenter_href',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='vcdserverinfo',
            name='virtual_data_center_href',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
