# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-05 15:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourcehandlers', '0010_auto_20180523_1626'),
        ('orders', '0023_merge_20180529_2028'),
        ('vcloud_director', '0004_auto_20180703_2132'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCDNetwork',
            fields=[
                ('resourcenetwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resourcehandlers.ResourceNetwork')),
                ('orgs_and_vdcs', models.ManyToManyField(blank=True, to='orders.CustomFieldValue')),
            ],
            options={
                'abstract': False,
            },
            bases=('resourcehandlers.resourcenetwork',),
        ),
        migrations.AlterModelOptions(
            name='vcdhandler',
            options={'verbose_name': 'vCloud Director resource handler'},
        ),
        migrations.AlterField(
            model_name='vcdhandler',
            name='networks',
            field=models.ManyToManyField(blank=True, to='vcloud_director.VCDNetwork'),
        ),
    ]
