# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-10 12:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0038_auto_20180625_2145'),
        ('vcloud_director', '0005_auto_20180705_1543'),
    ]

    operations = [
        migrations.CreateModel(
            name='VCDDisk',
            fields=[
                ('disk_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infrastructure.Disk')),
                ('address_on_parent', models.CharField(blank=True, max_length=10, null=True)),
                ('parent_id', models.CharField(blank=True, max_length=10, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('infrastructure.disk',),
        ),
        migrations.CreateModel(
            name='VCDStorageProfile',
            fields=[
                ('diskstorage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infrastructure.DiskStorage')),
                ('href', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('infrastructure.diskstorage',),
        ),
    ]
