# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-12 17:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vcloud_director', '0006_vcddisk_vcdstorageprofile'),
    ]

    operations = [
        migrations.AddField(
            model_name='vcdstorageprofile',
            name='vdc_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='vcdstorageprofile',
            name='vdc_uuid',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
