# Generated by Django 2.2.16 on 2021-06-18 22:39

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('azure_arm', '0052_auto_20210219_1454'),
        ('dataprotection', '0005_set_global_id_for_dataprotection'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureBackupDataProtection',
            fields=[
                ('dataprotection_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dataprotection.DataProtection')),
                ('resourcehandler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azure_arm.AzureARMHandler', verbose_name='Azure Resource Handler')),
            ],
            options={
                'verbose_name': 'Azure Data Protection',
                'abstract': False,
            },
            bases=('dataprotection.dataprotection',),
        ),
    ]
