# Generated by Django 2.2.10 on 2020-03-24 21:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0002_auto_20200323_1755'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmetadata',
            name='job_id',
            field=models.CharField(max_length=36, unique=True),
        ),
    ]
