# Generated by Django 2.2.10 on 2020-03-25 20:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0005_auto_20200324_2252'),
    ]

    operations = [
        migrations.RenameField(
            model_name='jobmetadata',
            old_name='end_time',
            new_name='_end_time',
        ),
        migrations.RenameField(
            model_name='jobmetadata',
            old_name='start_time',
            new_name='_start_time',
        ),
    ]
