# Generated by Django 2.2.10 on 2020-03-25 22:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0006_auto_20200325_2055'),
    ]

    operations = [
        migrations.RenameField(
            model_name='joblog',
            old_name='timestamp',
            new_name='_timestamp',
        ),
    ]
