# Generated by Django 2.2.10 on 2020-03-26 21:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0008_namingjobparameters_job_metadata'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmetadata',
            name='duration',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
