# Generated by Django 2.2.10 on 2020-04-21 22:41

import django.core.validators
from django.db import migrations, models
import driven_apps.common.custom_fields
import driven_apps.common.mixins
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0009_auto_20200326_2153'),
    ]

    operations = [
        migrations.CreateModel(
            name='Endpoint',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', driven_apps.common.custom_fields.LowerCaseCharField(help_text='The type of this endpoint.', max_length=64)),
                ('name', models.CharField(help_text='The user-specified name of this endpoint.', max_length=255)),
                ('host', models.CharField(help_text='The host name or IP address for this endpoint.', max_length=255, validators=[driven_apps.common.validators.HostAddressValidator()])),
                ('port', models.IntegerField(help_text='The port number for this endpoint.', validators=[django.core.validators.MinValueValidator(1), django.core.validators.MaxValueValidator(65535)])),
                ('description', models.TextField(blank=True, default='', help_text='The description text for this endpoint.')),
            ],
            options={
                'verbose_name': 'endpoint',
                'verbose_name_plural': 'endpoints',
                'db_table': 'endpoint',
                'ordering': ['id'],
                'abstract': False,
                'unique_together': {('type', 'name')},
                'index_together': {('type', 'name')},
            },
            bases=(models.Model, driven_apps.common.mixins.RoleBasedHalFilteringMixin),
        ),
    ]
