# Generated by Django 2.2.10 on 2020-04-28 02:27

import django.core.validators
from django.db import migrations, models
import driven_apps.common.custom_fields
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0011_auto_20200423_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='description',
            field=models.TextField(blank=True, default='', help_text='The description text for this endpoint.'),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='name',
            field=models.CharField(help_text='The user-specified name of this endpoint.', max_length=255, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='name'), driven_apps.common.validators.MinLengthValidator(3, True), django.core.validators.RegexValidator('^[0-9A-Za-z_-]*$', 'Must be alphanumeric characters and dashes and/or underscores')]),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='type',
            field=driven_apps.common.custom_fields.LowerCaseCharField(help_text='The type of this endpoint.', max_length=64, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='type'), driven_apps.common.validators.OneOfValidator(['dns'])]),
        ),
    ]
