# Generated by Django 2.2.12 on 2020-05-08 15:29

import django.core.validators
from django.db import migrations, models
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0015_auto_20200506_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='name',
            field=models.CharField(help_text='The user-specified name of this endpoint.', max_length=255, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='name'), driven_apps.common.validators.MinLengthValidator(3, True), django.core.validators.RegexValidator('^[0-9A-Za-z_]*$', 'Must be alphanumeric characters and/or underscores.')]),
        ),
        migrations.AlterField(
            model_name='namingpolicy',
            name='name',
            field=models.CharField(max_length=254, unique=True, validators=[driven_apps.common.validators.not_blank, driven_apps.common.validators.MinLengthValidator(3, True), django.core.validators.RegexValidator('^[0-9A-Za-z_]*$', 'Must be alphanumeric characters and/or underscores.')]),
        ),
        migrations.AlterField(
            model_name='namingsequence',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[driven_apps.common.validators.not_blank, driven_apps.common.validators.MinLengthValidator(3, True), django.core.validators.RegexValidator('^[0-9A-Za-z_]*$', 'Must be alphanumeric characters and/or underscores.')]),
        ),
    ]
