# Generated by Django 2.2.12 on 2020-05-13 00:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0017_auto_20200512_1749'),
        ('validators', '0006_auto_20200511_2011')
    ]

    operations = [
        migrations.AlterField(
            model_name='namingpolicy',
            name='validation_policies',
            field=models.ManyToManyField(blank=True, to='validators.Validator'),
        ),
        migrations.DeleteModel(
            name='ValidationPolicy',
        ),
    ]
