# Generated by Django 2.2.12 on 2020-05-26 20:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20200323_1456'),
        ('naming', '0018_auto_20200513_0003'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmetadata',
            name='workspace',
            field=models.ForeignKey(blank=True, help_text='The workspace in which this job executed', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Group'),
        ),
    ]
