# Generated by Django 2.2.12 on 2020-05-26 20:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0019_jobmetadata_workspace'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmetadata',
            name='job_type',
            field=models.CharField(max_length=1024),
        ),
    ]
