# Generated by Django 2.2.12 on 2020-05-27 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0020_auto_20200526_2041'),
    ]

    operations = [
        migrations.AddField(
            model_name='customname',
            name='job_metadata',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='naming.JobMetadata'),
        ),
        migrations.AddField(
            model_name='customname',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='naming.NamingPolicy'),
        ),
    ]
