# Generated by Django 2.2.12 on 2020-06-02 20:01

from django.db import migrations, models
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0021_auto_20200527_1934'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namingpolicy',
            name='dns_suffix',
            field=models.CharField(blank=True, default='', max_length=253, validators=[driven_apps.common.validators.TemplatableDnsNameValidator(field_name='dns_suffix')]),
        ),
    ]
