# Generated by Django 2.2.12 on 2020-06-03 17:37

from django.db import migrations, models
import driven_apps.common.custom_fields
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0022_auto_20200602_2001'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='name',
            field=models.CharField(help_text='The user-specified name of this endpoint.', max_length=255, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='name'), driven_apps.common.validators.MinLengthValidator(constraint=3, field_name='name', required=True), driven_apps.common.validators.RegexValidator(field_name='name', message='Must be alphanumeric characters and/or underscores.', regex='^[0-9A-Za-z_]*$')]),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='type',
            field=driven_apps.common.custom_fields.LowerCaseCharField(help_text='The type of this endpoint.', max_length=64, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='type'), driven_apps.common.validators.OneOfValidator(allowed_values=['dns'], field_name='type')]),
        ),
        migrations.AlterField(
            model_name='namingpolicy',
            name='name',
            field=models.CharField(max_length=254, unique=True, validators=[driven_apps.common.validators.NotBlankValidator(field_name='name', required=True), driven_apps.common.validators.MinLengthValidator(constraint=3, field_name='name', required=True), driven_apps.common.validators.RegexValidator(field_name='name', message='Must be alphanumeric characters and/or underscores.', regex='^[0-9A-Za-z_]*$')]),
        ),
        migrations.AlterField(
            model_name='namingpolicy',
            name='template',
            field=models.CharField(max_length=1024, validators=[driven_apps.common.validators.NotBlankValidator(field_name='template', required=True)]),
        ),
        migrations.AlterField(
            model_name='namingsequence',
            name='length',
            field=models.IntegerField(blank=True, null=True, validators=[driven_apps.common.validators.MinValueValidator(constraint=1, field_name='length', required=False)]),
        ),
        migrations.AlterField(
            model_name='namingsequence',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[driven_apps.common.validators.NotBlankValidator(field_name='name', required=True), driven_apps.common.validators.MinLengthValidator(constraint=3, field_name='name', required=True), driven_apps.common.validators.RegexValidator(field_name='name', message='Must be alphanumeric characters and/or underscores.', regex='^[0-9A-Za-z_]*$')]),
        ),
        migrations.AlterField(
            model_name='namingsequence',
            name='pad',
            field=models.CharField(blank=True, max_length=1024, null=True, validators=[driven_apps.common.validators.MaxLengthValidator(constraint=1, field_name='pad', required=False)]),
        ),
        migrations.AlterField(
            model_name='namingsequence',
            name='type',
            field=models.CharField(choices=[('BASE8', 'Octal'), ('BASE10', 'Decimal'), ('BASE16', 'Hexadecimal'), ('PATTERN', 'Pattern')], max_length=50, validators=[driven_apps.common.validators.OneOfValidator(allowed_values=('BASE8', 'BASE10', 'BASE16', 'PATTERN'), field_name='type')]),
        ),
    ]
