# Generated by Django 2.2.12 on 2020-06-17 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0023_auto_20200603_1737'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmetadata',
            name='_start_time',
            field=models.DateTimeField(null=True),
        ),
    ]
