# Generated by Django 2.2.12 on 2020-06-26 21:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0008_auto_20200619_1623'),
        ('accounts', '0052_auto_20200526_0144'),
        ('naming', '0025_auto_20200619_1623'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Endpoint',
            new_name='FuseEndpoint',
        ),
    ]
