# Generated by Django 2.2.12 on 2020-06-29 18:09

from django.db import migrations
from django.contrib.contenttypes.models import ContentType

def forwards_func(apps, schema_editor):
    FuseEndpoint = apps.get_model('naming', 'FuseEndpoint')
    DnsEndpoint = apps.get_model('naming', 'DnsEndpoint')
    ContentType = apps.get_model('contenttypes', 'ContentType')
    ctype = ContentType.objects.get_for_model(DnsEndpoint)
    for endpoint in FuseEndpoint.objects.all():
        if endpoint.type is not None and endpoint.type == 'dns':
            qs = DnsEndpoint.objects.filter(pk=endpoint.id)
            if not qs.exists():
                dnsendpoint = DnsEndpoint()
                dnsendpoint.real_type=ctype
                dnsendpoint.id = endpoint.id
                dnsendpoint.workspace = endpoint.workspace
                dnsendpoint.type = endpoint.type
                dnsendpoint.name = endpoint.name
                dnsendpoint.description = endpoint.description
                dnsendpoint.host = endpoint.host
                dnsendpoint.port = endpoint.port
                dnsendpoint.save()

def reverse_func(apps, schema_editor):
    DnsEndpoint = apps.get_model('naming', 'DnsEndpoint')
    FuseEndpoint = apps.get_model('naming', 'FuseEndpoint')
    for dnsendpoint in DnsEndpoint.objects.all():
        if dnsendpoint.type is not None and dnsendpoint.type == 'dns':
            qs = FuseEndpoint.objects.filter(pk=dnsendpoint.id)
            if not qs.exists():
                endpoint = FuseEndpoint()
                endpoint.id = dnsendpoint.id
                endpoint.workspace = dnsendpoint.workspace
                endpoint.type = dnsendpoint.type
                endpoint.name = dnsendpoint.name
                endpoint.description = dnsendpoint.description
                endpoint.host = dnsendpoint.host
                endpoint.port = dnsendpoint.port
                endpoint.save()

class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0027_auto_20200629_1543'),
    ]

    operations = [
        migrations.RunPython(forwards_func, reverse_func),
    ]
