# Generated by Django 2.2.12 on 2020-06-30 05:57

from django.db import migrations, models
import django.db.models.deletion
import driven_apps.common.custom_fields
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0029_delete_fuseendpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='endpoint',
            name='type',
            field=driven_apps.common.custom_fields.LowerCaseCharField(help_text='The type of this endpoint.', max_length=64, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='type')]),
        ),
        migrations.AlterField(
            model_name='endpoint',
            name='workspace',
            field=models.ForeignKey(help_text='Workspace URL', on_delete=django.db.models.deletion.PROTECT, to='accounts.Group'),
        ),
    ]
