# Generated by Django 2.2.12 on 2020-06-30 15:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_auto_20200626_2246'),
        ('naming', '0030_auto_20200630_0557'),
    ]

    operations = [
        migrations.AddField(
            model_name='vra8endpoint',
            name='credential',
            field=models.ForeignKey(help_text='Credential for this endpoint.', on_delete=django.db.models.deletion.PROTECT, to='credentials.ModuleCredential'),
        ),
    ]
