# Generated by Django 2.2.10 on 2020-07-13 16:19

from django.db import migrations, models
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0033_microsoftendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='vra8endpoint',
            name='vra_single_threaded',
            field=models.BooleanField(default=False, help_text='Enable single-threaded operation for this endpoint.'),
        ),
        migrations.AlterField(
            model_name='vra8endpoint',
            name='vra_organization_name',
            field=models.CharField(default='default', help_text='The vRA organization name for this endpoint.', max_length=256, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='vraOrganizationName'), driven_apps.common.validators.MinLengthValidator(constraint=1, field_name='vraOrganizationName', required=True)]),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='vra8endpoint',
            name='vra_version',
            field=models.CharField(default='8.1', help_text='The vRA version for this endpoint.', max_length=32, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='vraVersion'), driven_apps.common.validators.MinLengthValidator(constraint=1, field_name='vraVersion', required=True)]),
            preserve_default=False,
        ),
    ]
