# Generated by Django 2.2.10 on 2020-07-13 21:24

from django.db import migrations, models
import django.db.models.deletion
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_auto_20200626_2246'),
        ('naming', '0034_auto_20200713_1619'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vra7Endpoint',
            fields=[
                ('endpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='naming.Endpoint')),
                ('host', models.CharField(help_text='The host name or IP address for this endpoint.', max_length=255, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='host'), driven_apps.common.validators.HostAddressValidator(field_name='host')])),
                ('port', models.IntegerField(help_text='The port number for this endpoint.', validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='port'), driven_apps.common.validators.IntegerRangeValidator(1, 65535, field_name='port')])),
                ('ssl', models.BooleanField(default=False, help_text='Flag to enable SSL for this endpoint.')),
                ('vra_version', models.CharField(help_text='The vRA version for this endpoint.', max_length=32, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='vraVersion'), driven_apps.common.validators.MinLengthValidator(constraint=1, field_name='vraVersion', required=True)])),
                ('vra_tenant_name', models.CharField(help_text='The vRA tenant name for this endpoint.', max_length=256, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='vraTenantName'), driven_apps.common.validators.MinLengthValidator(constraint=1, field_name='vraTenantName', required=True)])),
                ('vra_single_threaded', models.BooleanField(default=False, help_text='Enable single-threaded operation for this endpoint.')),
                ('credential', models.ForeignKey(help_text='Credential for this endpoint.', on_delete=django.db.models.deletion.PROTECT, to='credentials.ModuleCredential')),
            ],
            options={
                'db_table': 'endpoints_vra7',
                'ordering': ['id'],
                'abstract': False,
            },
            bases=('naming.endpoint', models.Model),
        ),
    ]
