# Generated by Django 2.2.10 on 2020-07-15 22:10

from django.db import migrations, models
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0035_vra7endpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vra7endpoint',
            name='vra_tenant_name',
        ),
        migrations.AlterField(
            model_name='vra7endpoint',
            name='vra_version',
            field=models.CharField(help_text='The vRA version for this endpoint.', max_length=32, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='vraVersion'), driven_apps.common.validators.MinLengthValidator(constraint=1, field_name='vraVersion', required=True), driven_apps.common.validators.OneOfValidator(allowed_values=['7.6'], field_name='vraVersion')]),
        ),
        migrations.AlterField(
            model_name='vra8endpoint',
            name='vra_version',
            field=models.CharField(help_text='The vRA version for this endpoint.', max_length=32, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='vraVersion'), driven_apps.common.validators.MinLengthValidator(constraint=1, field_name='vraVersion', required=True), driven_apps.common.validators.OneOfValidator(allowed_values=['8.1'], field_name='vraVersion')]),
        ),
    ]
