# Generated by Django 2.2.10 on 2020-07-21 21:21

from django.db import migrations, models
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0036_auto_20200715_2210'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsoftendpoint',
            name='ssl',
            field=models.BooleanField(default=False, help_text='Flag to enable SSL for this endpoint.', validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='ssl'), driven_apps.common.validators.BooleanFieldValidator(field_name='ssl')]),
        ),
        migrations.AlterField(
            model_name='vra7endpoint',
            name='ssl',
            field=models.BooleanField(default=False, help_text='Flag to enable SSL for this endpoint.', validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='ssl'), driven_apps.common.validators.BooleanFieldValidator(field_name='ssl')]),
        ),
        migrations.AlterField(
            model_name='vra7endpoint',
            name='vra_single_threaded',
            field=models.BooleanField(default=False, help_text='Enable single-threaded operation for this endpoint.', validators=[driven_apps.common.validators.BooleanFieldValidator(field_name='vraSingleThreaded')]),
        ),
        migrations.AlterField(
            model_name='vra8endpoint',
            name='ssl',
            field=models.BooleanField(default=False, help_text='Flag to enable SSL for this endpoint.', validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='ssl'), driven_apps.common.validators.BooleanFieldValidator(field_name='ssl')]),
        ),
        migrations.AlterField(
            model_name='vra8endpoint',
            name='vra_single_threaded',
            field=models.BooleanField(default=False, help_text='Enable single-threaded operation for this endpoint.', validators=[driven_apps.common.validators.BooleanFieldValidator(field_name='vraSingleThreaded')]),
        ),
    ]
