# Generated by Django 2.2.10 on 2020-07-23 20:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0037_auto_20200721_2121'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='customname',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Custom Names'},
        ),
    ]
