# Generated by Django 2.2.10 on 2020-07-27 16:24

from django.db import migrations, models
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0038_auto_20200723_2010'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namingpolicy',
            name='dns_suffix',
            field=models.CharField(blank=True, default='', max_length=253, validators=[driven_apps.common.validators.TemplatableDnsNameValidator(field_name='dnsSuffix')]),
        ),
    ]
