# Generated by Django 2.2.10 on 2020-08-12 16:18

from django.db import migrations, models
import django.db.models.deletion
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_auto_20200626_2246'),
        ('naming', '0039_auto_20200727_1624'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vra7endpoint',
            name='vra_single_threaded',
        ),
        migrations.RemoveField(
            model_name='vra8endpoint',
            name='vra_single_threaded',
        ),
        migrations.AddField(
            model_name='endpoint',
            name='single_threaded',
            field=models.BooleanField(default=False, help_text='Enable single-threaded operation for this endpoint.', validators=[driven_apps.common.validators.BooleanFieldValidator(field_name='singleThreaded')]),
        ),
        migrations.CreateModel(
            name='InfobloxEndpoint',
            fields=[
                ('endpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='naming.Endpoint')),
                ('host', models.CharField(help_text='The host name or IP address for this endpoint.', max_length=255, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='host'), driven_apps.common.validators.HostAddressValidator(field_name='host')])),
                ('port', models.IntegerField(help_text='The port number for this endpoint.', validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='port'), driven_apps.common.validators.IntegerRangeValidator(1, 65535, field_name='port')])),
                ('ssl', models.BooleanField(default=False, help_text='Flag to enable SSL for this endpoint.', validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='ssl'), driven_apps.common.validators.BooleanFieldValidator(field_name='ssl')])),
                ('infoblox_version', models.CharField(help_text='The Infoblox version for this endpoint.', max_length=32, null=True)),
                ('credential', models.ForeignKey(help_text='Credential for this endpoint.', on_delete=django.db.models.deletion.PROTECT, to='credentials.ModuleCredential')),
            ],
            options={
                'db_table': 'endpoints_infoblox',
                'ordering': ['id'],
                'abstract': False,
            },
            bases=('naming.endpoint', models.Model),
        ),
    ]
