# Generated by Django 2.2.10 on 2020-08-03 20:52

from django.db import migrations

def rename_source(apps, schema_editor):
    JobMetadata = apps.get_model('naming', 'JobMetadata')
    for entry in JobMetadata.objects.all():
        if entry.source is not None and entry.source == 'vRA7 Plug-in':
            entry.source = 'vRealize Automation 7 Plug-in'
        if entry.source is not None and entry.source == 'vRA8 Plug-in':
            entry.source = 'vRealize Automation 8 Plug-in'

        entry.save()

class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0039_auto_20200727_1624'),
    ]

    operations = [
        migrations.RunPython(rename_source),
    ]
