# Generated by Django 2.2.10 on 2020-08-14 17:14

from django.db import migrations, models
import django.db.models.deletion
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_auto_20200626_2246'),
        ('naming', '0040_auto_20200812_1618'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueCatEndpoint',
            fields=[
                ('endpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='naming.Endpoint')),
                ('host', models.CharField(help_text='The host name or IP address for this endpoint.', max_length=255, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='host'), driven_apps.common.validators.HostAddressValidator(field_name='host')])),
                ('port', models.IntegerField(help_text='The port number for this endpoint.', validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='port'), driven_apps.common.validators.IntegerRangeValidator(1, 65535, field_name='port')])),
                ('ssl', models.BooleanField(default=False, help_text='Flag to enable SSL for this endpoint.', validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='ssl'), driven_apps.common.validators.BooleanFieldValidator(field_name='ssl')])),
                ('bluecat_version', models.CharField(help_text='The BlueCat version for this endpoint.', max_length=32, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='bluecatVersion'), driven_apps.common.validators.MinLengthValidator(constraint=1, field_name='bluecatVersion', required=True), driven_apps.common.validators.OneOfValidator(allowed_values=['9.0'], field_name='bluecatVersion')])),
                ('configuration_name', models.CharField(help_text='BlueCat configuration context.', max_length=255)),
                ('credential', models.ForeignKey(help_text='Credential for this endpoint.', on_delete=django.db.models.deletion.PROTECT, to='credentials.ModuleCredential')),
            ],
            options={
                'db_table': 'endpoints_bluecat',
                'ordering': ['id'],
                'abstract': False,
            },
            bases=('naming.endpoint', models.Model),
        ),
    ]
