# Generated by Django 2.2.10 on 2020-08-19 16:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0040_auto_20200803_2052'),
        ('naming', '0041_bluecatendpoint'),
    ]

    operations = [
    ]
