# Generated by Django 2.2.10 on 2020-08-27 18:57

import common.fields
from django.db import migrations
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0043_menandmiceendpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namingpolicy',
            name='dns_suffix',
            field=common.fields.TemplatableField(blank=True, default='', max_length=65536, validators=[driven_apps.common.validators.TemplatableDnsNameValidator(field_name='dnsSuffix')]),
        ),
        migrations.AlterField(
            model_name='namingpolicy',
            name='template',
            field=common.fields.TemplatableField(max_length=65536, validators=[driven_apps.common.validators.NotBlankValidator(field_name='template', required=True)]),
        ),
        migrations.AlterField(
            model_name='namingsequence',
            name='unique_key',
            field=common.fields.TemplatableField(blank=True, max_length=65536, null=True),
        ),
    ]
