# Generated by Django 2.2.10 on 2020-08-26 17:37

from django.db import migrations, models
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0043_menandmiceendpoint'),
    ]

    operations = [
        migrations.AddField(
            model_name='infobloxendpoint',
            name='a_record_template',
            field=models.TextField(default='{"name":"{{request.hostname}}","ipv4addr":"{{request.ipaddress}}","view":"{{endpoint.dnsView}}","comment":"Created by OneFuseExtensibility Module"}', help_text='(Templatable) A Record Template', validators=[driven_apps.common.validators.StringFieldValidator(blank=True, field_name='aRecordTemplate', template=True)]),
        ),
        migrations.AddField(
            model_name='infobloxendpoint',
            name='dns_view',
            field=models.TextField(default='default', help_text='(Templatable) DNS View.', validators=[driven_apps.common.validators.StringFieldValidator(blank=False, field_name='dnsView', template=True)]),
        ),
        migrations.AddField(
            model_name='infobloxendpoint',
            name='host_record_template',
            field=models.TextField(default='{"name":"{{request.hostname}}","view":"{{endpoint.dnsView}}","comment":"Created by OneFuseExtensibility Module","ipv4addrs":[{"ipv4addr":"{{ request.ipaddress }}"}]}', help_text='(Templatable) Host Record Template', validators=[driven_apps.common.validators.StringFieldValidator(blank=True, field_name='hostRecordTemplate', template=True)]),
        ),
        migrations.AddField(
            model_name='infobloxendpoint',
            name='ptr_record_template',
            field=models.TextField(default='{"name":"{{request.hostname}}","ptrdname":"{{request.hostname}}","ipv4addr":"{{request.ipaddress}}","view":"{{endpoint.dnsView}}","comment":"Created by OneFuseExtensibility Module"}', help_text='(Templatable) Ptr Record Template', validators=[driven_apps.common.validators.StringFieldValidator(blank=True, field_name='ptrRecordTemplate', template=True)]),
        ),
        migrations.AlterField(
            model_name='infobloxendpoint',
            name='infoblox_version',
            field=models.CharField(default='8.5', help_text='The Infoblox version for this endpoint.', max_length=32),
        ),
    ]
