# Generated by Django 2.2.10 on 2020-09-01 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0044_auto_20200827_1857'),
        ('naming', '0044_auto_20200826_1737'),
    ]

    operations = [
    ]
