# Generated by Django 2.2.10 on 2020-09-04 18:34

import common.fields
from django.db import migrations
import driven_apps.common.validators
import driven_apps.naming.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0045_merge_20200901_1738'),
    ]

    operations = [
        migrations.AddField(
            model_name='infobloxendpoint',
            name='fixed_address_record_template',
            field=common.fields.TemplatableField(default='{"name":"{{request.hostname}}","ipv4addr":"{{request.ipaddress}}","mac":"{{request.mac}}","network_view":"{{endpoint.networkView}}","comment":"Created by OneFuse."}', help_text='A json dict detailing the template for the fixed address record in Infoblox IPAM', max_length=65536, validators=[driven_apps.common.validators.StringFieldValidator(blank=False, field_name='fixedAddressRecordTemplate', template=True), driven_apps.naming.validators.FixedAddressRecordTemplateValidator(field_name='fixedAddressRecordTemplate')]),
        ),
        migrations.AddField(
            model_name='infobloxendpoint',
            name='network_view',
            field=common.fields.TemplatableField(default='default', help_text='The name of the network view in Infoblox IPAM', max_length=65536, validators=[driven_apps.common.validators.StringFieldValidator(blank=False, field_name='networkView', template=True)]),
        ),
    ]
