# Generated by Django 2.2.10 on 2020-09-08 14:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0046_auto_20200904_1445'),
        ('naming', '0046_auto_20200904_1834'),
    ]

    operations = [
    ]
