# Generated by Django 2.2.10 on 2020-09-08 23:13

import common.fields
from django.db import migrations
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0047_merge_20200908_1457'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoftendpoint',
            name='share_path_for_temporary_directory',
            field=common.fields.TemplatableField(blank=True, max_length=65536, null=True, validators=[driven_apps.common.validators.StringFieldValidator(blank=True, field_name='sharePathForTemporaryDirectory', template=True)]),
        ),
        migrations.AddField(
            model_name='microsoftendpoint',
            name='temporary_directory_for_scripts',
            field=common.fields.TemplatableField(default='C:\\Windows\\temp', max_length=65536, validators=[driven_apps.common.validators.StringFieldValidator(blank=False, field_name='temporaryDirectoryForScripts', template=True)]),
        ),
    ]
