# Generated by Django 2.2.10 on 2020-09-09 21:14

from django.db import migrations, models
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0048_auto_20200908_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoftendpoint',
            name='jump_host',
            field=models.CharField(blank=True, default=None, help_text='The host name or IP address for this endpoint.', max_length=255, null=True, validators=[driven_apps.common.validators.HostAddressValidator(blank=True, field_name='jumpHost')]),
        ),
        migrations.AddField(
            model_name='microsoftendpoint',
            name='jump_port',
            field=models.IntegerField(help_text='The port number for the jump host.', null=True, validators=[driven_apps.common.validators.IntegerRangeValidator(1, 65535, allow_blank=True, field_name='jumpPort')]),
        ),
    ]
