# Generated by Django 2.2.10 on 2020-09-17 16:53

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0049_auto_20200909_2114'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluecatendpoint',
            name='ip_address_record_user_defined_fields',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text='IP address record user defined field.', null=True),
        ),
    ]
