# Generated by Django 2.2.10 on 2020-09-17 13:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0049_auto_20200909_2114'),
    ]

    operations = [
        migrations.AlterField(
            model_name='menandmiceendpoint',
            name='men_and_mice_version',
            field=models.CharField(help_text='The Men & Mice version for this endpoint.', max_length=32, null=True),
        ),
    ]
