# Generated by Django 2.2.10 on 2020-09-21 18:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0050_bluecatendpoint_ip_address_record_user_defined_fields'),
        ('naming', '0050_auto_20200917_1303'),
    ]

    operations = [
    ]
