# Generated by Django 2.2.10 on 2020-09-22 21:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0051_auto_20200921_1657'),
        ('naming', '0051_auto_20200921_1720'),
    ]

    operations = [
    ]
