# Generated by Django 2.2.10 on 2020-09-23 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0051_merge_20200921_1809'),
        ('naming', '0051_auto_20200921_1657'),
    ]

    operations = [
    ]
