# Generated by Django 2.2.10 on 2020-09-23 20:29

import common.fields
from django.db import migrations
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0052_merge_20200922_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluecatendpoint',
            name='dns_view',
            field=common.fields.TemplatableField(blank=True, default='default', help_text='(Templatable) DNS View.', max_length=65536, null=True, validators=[driven_apps.common.validators.StringFieldValidator(blank=True, field_name='dnsView', template=True)]),
        ),
    ]
