# Generated by Django 2.2.10 on 2020-09-24 18:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0052_merge_20200923_0032'),
        ('naming', '0053_auto_20200923_2029'),
    ]

    operations = [
    ]
