# Generated by Django 2.2.10 on 2020-09-24 19:43

from django.db import migrations
import django_extensions.db.fields.json
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0054_merge_20200924_1807'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluecatendpoint',
            name='host_record_user_defined_fields',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text='Host record user defined field.', null=True, validators=[driven_apps.common.validators.JSONValidator('hostRecordUserDefinedFields', allow_array=False, allow_string=False)]),
        ),
    ]
