# Generated by Django 2.2.10 on 2020-09-25 01:01

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0055_auto_20200924_1943'),
    ]

    operations = [
        migrations.AddField(
            model_name='menandmiceendpoint',
            name='ip_address_record_user_defined_fields',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text='IP address record user defined fields.', null=True),
        ),
    ]
