# Generated by Django 2.2.10 on 2020-09-25 20:05

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0056_menandmiceendpoint_ip_address_record_user_defined_fields'),
        ('naming', '0056_bluecatendpoint_deployment_method'),
    ]

    operations = [
    ]
