# Generated by Django 2.2.10 on 2020-09-25 21:46

from django.db import migrations
import django_extensions.db.fields.json
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0057_merge_20200925_2005'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluecatendpoint',
            name='host_record_user_defined_fields',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text='Host record user defined fields.', null=True, validators=[driven_apps.common.validators.JSONValidator('hostRecordUserDefinedFields', allow_array=False, allow_string=False)]),
        ),
        migrations.AlterField(
            model_name='bluecatendpoint',
            name='ip_address_record_user_defined_fields',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text='IP address record user defined fields.', null=True, validators=[driven_apps.common.validators.JSONValidator('ipAddressRecordUserDefinedFields', allow_array=False, allow_string=False)]),
        ),
        migrations.AlterField(
            model_name='menandmiceendpoint',
            name='ip_address_record_user_defined_fields',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text='IP address record user defined fields.', null=True, validators=[driven_apps.common.validators.JSONValidator('ipAddressRecordUserDefinedFields', allow_array=False, allow_string=False)]),
        ),
    ]
