# Generated by Django 2.2.10 on 2020-09-29 23:07

from django.db import migrations
import django_extensions.db.fields.json
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0058_auto_20200925_2146'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='menandmiceendpoint',
            name='ip_address_record_user_defined_fields',
        ),
        migrations.AddField(
            model_name='menandmiceendpoint',
            name='device_custom_properties',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text='Device custom properties.', null=True, validators=[driven_apps.common.validators.JSONValidator('deviceCustomProperties', allow_array=False, allow_string=False)]),
        ),
    ]
