# Generated by Django 2.2.10 on 2020-10-05 19:31

import common.fields
from django.db import migrations
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0059_auto_20200929_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluecatendpoint',
            name='dns_view',
            field=common.fields.TemplatableField(default='', help_text='(Templatable) DNS View.', max_length=65536, validators=[driven_apps.common.validators.StringFieldValidator(blank=False, field_name='dnsView', template=True)]),
            preserve_default=False,
        ),
    ]
