# Generated by Django 2.2.10 on 2020-10-06 17:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0060_auto_20201005_1931'),
        ('naming', '0060_auto_20201005_2038'),
    ]

    operations = [
    ]
