# Generated by Django 2.2.10 on 2020-10-07 21:55

import common.fields
from django.db import migrations
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0061_merge_20201006_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluecatendpoint',
            name='dns_view',
            field=common.fields.TemplatableField(help_text='(Templatable) DNS View.', max_length=65536, validators=[driven_apps.common.validators.NotBlankValidator(field_name='dnsView', required=True)]),
        ),
    ]
