# Generated by Django 2.2.16 on 2020-10-15 22:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0063_auto_20201008_2054'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmetadata',
            name='_managed_object_href',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='jobmetadata',
            name='_policy_href',
            field=models.TextField(blank=True, null=True),
        ),
    ]
