# Generated by Django 2.2.10 on 2020-10-21 14:27

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0064_ansibletowerendpoint'),
    ]

    operations = [
        migrations.AlterField(
            model_name='bluecatendpoint',
            name='host_record_user_defined_fields',
            field=common.fields.TemplatableField(blank=True, help_text='Host record user defined fields.', max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='bluecatendpoint',
            name='ip_address_record_user_defined_fields',
            field=common.fields.TemplatableField(blank=True, help_text='IP address record user defined fields.', max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='menandmiceendpoint',
            name='device_custom_properties',
            field=common.fields.TemplatableField(blank=True, help_text='Device custom properties.', max_length=65536, null=True),
        ),
    ]
