# Generated by Django 2.2.16 on 2020-10-23 17:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0064_auto_20201015_2233'),
        ('naming', '0065_auto_20201021_1427'),
    ]

    operations = [
    ]
