# Generated by Django 2.2.16 on 2020-10-23 23:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0066_merge_20201023_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobmetadata',
            name='job_state',
            field=models.CharField(choices=[('Initialized', 'Initialized'), ('In_Progress', 'In_Progress'), ('Successful', 'Successful'), ('Canceled', 'Canceled'), ('Failed', 'Failed')], max_length=1024),
        ),
    ]
