# Generated by Django 2.2.16 on 2020-11-20 07:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0047_auto_20201120_0724'),
        ('naming', '0067_auto_20201023_2340'),
    ]

    operations = [
        migrations.DeleteModel(
            name='NamingJobParameters',
        ),
    ]
