# Generated by Django 2.2.16 on 2021-01-05 21:25

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_modulecredential_connection_method'),
        ('naming', '0068_delete_namingjobparameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNowEndpoint',
            fields=[
                ('endpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='naming.Endpoint')),
                ('service_now_version', models.CharField(help_text='ServiceNow version for this endpoint.', max_length=32, null=True, validators=[driven_apps.common.validators.RequiredFieldValidator(allow_null=True, field_name='serviceNowVersion'), driven_apps.common.validators.OneOfValidator(allowed_values=['New York'], field_name='serviceNowVersion')])),
                ('service_now_instance', models.CharField(help_text='The ServiceNow instance for this endpoint.', max_length=255, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='serviceNowInstance'), django.core.validators.URLValidator(message="Field 'serviceNowInstance' must be a valid https URL.", schemes=['https'])])),
                ('credential', models.ForeignKey(help_text='Credential for this endpoint.', on_delete=django.db.models.deletion.PROTECT, to='credentials.ModuleCredential')),
            ],
            options={
                'db_table': 'endpoints_service_now',
                'ordering': ['id'],
                'abstract': False,
            },
            bases=('naming.endpoint', models.Model),
        ),
    ]
