# Generated by Django 2.2.16 on 2021-01-08 19:29

import django.core.validators
from django.db import migrations, models
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0069_servicenowendpoint'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicenowendpoint',
            name='service_now_instance',
        ),
        migrations.RemoveField(
            model_name='servicenowendpoint',
            name='service_now_version',
        ),
        migrations.AddField(
            model_name='servicenowendpoint',
            name='instance',
            field=models.CharField(help_text='The ServiceNow Instance for this endpoint.', max_length=255, null=True, validators=[driven_apps.common.validators.RequiredFieldValidator(allow_null=True, field_name='instance'), django.core.validators.URLValidator(message="Field 'instance' must be a valid https URL.", schemes=['https'])]),
        ),
        migrations.AddField(
            model_name='servicenowendpoint',
            name='version',
            field=models.CharField(help_text='ServiceNow version for this endpoint.', max_length=32, null=True, validators=[driven_apps.common.validators.RequiredFieldValidator(allow_null=True, field_name='version'), driven_apps.common.validators.OneOfValidator(allowed_values=['New York'], field_name='version')]),
        ),
        migrations.AlterModelTable(
            name='servicenowendpoint',
            table='endpoints_servicenow',
        ),
    ]
