# Generated by Django 2.2.16 on 2021-01-12 18:07

from django.db import migrations, models
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0070_auto_20210108_1929'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenowendpoint',
            name='instance',
            field=models.CharField(default=None, help_text='The ServiceNow Instance for this endpoint.', max_length=255, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='instance'), driven_apps.common.validators.ServicenowInstanceValidator(field_name='instance')]),
        ),
        migrations.AlterField(
            model_name='servicenowendpoint',
            name='version',
            field=models.CharField(default=None, help_text='ServiceNow version for this endpoint.', max_length=32, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='version'), driven_apps.common.validators.OneOfValidator(allowed_values=['New York'], field_name='version')]),
        ),
    ]
