# Generated by Django 2.2.16 on 2021-02-09 19:57

from django.db import migrations, models
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0073_auto_20210126_1922'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vra8endpoint',
            name='vra_version',
            field=models.CharField(help_text='The vRA version for this endpoint.', max_length=32, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='vraVersion'), driven_apps.common.validators.MinLengthValidator(constraint=1, field_name='vraVersion', required=True), driven_apps.common.validators.OneOfValidator(allowed_values=['8.1', '8.3'], field_name='vraVersion')]),
        ),
    ]
