# Generated by Django 2.2.16 on 2021-03-09 16:14

import common.fields
from django.db import migrations, models
import django.db.models.deletion
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0003_modulecredential_connection_method'),
        ('naming', '0075_jobmetadata__rendered_templates'),
    ]

    operations = [
        migrations.CreateModel(
            name='SolarWindsEndpoint',
            fields=[
                ('endpoint_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='naming.Endpoint')),
                ('host', models.CharField(help_text='The host name or IP address for this endpoint.', max_length=255, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='host'), driven_apps.common.validators.HostAddressValidator(field_name='host')])),
                ('port', models.IntegerField(help_text='The port number for this endpoint.', validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='port'), driven_apps.common.validators.IntegerRangeValidator(1, 65535, field_name='port')])),
                ('ssl', models.BooleanField(default=False, help_text='Flag to enable SSL for this endpoint.', validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='ssl'), driven_apps.common.validators.BooleanFieldValidator(field_name='ssl')])),
                ('version', models.CharField(help_text='The SolarWinds version for this endpoint.', max_length=32, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='version'), driven_apps.common.validators.MinLengthValidator(constraint=1, field_name='version', required=True), driven_apps.common.validators.OneOfValidator(allowed_values=['4.6'], field_name='version')])),
                ('ipam_comment', common.fields.TemplatableField(blank=True, max_length=65536, null=True, validators=[driven_apps.common.validators.StringFieldValidator(blank=True, field_name='ipamComment', template=True)])),
                ('skip_ip_address_scanning', models.BooleanField(default=False, help_text='Do not scan and reclaim unused IP Addresses. Allows management of unused IP Addresses to set the status without affecting the whole subnet.', validators=[driven_apps.common.validators.BooleanFieldValidator(field_name='skipIpAddressScanning')])),
                ('credential', models.ForeignKey(help_text='Credential for this endpoint.', on_delete=django.db.models.deletion.PROTECT, to='credentials.ModuleCredential')),
            ],
            options={
                'db_table': 'endpoints_solarwinds',
                'ordering': ['id'],
                'abstract': False,
            },
            bases=('naming.endpoint', models.Model),
        ),
    ]
