# Generated by Django 2.2.16 on 2021-03-26 17:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0077_auto_20210311_1506'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='solarwindsendpoint',
            name='skip_ip_address_scanning',
        ),
    ]
