# Generated by Django 2.2.16 on 2021-06-03 20:37

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0080_auto_20210414_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmetadata',
            name='_resolved_properties',
            field=django_extensions.db.fields.json.JSONField(blank=True, default={}, help_text='Stores the resovled_properties.', null=True),
        ),
    ]
