# Generated by Django 3.2.3 on 2021-06-15 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0081_jobmetadata__resolved_properties'),
    ]

    operations = [
        migrations.AlterField(
            model_name='namingsequence',
            name='_naming_data',
            field=models.TextField(default='{}', max_length=65536),
        ),
    ]
