# Generated by Django 3.2.3 on 2021-06-25 13:52

from django.db import migrations, models
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0083_alter_menandmiceendpoint_men_and_mice_version'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenowendpoint',
            name='version',
            field=models.CharField(default=None, help_text='ServiceNow version for this endpoint.', max_length=32, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='version'), driven_apps.common.validators.OneOfValidator(allowed_values=['New York', 'Orlando', 'Paris', 'Quebec'], field_name='version')]),
        ),
    ]
