# Generated by Django 3.2.3 on 2021-07-09 15:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0085_jobmetadata_job_engine_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobmetadata',
            name='action_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
