# Generated by Django 3.2.3 on 2021-07-15 14:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0085_remove_servicenowendpoint_version'),
        ('naming', '0086_jobmetadata_action_name'),
    ]

    operations = [
    ]
