# Generated by Django 3.2.3 on 2021-07-16 14:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0086_auto_20210714_2119'),
        ('naming', '0087_merge_20210715_1427'),
    ]

    operations = [
    ]
