# Generated by Django 3.2.3 on 2021-07-19 17:38

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0088_merge_20210716_1410'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansibletowerendpoint',
            name='ansible_tower_version',
        ),
    ]
