# Generated by Django 3.2.3 on 2021-07-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0089_remove_ansibletowerendpoint_ansible_tower_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='bluecatendpoint',
            name='bluecat_version',
        ),
        migrations.RemoveField(
            model_name='infobloxendpoint',
            name='infoblox_version',
        ),
        migrations.RemoveField(
            model_name='menandmiceendpoint',
            name='men_and_mice_version',
        ),
        migrations.RemoveField(
            model_name='microsoftendpoint',
            name='microsoft_version',
        ),
        migrations.RemoveField(
            model_name='solarwindsendpoint',
            name='solarwinds_version',
        ),
    ]
