DATA_BACKUP_HOURS = 6

API_ENDPOINTS_DICT = {
    'report_dashboard': '/reportapi/api/v2/cb_integration/aws/report_dashboards',
    'potential_benefit': '/api/api/v1/cb_integration/service_advisers/cost_efficiency_summary',
    'service_type_count': '/api/api/v1/cb_integration/service_advisers/list_service_type_with_count',
    'misc_details': '/reportapi/api/v2/cb_integration/aws/report_dashboards/misc_cost_details',
    'cost_by_days': '/reportapi/api/v2/cb_integration/aws/report_dashboards/cost_by_days',
    'cost_by_months': '/reportapi/api/v2/cb_integration/aws/report_dashboards/cost_by_months',
    'cost_by_accounts': '/reportapi/api/v2/cb_integration/aws/report_dashboards/cost_by_accounts',
    'cost_by_services': '/reportapi/api/v2/cb_integration/aws/report_dashboards/cost_by_services',
    'filtration_menu': '/reportapi/api/v2/cb_integration/aws/reports/filteration_menu',
    'get_aws_forecast': '/reportapi/api/v2/cb_integration/aws/reports/get_aws_forecast',
    'ignored_services': '/api/api/v1/cb_integration/service_advisers/show_ignored_services',
    'get_chart_data': '/reportapi/api/v2/cb_integration/aws/reports/get_chart_data',
    'get_csv_download': '/api/api/v1/cb_integration/service_advisers/get_recommendation_csv/',
    'get_service_type_details': '/api/api/v1/cb_integration/service_advisers/list_service_type_with_detail',
    'get_regions_list': '/api/api/v1/cb_integration/account_regions',
    'get_tags_list': '/api/api/v1/cb_integration/service_advisers/get_key_values_array',
    'ec2_rightsize': '/api/api/v1/cb_integration/service_advisers/get_right_sized_instances',
    'ec2_rightsizing_csv': '/api/api/v1/cb_integration/service_advisers/get_formatted_csv',
    'aws_ri_purchase_recommendations': '/reportapi/api/v2/cb_integration/aws/reports/ri_purchase_recommendations',
    'azure_ri_purchase_recommendations': '/reportapi/api/v2/cb_integration/azure/reports/ri_purchase_recommendations',
    'azure_cost_by_days': '/reportapi/api/v2/cb_integration/azure/report_dashboards/azure_cost_by_days',
    'azure_cost_by_months': '/reportapi/api/v2/cb_integration/azure/report_dashboards/azure_cost_by_months',
    'azure_cost_by_accounts': '/reportapi/api/v2/cb_integration/azure/report_dashboards/azure_cost_by_subscriptions',
    'azure_cost_by_services': '/reportapi/api/v2/cb_integration/azure/report_dashboards/azure_cost_by_services',
    'azure_misc_details': '/reportapi/api/v2/cb_integration/azure/report_dashboards/azure_misc_cost_details',
    'azure_filtration_menu': '/reportapi/api/v2/cb_integration/azure/reports/azure_filteration_menu',
    'azure_get_chart_data': '/reportapi/api/v2/cb_integration/azure/reports/get_azure_chart_data',
    'azure_resource_groups': '/reportapi/api/v2/cb_integration/azure/reports/get_resource_groups',
    'azure_resource_names': '/reportapi/api/v2/cb_integration/azure/reports/get_resource_names',
    'azure_tag_keys': '/reportapi/api/v2/cb_integration/azure/reports/get_azure_tag_keys',
    'azure_tag_values': '/reportapi/api/v2/cb_integration/azure/reports/get_azure_tag_values',
    'get_azure_forecast': '/reportapi/api/v2/cb_integration/azure/reports/get_azure_forecast',
    'get_mapped_adapters': '/api/api/v1/cb_integration/adapters',
    'get_graph_data': '/api/api/v1/cb_integration/metrics/search_info',
    'validate_cred': '/reportapi/api/v2/cb_integration/aws/reports/get_billing_adapters',
    'validate_api_token': '/reportapi/api/v2/cb_integration/api_tokens/validate',
    'azure_currency': '/reportapi/api/v2/cb_integration/azure/reports/get_azure_currency',
    'get_server_cost_summary': '/reportapi/api/v2/cb_integration/aws/servers/cost_summary',
    'get_server_operational_cost_breakdown': '/reportapi/api/v2/cb_integration/aws/servers/operational_cost_breakdown',
    'get_server_cost_breakdown': '/reportapi/api/v2/cb_integration/aws/servers/resource_cost_breakdown',
    'get_potential_savings': '/api/api/v1/cb_integration/servers/server_potential_savings',
    'get_config': '/api/api/v1/cb_integration/service_adviser_configurations',
    'azure_server_potential_savings': '/api/api/v1/cb_integration/servers/azure_server_potential_savings',
    'get_azure_cost_summary': '/reportapi/api/v2/cb_integration/azure/servers/cost_summary',
    'get_azure_cost_breakdown': '/reportapi/api/v2/cb_integration/azure/servers/cost_breakdown',
}

UNUSED_SERVICES = [
    'AwsRecords::Snapshots::Volume',
    'AwsRecords::Snapshots::Rds',
    'Services::Network::ElasticIP',
    'Services::Network::AutoScalingConfiguration',
    'unused_provisioned_iops_volumes',
    'unused_provisioned_iops_rds',
    'Services::Network::LoadBalancer',
    'idle_ec2',
    'idle_rds',
    'idle_stopped_ec2',
    'idle_stopped_rds',
    'idle_volume',
    'Services::Compute::Server::Volume',
    'idle_load_balancer',
    'amis',
    'idle_vm',
    'idle_stopped_vm',
    'idle_databases',
    'idle_disks',
    'idle_lbs',
    'unassociated_lbs',
    'unassociated_public_ips',
    'unattached_disks',
    'unused_snapshots',
]

UNOPTIMIZED_SERVICES = [
    'Services::Compute::Server',
    'Services::Database::Rds',
    'ec2_right_sizings'
]

REGIONS_DICT = {
    "af-south-1": "Africa (Cape Town)",
    "ap-east-1": "Asia Pacific (Hong Kong)",
    "ap-south-1": "Asia Pacific (Mumbai)",
    "ap-northeast-3": "Asia Pacific (Osaka-Local)",
    "ap-northeast-2": "Asia Pacific (Seoul)",
    "ap-southeast-1": "Asia Pacific (Singapore)",
    "ap-southeast-2": "Asia Pacific (Sydney)",
    "ap-northeast-1": "Asia Pacific (Tokyo)",
    "ca-central-1": "Canada (Central)",
    "eu-central-1": "EU (Frankfurt)",
    "eu-west-1": "EU (Ireland)",
    "eu-west-2": "EU (London)",
    "eu-south-1": "EU (Milan)",
    "eu-west-3": "EU (Paris)",
    "eu-north-1": "EU (Stockholm)",
    "me-south-1": "Middle East (Bahrain)",
    "sa-east-1": "South America (Sao Paulo)",
    "us-east-1": "US East (N. Virginia)",
    "us-east-2": "US East (Ohio)",
    "us-west-1": "US West (N. California)",
    "us-west-2": "US West (Oregon)"
}
