# Generated by Django 2.2.10 on 2020-04-14 20:43

import cb_secrets.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprotection', '0001_squashed_0008_auto_20200408_2101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprotection',
            name='dataprotection_technology',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprotection.DataProtectionTechnology'),
        ),
        migrations.AlterField(
            model_name='dataprotection',
            name='ip',
            field=models.CharField(max_length=50, verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='dataprotection',
            name='serviceaccount',
            field=models.CharField(help_text='Username of account authorized to run commands on this ip manager', max_length=250, verbose_name='Account username'),
        ),
        migrations.AlterField(
            model_name='dataprotection',
            name='servicepasswd',
            field=cb_secrets.fields.EncryptedPasswordField(verbose_name='Account password'),
        ),
        migrations.AlterField(
            model_name='protectionplan',
            name='dataprotection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='dataprotection.DataProtection'),
        ),
        migrations.AlterField(
            model_name='protectionplan',
            name='system_id',
            field=models.CharField(max_length=100, verbose_name='Plan id in data protection solution'),
        ),
    ]
