# Generated by Django 2.2.12 on 2020-05-22 18:54

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprotection', '0002_auto_20200414_2043'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dataprotection',
            name='port',
            field=models.IntegerField(default=443, help_text='Port used to connect to this data protection backend', validators=[common.validators.is_only_digits]),
        ),
        migrations.AlterField(
            model_name='dataprotection',
            name='protocol',
            field=models.CharField(choices=[('http', 'http'), ('https', 'https')], default='https', help_text='Protocol used to connect to this data protection backend', max_length=10),
        ),
        migrations.AlterField(
            model_name='dataprotection',
            name='serviceaccount',
            field=models.CharField(help_text='Username of account authorized to run commands on this data protection backend', max_length=250, verbose_name='Account username'),
        ),
    ]
