# Generated by Django 2.2.16 on 2021-06-22 01:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dataprotection', '0005_set_global_id_for_dataprotection'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protectionplan',
            name='system_id',
            field=models.CharField(max_length=255, verbose_name='Plan id in data protection solution'),
        ),
    ]
