# Generated by Django 2.2.16 on 2020-10-26 20:23

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json
import driven_apps.common.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0065_auto_20201021_1427'),
        ('accounts', '0054_auto_20201019_1709'),
        ('ansible_tower', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleTowerDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('limit', models.CharField(max_length=256)),
                ('provisioning_job_results', django_extensions.db.fields.json.JSONField(default=dict, help_text='Provisioning Job Results')),
                ('job_metadata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='naming.JobMetadata')),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ansible_tower.AnsibleTowerPolicy')),
                ('workspace', models.ForeignKey(help_text='Workspace URL', on_delete=django.db.models.deletion.PROTECT, to='accounts.Group')),
            ],
            options={
                'verbose_name_plural': 'Ansible Tower Deployments',
                'db_table': 'ansible_tower_deployments',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(models.Model, driven_apps.common.mixins.RoleBasedHalFilteringMixin),
        ),
    ]
