# Generated by Django 2.2.10 on 2020-10-27 16:03

import common.fields
from django.db import migrations
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_tower', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibletowerpolicy',
            name='extra_vars_override',
            field=common.fields.TemplatableField(blank=True, help_text='Extra Vars override', max_length=65536, null=True, validators=[driven_apps.common.validators.StringFieldValidator(blank=True, field_name='extraVarsOverride', template=True)]),
        ),
        migrations.AddField(
            model_name='ansibletowerpolicy',
            name='machine_credential_override',
            field=common.fields.TemplatableField(blank=True, help_text='Machine Credential override', max_length=65536, null=True, validators=[driven_apps.common.validators.StringFieldValidator(blank=True, field_name='machineCredentialOverride', template=True)]),
        ),
    ]
