# Generated by Django 2.2.16 on 2020-10-27 18:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_tower', '0002_ansibletowerdeployment'),
        ('ansible_tower', '0002_auto_20201027_1603'),
    ]

    operations = [
    ]
