# Generated by Django 2.2.16 on 2020-10-28 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_tower', '0003_merge_20201027_1832'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ansibletowerpolicy',
            options={'ordering': ['id'], 'verbose_name_plural': 'Ansible Tower Policies'},
        ),
        migrations.AlterModelTable(
            name='ansibletowerpolicy',
            table='ansible_tower_policies',
        ),
    ]
