# Generated by Django 2.2.16 on 2020-11-05 21:12

import common.fields
from django.db import migrations, models
import django_extensions.db.fields.json
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_tower', '0005_auto_20201028_1618'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibletowerdeployment',
            name='hosts',
            field=django_extensions.db.fields.json.JSONField(default=dict),
        ),
        migrations.AddField(
            model_name='ansibletowerdeployment',
            name='inventory_name',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
        migrations.AddField(
            model_name='ansibletowerpolicy',
            name='inventory_name',
            field=common.fields.TemplatableField(blank=True, help_text='Ansible Tower Inventory Name.', max_length=65536, null=True, validators=[driven_apps.common.validators.StringFieldValidator(blank=True, field_name='inventoryName', template=True)]),
        ),
        migrations.AlterField(
            model_name='ansibletowerdeployment',
            name='limit',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
