# Generated by Django 2.2.16 on 2020-11-16 16:24

import common.fields
from django.db import migrations
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_tower', '0007_auto_20201112_1538'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibletowerpolicy',
            name='deprovisioning_job_templates',
            field=common.fields.TemplatableField(blank=True, help_text='Ansible Tower deprovisioning job templates.', max_length=65536, null=True, validators=[driven_apps.common.validators.StringFieldValidator(blank=True, field_name='deprovisioningJobTemplates', template=True)]),
        ),
    ]
