# Generated by Django 2.2.10 on 2020-11-17 20:08

from django.db import migrations, models
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_tower', '0008_ansibletowerpolicy_deprovisioning_job_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibletowerdeployment',
            name='archived',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='ansibletowerdeployment',
            name='deprovisioning_job_results',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text='Deprovisioning Job Results', null=True),
        ),
    ]
