# Generated by Django 2.2.10 on 2020-11-18 18:24

from django.db import migrations, models
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_tower', '0008_ansibletowerpolicy_deprovisioning_job_templates'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansibletowerpolicy',
            name='verify_prompt_on_launch_for_limit',
            field=models.BooleanField(default=True, help_text='verify_prompt_on_launch_for_limit', validators=[driven_apps.common.validators.BooleanFieldValidator(field_name='verifyPromptOnLaunchForLimit')]),
        ),
    ]
