# Generated by Django 2.2.16 on 2020-11-17 22:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_tower', '0008_ansibletowerpolicy_deprovisioning_job_templates'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ansibletowerpolicy',
            name='group_separator',
        ),
    ]
