# Generated by Django 2.2.10 on 2020-11-18 19:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_tower', '0009_auto_20201117_2008'),
        ('ansible_tower', '0009_remove_ansibletowerpolicy_group_separator'),
    ]

    operations = [
    ]
