# Generated by Django 2.2.10 on 2020-11-19 21:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible_tower', '0010_merge_20201118_1900'),
        ('ansible_tower', '0009_ansibletowerpolicy_verify_prompt_on_launch_for_limit'),
    ]

    operations = [
    ]
