# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-10 14:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0005_auto_20190710_1848'),
        ('bluecat', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueCatNetwork',
            fields=[
                ('ipamnetwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ipam.IPAMNetwork')),
                ('bluecat_id', models.IntegerField()),
                ('configuration_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('ipam.ipamnetwork',),
        ),
    ]
