# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-17 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bluecat', '0002_bluecatnetwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='bluecatnetwork',
            name='parent_id',
            field=models.IntegerField(default=None),
            preserve_default=False,
        ),
    ]
