# Generated by Django 2.2.10 on 2020-03-24 17:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0007_availableipamnetwork'),
        ('bluecat', '0003_bluecatnetwork_parent_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='AvailableBluecatNetwork',
            fields=[
                ('availableipamnetwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ipam.AvailableIPAMNetwork')),
                ('bluecat_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('ipam.availableipamnetwork',),
        ),
    ]
