# Generated by Django 2.2.12 on 2020-06-01 22:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('itsm', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cmdb',
            name='table_name',
            field=models.CharField(default='cmdb_ci_server', help_text='Table used for technology ci entries.', max_length=255, null=True),
        ),
    ]
