# Generated by Django 2.2.12 on 2020-07-02 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itsm', '0002_cmdb_table_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='cmdb',
            old_name='environment',
            new_name='environments',
        ),
        migrations.RenameField(
            model_name='cmdb',
            old_name='osbuild',
            new_name='os_builds',
        ),
        migrations.RenameField(
            model_name='itsm',
            old_name='environment',
            new_name='environments',
        ),
    ]
