# Generated by Django 2.2.16 on 2021-01-08 18:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('itsm', '0005_set_global_id_for_itsm_20201222_1622'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='itsm',
            options={'verbose_name_plural': 'ITSM integrations'},
        ),
    ]
