# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-27 17:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_parent_service'),
        ('orders', '0006_auto_20161213_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='installserviceorderitem',
            name='parent_service',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.Service'),
        ),
    ]
