# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-27 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontent', '0003_auto_20161004_2121'),
        ('orders', '0006_auto_20161213_2338'),
    ]

    operations = [
        migrations.AddField(
            model_name='installserviceitemoptions',
            name='applications',
            field=models.ManyToManyField(to='externalcontent.Application'),
        ),
    ]
