# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-30 22:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0008_merge'),
        ('orders', '0007_installserviceorderitem_parent_service'),
    ]

    operations = [
        migrations.AddField(
            model_name='installserviceorderitem',
            name='blueprint_service_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='bpsi', to='servicecatalog.BlueprintServiceItem'),
        ),
    ]
