# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-01 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0007_installserviceitemoptions_applications'),
        ('orders', '0008_installserviceorderitem_blueprint_service_item'),
    ]

    operations = [
    ]
