# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-16 17:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0002_update_location_type_choices'),
        ('orders', '0009_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='installpodorderitem',
            name='config_file',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='files.ConfigurationFile'),
        ),
        migrations.AlterField(
            model_name='installpodorderitem',
            name='images',
            field=models.TextField(blank=True, default=''),
        ),
    ]
