# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 22:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0010_installpod_add_config_file'),
    ]

    operations = [
        migrations.AddField(
            model_name='installpodorderitem',
            name='custom_field_values',
            field=models.ManyToManyField(blank=True, to='orders.CustomFieldValue'),
        ),
    ]
