# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 19:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0017_auto_20170727_1524'),
        ('orders', '0011_installpodorderitem_custom_field_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='blueprint',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicecatalog.ServiceBlueprint'),
        ),
    ]
