# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_set_blueprint_on_old_orders'),
    ]

    operations = [
        migrations.AlterField(
            model_name='preconfigurationvalueset',
            name='applications',
            field=models.ManyToManyField(blank=True, to='externalcontent.Application', verbose_name='Applications'),
        ),
        migrations.AlterField(
            model_name='provisionserverorderitem',
            name='applications',
            field=models.ManyToManyField(blank=True, to='externalcontent.Application', verbose_name='Applications'),
        ),
        migrations.AlterField(
            model_name='servermodorderitem',
            name='applications',
            field=models.ManyToManyField(blank=True, to='externalcontent.Application', verbose_name='Applications'),
        ),
    ]
