# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-27 20:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0013_set_blueprint_on_old_orders'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstallServiceOrderItem',
            new_name='BlueprintOrderItem',
        ),
        migrations.RenameField(
            model_name='installserviceitemoptions',
            old_name='isoi',
            new_name='boi',
        ),
    ]
