# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-03 16:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0014_auto_20170927_2000'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='InstallServiceItemOptions',
            new_name='BlueprintItemArguments',
        ),
    ]
