# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 17:42
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0015_auto_20171003_1614'),
        ('orders', '0014_auto_20171012_1842'),
    ]

    operations = [
    ]
