# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-27 12:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0016_merge_20171016_1742'),
    ]

    operations = [
        migrations.AlterField(
            model_name='order',
            name='name',
            field=models.TextField(blank=1, default='', max_length=1024, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='order',
            name='name_pristine',
            field=models.BooleanField(default=True, help_text='Set to False when the name field has been overridden by a user. If True, CB will continue to overwrite the name whenever items are added or removed from the order. If False, this indicates that the user has added a more meaningful name and CB will no longer change the name.'),
        ),
    ]
