# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 14:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20171027_1226'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blueprintorderitem',
            old_name='parent_service',
            new_name='parent_resource',
        ),
    ]
