# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0017_auto_20171027_1226'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfieldvalue',
            name='display_seq',
            field=models.IntegerField(blank=True, help_text='Order in which item will be displayed in forms and elsewhere', null=True),
        ),
    ]
