# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 14:58
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_auto_20180108_1429'),
    ]

    operations = [
        migrations.RenameField(
            model_name='blueprintorderitem',
            old_name='service_name',
            new_name='resource_name',
        ),
    ]
