# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-31 12:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0019_auto_20180108_1458'),
        ('orders', '0019_auto_20180119_1924'),
    ]

    operations = [
    ]
