# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-14 13:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0031_externaluserattributemapping'),
        ('orders', '0021_auto_20180202_1944'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='recipient',
            field=models.ForeignKey(blank=True, help_text='Optional user that this Order is being ordered on behalf of. They will be the owner of the objects resulting from completion of the order (e.g., Servers, Resources).', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='orders_received', to='accounts.UserProfile', verbose_name='Target User'),
        ),
    ]
