# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-29 20:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0018_customfieldvalue_display_seq'),
        ('orders', '0022_order_recipient'),
    ]

    operations = [
    ]
