# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 18:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0039_auto_20190618_2147'),
        ('orders', '0023_merge_20180529_2028'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='_approval_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='accounts.Group', verbose_name='Approval Group'),
        ),
    ]
