# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-18 00:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import jobs.models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20190607_1527'),
        ('infrastructure', '0039_auto_20190503_2313'),
        ('contenttypes', '0002_remove_content_type_name'),
        ('orders', '0023_merge_20180529_2028'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionJobOrderItem',
            fields=[
                ('orderitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='orders.OrderItem')),
                ('action_type_id', models.PositiveIntegerField()),
                ('_arguments', models.TextField(help_text='JSON representation of the dictionary of name/value pairs to be passed to this action.')),
                ('content_type', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='resources.Resource')),
                ('server', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.Server')),
            ],
            options={
                'abstract': False,
            },
            bases=('orders.orderitem', models.Model, jobs.models.ArgumentsMixin),
        ),
    ]
