# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-03 17:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0023_merge_20180529_2028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldvalue',
            name='file_value',
            field=models.FileField(blank=1, null=1, upload_to='CB_files'),
        ),
    ]
