# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-25 17:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_actionjoborderitem'),
        ('orders', '0024_order__approval_group'),
    ]

    operations = [
    ]
