# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-27 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0024_auto_20190603_1755'),
        ('orders', '0025_merge_20190625_1741'),
    ]

    operations = [
    ]
