# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-19 21:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0027_auto_20190627_2049'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installpodorderitem',
            name='container_orchestrator',
        ),
    ]
