# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-14 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0028_remove_installpodorderitem_container_orchestrator'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprintorderitem',
            name='preconfiguration_values',
            field=models.ManyToManyField(blank=True, to='orders.PreconfigurationValueSet'),
        ),
    ]
