# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-06 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0029_blueprintorderitem_preconfiguration_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='installpodorderitem',
            name='deploy_new_cluster',
            field=models.BooleanField(default=False),
        ),
    ]
