# Generated by Django 2.2.9 on 2019-12-12 00:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0030_installpodorderitem_deploy_new_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actionjoborderitem',
            name='content_type',
            field=models.ForeignKey(limit_choices_to={models.Q(models.Q(('app_label', 'cbhooks'), ('model', 'ServerAction')), models.Q(('app_label', 'cbhooks'), ('model', 'ResourceAction')), _connector='OR')}, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType'),
        ),
    ]
