# Generated by Django 2.2.10 on 2020-10-16 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0011_portalconfig_sso_provider'),
        ('orders', '0031_auto_20191212_0057'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='portal',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='portals.PortalConfig'),
        ),
    ]
