# Generated by Django 2.2.16 on 2021-03-03 00:08

from django.db import migrations


def decrypt_arguments(apps, schema_editor):
    ActionJobOrderItem = apps.get_model("orders", "ActionJobOrderItem")
    for row in ActionJobOrderItem.objects.all():
        row._arguments = row._encrypted_arguments
        row.save()


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0034_encrypted_arguments"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, decrypt_arguments),
        migrations.RemoveField(model_name="actionjoborderitem", name="_arguments",),
    ]
