# Generated by Django 2.2.16 on 2021-03-09 17:46

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0035_remove_unencrypted_arguments'),
    ]

    if "postgresql" in settings.DATABASES["default"]["ENGINE"]:
        operations = [
            migrations.RunSQL(
                sql=[("CREATE INDEX pwd_value on orders_customfieldvalue(left(pwd_value,16))")],
                reverse_sql=[("DROP INDEX pwd_value")],
            ),
            migrations.RunSQL(
                sql=[("CREATE INDEX str_value on orders_customfieldvalue(left(str_value,16))")],
                reverse_sql=[("DROP INDEX str_value")],
            ),
            migrations.RunSQL(
                sql=[("CREATE INDEX txt_value on orders_customfieldvalue(left(txt_value,16))")],
                reverse_sql=[("DROP INDEX txt_value")],
            ),
            migrations.RunSQL(
                sql=[("CREATE INDEX datetime_value on orders_customfieldvalue(datetime_value)")],
                reverse_sql=[("DROP INDEX datetime_value")],
            ),
            migrations.RunSQL(
                sql=[("CREATE INDEX email_value on orders_customfieldvalue(email_value)")],
                reverse_sql=[("DROP INDEX email_value")],
            ),
            migrations.RunSQL(
                sql=[("CREATE INDEX decimal_value on orders_customfieldvalue(decimal_value)")],
                reverse_sql=[("DROP INDEX decimal_value")],
            ),
            migrations.RunSQL(
                sql=[("CREATE INDEX int_value on orders_customfieldvalue(int_value)")],
                reverse_sql=[("DROP INDEX int_value")],
            ),
            migrations.RunSQL(
                sql=[("CREATE INDEX ip_value on orders_customfieldvalue(ip_value)")],
                reverse_sql=[("DROP INDEX ip_value")],
            ),
            migrations.RunSQL(
                sql=[("CREATE INDEX url_value on orders_customfieldvalue(url_value)")],
                reverse_sql=[("DROP INDEX url_value")],
            ),
        ]
    else:
        operations = [
            migrations.RunSQL(
                sql=[("CREATE INDEX pwd_value on orders_customfieldvalue(pwd_value(16))")],
                reverse_sql=[("DROP INDEX pwd_value on orders_customfieldvalue")],
            ),
            migrations.RunSQL(
                sql=[("CREATE INDEX str_value on orders_customfieldvalue(str_value(16))")],
                reverse_sql=[("DROP INDEX str_value on orders_customfieldvalue")],
            ),
            migrations.RunSQL(
                sql=[("CREATE INDEX txt_value on orders_customfieldvalue(txt_value(16))")],
                reverse_sql=[("DROP INDEX txt_value on orders_customfieldvalue")],
            ),
            migrations.RunSQL(
                sql=[("CREATE INDEX datetime_value on orders_customfieldvalue(datetime_value)")],
                reverse_sql=[("DROP INDEX datetime_value on orders_customfieldvalue")],
            ),
            migrations.RunSQL(
                sql=[("CREATE INDEX email_value on orders_customfieldvalue(email_value)")],
                reverse_sql=[("DROP INDEX email_value on orders_customfieldvalue")],
            ),
            migrations.RunSQL(
                sql=[("CREATE INDEX decimal_value on orders_customfieldvalue(decimal_value)")],
                reverse_sql=[("DROP INDEX decimal_value on orders_customfieldvalue")],
            ),
            migrations.RunSQL(
                sql=[("CREATE INDEX int_value on orders_customfieldvalue(int_value)")],
                reverse_sql=[("DROP INDEX int_value on orders_customfieldvalue")],
            ),
            migrations.RunSQL(
                sql=[("CREATE INDEX ip_value on orders_customfieldvalue(ip_value)")],
                reverse_sql=[("DROP INDEX ip_value on orders_customfieldvalue")],
            ),
            migrations.RunSQL(
                sql=[("CREATE INDEX url_value on orders_customfieldvalue(url_value)")],
                reverse_sql=[("DROP INDEX url_value on orders_customfieldvalue")],
            ),
        ]
