# Generated by Django 2.2.16 on 2021-06-01 11:09

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_orderitem_global_id'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfieldvalue',
            name='tenant',
        ),
    ]
