# Generated by Django 2.2.10 on 2020-10-09 16:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0004_auto_20200420_2140'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basessoprovider',
            name='_required_attributes',
            field=models.CharField(blank=True, default='email,username,first_name,last_name', help_text="The combination of attributes that this SP will use, in additon to 'username', for verifying a User that is sent from the IdP", max_length=512, verbose_name='Required Attributes'),
        ),
        migrations.AlterField(
            model_name='basessoprovider',
            name='user_attribute_email',
            field=models.CharField(blank=True, help_text="Key for the IdP's 'email' attribute.", max_length=80, verbose_name='Email Attribute Name'),
        ),
        migrations.AlterField(
            model_name='basessoprovider',
            name='user_attribute_given_name',
            field=models.CharField(blank=True, help_text="Key for the IdP's 'first name' attribute.", max_length=80, verbose_name='First Name Attribute Name'),
        ),
        migrations.AlterField(
            model_name='basessoprovider',
            name='user_attribute_sn',
            field=models.CharField(blank=True, help_text="Key for the IdP's 'last name' attribute.", max_length=80, verbose_name='Last Name Attribute Name'),
        ),
        migrations.AlterField(
            model_name='basessoprovider',
            name='user_attribute_uid',
            field=models.CharField(help_text="Key for the IdP's 'username' attribute.", max_length=80, verbose_name='Username Attribute Name'),
        ),
    ]
