# Generated by Django 2.2.10 on 2020-10-15 19:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0012_remove_portalconfig_sso_provider'),
        ('sso', '0005_auto_20201009_1658'),
    ]

    operations = [
        migrations.AddField(
            model_name='basessoprovider',
            name='portal_config',
            field=models.OneToOneField(blank=True, help_text="Branded Portal that this SSO Provider is configured for. Defaults to the 'default portal' if not selected.", null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sso_provider', to='portals.PortalConfig', verbose_name='Branded Portal'),
        ),
    ]
