# Generated by Django 2.2.16 on 2021-01-23 00:27

import common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0006_basessoprovider_portal_config'),
    ]

    operations = [
        migrations.AddField(
            model_name='basessoprovider',
            name='global_id',
            field=models.CharField(default=common.mixins.get_global_id_chars, help_text='Identifier that can be used to access this object through the API across instances.', max_length=16, verbose_name='Global ID'),
        ),
    ]
