# Generated by Django 2.2.16 on 2021-01-23 00:28

from django.db import migrations

from common.mixins import get_global_id_chars


class Migration(migrations.Migration):
    def set_global_ids(apps, schema_editor):
        SSOModel = apps.get_model("sso", "BaseSSOProvider")
        prefix = "SSO"
        for row in SSOModel.objects.all():
            chars = get_global_id_chars()
            row.global_id = f"{prefix}-{chars}"
            row.save()

    dependencies = [
        ("sso", "0007_sso_global_id"),
    ]

    operations = [
        migrations.RunPython(set_global_ids, migrations.RunPython.noop),
    ]
