# Generated by Django 3.2.1 on 2021-05-25 04:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0008_set_sso_global_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='basessoprovider',
            name='name_id_format',
            field=models.CharField(choices=[('urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified', 'Unspecified'), ('urn:oasis:names:tc:SAML:2.0:nameid-format:persistent', 'Persistent'), ('urn:oasis:names:tc:SAML:2.0:nameid-format:transient', 'Transient'), ('urn:oasis:names:tc:SAML:2.0:nameid-format:entity', 'Entity'), ('urn:oasis:names:tc:SAML:1.1:nameid-format:emailAddress', 'Email Address'), ('urn:oasis:names:tc:SAML:2.0:nameid-format:encrypted', 'Encrypted')], default='urn:oasis:names:tc:SAML:1.1:nameid-format:unspecified', help_text='Defines the name identifier format supported by the IdP.', max_length=64, verbose_name='Name ID Format'),
        ),
    ]
