# Generated by Django 3.2.3 on 2021-07-12 22:19

import authentication.utils
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0009_alter_basessoprovider_name_id_format'),
    ]

    operations = [
        migrations.AddField(
            model_name='basessoprovider',
            name='encryption_private_key_file',
            field=models.FileField(blank=True, help_text='If not provided, a Private Key will be generated.', null=True, storage=authentication.utils.ProservSamlFileSystemStorage(private=True), upload_to=authentication.utils.ProservSamlFileSystemStorage.get_file_path_for_instance, verbose_name='Encryption Private Key'),
        ),
        migrations.AddField(
            model_name='basessoprovider',
            name='encryption_public_key_file',
            field=models.FileField(blank=True, help_text='If not provided, a Public Key will be generated.', null=True, storage=authentication.utils.ProservSamlFileSystemStorage(), upload_to=authentication.utils.ProservSamlFileSystemStorage.get_file_path_for_instance, verbose_name='Encryption Public Key'),
        ),
    ]
