# Generated by Django 3.2.5 on 2021-10-27 19:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0010_auto_20210712_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='basessoprovider',
            name='digest_algorithm',
            field=models.CharField(choices=[('sha1', 'SHA1'), ('sha256', 'SHA256')], default='sha1', help_text='Algorithm used for the Digest Value in the SAML request to the IdP.', max_length=20, verbose_name='Digest Algorithm'),
        ),
        migrations.AddField(
            model_name='basessoprovider',
            name='signing_algorithm',
            field=models.CharField(choices=[('sha1', 'SHA1'), ('sha256', 'SHA256')], default='sha1', help_text='Algorithm used for the Signing Value in the SAML request to the IdP.', max_length=20, verbose_name='Signing Algorithm'),
        ),
    ]
