# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-29 09:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slayer', '0005_auto_20190102_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='slayernetwork',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Marks an IBM networs as public or private.'),
        ),
    ]
