# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-09 17:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slayer', '0007_slayernetwork_datacenter'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slayernetwork',
            name='is_public',
            field=models.BooleanField(default=True, help_text='Marks an IBM network as public or private.'),
        ),
    ]
