# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-11 18:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slayer', '0007_rename_ibm_slayer'),
        ('slayer', '0008_auto_20191209_1714'),
    ]

    operations = [
    ]
