# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-16 19:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('slayer', '0009_merge_20191211_1820'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='slayernetwork',
            options={'verbose_name': 'IBM Cloud Network'},
        ),
        migrations.AlterModelOptions(
            name='slayerosbuildattribute',
            options={'verbose_name': 'IBM Cloud OS Build Attribute'},
        ),
        migrations.AlterModelOptions(
            name='slayerresourcehandler',
            options={'verbose_name': 'IBM Cloud Resource Handler'},
        ),
    ]
