# Generated by Django 3.2.3 on 2021-09-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('slayer', '0011_auto_20191227_1024'),
    ]

    operations = [
        migrations.AlterField(
            model_name='slayerresourcehandler',
            name='clusterName',
            field=models.CharField(db_column='clustername', default='', max_length=100),
        ),
    ]
