# Generated by Django 2.2.10 on 2020-08-20 00:03

from django.db import migrations, models
import django.db.models.deletion
import driven_apps.common.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0041_bluecatendpoint'),
        ('accounts', '0052_auto_20200526_0144'),
        ('fuse_ipam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IpamReservation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip_address', models.CharField(max_length=256)),
                ('job_metadata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='naming.JobMetadata')),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuse_ipam.IpamPolicy')),
                ('workspace', models.ForeignKey(help_text='Workspace URL', on_delete=django.db.models.deletion.PROTECT, to='accounts.Group')),
            ],
            options={
                'verbose_name_plural': 'IPAM Reservations',
                'db_table': 'ipam_reservation',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(models.Model, driven_apps.common.mixins.RoleBasedHalFilteringMixin),
        ),
    ]
