# Generated by Django 2.2.10 on 2020-08-21 14:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_ipam', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='InfobloxIpamPolicy',
            fields=[
                ('ipampolicy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fuse_ipam.IpamPolicy')),
            ],
            options={
                'db_table': 'ipam_policies_infoblox',
                'ordering': ['id'],
                'abstract': False,
            },
            bases=('fuse_ipam.ipampolicy',),
        ),
    ]
