# Generated by Django 2.2.10 on 2020-08-21 20:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_ipam', '0002_ipamreservation'),
        ('fuse_ipam', '0002_infobloxipampolicy'),
    ]

    operations = [
    ]
