# Generated by Django 2.2.10 on 2020-09-10 14:42

from django.db import migrations
import django_extensions.db.fields.json
import driven_apps.fuse_ipam.validators.ipam_policy_validators


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_ipam', '0005_auto_20200904_1440'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipampolicy',
            name='excluded_ips',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=None, help_text='IP Addresses to be excluded from this IPAM policy', null=True, validators=[driven_apps.fuse_ipam.validators.ipam_policy_validators.IpamPolicyIPListValidator(field_name='excludedIps')]),
        ),
    ]
