# Generated by Django 2.2.10 on 2020-09-11 15:02

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_ipam', '0006_ipampolicy_excluded_ips'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipampolicy',
            name='excluded_ips',
        ),
    ]
