# Generated by Django 2.2.10 on 2020-09-17 13:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_ipam', '0007_remove_ipampolicy_excluded_ips'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenAndMiceIpamPolicy',
            fields=[
                ('ipampolicy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fuse_ipam.IpamPolicy')),
            ],
            options={
                'db_table': 'ipam_policy_men_anm_mice',
                'ordering': ['id'],
                'abstract': False,
            },
            bases=('fuse_ipam.ipampolicy',),
        ),
    ]
