# Generated by Django 2.2.10 on 2020-09-17 16:06

import common.fields
from django.db import migrations
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_ipam', '0007_remove_ipampolicy_excluded_ips'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipampolicy',
            name='nic_label',
            field=common.fields.TemplatableField(blank=True, help_text='The NIC label for the IPAM Policy', max_length=65536, null=True, validators=[driven_apps.common.validators.StringFieldValidator(blank=True, field_name='nicLabel', template=True)]),
        ),
        migrations.AddField(
            model_name='ipamreservation',
            name='nic_label',
            field=common.fields.TemplatableField(blank=True, help_text='The NIC label for the IPAM Reservation', max_length=65536, null=True, validators=[driven_apps.common.validators.StringFieldValidator(blank=True, field_name='nicLabel', template=True)]),
        ),
    ]
