# Generated by Django 2.2.10 on 2020-09-19 05:20

from django.db import migrations, models
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_ipam', '0008_auto_20200917_1606'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipampolicy',
            name='host_name_override',
            field=models.CharField(blank=True, help_text='The optional host name override for this IPAM policy.', max_length=1023, null=True, validators=[driven_apps.common.validators.DNSNameValidator(blank=True, field_name='hostNameOverride', template=True)]),
        ),
    ]
