# Generated by Django 2.2.10 on 2020-09-21 18:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_ipam', '0009_ipampolicy_host_name_override'),
        ('fuse_ipam', '0008_menandmiceipampolicy'),
    ]

    operations = [
    ]
