# Generated by Django 2.2.10 on 2020-09-21 17:54

import common.fields
from django.db import migrations
import driven_apps.common.validators
import driven_apps.fuse_ipam.validators.ipam_policy_validators


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_ipam', '0009_ipampolicy_host_name_override'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipampolicy',
            name='alternate_wins',
            field=common.fields.TemplatableField(blank=True, help_text='The optional alternate WINS server for this IPAM policy.', max_length=1023, null=True, validators=[driven_apps.common.validators.IPAddressValidator(blank=True, field_name='alternateWins', template=True)]),
        ),
        migrations.AddField(
            model_name='ipampolicy',
            name='dns_search_suffixes',
            field=common.fields.TemplatableField(blank=True, help_text='The optional preferred WINS server for this IPAM policy.', max_length=65536, null=True, validators=[driven_apps.fuse_ipam.validators.ipam_policy_validators.IpamPolicyHostAddressListValidator(blank=True, field_name='dnsSearchSuffixes', string_format=True, template=True)]),
        ),
        migrations.AddField(
            model_name='ipampolicy',
            name='dns_suffix',
            field=common.fields.TemplatableField(blank=True, help_text='The optional DNS suffix for this IPAM policy.', max_length=65536, null=True, validators=[driven_apps.common.validators.DNSNameValidator(blank=True, field_name='dnsSuffix', template=True)]),
        ),
        migrations.AddField(
            model_name='ipampolicy',
            name='preferred_wins',
            field=common.fields.TemplatableField(blank=True, help_text='The optional preferred WINS server for this IPAM policy.', max_length=1023, null=True, validators=[driven_apps.common.validators.IPAddressValidator(blank=True, field_name='preferredWins', template=True)]),
        ),
        migrations.AddField(
            model_name='ipampolicy',
            name='primary_dns',
            field=common.fields.TemplatableField(blank=True, help_text='The optional primary DNS server for this IPAM policy.', max_length=65536, null=True, validators=[driven_apps.common.validators.IPAddressValidator(blank=True, field_name='primaryDns', template=True)]),
        ),
        migrations.AddField(
            model_name='ipampolicy',
            name='secondary_dns',
            field=common.fields.TemplatableField(blank=True, help_text='The optional secondary DNS server for this IPAM policy.', max_length=65536, null=True, validators=[driven_apps.common.validators.IPAddressValidator(blank=True, field_name='secondaryDns', template=True)]),
        ),
        migrations.AddField(
            model_name='ipamreservation',
            name='alternate_wins',
            field=common.fields.TemplatableField(blank=True, help_text='The optional alternate WINS server for this IPAM reservation.', max_length=1023, null=True, validators=[driven_apps.common.validators.IPAddressValidator(blank=True, field_name='alternateWins', template=True)]),
        ),
        migrations.AddField(
            model_name='ipamreservation',
            name='dns_search_suffixes',
            field=common.fields.TemplatableField(blank=True, help_text='The optional preferred WINS server for this IPAM policy.', max_length=65536, null=True, validators=[driven_apps.fuse_ipam.validators.ipam_policy_validators.IpamPolicyHostAddressListValidator(blank=True, field_name='dnsSearchSuffixes', string_format=True, template=True)]),
        ),
        migrations.AddField(
            model_name='ipamreservation',
            name='dns_suffix',
            field=common.fields.TemplatableField(blank=True, help_text='The optional DNS suffix for this IPAM reservation.', max_length=65536, null=True, validators=[driven_apps.common.validators.DNSNameValidator(blank=True, field_name='dnsSuffix', template=True)]),
        ),
        migrations.AddField(
            model_name='ipamreservation',
            name='preferred_wins',
            field=common.fields.TemplatableField(blank=True, help_text='The optional preferred WINS server for this IPAM reservation.', max_length=1023, null=True, validators=[driven_apps.common.validators.IPAddressValidator(blank=True, field_name='preferredWins', template=True)]),
        ),
        migrations.AddField(
            model_name='ipamreservation',
            name='primary_dns',
            field=common.fields.TemplatableField(blank=True, help_text='The optional primary DNS server for this IPAM reservation.', max_length=65536, null=True, validators=[driven_apps.common.validators.IPAddressValidator(blank=True, field_name='primaryDns', template=True)]),
        ),
        migrations.AddField(
            model_name='ipamreservation',
            name='secondary_dns',
            field=common.fields.TemplatableField(blank=True, help_text='The optional secondary DNS server for this IPAM reservation.', max_length=65536, null=True, validators=[driven_apps.common.validators.IPAddressValidator(blank=True, field_name='secondaryDns', template=True)]),
        ),
    ]
