# Generated by Django 2.2.10 on 2020-09-22 16:57

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_ipam', '0010_auto_20200921_1754'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipampolicy',
            name='alternate_wins',
        ),
        migrations.RemoveField(
            model_name='ipampolicy',
            name='preferred_wins',
        ),
        migrations.RemoveField(
            model_name='ipamreservation',
            name='alternate_wins',
        ),
        migrations.RemoveField(
            model_name='ipamreservation',
            name='preferred_wins',
        ),
    ]
