# Generated by Django 2.2.10 on 2020-09-22 00:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_ipam', '0010_merge_20200921_1810'),
        ('fuse_ipam', '0010_auto_20200921_1754'),
    ]

    operations = [
    ]
