# Generated by Django 2.2.10 on 2020-09-23 16:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_ipam', '0011_auto_20200922_1657'),
        ('fuse_ipam', '0011_merge_20200922_0032'),
    ]

    operations = [
    ]
