# Generated by Django 2.2.10 on 2020-09-24 14:02

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_ipam', '0011_auto_20200922_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipamreservation',
            name='subnet',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=None, help_text='Subnet entry for this IPAM Reservation.', null=True),
        ),
    ]
