# Generated by Django 2.2.10 on 2020-09-23 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_ipam', '0012_merge_20200923_1651'),
    ]

    operations = [
        migrations.AlterModelTable(
            name='menandmiceipampolicy',
            table='ipam_policy_men_and_mice',
        ),
    ]
