# Generated by Django 2.2.10 on 2020-09-24 16:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_ipam', '0012_ipamreservation_subnet'),
        ('fuse_ipam', '0013_auto_20200923_2004'),
    ]

    operations = [
    ]
