# Generated by Django 2.2.10 on 2020-09-25 20:16

import common.fields
from django.db import migrations
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_ipam', '0015_auto_20200925_1454'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='ipampolicy',
            name='host_name_override',
        ),
        migrations.AddField(
            model_name='ipampolicy',
            name='hostname_override',
            field=common.fields.TemplatableField(blank=True, default='{{request.hostname}}', help_text='The optional hostname override for this IPAM policy.', max_length=65536, validators=[driven_apps.common.validators.StringFieldValidator(blank=True, field_name='hostnameOverride', template=True)]),
        ),
    ]
