# Generated by Django 2.2.10 on 2020-10-07 16:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_ipam', '0016_auto_20200925_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipamreservation',
            name='hostname',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
