# Generated by Django 2.2.16 on 2020-10-20 22:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_ipam', '0017_auto_20201007_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipamreservation',
            name='ip_address',
            field=models.CharField(blank=True, max_length=256, null=True),
        ),
    ]
