# Generated by Django 2.2.16 on 2021-04-14 16:18

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
        ('fuse_ipam', '0021_solarwindsipampolicy'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipamreservation',
            name='ingest_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.IngestEvent'),
        ),
    ]
