# Generated by Django 2.2.16 on 2021-06-10 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_ipam', '0022_ipamreservation_ingest_event'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftIpamPolicy',
            fields=[
                ('ipampolicy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='fuse_ipam.IpamPolicy')),
            ],
            options={
                'db_table': 'ipam_policy_microsoft',
                'ordering': ['id'],
                'abstract': False,
            },
            bases=('fuse_ipam.ipampolicy',),
        ),
    ]
