# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-24 21:54
from __future__ import unicode_literals

from django.db import migrations


def rename_osx_to_macos(apps, schema_editor):
    OSFamily = apps.get_model("externalcontent", "OSFamily")
    osf = OSFamily.objects.filter(name="OS X").first()
    if not osf:
        # perhaps cb_minimal had not been imported with the OS Family name "OS X"
        return
    osf.name = "macOS"
    osf.save()


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontent', '0003_auto_20161004_2121'),
    ]

    operations = [
        migrations.RunPython(rename_osx_to_macos, migrations.RunPython.noop),
    ]
