# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-25 15:06
from __future__ import unicode_literals

from django.db import migrations


def remove_old_macos_osfam(apps, schema_editor):
    """
    If OSF "Linux / macOS exists", delete it. Importing cb_min will recreate it in the right place
    (under Unix)
    """
    OSFamily = apps.get_model("externalcontent", "OSFamily")
    OSFamily.objects.filter(name="macOS", parent__name="Linux").delete()


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontent', '0004_auto_20170324_2154'),
    ]

    operations = [
        migrations.RunPython(remove_old_macos_osfam, migrations.RunPython.noop),
    ]
