# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 21:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourcehandlers', '0009_auto_20171212_1729'),
        ('externalcontent', '0005_auto_20170325_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='osbuildattribute',
            name='resourcehandler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='resourcehandlers.ResourceHandler'),
        ),
    ]
