# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-03 16:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontent', '0008_auto_20180503_0042'),
    ]

    operations = [
        migrations.AddField(
            model_name='osbuildattribute',
            name='_name',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
