# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-03 18:03
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontent', '0010_copy_template_name_to_osba_20180503_1658'),
        # rename the other 'template_name's to 'old_template_name' before renaming this field to 'template_name'
        ('acropolis', '0003_auto_20180503_1800'),
        ('azure_arm', '0026_auto_20180503_1800'),
        ('hyperv', '0010_auto_20180503_1800'),
        ('libcloudhandler', '0005_auto_20180503_1800'),
        ('qemu', '0006_auto_20180503_1800'),
        ('slayer', '0004_auto_20180503_1800'),
        ('vmware', '0014_auto_20180503_1800'),
        ('xen', '0004_auto_20180503_1800'),
    ]

    operations = [
        migrations.RenameField(
            model_name='osbuildattribute',
            old_name='_name',
            new_name='template_name',
        ),
    ]
