# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-23 11:37
from __future__ import unicode_literals

from django.db import migrations

from common.mixins import get_global_id_chars


def set_global_ids(apps, schema_editor):
    """
    Set random values with appropriate prefixes for the global_id field on
    all existing Applications. The initial schema migration to add the field to the
    Application model by way of the GlobalIDForAPIMixin will leave all Applications
    with the same 8 random characters (and no prefix yet) because the function
    is only called once to calculate the default value for the entire new column
    (https://stackoverflow.com/a/42497696).
    Therefore, we regenerate the 8 random characters to make them different
    across the Applications and then add the prefix, like would be done by
    the custom save method for normal object creation.
    """
    Application = apps.get_model('externalcontent', 'Application')
    prefix = 'APP-'
    for app in Application.objects.all():
        chars = get_global_id_chars()
        app.global_id = '{}{}'.format(prefix, chars)
        app.save()


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontent', '0015_application_global_id'),
    ]

    operations = [
        migrations.RunPython(set_global_ids,
                             migrations.RunPython.noop),
    ]
