# Generated by Django 2.2.10 on 2020-10-19 17:09

import common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontent', '0016_set_app_ids_20190923_1137'),
    ]

    operations = [
        migrations.AlterField(
            model_name='application',
            name='global_id',
            field=models.CharField(default=common.mixins.get_global_id_chars, help_text='Identifier that can be used to access this object through the API across instances.', max_length=16, verbose_name='Global ID'),
        ),
        migrations.AlterField(
            model_name='osbuild',
            name='global_id',
            field=models.CharField(default=common.mixins.get_global_id_chars, help_text='Identifier that can be used to access this object through the API across instances.', max_length=16, verbose_name='Global ID'),
        ),
    ]
