# Generated by Django 2.2.16 on 2021-02-25 17:59

from django.db import migrations
from common.mixins import get_global_id_chars

class Migration(migrations.Migration):
    def set_global_ids(apps, schema_editor):
        ImageModel = apps.get_model('externalcontent', 'OSBuildAttribute')
        prefix = 'IMG'
        for row in ImageModel.objects.all():
            chars = get_global_id_chars()
            row.global_id = f'{prefix}-{chars}'
            row.save()

    dependencies = [
        ('externalcontent', '0018_os_build_attribute_global_id'),
    ]

    operations = [
        migrations.RunPython(set_global_ids, migrations.RunPython.noop),
    ]
