# Generated by Django 2.2.16 on 2021-02-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontent', '0018_auto_20210218_1007'),
        ('externalcontent', '0019_set_global_id_for_os_build_attribute'),
    ]

    operations = [
    ]
