# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('services', '0003_service_parent_service'),
        ('containerorchestrators', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ContainerResource',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('ACTIVE', 'Active'), ('HISTORICAL', 'Historical')], default='ACTIVE', max_length=10)),
                ('container_orchestrator', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='containerorchestrators.ContainerOrchestrator')),
                ('real_type', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
                ('service', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_resources', to='services.Service')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
