# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 20:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containerorchestrators', '0002_containerresource'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerresource',
            name='container_orchestrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='containerorchestrators.ContainerOrchestrator'),
        ),
    ]
