# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-08 17:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containerorchestrators', '0003_make_container_orchestrator_nullable'),
    ]

    operations = [
        migrations.RenameField(
            model_name='containerresource',
            old_name='service',
            new_name='resource',
        ),
    ]
