# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-19 18:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containerorchestrators', '0005_auto_20180202_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerresource',
            name='resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_objects', to='resources.Resource'),
        ),
        migrations.AlterField(
            model_name='containerresource',
            name='container_orchestrator',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='container_objects', to='containerorchestrators.ContainerOrchestrator'),
        ),
    ]
