# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-23 13:45
from __future__ import unicode_literals

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containerorchestrators', '0006_rename_related_objects_to_container_objects'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerorchestrator',
            name='port',
            field=models.IntegerField(blank=True, help_text='Port used to connect to this resource handler', null=True, validators=[common.validators.is_only_digits]),
        ),
    ]
