# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-25 21:21
from __future__ import unicode_literals

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('containerorchestrators', '0007_auto_20180823_1345'),
    ]

    operations = [
        migrations.AlterField(
            model_name='containerorchestrator',
            name='ip',
            field=models.CharField(max_length=255, validators=[common.validators.validate_domain_or_ip], verbose_name='IP address'),
        ),
    ]
