# Generated by Django 2.2.16 on 2021-02-10 14:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('containerorchestrators', '0009_auto_20191204_2219'),
    ]

    operations = [
        migrations.AddField(
            model_name='containerorchestrator',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant'),
        ),
    ]
