# Generated by Django 2.2.16 on 2021-02-09 03:37

from django.db import migrations
from common.mixins import get_global_id_chars

class Migration(migrations.Migration):

    def set_global_ids(apps, schema_editor):
        ContainerOrchestratorModel = apps.get_model('containerorchestrators', 'ContainerOrchestrator')
        prefix = 'COR'
        for row in ContainerOrchestratorModel.objects.all():
            chars = get_global_id_chars()
            row.global_id = f'{prefix}-{chars}'
            row.save()

    dependencies = [
        ('containerorchestrators', '0010_container_orchestrators_global_id'),
    ]

    operations = [
        migrations.RunPython(set_global_ids, migrations.RunPython.noop),
    ]
