# Generated by Django 2.2.16 on 2021-02-17 21:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('containerorchestrators', '0011_set_global_id_for_containerorchestrators'),
        ('containerorchestrators', '0010_containerorchestrator_tenant'),
    ]

    operations = [
    ]
