# Generated by Django 2.2.12 on 2020-06-30 18:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('network_virtualization', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSXTNetworkVirtualization',
            fields=[
                ('networkvirtualization_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='network_virtualization.NetworkVirtualization')),
            ],
            options={
                'abstract': False,
            },
            bases=('network_virtualization.networkvirtualization',),
        ),
    ]
