# Generated by Django 2.2.12 on 2020-07-08 13:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('nsx_t', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NSXTTransportZone',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('uuid', models.CharField(editable=False, max_length=100)),
                ('_raw_json_representation', models.TextField(help_text='JSON representation of the dictionary of name/value pairs returned by the 3rd party API.')),
                ('real_type', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='NSXTLogicalRouterGateway',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('display_name', models.CharField(max_length=100)),
                ('uuid', models.CharField(editable=False, max_length=100)),
                ('_raw_json_representation', models.TextField(help_text='JSON representation of the dictionary of name/value pairs returned by the 3rd party API.')),
                ('router_type', models.CharField(editable=False, max_length=500)),
                ('real_type', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
