# Generated by Django 2.2.12 on 2020-07-08 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_virtualization', '0003_networkvirtualization_enable_ssl_verification'),
        ('nsx_t', '0002_nsxtlogicalroutergateway_nsxttransportzone'),
    ]

    operations = [
        migrations.AddField(
            model_name='nsxtlogicalroutergateway',
            name='network_virtualization',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='network_virtualization.NetworkVirtualization'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nsxttransportzone',
            name='network_virtualization',
            field=models.ForeignKey(default=-1, on_delete=django.db.models.deletion.CASCADE, to='network_virtualization.NetworkVirtualization'),
            preserve_default=False,
        ),
    ]
