# Generated by Django 2.2.16 on 2021-01-16 00:01

from django.db import migrations
from common.mixins import get_global_id_chars

class Migration(migrations.Migration):

    def set_global_ids(apps, schema_editor):
        LoadBalancerAppliance = apps.get_model('loadbalancers', 'LoadBalancerAppliance')
        prefix = 'LBA'
        for row in LoadBalancerAppliance.objects.all():
            chars = get_global_id_chars()
            row.global_id = f'{prefix}-{chars}'
            row.save()

    dependencies = [
        ('loadbalancers', '0002_loadbalancerapplication_global_id'),
    ]

    operations = [
        migrations.RunPython(set_global_ids, migrations.RunPython.noop),
    ]
