# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-10 15:20
from __future__ import unicode_literals

from django.db import migrations


def rename_old_vco_tech(apps, schema_editor):
    """
    If a vco Orchestration Tech with the old name exists, we update it.
    Importing cb_min will create it on fresh installs but this migration addresses existing
    customers that might have the tech with the old name in use..
    """
    OrchTech = apps.get_model("orchestrationengines", "OrchestrationTechnology")
    for ot in OrchTech.objects.filter(name="vCenter Orchestrator"):
        ot.name = "vCenter/vRealize Orchestrator"
        ot.version = "5.5 - 7.0.1+"
        ot.save()


class Migration(migrations.Migration):

    dependencies = [
        ('orchestrationengines', '0002_auto_20161004_2141'),
    ]

    operations = [
        migrations.RunPython(rename_old_vco_tech, migrations.RunPython.noop),
    ]
