# Generated by Django 2.2.10 on 2020-09-01 17:40

from django.db import migrations, models
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dnspolicy',
            name='create_ptr_record',
            field=models.BooleanField(default=False, help_text='Create the Ptr Record', validators=[driven_apps.common.validators.BooleanFieldValidator(field_name='createPtrRecord')]),
        ),
        migrations.AlterField(
            model_name='dnspolicy',
            name='post_validate_ptr_record',
            field=models.BooleanField(default=False, help_text='Post-validate the Ptr Record', validators=[driven_apps.common.validators.BooleanFieldValidator(field_name='postValidatePtrRecord')]),
        ),
        migrations.AlterField(
            model_name='dnspolicy',
            name='pre_validate_ptr_record',
            field=models.BooleanField(default=False, help_text='Pre-validate the Ptr Record', validators=[driven_apps.common.validators.BooleanFieldValidator(field_name='preValidatePtrRecord')]),
        ),
    ]
