# Generated by Django 2.2.10 on 2020-09-14 21:03

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0005_auto_20200910_2232'),
    ]

    operations = [
        migrations.CreateModel(
            name='MenAndMiceDnsPolicy',
            fields=[
                ('dnspolicy_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='dns.DnsPolicy')),
            ],
            options={
                'db_table': 'dns_policies_men_and_mice',
                'ordering': ['id'],
                'abstract': False,
            },
            bases=('dns.dnspolicy',),
        ),
    ]
