# Generated by Django 2.2.16 on 2021-06-07 16:40

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
        ('dns', '0008_auto_20210126_1922'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnsreservation',
            name='ingest_event',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='ingest.IngestEvent'),
        ),
    ]
