# Generated by Django 3.2.3 on 2021-06-29 13:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0009_dnsreservation_ingest_event'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='dnsreservation',
            name='ingest_event',
        ),
    ]
