# Generated by Django 3.2.3 on 2021-09-30 18:11

from django.db import migrations, models
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('dns', '0010_remove_dnsreservation_ingest_event'),
    ]

    operations = [
        migrations.AddField(
            model_name='dnspolicy',
            name='create_c_name_record',
            field=models.BooleanField(default=False, help_text='Create the CNAME Record', validators=[driven_apps.common.validators.BooleanFieldValidator(field_name='createCNameRecord')]),
        ),
        migrations.AddField(
            model_name='dnspolicy',
            name='post_validate_c_name_record',
            field=models.BooleanField(default=False, help_text='Post-validate the CNAME Record', validators=[driven_apps.common.validators.BooleanFieldValidator(field_name='postValidateCNameRecord')]),
        ),
        migrations.AddField(
            model_name='dnspolicy',
            name='pre_validate_c_name_record',
            field=models.BooleanField(default=False, help_text='Pre-validate the CNAME Record', validators=[driven_apps.common.validators.BooleanFieldValidator(field_name='preValidateCNameRecord')]),
        ),
    ]
