# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0030_auto_20180202_1944'),
        ('resources', '0002_move_services_app_objs_to_resources_app_20180201_1903'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetype',
            name='list_view_columns',
            field=models.ManyToManyField(blank=True, help_text='The parameters to show as additional columns when viewing a list of Resources of this type.', to='infrastructure.CustomField', verbose_name='Resource List View Columns'),
        ),
    ]
