# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-05 19:14
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resourcetype_list_view_columns'),
        ('resources', '0003_resourcetype_icon'),
    ]

    operations = [
    ]
