# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-21 12:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0003_resource_misc_rate'),
        ('resources', '0004_merge_20180305_1914'),
    ]

    operations = [
    ]
