# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-21 19:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0005_merge_20180321_1224'),
        ('resources', '0004_auto_20180306_0115'),
    ]

    operations = [
    ]
