# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-17 01:01
from __future__ import unicode_literals

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0009_auto_20190607_1527'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetype',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='resourcetype',
            name='name',
            field=models.CharField(help_text='Alphanumeric characters, starting with a letter, with optional underscores.', max_length=50, unique=True, validators=[common.validators.valid_python_identifier], verbose_name='Name'),
        ),
    ]
