# Generated by Django 2.2.16 on 2021-05-18 03:42

import common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0012_set_global_id_for_resource_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='resource',
            name='global_id',
            field=models.CharField(default=common.mixins.get_global_id_chars, help_text='Identifier that can be used to access this object through the API across instances.', max_length=16, verbose_name='Global ID'),
        ),
    ]
