# Generated by Django 2.2.16 on 2021-05-18 03:45

from django.db import migrations
from common.mixins import get_global_id_chars

class Migration(migrations.Migration):

    def set_global_ids(apps, schema_editor):
        ResourceModel = apps.get_model("resources", "Resource")
        prefix = "RSC"
        for row in ResourceModel.objects.all():
            chars = get_global_id_chars()
            row.global_id = f"{prefix}-{chars}"
            row.save()

    dependencies = [
        ('resources', '0013_resource_global_id'),
    ]

    operations = [
        migrations.RunPython(set_global_ids, migrations.RunPython.noop),
    ]
