# Generated by Django 2.2.16 on 2021-06-21 16:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resources', '0014_set_global_id_for_resources'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcetype',
            name='icon',
            field=models.CharField(blank=True, default='', help_text='Optionally provide a special icon to be displayed for this Resource Type. Must correspond to an available icon name, such as "icon-delete", "glyphicon glyphicon-time", or "fas fa-heartbeat". For more examples, see <a href="http://fortawesome.github.io/Font-Awesome/icons/">Font Awesome</a> and <a href="https://getbootstrap.com/docs/3.3/components/">Glyphicons</a>.', max_length=255),
        ),
    ]
