# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-26 23:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcehandlers', '0002_auto_20161004_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcetechnology',
            name='slug',
            field=models.SlugField(blank=1, max_length=100, verbose_name='Slugified name of the resource technology (ex. vmware)'),
        ),
    ]
