# -*- coding: utf-8 -*-

# Generated by Django 1.11.3 on 2017-07-21 14:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcehandlers', '0003_resourcetechnology_slug'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcehandler',
            name='enable_ssl_verification',
            field=models.BooleanField(default=True, help_text='When disabled, SSL certificates will not be verified when connecting to this resource handler.', verbose_name='SSL Verification'),
        ),
    ]
