# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-07 20:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcehandlers', '0006_auto_20170927_1034'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcehandler',
            name='enable_console_feature',
            field=models.BooleanField(default=True, help_text='Enables users to get console on servers which have this Resource Handler.', verbose_name='Console feature'),
        ),
    ]
