# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-12 17:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcehandlers', '0008_auto_20171212_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcehandler',
            name='enable_console_feature',
            field=models.BooleanField(default=True, help_text='Enables users to use the console on servers with this Resource Handler.', verbose_name='Console feature'),
        ),
    ]
