# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-26 10:01
from __future__ import unicode_literals

from django.db import migrations, models
from django.db.migrations.state import StateApps


def fwd_migrate_terminal_setting(apps: StateApps, schema_editor):
    GlobalPreferences = apps.get_model("utilities", "GlobalPreferences")
    db = schema_editor.connection.alias

    try:
        gp = GlobalPreferences.objects.using(db).get()
    except GlobalPreferences.DoesNotExist:
        return

    if gp.enable_remote_feature:
        ResourceHandler = apps.get_model("resourcehandlers", "ResourceHandler")
        for rh in ResourceHandler.objects.using(db).all():
            rh.enable_terminal_feature = True
            rh.save()


def rev_migrate_terminal_setting(apps: StateApps, schema_editor):
    pass


class Migration(migrations.Migration):
    dependencies = [
        ('resourcehandlers', '0010_auto_20180523_1626'),
        ('utilities', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcehandler',
            name='enable_terminal_feature',
            field=models.BooleanField(default=False,
                                      help_text='Enables access to the integrated RDP/SSH terminal for this Resource Handler.',
                                      verbose_name='RDP/SSH Terminal'),
        ),

        migrations.RunPython(
            fwd_migrate_terminal_setting,
            reverse_code=rev_migrate_terminal_setting,
        )
    ]
