# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-20 21:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0002_auto_20190605_2238'),
        ('resourcehandlers', '0012_auto_20190501_1815'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcenetwork',
            name='ipam_networks',
            field=models.ManyToManyField(blank=True, to='ipam.IPAMNetwork'),
        ),
    ]
