# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-13 22:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourcehandlers', '0013_resourcenetwork_ipam_networks'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='resourcenetwork',
            name='ipam_networks',
        ),
    ]
