# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-13 22:36
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0005_auto_20190710_1848'),
        ('resourcehandlers', '0014_remove_resourcenetwork_ipam_networks'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcenetwork',
            name='ipam_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='resource_networks', to='ipam.IPAMNetwork'),
        ),
    ]
