# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-17 01:01
from __future__ import unicode_literals

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcehandlers', '0015_resourcenetwork_ipam_network'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcehandler',
            name='description',
            field=models.TextField(blank=True, help_text='Optional. Explain purpose or details about this resource handler.', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='resourcehandler',
            name='ignore_vm_folders',
            field=models.TextField(blank=True, help_text='A comma separated list of the folders of VMs to exclude during VM synchronization. These folders names are regular expressions. Example: <code>Secure Servers.*, AD Servers</code>. Specifying this field will slow down VM synchronization jobs for some technologies (ex. VMware). If a rule is introduced which ignores a VM already managed by CloudBolt, that VM will be marked historical in CloudBolt after the next sync.', null=True, verbose_name='VM Folders To Ignore'),
        ),
        migrations.AlterField(
            model_name='resourcehandler',
            name='ignore_vm_names',
            field=models.TextField(blank=True, help_text='A comma separated list of the names of VMs to exclude during VM synchronization. These names are regular expressions, and any whitespace surrounding each rule will be ignored. Example: <code> proddb.*, joetest1, .*qalab.*</code>. If a rule is introduced which ignores a VM already managed by CloudBolt, that VM will be marked historical in CloudBolt after the next sync.', null=True, verbose_name='VM Names to Ignore'),
        ),
        migrations.AlterField(
            model_name='resourcehandler',
            name='name',
            field=models.CharField(help_text='Display name. Not used in any programmatic fashion and can be changed safely.', max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='resourcehandler',
            name='port',
            field=models.IntegerField(default=443, help_text='Port used to connect to this resource handler', validators=[common.validators.is_only_digits], verbose_name='Port'),
        ),
        migrations.AlterField(
            model_name='resourcehandler',
            name='protocol',
            field=models.CharField(choices=[('http', 'http'), ('https', 'https'), ('ssh', 'ssh'), ('udp', 'udp')], help_text='Protocol used to connect to this resource handler', max_length=10, verbose_name='Protocol'),
        ),
    ]
