# Generated by Django 2.2.10 on 2020-04-28 17:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcehandlers', '0017_auto_20191107_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcehandler',
            name='include_vm_tags',
            field=models.TextField(blank=True, help_text='A comma separated list of the tags in which to restrict VM Synchronization to. If no tags are listed, CloudBolt will synchronize all VMs. The tag names are regular expressions. If a rule is introduced which ignores a VM already managed by CloudBolt, that VM will be marked historical in CloudBolt after the next sync.', null=True, verbose_name='VM Tags to Include'),
        ),
    ]
