# Generated by Django 2.2.16 on 2021-02-09 13:36

import common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0011_gcphandler_remove_global_id'),
        ('resourcehandlers', '0019_auto_20200925_1322'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcehandler',
            name='global_id',
            field=models.CharField(default=common.mixins.get_global_id_chars, help_text='Identifier that can be used to access this object through the API across instances.', max_length=16, verbose_name='Global ID'),
        ),
    ]
