# Generated by Django 2.2.16 on 2021-06-07 18:30

from django.db import migrations, connection

# Since this is a migration to remove an app that may or may not exist in
# the database, we can not use any of the normal DeleteModel, etc, everything
# has to be done explicitly through SQL. And if the table to remove does
# not exist we don't want to throw an error.  For that reason, and to help
# prevent errors during reverse migrations, the deleted tables are added back
# in the reverse_sql attribute. The intention of this is not to make the feature
# usable

APP_TO_REMOVE = "azure"


def get_id_to_remove(apps, schema_editor):
    ResourceTechnology = apps.get_model('resourcehandlers', 'ResourceTechnology')
    if ResourceTechnology.objects.filter(name="Azure Classic").exists():
        return ResourceTechnology.objects.get(name="Azure Classic").id
    else:
        return -1


def remove_azure_networks(apps, schema_editor):
    ResourceNetwork = apps.get_model('resourcehandlers', 'ResourceNetwork')
    if ResourceNetwork.objects.filter(real_type__model="azuresubnet").exists():
        ResourceNetwork.objects.filter(real_type__model="azuresubnet").delete()


def remove_azure_resource_handlers(apps, schema_editor):
    ResourceHandler = apps.get_model('resourcehandlers', 'ResourceHandler')
    tech_id = get_id_to_remove(apps, schema_editor)
    if ResourceHandler.objects.filter(resource_technology_id=tech_id).exists():
        ResourceHandler.objects.filter(resource_technology_id=tech_id).delete()


def remove_azure_from_technology(apps, schema_editor):
    ResourceTechnology = apps.get_model('resourcehandlers', 'ResourceTechnology')
    tech_id = get_id_to_remove(apps, schema_editor)
    if tech_id != -1:
        ResourceTechnology.objects.filter(id=tech_id).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('resourcehandlers', '0023_retire_terremark'),
    ]

    # We are dynamically building the operations array to avoid deletions from
    # tables that don't exist
    operations = []

    # Query all table names in the db so we can add appropriate DELETES/DROPS
    all_tables = connection.introspection.table_names()

    if 'azure_azurehandler_networks' in all_tables:
        operations.append(migrations.RunSQL(
            sql=['DELETE FROM azure_azurehandler_networks;',],
            reverse_sql= [],)
        )
    operations.append(migrations.RunSQL(
        sql=['DROP TABLE IF EXISTS azure_azurehandler_networks CASCADE;'],
        reverse_sql= [""" CREATE TABLE `azure_azurehandler_networks` (
            `id` int(11) NOT NULL AUTO_INCREMENT,
            `azurehandler_id` int(11) NOT NULL,
            `azuresubnet_id` int(11) NOT NULL,
            PRIMARY KEY (`id`));
        """ ],)
    )

    # This is a lecacy table and only impacts old installations of CloudBolt that was not cleaned up when depracated.
    # There is no reverse SQL for this because we do not want to create this table since it is no longer part of the product.
    operations.append(migrations.RunSQL(
        sql=["DROP TABLE IF EXISTS azure_azurehandler_os_build_attributes CASCADE;"],
        reverse_sql=[],
    ))

    if 'azure_azurehandler' in all_tables:
        operations.append(migrations.RunSQL(
            sql=['DELETE FROM azure_azurehandler;',],
            reverse_sql= [],)
        )
    operations.append(migrations.RunSQL(
        sql=['DROP TABLE IF EXISTS azure_azurehandler CASCADE;'],
        reverse_sql= [""" CREATE TABLE `azure_azurehandler` (
            `resourcehandler_ptr_id` int(11) NOT NULL,
            PRIMARY KEY (`resourcehandler_ptr_id`));
        """ ],)
    )

    if 'azure_azureimage' in all_tables:
        operations.append(migrations.RunSQL(
            sql=['DELETE FROM azure_azureimage;',],
            reverse_sql= [],)
        )
    operations.append(migrations.RunSQL(
        sql=['DROP TABLE IF EXISTS azure_azureimage CASCADE;'],
        reverse_sql= [""" CREATE TABLE `azure_azureimage` (
            `osbuildattribute_ptr_id` int(11) NOT NULL,
            `azure_image_name` varchar(255) NOT NULL,
            `location_availability` varchar(255) NOT NULL,
            `total_disk_size` decimal(10,4) DEFAULT NULL,
            PRIMARY KEY (`osbuildattribute_ptr_id`));
        """ ],)
    )

    if 'azure_azureserverinfo' in all_tables:
        operations.append(migrations.RunSQL(
            sql=['DELETE FROM azure_azureserverinfo;',],
            reverse_sql= [],)
        )
    operations.append(migrations.RunSQL(
        sql=['DROP TABLE IF EXISTS azure_azureserverinfo CASCADE;'],
        reverse_sql= [""" CREATE TABLE `azure_azureserverinfo` (
            `server_id` int(11) NOT NULL,
            `location` varchar(100) NOT NULL,
            `deployment` varchar(100) NOT NULL,
            `hosted_service` varchar(100) NOT NULL,
            PRIMARY KEY (`server_id`));
        """ ],)
    )

    if 'azure_azuresubnet' in all_tables:
        operations.append(migrations.RunSQL(
            sql=['DELETE FROM azure_azuresubnet;',],
            reverse_sql= [],)
        )
    operations.append(migrations.RunSQL(
        sql=['DROP TABLE IF EXISTS azure_azuresubnet CASCADE;'],
        reverse_sql= [""" CREATE TABLE `azure_azuresubnet` (
            `resourcenetwork_ptr_id` int(11) NOT NULL,
            `cidr_block` varchar(30) NOT NULL,
            `parent_network` varchar(30) NOT NULL,
            PRIMARY KEY (`resourcenetwork_ptr_id`));
        """ ],)
    )

    # Letting Python handle deletions of objects that will still exist, including the
    # associated ResourceTechnology and any parent objects for child models removed in the SQL above
    operations.append(migrations.RunPython(remove_azure_networks, migrations.RunPython.noop))
    operations.append(migrations.RunPython(remove_azure_resource_handlers, migrations.RunPython.noop))
    operations.append(migrations.RunPython(remove_azure_from_technology, migrations.RunPython.noop))

    # These calls shouldn't need customizing
    operations.append(migrations.RunSQL(
        sql=[f"DELETE FROM django_migrations where app='{APP_TO_REMOVE}';"],
        reverse_sql=[], )
    )
    if 'auth_permission' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM auth_permission WHERE content_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'django_admin_log' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM django_admin_log WHERE content_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'alerts_alertchannel' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM alerts_alertchannel WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'cbhooks_orchestrationhook' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM cbhooks_orchestrationhook WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'connectors_connectorconf' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM connectors_connectorconf WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'containerorchestrators_containerorchestrator' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM containerorchestrators_containerorchestrator WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'containerorchestrators_containerresource' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM containerorchestrators_containerresource WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'cscv_cittest' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM cscv_cittest WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'dataprotection_dataprotection' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM dataprotection_dataprotection WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'dns_policies' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM dns_policies WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'endpoints' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM endpoints WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'externalcontent_osbuildattribute' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM externalcontent_osbuildattribute WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'externalcontent_vendorapplication' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM externalcontent_vendorapplication WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'history_historymodel' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM history_historymodel WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'infrastructure_disk' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM infrastructure_disk WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'infrastructure_diskstorage' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM infrastructure_diskstorage WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'infrastructure_servernetworkcard' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM infrastructure_servernetworkcard WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'ipam_availableipamnetwork' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM ipam_availableipamnetwork WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'ipam_ipam' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM ipam_ipam WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'ipam_ipamnetwork' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM ipam_ipamnetwork WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'ipam_policy' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM ipam_policy WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'itsm_itsm' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM itsm_itsm WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'jobs_cfvchangeparameters' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM jobs_cfvchangeparameters WHERE content_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'jobs_jobparameters' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM jobs_jobparameters WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'jobs_recurringjob' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM jobs_recurringjob WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'network_virtualization_networkvirtualization' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM network_virtualization_networkvirtualization WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'networks_loadbalancer' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM networks_loadbalancer WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'nsx_t_nsxtlogicalroutergateway' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM nsx_t_nsxtlogicalroutergateway WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'nsx_t_nsxttransportzone' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM nsx_t_nsxttransportzone WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'orchestrationengines_orchestrationengine' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM orchestrationengines_orchestrationengine WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'orders_actionjoborderitem' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM orders_actionjoborderitem WHERE content_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'provisionengines_provisionengine' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM provisionengines_provisionengine WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'resourcehandlers_resourcehandler' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM resourcehandlers_resourcehandler WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'reversion_version' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM reversion_version WHERE content_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'servicecatalog_serviceitem' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM servicecatalog_serviceitem WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'siem_siemprovider' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM siem_siemprovider WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'sso_basessoprovider' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM sso_basessoprovider WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'taggit_taggeditem' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM taggit_taggeditem WHERE content_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'tags_taggeditem' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM tags_taggeditem WHERE content_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'utilities_sshkey' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM utilities_sshkey WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )
    if 'vra_policies' in all_tables:
        operations.append(migrations.RunSQL(
            sql=[
                f"DELETE FROM vra_policies WHERE real_type_id in (SELECT id FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}');"],
            reverse_sql=[], )
        )

    operations.append(migrations.RunSQL(
        sql=[f"DELETE FROM django_content_type WHERE app_label = '{APP_TO_REMOVE}';"],
        reverse_sql=[], )
    )
