# Generated by Django 3.2.3 on 2021-06-28 18:46

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourcehandlers', '0024_retire_azure_classic_20210607_1830'),
        ('resourcehandlers', '0024_retire_centurylink_20210607_1927'),
    ]

    operations = [
    ]
