# Generated by Django 2.2.16 on 2021-07-12 13:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('resourcehandlers', '0026_retire_rhev'),
        ('resourcehandlers', '0026_retire_oracle_20210707_2024'),
    ]

    operations = [
    ]
