# Generated by Django 3.2.3 on 2021-08-02 23:57

import common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('resourcehandlers', '0027_merge_20210712_1328'),
    ]

    operations = [
        migrations.AddField(
            model_name='resourcenetwork',
            name='global_id',
            field=models.CharField(default=common.mixins.get_global_id_chars, help_text='Identifier that can be used to access this object through the API across instances.', max_length=16, verbose_name='Global ID'),
        ),
    ]
