# Generated by Django 3.2.3 on 2021-08-02 23:59

from django.db import migrations

from common.mixins import get_global_id_chars


class Migration(migrations.Migration):

    def set_global_ids(apps, schema_editor):
        ResourceNetwork = apps.get_model("resourcehandlers", "ResourceNetwork")
        prefix = "NET"
        for row in ResourceNetwork.objects.all():
            chars = get_global_id_chars()
            row.global_id = f"{prefix}-{chars}"
            row.save()

    dependencies = [
        ('resourcehandlers', '0028_resource_network_global_id'),
    ]

    operations = [
        migrations.RunPython(set_global_ids, migrations.RunPython.noop)
    ]
