# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-31 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0003_change_help_text'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalconfig',
            name='topnav_search_bg_color',
        ),
    ]
