# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-31 14:47
from __future__ import unicode_literals

from django.db import migrations


def rename_default_portal(apps, schema_editor):
    # Rename any default portals to 'CloudBolt' so it can be used
    # as the site label.
    apps.get_model("portals", "PortalConfig").objects \
        .filter(name='Default Portal').update(name="CloudBolt", is_default=True)


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0005_auto_20170728_1425'),
    ]

    operations = [
        migrations.RunPython(rename_default_portal),
    ]
