# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 20:11
from __future__ import unicode_literals

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0006_auto_20170731_1447'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalconfig',
            name='email_background_color',
            field=common.fields.ColorPickerField(blank=True, default='#335b83', help_text='Background color used in emails', max_length=7, null=True),
        ),
        migrations.AddField(
            model_name='portalconfig',
            name='email_header_image_url',
            field=models.URLField(blank=True, default='http://downloads.cloudbolt.io/images/cb_logo.png', help_text='A publicly-available url for an image to show in the header of emails.  700px wide is optimal.'),
        ),
    ]
