# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-27 02:08
from __future__ import unicode_literals

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0007_auto_20171012_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalconfig',
            name='login_banner',
            field=common.fields.PreviewImageField(blank=True, default='', help_text='Logo shown on the login page, at the top of the login form.  Max 80px tall is optimal.', null=True, upload_to='branding/'),
        ),
        migrations.AlterField(
            model_name='portalconfig',
            name='custom_banner',
            field=common.fields.PreviewImageField(blank=True, default='',
                                                  help_text='Logo shown in as banner above the navigation menu.  Max 80px tall is optimal.',
                                                  null=True, upload_to='branding/', verbose_name='Top banner'),
        ),
    ]
