# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-27 23:21
from __future__ import unicode_literals

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0007_auto_20171012_2011'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalconfig',
            name='login_background_image',
            field=common.fields.PreviewImageField(blank=True, default='', help_text='Background image shown when the login page is displayed.', null=True, upload_to='branding/'),
        ),
    ]
