# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-05 16:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0008_portalconfig_login_image'),
        ('portals', '0009_auto_20190227_0209'),
    ]

    operations = [
    ]
