# Generated by Django 2.2.10 on 2020-02-25 19:41

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('sso', '0001_initial'),
        ('portals', '0010_merge_20190405_1639'),
    ]

    operations = [
        migrations.AddField(
            model_name='portalconfig',
            name='sso_provider',
            field=models.ForeignKey(blank=True, help_text='SSO IdP to show on the login page for this portal. Unrestricted if not selected.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='sso.BaseSSOProvider', verbose_name='Single Sign-On Provider'),
        ),
    ]
