# Generated by Django 2.2.10 on 2020-10-15 18:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0011_portalconfig_sso_provider'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='portalconfig',
            name='sso_provider',
        ),
    ]
