# Generated by Django 2.2.10 on 2020-10-14 18:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('portals', '0012_remove_portalconfig_sso_provider'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portalconfig',
            name='ldaps',
            field=models.ManyToManyField(blank=True, help_text='LDAP domains to show on the login page for this portal. Local credential store is used if not selected.', to='utilities.LDAPUtility', verbose_name='Login LDAP Domains'),
        ),
        migrations.AddField(
            model_name='portalconfig',
            name='enable_local_credentials_store',
            field=models.BooleanField(blank=True, choices=[(None, 'Inherit'), (True, 'Enabled'), (False, 'Disabled')], help_text="Selecting Inherit will use the global preference set on the LDAP Authentication settings page found <a href='/admin/ldap_settings/'>here</a>.", null=True, verbose_name='Local Credential Store'),
        ),
    ]
