# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-10 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0004_auto_20161004_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveraction',
            name='dialog_message',
            field=models.TextField(blank=True, default='', help_text='Message to be shown in confirmation dialog after the action is chosen'),
        ),
        migrations.AddField(
            model_name='serveraction',
            name='submit_button_label',
            field=models.CharField(blank=True, default='', help_text='Text to be shown in confirmation dialog on the submit button', max_length=50),
        ),
        migrations.AlterField(
            model_name='cloudbolthook',
            name='source_code_url',
            field=models.TextField(blank=True, help_text='\n            Code will be fetched from here before action is run. E.g. URL\n            (without any authentication tokens) to the raw file hosted on your\n            github.com repository or on the <span class="cb-forge-btn"><a class="link no-tooltip-affordance"\n            href="https://github.com/CloudBoltSoftware/cloudbolt-forge"\n            target="_blank"\n            data-toggle="tooltip"\n            data-placement="bottom"\n            title="View and use actions shared by the CloudBolt community (new window)">\n            CloudBolt Forge \n            <i class="glyphicon glyphicon-fire"></i></a></span>\n.  For details \n<a href="/static/docs/advanced/orchestration-actions/actions.html#external-source-code"\n    target="help"\n    class="no-tooltip-affordance"\n    data-toggle="tooltip"\n    data-html="true"\n    title="Learn more in the CloudBolt Docs <p>(new window)</p>">\n     see the docs \n    <i class="icon-help"></i>\n</a>\n.\n            ', null=True, verbose_name='URL for source code'),
        ),
        migrations.AlterField(
            model_name='remotescripthook',
            name='source_code_url',
            field=models.TextField(blank=True, help_text='\n            Code will be fetched from here before action is run. E.g. URL\n            (without any authentication tokens) to the raw file hosted on your\n            github.com repository or on the <span class="cb-forge-btn"><a class="link no-tooltip-affordance"\n            href="https://github.com/CloudBoltSoftware/cloudbolt-forge"\n            target="_blank"\n            data-toggle="tooltip"\n            data-placement="bottom"\n            title="View and use actions shared by the CloudBolt community (new window)">\n            CloudBolt Forge \n            <i class="glyphicon glyphicon-fire"></i></a></span>\n.  For details \n<a href="/static/docs/advanced/orchestration-actions/actions.html#external-source-code"\n    target="help"\n    class="no-tooltip-affordance"\n    data-toggle="tooltip"\n    data-html="true"\n    title="Learn more in the CloudBolt Docs <p>(new window)</p>">\n     see the docs \n    <i class="icon-help"></i>\n</a>\n.\n            ', null=True, verbose_name='URL for source code'),
        ),
        migrations.AlterField(
            model_name='serviceaction',
            name='dialog_message',
            field=models.TextField(blank=True, default='', help_text='Message to be shown in confirmation dialog after the action is chosen'),
        ),
        migrations.AlterField(
            model_name='serviceaction',
            name='submit_button_label',
            field=models.CharField(blank=True, default='', help_text='Text to be shown in confirmation dialog on the submit button', max_length=50),
        ),
    ]
