# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-23 17:05
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0005_auto_20170110_0106'),
    ]

    operations = [
        migrations.AddField(
            model_name='hookinput',
            name='hide_if_default_value',
            field=models.BooleanField(default=False),
        ),
    ]
