# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-23 17:07
from __future__ import unicode_literals

from django.db import migrations


def copy_hide_single_value(apps, schema_editor):
    """
    This is to be run between adding hide_if_single_value to the HookInput model
    and removing hide_single_value from the CustomField model (and therefore the
    HookInput model), so at this point the HookInput has both attributes and we
    want to copy the value from the old to the new so it will be preserved.
    (hide_if_default_value replaces hide_single_value)
    """
    HookInput = apps.get_model("cbhooks", "HookInput")
    for hi in HookInput.objects.all():
        hi.hide_if_default_value = hi.hide_single_value
        hi.save()


def copy_hide_if_default_value(apps, schema_editor):
    """
    In case we need to reverse the process of converting hide_single_value to
    hide_if_default_value, this will copy the value of the latter to the former
    (after hide_single_value has been added back by reversing the infrastructure
    migration and before hide_if_default_value is removed by reversing the
    cbhooks migration)
    """
    HookInput = apps.get_model("cbhooks", "HookInput")
    for hi in HookInput.objects.all():
        hi.hide_single_value = hi.hide_if_default_value
        hi.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0006_hookinput_hide_if_default_value'),
    ]

    operations = [
        migrations.RunPython(copy_hide_single_value, copy_hide_if_default_value),
    ]
