# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-03 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0006_auto_20170130_2012'),
        ('cbhooks', '0007_sethideifdefaultvalue_20170123_1707'),
    ]

    operations = [
    ]
