# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-08 19:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0008_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudbolthook',
            name='ootb_module_file',
            field=models.FileField(blank=True, help_text='Path to the OOTB module file for this action', max_length=255, null=True, upload_to=''),
        ),
        migrations.AddField(
            model_name='remotescripthook',
            name='ootb_script_file',
            field=models.FileField(blank=True, help_text='Path to the OOTB script for this action', max_length=255, null=True, upload_to=''),
        ),
    ]
