# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-22 21:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0003_auto_20170106_0056'),
        ('cbhooks', '0008_merge'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestrationhook',
            name='configuration_managers',
            field=models.ManyToManyField(blank=True, help_text='Which Configuration Managers this script is executable on', related_name='hooks', to='connectors.ConnectorConf'),
        ),
        migrations.AlterField(
            model_name='hookpoint',
            name='job_type',
            field=models.CharField(blank=True, choices=[('provision', 'Provision Server'), ('decom', 'Delete Server'), ('healthcheck', 'Health Check'), ('expire', 'Expire'), ('servermodification', 'Server Modification'), ('install_service', 'Install Service'), ('install_pod', 'Install Pod'), ('installapplications', 'Install Applications'), ('uninstallapplications', 'Uninstall Applications'), ('syncvms', 'Synchronize VMs from Resource Handlers'), ('sync_svrs_from_pe', 'Synchronize servers from Provision Engines'), ('functionaltest', 'Continuous Infrastructure Testing'), ('runautomations', 'Execute Rules'), ('runautomationactions', 'Execute Rule Actions'), ('sync_users_from_ldap', 'Synchronize users from an LDAP server'), ('run_flow', 'Orchestration Flow'), ('install_apps_with_connector', 'Install Applications with Configuration Manager'), ('manage_nics', 'Manage NICs'), ('orchestration_hook', 'Orchestration Action'), ('delete_snapshots', 'Delete Snapshots')], max_length=50, null=True, verbose_name='Job Type'),
        ),
    ]
