# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-23 01:50
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0010_auto_20170130_2012'),
        ('cbhooks', '0009_auto_20170208_1957'),
    ]

    operations = [
        migrations.CreateModel(
            name='RecurringActionJob',
            fields=[
                ('recurringjob_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jobs.RecurringJob')),
                ('hook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cbhooks.OrchestrationHook')),
                ('input_mappings', models.ManyToManyField(to='cbhooks.RunHookInputMapping')),
            ],
            options={
                'abstract': False,
            },
            bases=('jobs.recurringjob', models.Model),
        ),
    ]
