# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-18 01:06
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontent', '0003_auto_20161004_2121'),
        ('cbhooks', '0009_auto_20170208_1957'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudbolthook',
            name='os_families',
            field=models.ManyToManyField(blank=True, help_text='Which OS Families this action should be run on. Used to filter the servers in the context, when there are some.', to='externalcontent.OSFamily', verbose_name='OS families'),
        ),
    ]
