# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-24 00:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0010_cloudbolthook_os_families'),
        ('cbhooks', '0010_recurringactionjob'),
    ]

    operations = [
    ]
