# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-23 17:04
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0010_cloudbolthook_os_families'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestrationhook',
            name='max_retries',
            field=models.IntegerField(default=0, help_text='The maximum number of times to try running the action again if it fails.', validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
