# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-25 01:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0011_merge'),
        ('cbhooks', '0011_hookpointaction_continue_on_failure'),
    ]

    operations = [
    ]
