# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-27 21:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0012_merge'),
        ('cbhooks', '0011_orchestrationhook_max_retries'),
    ]

    operations = [
    ]
