# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-28 00:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0009_auto_20170222_2155'),
        ('cbhooks', '0013_merge'),
    ]

    operations = [
    ]
