# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-04 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0015_auto_20170303_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestrationhook',
            name='is_ootb',
            field=models.BooleanField(default=False),
        ),
    ]
