# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-05 20:23
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0018_auto_20170824_2042'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudbolthook',
            name='source_code_url',
            field=models.TextField(blank=True, help_text='Code will be fetched from here before action is run. E.g. URL (without any authentication tokens) to the raw file hosted on your github.com repository or on the \n\n<span class="cb-forge-btn"><a class="link no-tooltip-affordance"\n            href="https://github.com/CloudBoltSoftware/cloudbolt-forge"\n            target="_blank"\n            data-toggle="tooltip"\n            data-placement="bottom"\n            title="View and use actions shared by the CloudBolt community (new window)">\n            \n                \n                CloudBolt Forge\n            \n            <i class="glyphicon glyphicon-fire"></i></a></span>\n. For details \n\n\n\n\n\n<a href="/static/docs/advanced/orchestration-actions/actions.html#external-source-code"\n    target="help"\n    class="no-tooltip-affordance"\n    data-toggle="tooltip"\n    data-html="true"\n    title="Learn more in the docs <p>(new window)</p>">\n     see the docs \n    <i class="icon-help"></i>\n</a>\n.', null=True, verbose_name='URL for source code'),
        ),
        migrations.AlterField(
            model_name='remotescripthook',
            name='source_code_url',
            field=models.TextField(blank=True, help_text='Code will be fetched from here before action is run. E.g. URL (without any authentication tokens) to the raw file hosted on your github.com repository or on the \n\n<span class="cb-forge-btn"><a class="link no-tooltip-affordance"\n            href="https://github.com/CloudBoltSoftware/cloudbolt-forge"\n            target="_blank"\n            data-toggle="tooltip"\n            data-placement="bottom"\n            title="View and use actions shared by the CloudBolt community (new window)">\n            \n                \n                CloudBolt Forge\n            \n            <i class="glyphicon glyphicon-fire"></i></a></span>\n. For details \n\n\n\n\n\n<a href="/static/docs/advanced/orchestration-actions/actions.html#external-source-code"\n    target="help"\n    class="no-tooltip-affordance"\n    data-toggle="tooltip"\n    data-html="true"\n    title="Learn more in the docs <p>(new window)</p>">\n     see the docs \n    <i class="icon-help"></i>\n</a>\n.', null=True, verbose_name='URL for source code'),
        ),
    ]
