# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-17 19:07
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0022_merge_20171016_1741'),
    ]

    operations = [
        migrations.AddField(
            model_name='remotescripthook',
            name='remove_after_run',
            field=models.BooleanField(default=True, help_text='Remove this script from the server after execution completes.'),
        ),
    ]
