# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 14:31
from __future__ import unicode_literals

from django.db import migrations


def rename_action_and_update_related(apps, schema_editor):
    """
    We renamed the "Delete Service" action to "Delete Resource".
    For existing customers, rather than relying completely on create_objects/
    cb_minimal, which would create a brand new action, just change the necessary
    attributes of the existing action here. Namely, if we update the name, then
    when the new cb_minimal is used it'll correctly find the old action with the
    new name and update many of the other attributes, such as the
    ootb_module_file and module_file if the code hasn't been changed, as
    desired.
    """
    CloudBoltHook = apps.get_model("cbhooks", "CloudBoltHook")

    action = CloudBoltHook.objects.filter(name='Delete Service').first()
    if action:
        action.name = 'Delete Resource'
        action.save()
        # It looks like the Service Action's dialog message won't get updated by
        # create_objects/ c2_wrapper for existing actions, so update it here
        svc_action = action.serviceaction_set.first()
        if svc_action:
            svc_action.dialog_message = (
                'This will delete all servers in the resource and then mark '
                'the resource as historical.'
            )
            svc_action.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0023_remotescripthook_remove_after_run'),
    ]

    operations = [
        migrations.RunPython(rename_action_and_update_related,
                             migrations.RunPython.noop),
    ]
