# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 15:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0023_remotescripthook_remove_after_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestrationhook',
            name='sequenced_action_inputs',
            field=models.CharField(blank=True, help_text='Comma-separated list of action input ids, indicating desired display sequence.', max_length=255, null=True),
        ),
    ]
