# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 19:35
from __future__ import unicode_literals

from django.db import migrations


def rename_trigger_points(apps, schema_editor):
    """
    We renamed the Pre-Delete Service and Post-Delete Service trigger points for
    Orchestration Actions to Pre-/Post-Delete Resource.
    Rather than relying completely on create_objects/cb_minimal, which would
    create new additional trigger points for existing customers, we rename the
    existing trigger points here. Then when create_objects runs it'll correctly
    find the old trigger points with the new names and update their other
    attributes as desired.
    """
    HookPoint = apps.get_model("cbhooks", "HookPoint")

    pre_point = HookPoint.objects.filter(name='pre_delete_service').first()
    if pre_point:
        pre_point.name = 'pre_delete_resource'
        pre_point.save()

    post_point = HookPoint.objects.filter(name='post_delete_service').first()
    if post_point:
        post_point.name = 'post_delete_resource'
        post_point.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0024_delete_service_action_becomes_delete_resource_20180110_1431'),
    ]

    operations = [
        migrations.RunPython(rename_trigger_points,
                             migrations.RunPython.noop),
    ]
