# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 19:21
from __future__ import unicode_literals

from django.db import migrations


def update_dialog_message(apps, schema_editor):
    """
    Changed some attributes of the "Associate Servers" Resource Action (FKA
    Service Action) in cb_minimal. Most will propagate correctly when
    create_objects is run, but the dialog message is not updated for existing
    actions, so take care of that here instead.
    """
    ServiceAction = apps.get_model("cbhooks", "ServiceAction")

    action = ServiceAction.objects.filter(label='Associate Servers').first()
    if action:
        action.dialog_message = action.dialog_message.replace(
            'service', 'resource')
        action.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0026_expire_services_rule_becomes_expire_resources_20180111_1248'),
    ]

    operations = [
        migrations.RunPython(update_dialog_message,
                             migrations.RunPython.noop),
    ]
