# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-11 19:42
from __future__ import unicode_literals

from django.db import migrations


def rename_action_and_update_related(apps, schema_editor):
    """
    To support the change from services to resources, we changed the name,
    label, and other attributes of the "Scale" Resource Action in cb_minimal.
    However, relying completely on create_objects would cause new actions to be
    created instead so we change the name of the base action and the label of
    the ServiceAction here first. Then create objects can update the other
    attributes (other than the dialog message, which isn't updated for existing
    actions so we do that here too).
    """
    CloudBoltHook = apps.get_model("cbhooks", "CloudBoltHook")

    action = CloudBoltHook.objects.filter(name='Scale Service').first()
    if action:
        action.name = 'Scale Resource'
        action.save()
        svc_action = action.serviceaction_set.first()
        if svc_action:
            svc_action.label = 'Scale'
            svc_action.dialog_message = (
                'Add/remove servers in a specific tier and reconfigure '
                'the load balancer as appropriate'
            )
            svc_action.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0027_update_associate_servers_dialog_20180111_1921'),
    ]

    operations = [
        migrations.RunPython(rename_action_and_update_related,
                             migrations.RunPython.noop),
    ]
