# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-12 18:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0029_scaling_rule_reference_resources_20180112_1352'),
        ('accounts', '0025_auto_20180112_1837'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceAction',
            new_name='ResourceAction',
        ),
    ]
