# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-12 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0030_auto_20180112_1837'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceaction',
            name='list_view_visible',
            field=models.BooleanField(default=True, help_text='Determines whether this action is a viable option to list when running bulk resource actions.'),
        ),
    ]
