# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-15 13:57
from __future__ import unicode_literals

from django.db import migrations


def rename_hook_point(apps, schema_editor):
    """
    We changed Service Actions to be Resource Actions, and therefore changed the
    service_actions Hook Point in cb_minimal to resource_actions. Even though
    I'm not sure we use the actual HookPoint object for much, for cleanliness
    rename it here (otherwise running create_objects would make a new one).
    """
    HookPoint = apps.get_model("cbhooks", "HookPoint")

    hook_point = HookPoint.objects.filter(name='service_actions').first()
    if hook_point:
        hook_point.name = 'resource_actions'
        hook_point.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0031_auto_20180112_1932'),
    ]

    operations = [
        migrations.RunPython(rename_hook_point,
                             migrations.RunPython.noop),
    ]
