# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0033_service_hookpoint_becomes_blueprint_20180115_2032'),
        ('cbhooks', '0024_orchestrationhook_sequenced_action_inputs'),
    ]

    operations = [
    ]
