# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-07 16:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0036_serveraction_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='serveraction',
            name='condition',
            field=models.ForeignKey(blank=True, help_text='Additional conditions that describe when this Server Action should be displayed, implemented as a CloudBolt plug-in.', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='server_actions_is_condition_for', to='cbhooks.CloudBoltHook', verbose_name='Display Condition Plug-in'),
        ),
    ]
