# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-17 18:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0037_serveraction_condition'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudbolthook',
            name='module_file',
            field=models.FileField(blank=True, help_text='For more information on the requirements for CloudBolt plug-ins see the <a target="cbhelp" href="/static/docs/advanced/orchestration-actions/cloudbolt-plugins/index.html">CloudBolt Documentation.</a>', max_length=255, null=True, upload_to='hooks'),
        ),
    ]
