# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-20 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0038_auto_20190117_1838'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudbolthook',
            name='source_code_url',
            field=models.TextField(blank=True, help_text='Code will be fetched from here before action is run. E.g. URL (without any authentication tokens) to the raw file hosted on your github.com repository. For details \n\n\n\n\n\n<a class="no-tooltip-affordance" data-html="true" data-toggle="tooltip" href="/static/docs/advanced/orchestration-actions/actions.html#external-source-code" target="help" title="Learn more in the docs &lt;p&gt;(new window)&lt;/p&gt;">\n     see the docs \n    <i class="icon-help"></i>\n</a>\n.', null=True, verbose_name='URL for source code'),
        ),
        migrations.AlterField(
            model_name='remotescripthook',
            name='source_code_url',
            field=models.TextField(blank=True, help_text='Code will be fetched from here before action is run. E.g. URL (without any authentication tokens) to the raw file hosted on your github.com repository. For details \n\n\n\n\n\n<a class="no-tooltip-affordance" data-html="true" data-toggle="tooltip" href="/static/docs/advanced/orchestration-actions/actions.html#external-source-code" target="help" title="Learn more in the docs &lt;p&gt;(new window)&lt;/p&gt;">\n     see the docs \n    <i class="icon-help"></i>\n</a>\n.', null=True, verbose_name='URL for source code'),
        ),
    ]
