# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-01 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0038_auto_20190117_1838'),
    ]

    operations = [
        migrations.RenameField(
            model_name='remotescripthook',
            old_name='script_file',
            new_name='module_file',
        ),
        migrations.RenameField(
            model_name='remotescripthook',
            old_name='ootb_script_file',
            new_name='ootb_module_file',
        ),
    ]
