# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-10 19:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0039_auto_20190301_2345'),
        ('cbhooks', '0040_auto_20190404_1904'),
    ]

    operations = [
    ]
