# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-13 20:25
from __future__ import unicode_literals

import cbhooks.models
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0041_merge_20190410_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerraformPlanHook',
            fields=[
                ('orchestrationhook_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cbhooks.OrchestrationHook')),
                ('plan_path', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Terraform Plan',
            },
            bases=('cbhooks.orchestrationhook', cbhooks.models.CodeActionMixin),
        ),
    ]
