# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 20:16
from __future__ import unicode_literals

import cbhooks.models
import common.mixins
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontent', '0012_duplicate_osbas_in_multiple_rhs'),
        ('orders', '0023_merge_20180529_2028'),
        ('cbhooks', '0041_merge_20190410_1923'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyFileAction',
            fields=[
                ('orchestrationhook_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cbhooks.OrchestrationHook')),
                ('module_file', models.FileField(blank=True, help_text='Path to the file to copy', max_length=255, null=True, upload_to='hooks')),
                ('destination_path', models.CharField(help_text='Full path to the directory the file should be copied to.', max_length=1024)),
                ('size', models.IntegerField(blank=True, null=True)),
                ('source_code_url', models.TextField(blank=True, help_text='Code will be fetched from here before action is run. E.g. URL (without any authentication tokens) to the raw file hosted on your github.com repository. For details \n\n\n\n\n\n<a href="/static/docs/advanced/orchestration-actions/actions.html#external-source-code"\n    target="help"\n    class="no-tooltip-affordance"\n    data-toggle="tooltip"\n    data-html="true"\n    title="Learn more in the docs <p>(new window)</p>">\n     see the docs \n    <i class="icon-help"></i>\n</a>\n.', null=True, verbose_name='URL for source code')),
                ('custom_field_values', models.ManyToManyField(blank=True, to='orders.CustomFieldValue')),
                ('os_families', models.ManyToManyField(blank=True, help_text='Which OS Families this file should be copied to', to='externalcontent.OSFamily', verbose_name='OS Families')),
            ],
            options={
                'abstract': False,
            },
            bases=('cbhooks.orchestrationhook', cbhooks.models.CodeActionMixin, common.mixins.HasCustomFieldValuesMixin, cbhooks.models.UsesServersMixin),
        ),
    ]
