# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-14 21:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0042_create_terraformplanhook'),
        ('cbhooks', '0042_copyfileaction'),
    ]

    operations = [
    ]
