# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 14:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0043_auto_20190621_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='orchestrationhook',
            name='minimum_version_required',
            field=models.CharField(default='8.6', help_text='This setting will be used to filter components during exports.', max_length=20),
        ),
    ]
