# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-21 22:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import files.models


class Migration(migrations.Migration):
    dependencies = [
        ('servicecatalog', '0043_merge_20190614_2135'),
        ('resources', '0009_auto_20190607_1527'),
        ('cbhooks', '0043_merge_20190614_2135'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerraformStateFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('module_file', models.FileField(blank=True, max_length=255, null=True, upload_to='terraform')),
                ('resource', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resources.Resource')),
                ('service_item', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicecatalog.RunTerraformPlanHookServiceItem')),
            ],
            bases=(models.Model, files.models.ExternalSourceCodeMixin),
        ),
    ]
