# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0043_auto_20190613_2145'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudbolthook',
            name='debugger_enabled',
            field=models.BooleanField(default=False),
        ),
    ]
