# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-28 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0044_cloudbolthook_debugger_enabled'),
        ('cbhooks', '0044_terraformstatefile'),
    ]

    operations = [
    ]
