# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-11 19:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


def apply_hook_migration(apps, schema_editor):
    """
    Ensures that all TerraformStateFile `hook` fields are set to a non-None value.
    """
    TerraformStateFile = apps.get_model('cbhooks', 'TerraformStateFile')
    TerraformPlanHook = apps.get_model('cbhooks', 'TerraformPlanHook')
    for state_file in TerraformStateFile.objects.all():
        # We would usually set `state_file.hook` to `state_file.service_item.hook.cast()`
        # However in a migration we cannot depend on that method or existing Model Classes
        # So instead we assign the hook to the result of a database lookup
        state_file.hook = TerraformPlanHook.objects.get(id=state_file.service_item.hook.id)
        state_file.save()

def reverse_hook_migration(apps, schema_editor):
    """
    Reverses the `apply_hook_migration` above.
    """
    TerraformStateFile = apps.get_model('cbhooks', 'TerraformStateFile')
    for state_file in TerraformStateFile.objects.all():
        state_file.hook = None
        state_file.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0046_merge_20190702_2325'),
    ]

    operations = [
        migrations.AddField(
            model_name='terraformstatefile',
            name='hook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='cbhooks.TerraformPlanHook'),
        ),
        migrations.RunPython(apply_hook_migration, reverse_hook_migration),
        migrations.AlterField(
            model_name='terraformstatefile',
            name='hook',
            field=models.ForeignKey(null=False, on_delete=django.db.models.deletion.CASCADE, to='cbhooks.TerraformPlanHook'),
        ),
        migrations.AlterField(
            model_name='terraformstatefile',
            name='service_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicecatalog.RunTerraformPlanHookServiceItem'),
        ),
    ]
