# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-02 00:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0005_auto_20190710_1848'),
        ('cbhooks', '0048_terraformplanhook_module_file_20190718_0014'),
    ]

    operations = [
        migrations.CreateModel(
            name='IPAMHook',
            fields=[
                ('cloudbolthook_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cbhooks.CloudBoltHook')),
                ('ipam', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hooks', to='ipam.IPAM')),
                ('ipam_technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hooks', to='ipam.IPAMTechnology')),
            ],
            bases=('cbhooks.cloudbolthook',),
        ),
        migrations.AlterUniqueTogether(
            name='ipamhook',
            unique_together=set([('ipam_technology', 'ipam')]),
        ),
    ]
