# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-13 19:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0049_auto_20190802_0010'),
        ('cbhooks', '0049_auto_20190812_1854'),
    ]

    operations = [
    ]
