# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-19 23:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0052_terraformplanhook_git_source_code_url'),
        ('cbhooks', '0052_ipamhook_enabled'),
    ]

    operations = [
    ]
