# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-27 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0051_merge_20190815_1435'),
        ('cbhooks', '0053_merge_20190819_2341'),
    ]

    operations = [
    ]
