# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-05 02:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0054_merge_20190827_1838'),
        ('cbhooks', '0054_merge_20190827_2031'),
    ]

    operations = [
    ]
