# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-09 20:43
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0070_merge_20190815_2030'),
        ('cbhooks', '0055_merge_20190905_0244'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNowCMDBHook',
            fields=[
                ('cloudbolthook_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cbhooks.CloudBoltHook')),
                ('enabled', models.BooleanField(default=False)),
                ('servicenow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='hooks', to='utilities.ServiceNow')),
            ],
            options={
                'abstract': False,
            },
            bases=('cbhooks.cloudbolthook',),
        ),
    ]
