# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-18 17:30
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0056_servicenowcmdbhook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenowcmdbhook',
            name='servicenow',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hooks', to='utilities.ServiceNow'),
        ),
    ]
