# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-23 22:09
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0034_auto_20190613_2145'),
        ('utilities', '0070_merge_20190815_2030'),
        ('cscv', '0009_auto_20190814_1416'),
        ('servicecatalog', '0053_set_bp_global_ids_20190913_1747'),
        ('cbhooks', '0057_auto_20190918_1730'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNowHook',
            fields=[
                ('cloudbolthook_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cbhooks.CloudBoltHook')),
                ('enabled', models.BooleanField(default=False)),
                ('action', models.CharField(max_length=255, unique=True)),
                ('servicenow', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hooks', to='utilities.ServiceNow')),
            ],
            options={
                'abstract': False,
            },
            bases=('cbhooks.cloudbolthook',),
        ),
        migrations.RemoveField(
            model_name='servicenowcmdbhook',
            name='cloudbolthook_ptr',
        ),
        migrations.RemoveField(
            model_name='servicenowcmdbhook',
            name='servicenow',
        ),
        migrations.DeleteModel(
            name='ServiceNowCMDBHook',
        ),
    ]
