# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-09 05:54
from __future__ import unicode_literals

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0057_auto_20190918_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='triggerpoint',
            name='last_updated',
            field=models.DateField(blank=True, null=True, verbose_name='Last Updated Date'),
        ),
        migrations.AddField(
            model_name='triggerpoint',
            name='library_list_image',
            field=common.fields.PreviewImageField(blank=True, default='', help_text='Any size. All standard image formats work, though PNGs with alpha transparency look best.', null=True, upload_to='content_library/', verbose_name='Library List Image'),
        ),
        migrations.AddField(
            model_name='triggerpoint',
            name='minimum_version_required',
            field=models.CharField(default='8.6', help_text='This setting will be used to filter components during exports.', max_length=20),
        ),
    ]
