# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-24 00:48
from __future__ import unicode_literals

from django.db import migrations


def action_for_existing_servicenow_hook(apps, schema_editor):
    ServiceNowHook = apps.get_model('cbhooks', 'ServiceNowHook')

    hook = ServiceNowHook.objects.filter(action='').first()

    if hook:
        hook.action = 'cmdb'
        hook.save()


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0058_auto_20190923_2209'),
    ]

    operations = [
        migrations.RunPython(action_for_existing_servicenow_hook, migrations.RunPython.noop)
    ]
