# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-02 21:25
from __future__ import unicode_literals

from django.db import migrations

def remove_unused_servicenowcmdbhooks(apps, schema_editor):
    """
    Cleaning up remnant ServiceNowCMDBHook which could have been left over from 
    https://github.com/CloudBoltSoftware/cloudbolt/pull/1981/files#diff-cd89eed5306323b9488f853bd844cb88L2993
    """
    OrchestrationHook = apps.get_model('cbhooks', 'OrchestrationHook')

    hooks = OrchestrationHook.objects.filter(name="ServiceNow Plug-in", is_ootb=True).all()

    for hook in hooks:
        hook.delete()

class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0059_auto_20190924_0048'),
    ]

    operations = [
        migrations.RunPython(remove_unused_servicenowcmdbhooks, migrations.RunPython.noop)
    ]
