# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-16 23:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0060_auto_20191002_2125'),
        ('cbhooks', '0058_auto_20191009_0554'),
    ]

    operations = [
    ]
