# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-17 01:01
from __future__ import unicode_literals

import cb_secrets.fields
import cbhooks.models
import common.validators
from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0061_merge_20191016_2333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyfileaction',
            name='custom_field_values',
            field=models.ManyToManyField(blank=True, to='orders.CustomFieldValue', verbose_name='Custom Field Values'),
        ),
        migrations.AlterField(
            model_name='copyfileaction',
            name='size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Size'),
        ),
        migrations.AlterField(
            model_name='emailhook',
            name='body',
            field=models.TextField(blank=True, help_text=cbhooks.models.emailhook_body_help_text, null=True, verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='emailhook',
            name='from_address',
            field=models.CharField(blank=True, help_text=cbhooks.models.emailhook_from_address_help_text, max_length=256, null=True, verbose_name='From Address'),
        ),
        migrations.AlterField(
            model_name='emailhook',
            name='send_to_address',
            field=models.CharField(blank=True, help_text='A comma separated list of recipients.', max_length=256, null=True, verbose_name='Send to Address'),
        ),
        migrations.AlterField(
            model_name='emailhook',
            name='send_to_job_owner',
            field=models.BooleanField(default=False, verbose_name='Send to Job Owner'),
        ),
        migrations.AlterField(
            model_name='emailhook',
            name='send_to_users',
            field=models.ManyToManyField(blank=True, to=settings.AUTH_USER_MODEL, verbose_name='Send to Users'),
        ),
        migrations.AlterField(
            model_name='emailhook',
            name='subject',
            field=models.CharField(blank=True, max_length=256, null=True, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='hookpoint',
            name='description',
            field=models.TextField(blank=True, help_text='Explains when this hook point is executed', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='hookpoint',
            name='label',
            field=models.CharField(help_text='A user-visible label for this hook point. Can be changed without impacting functionality.', max_length=255, unique=True, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='hookpointaction',
            name='description',
            field=models.TextField(blank=True, help_text='Explains the purpose of this action trigger', null=True, verbose_name='Description'),
        ),
        migrations.AlterField(
            model_name='hookpointaction',
            name='enabled',
            field=models.BooleanField(default=False, verbose_name='Enabled'),
        ),
        migrations.AlterField(
            model_name='hookpointaction',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='remotescripthook',
            name='commandline_args',
            field=models.CharField(blank=True, help_text=cbhooks.models.remotescripthook_commandline_args_help_text, max_length=256, null=True, verbose_name='Commandline args'),
        ),
        migrations.AlterField(
            model_name='remotescripthook',
            name='execution_timeout',
            field=models.IntegerField(default=120, help_text='Timeout (in seconds) before exiting out of the remotescript execution with an error', validators=[common.validators.is_only_digits], verbose_name='Execution timeout'),
        ),
        migrations.AlterField(
            model_name='remotescripthook',
            name='remove_after_run',
            field=models.BooleanField(default=True, help_text='Remove this script from the server after execution completes.', verbose_name='Remove after run'),
        ),
        migrations.AlterField(
            model_name='remotescripthook',
            name='run_on_server',
            field=models.ForeignKey(blank=True, help_text='The server to actually run this script on. Use if you want the script to run on a server other than the one(s) in the current context (e.g. the one(s) being provisioned).', null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.Server', verbose_name='Run on server'),
        ),
        migrations.AlterField(
            model_name='remotescripthook',
            name='run_with_sudo',
            field=models.BooleanField(default=False, help_text='Run this script with sudo on Unix-like servers.', verbose_name='Run with sudo'),
        ),
        migrations.AlterField(
            model_name='resourceaction',
            name='blueprints',
            field=models.ManyToManyField(blank=True, help_text='Blueprints that this action applies to. If none are selected, it will apply to all.', to='servicecatalog.ServiceBlueprint', verbose_name='Blueprints'),
        ),
        migrations.AlterField(
            model_name='resourceaction',
            name='dialog_message',
            field=models.TextField(blank=True, default='', help_text='Message to be shown in confirmation dialog after the action is chosen', verbose_name='Dialog message'),
        ),
        migrations.AlterField(
            model_name='resourceaction',
            name='extra_classes',
            field=models.CharField(blank=True, default='', help_text="Can be used to add an icon on the button. Must correspond to an icon name thatCloudBolt has. Ex. 'icon-delete', 'glyphicon glyphicon-time', 'fas fa-heartbeat'. Formore examples, see<a href='http://fortawesome.github.io/Font-Awesome/icons/'>Font Awesome</a> and<a href='http://getbootstrap.com/components/'>Glyphicons</a>", max_length=255, verbose_name='Extra classes'),
        ),
        migrations.AlterField(
            model_name='resourceaction',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='resourceaction',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Make order approval required befored this action job will start. Applies to Server and Resource Actions', verbose_name='Requires approval'),
        ),
        migrations.AlterField(
            model_name='resourceaction',
            name='submit_button_label',
            field=models.CharField(blank=True, default='', help_text='Text to be shown in confirmation dialog on the submit button', max_length=50, verbose_name='Submit button label'),
        ),
        migrations.AlterField(
            model_name='serveraction',
            name='dialog_message',
            field=models.TextField(blank=True, default='', help_text='Message to be shown in confirmation dialog after the action is chosen', verbose_name='Dialog message'),
        ),
        migrations.AlterField(
            model_name='serveraction',
            name='extra_classes',
            field=models.CharField(blank=True, default='', help_text="Can be used to add an icon on the button. Must correspond to an icon name thatCloudBolt has. Ex. 'icon-delete', 'glyphicon glyphicon-time', 'fas fa-heartbeat'. Formore examples, see<a href='http://fortawesome.github.io/Font-Awesome/icons/'>Font Awesome</a> and<a href='http://getbootstrap.com/components/'>Glyphicons</a>", max_length=255, verbose_name='Extra classes'),
        ),
        migrations.AlterField(
            model_name='serveraction',
            name='label',
            field=models.CharField(max_length=50, verbose_name='Label'),
        ),
        migrations.AlterField(
            model_name='serveraction',
            name='requires_approval',
            field=models.BooleanField(default=False, help_text='Make order approval required befored this action job will start. Applies to Server and Resource Actions', verbose_name='Requires approval'),
        ),
        migrations.AlterField(
            model_name='serveraction',
            name='submit_button_label',
            field=models.CharField(blank=True, default='', help_text='Text to be shown in confirmation dialog on the submit button', max_length=50, verbose_name='Submit button label'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='auth_header_name',
            field=models.CharField(blank=True, default='', help_text='If specified, CB will use token-based auth, adding a field with this name to the HTTP headers. Use either this or username, not both.', max_length=100, verbose_name='Auth header name'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='auth_header_value',
            field=models.CharField(blank=True, default='', max_length=512, verbose_name='Auth Header Value'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='authentication_method',
            field=models.CharField(choices=[('none', 'No authentication'), ('basic', 'HTTP basic auth'), ('token', 'Token-based')], default='basic', max_length=10, verbose_name='Authentication Method'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='content_type',
            field=models.CharField(choices=[('application/x-www-form-urlencoded', 'WWW-Form'), ('application/json', 'JSON'), ('application/xml', 'XML')], default='application/json', max_length=50, verbose_name='Content Type'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='custom_headers',
            field=models.TextField(blank=True, default='', help_text="JSON object where keys are HTTP header names and values are header values. Ex. {'user-agent': 'my-app/0.0.1'}", verbose_name='Custom headers'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='http_method',
            field=models.CharField(choices=[('delete', 'DELETE'), ('get', 'GET'), ('head', 'HEAD'), ('patch', 'PATCH'), ('post', 'POST'), ('put', 'PUT')], default='post', max_length=10, verbose_name='HTTP Method'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='http_password',
            field=cb_secrets.fields.EncryptedPasswordField(blank=True, default='', verbose_name='Http Password'),
        ),
        migrations.AlterField(
            model_name='webhook',
            name='payload',
            field=models.TextField(blank=True, default='', help_text='JSON formatted data to send in the request body.', verbose_name='Payload'),
        ),
    ]
