# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-07 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0062_auto_20191017_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ipamhook',
            name='ipam',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hooks', to='ipam.IPAM'),
        ),
    ]
