# Generated by Django 2.2.10 on 2020-01-23 21:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0065_remove_runhookinputmapping_options'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serveraction',
            name='label',
            field=models.CharField(max_length=255, verbose_name='Label'),
        ),
    ]
