# Generated by Django 2.2.10 on 2020-01-24 23:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0065_remove_runhookinputmapping_options'),
        ('cbhooks', '0065_auto_20191213_1834'),
    ]

    operations = [
    ]
