# Generated by Django 2.2.10 on 2020-01-25 01:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0066_auto_20200123_2155'),
        ('cbhooks', '0066_merge_20200124_2356'),
    ]

    operations = [
    ]
