# Generated by Django 2.2.10 on 2020-03-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0068_auto_20200204_0052'),
        ('cbhooks', '0065_auto_20200213_1443'),
    ]

    operations = [
    ]
