# Generated by Django 2.2.10 on 2020-04-22 17:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('dataprotection', '0002_auto_20200414_2043'),
        ('cbhooks', '0071_auto_20200324_0003'),
    ]

    operations = [
        migrations.CreateModel(
            name='DataProtectionHook',
            fields=[
                ('cloudbolthook_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cbhooks.CloudBoltHook')),
                ('enabled', models.BooleanField(default=False)),
                ('dataprotection', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='hooks', to='dataprotection.DataProtection')),
                ('dataprotection_technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hooks', to='dataprotection.DataProtectionTechnology')),
            ],
            options={
                'unique_together': {('dataprotection_technology', 'dataprotection')},
            },
            bases=('cbhooks.cloudbolthook',),
        ),
    ]
