# Generated by Django 2.2.12 on 2020-05-20 22:48

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0072_auto_20200427_1821'),
    ]

    operations = [
        migrations.CreateModel(
            name='ITSMHook',
            fields=[
                ('cloudbolthook_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='cbhooks.CloudBoltHook')),
                ('enabled', models.BooleanField(default=False)),
                ('action', models.CharField(max_length=255, unique=True)),
            ],
            bases=('cbhooks.cloudbolthook',),
        ),
    ]
