# Generated by Django 2.2.12 on 2020-05-15 17:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0072_dataprotectionhook'),
        ('cbhooks', '0072_auto_20200427_1821'),
    ]

    operations = [
    ]
