# Generated by Django 2.2.12 on 2020-06-01 22:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0074_auto_20200520_2248'),
        ('cbhooks', '0074_auto_20200522_1036'),
    ]

    operations = [
    ]
