# Generated by Django 2.2.12 on 2020-06-08 15:07

import cbhooks.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0075_merge_20200601_2235'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudbolthook',
            name='module_file',
            field=models.FileField(blank=True, help_text=cbhooks.models.get_module_file_help_text, max_length=255, null=True, upload_to='hooks'),
        ),
        migrations.AlterField(
            model_name='cloudbolthook',
            name='source_code_url',
            field=models.TextField(blank=True, help_text='Code will be fetched from here before action is run. E.g. URL (without any authentication tokens) to the raw file hosted on your github.com repository. For details \n\n\n\n\n\n<a href="docs/HTML/actions-with-code.html#external-source-code"\n    id="docs-link"\n    target="help"\n    class="no-tooltip-affordance"\n    data-toggle="tooltip"\n    data-html="true"\n    title="Learn more in the docs <p>(new window)</p>">\n     see the docs \n    <i class="icon-help"></i>\n</a>\n.', null=True, verbose_name='URL for source code'),
        ),
        migrations.AlterField(
            model_name='copyfileaction',
            name='source_code_url',
            field=models.TextField(blank=True, help_text='Code will be fetched from here before action is run. E.g. URL (without any authentication tokens) to the raw file hosted on your github.com repository. For details \n\n\n\n\n\n<a href="docs/HTML/actions-with-code.html#external-source-code"\n    id="docs-link"\n    target="help"\n    class="no-tooltip-affordance"\n    data-toggle="tooltip"\n    data-html="true"\n    title="Learn more in the docs <p>(new window)</p>">\n     see the docs \n    <i class="icon-help"></i>\n</a>\n.', null=True, verbose_name='URL for source code'),
        ),
        migrations.AlterField(
            model_name='remotescripthook',
            name='source_code_url',
            field=models.TextField(blank=True, help_text='Code will be fetched from here before action is run. E.g. URL (without any authentication tokens) to the raw file hosted on your github.com repository. For details \n\n\n\n\n\n<a href="docs/HTML/actions-with-code.html#external-source-code"\n    id="docs-link"\n    target="help"\n    class="no-tooltip-affordance"\n    data-toggle="tooltip"\n    data-html="true"\n    title="Learn more in the docs <p>(new window)</p>">\n     see the docs \n    <i class="icon-help"></i>\n</a>\n.', null=True, verbose_name='URL for source code'),
        ),
        migrations.AlterField(
            model_name='terraformplanhook',
            name='git_source_code_url',
            field=models.TextField(blank=True, help_text='Code will be fetched from here before action is run. E.g. URL (without any authentication tokens) to the raw file hosted on your github.com repository. For details \n\n\n\n\n\n<a href="docs/HTML/actions-with-code.html#external-source-code"\n    id="docs-link"\n    target="help"\n    class="no-tooltip-affordance"\n    data-toggle="tooltip"\n    data-html="true"\n    title="Learn more in the docs <p>(new window)</p>">\n     see the docs \n    <i class="icon-help"></i>\n</a>\n.', null=True, verbose_name='URL for source code'),
        ),
        migrations.AlterField(
            model_name='terraformplanhook',
            name='source_code_url',
            field=models.TextField(blank=True, help_text='Code will be fetched from here before action is run. E.g. URL (without any authentication tokens) to the raw file hosted on your github.com repository. For details \n\n\n\n\n\n<a href="docs/HTML/actions-with-code.html#external-source-code"\n    id="docs-link"\n    target="help"\n    class="no-tooltip-affordance"\n    data-toggle="tooltip"\n    data-html="true"\n    title="Learn more in the docs <p>(new window)</p>">\n     see the docs \n    <i class="icon-help"></i>\n</a>\n.', null=True, verbose_name='URL for source code'),
        ),
    ]
