# Generated by Django 2.2.12 on 2020-06-08 17:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0076_auto_20200608_1507'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudbolthook',
            name='source_code_url',
            field=models.TextField(blank=True, help_text='Code will be fetched from here before action is run. E.g. URL (without any authentication tokens) to the raw file hosted on your github.com repository. For details \n\n\n\n\n\n<a href="/static-b0175/docs/HTML/actions-with-code.html#external-source-code"\n    id="docs-link"\n    target="help"\n    class="no-tooltip-affordance"\n    data-toggle="tooltip"\n    data-html="true"\n    title="Learn more in the docs <p>(new window)</p>">\n     see the docs \n    <i class="icon-help"></i>\n</a>\n.', null=True, verbose_name='URL for source code'),
        ),
        migrations.AlterField(
            model_name='copyfileaction',
            name='source_code_url',
            field=models.TextField(blank=True, help_text='Code will be fetched from here before action is run. E.g. URL (without any authentication tokens) to the raw file hosted on your github.com repository. For details \n\n\n\n\n\n<a href="/static-b0175/docs/HTML/actions-with-code.html#external-source-code"\n    id="docs-link"\n    target="help"\n    class="no-tooltip-affordance"\n    data-toggle="tooltip"\n    data-html="true"\n    title="Learn more in the docs <p>(new window)</p>">\n     see the docs \n    <i class="icon-help"></i>\n</a>\n.', null=True, verbose_name='URL for source code'),
        ),
        migrations.AlterField(
            model_name='remotescripthook',
            name='source_code_url',
            field=models.TextField(blank=True, help_text='Code will be fetched from here before action is run. E.g. URL (without any authentication tokens) to the raw file hosted on your github.com repository. For details \n\n\n\n\n\n<a href="/static-b0175/docs/HTML/actions-with-code.html#external-source-code"\n    id="docs-link"\n    target="help"\n    class="no-tooltip-affordance"\n    data-toggle="tooltip"\n    data-html="true"\n    title="Learn more in the docs <p>(new window)</p>">\n     see the docs \n    <i class="icon-help"></i>\n</a>\n.', null=True, verbose_name='URL for source code'),
        ),
        migrations.AlterField(
            model_name='terraformplanhook',
            name='git_source_code_url',
            field=models.TextField(blank=True, help_text='Code will be fetched from here before action is run. E.g. URL (without any authentication tokens) to the raw file hosted on your github.com repository. For details \n\n\n\n\n\n<a href="/static-b0175/docs/HTML/actions-with-code.html#external-source-code"\n    id="docs-link"\n    target="help"\n    class="no-tooltip-affordance"\n    data-toggle="tooltip"\n    data-html="true"\n    title="Learn more in the docs <p>(new window)</p>">\n     see the docs \n    <i class="icon-help"></i>\n</a>\n.', null=True, verbose_name='URL for source code'),
        ),
        migrations.AlterField(
            model_name='terraformplanhook',
            name='source_code_url',
            field=models.TextField(blank=True, help_text='Code will be fetched from here before action is run. E.g. URL (without any authentication tokens) to the raw file hosted on your github.com repository. For details \n\n\n\n\n\n<a href="/static-b0175/docs/HTML/actions-with-code.html#external-source-code"\n    id="docs-link"\n    target="help"\n    class="no-tooltip-affordance"\n    data-toggle="tooltip"\n    data-html="true"\n    title="Learn more in the docs <p>(new window)</p>">\n     see the docs \n    <i class="icon-help"></i>\n</a>\n.', null=True, verbose_name='URL for source code'),
        ),
    ]
