# Generated by Django 2.2.16 on 2020-12-16 22:48

import common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0082_auto_20201120_0724'),
    ]

    operations = [
        migrations.AddField(
            model_name='hookpointaction',
            name='global_id',
            field=models.CharField(default=common.mixins.get_global_id_chars, help_text='Identifier that can be used to access this object through the API across instances.', max_length=16, verbose_name='Global ID'),
        ),
        migrations.AddField(
            model_name='resourceaction',
            name='global_id',
            field=models.CharField(default=common.mixins.get_global_id_chars, help_text='Identifier that can be used to access this object through the API across instances.', max_length=16, verbose_name='Global ID'),
        ),
        migrations.AddField(
            model_name='serveraction',
            name='global_id',
            field=models.CharField(default=common.mixins.get_global_id_chars, help_text='Identifier that can be used to access this object through the API across instances.', max_length=16, verbose_name='Global ID'),
        ),
    ]
