# Generated by Django 2.2.16 on 2020-12-16 22:12

from django.db import migrations

from common.mixins import get_global_id_chars


class Migration(migrations.Migration):

    def set_global_ids(apps, schema_editor):
        models = {
            "ResourceAction": "RSA",
            "HookPointAction": "HPA",
            "ServerAction": "SVA",
        }

        for model in models:
            action_model = apps.get_model("cbhooks", model)
            prefix = models[model]
            for row in action_model.objects.all():
                chars = get_global_id_chars()
                row.global_id = f"{prefix}-{chars}"
                row.save()

    dependencies = [
        ('cbhooks', '0083_actions_global_ids'),
    ]

    operations = [
        migrations.RunPython(set_global_ids, migrations.RunPython.noop)
    ]
