# Generated by Django 2.2.16 on 2020-12-17 17:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0084_set_actions_global_ids'),
        ('cbhooks', '0084_set_global_id_for_trigger_point'),
    ]

    operations = [
    ]
