# Generated by Django 2.2.16 on 2021-06-21 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0087_set_global_id_for_orchestration_hook'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceaction',
            name='extra_classes',
            field=models.CharField(blank=True, default='', help_text="Can be used to add an icon on the button. Must correspond to an icon name thatCloudBolt has. Ex. 'icon-delete', 'glyphicon glyphicon-time', 'fas fa-heartbeat'. Formore examples, see<a href='http://fortawesome.github.io/Font-Awesome/icons/'>Font Awesome</a> and<a href='https://getbootstrap.com/docs/3.3/components/'>Glyphicons</a>", max_length=255, verbose_name='Extra classes'),
        ),
        migrations.AlterField(
            model_name='serveraction',
            name='extra_classes',
            field=models.CharField(blank=True, default='', help_text="Can be used to add an icon on the button. Must correspond to an icon name thatCloudBolt has. Ex. 'icon-delete', 'glyphicon glyphicon-time', 'fas fa-heartbeat'. Formore examples, see<a href='http://fortawesome.github.io/Font-Awesome/icons/'>Font Awesome</a> and<a href='https://getbootstrap.com/docs/3.3/components/'>Glyphicons</a>", max_length=255, verbose_name='Extra classes'),
        ),
    ]
