# Generated by Django 3.2.3 on 2021-08-20 20:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0089_orchestrationhook_blueprints'),
    ]

    operations = [
        migrations.AddField(
            model_name='terraformplanhook',
            name='branch',
            field=models.CharField(blank=True, help_text='Branch of the git repo to use.', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='terraformplanhook',
            name='preserve_config_dir',
            field=models.BooleanField(default=False, help_text='Should the contents of the working directory be preserved across orders'),
        ),
        migrations.AddField(
            model_name='terraformplanhook',
            name='refresh_on_order',
            field=models.BooleanField(default=False, help_text='Refresh code from source on every order?'),
        ),
    ]
