# Generated by Django 3.2.3 on 2021-08-20 20:54

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0090_auto_20210820_2054'),
        ('servicecatalog', '0072_terraformconfigserviceitem'),
    ]

    operations = [
        migrations.AddField(
            model_name='terraformstatefile',
            name='config_service_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicecatalog.terraformconfigserviceitem', verbose_name='Terraform Config Service Item'),
        ),
        migrations.AlterField(
            model_name='terraformstatefile',
            name='service_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='servicecatalog.runterraformplanhookserviceitem', verbose_name='Terraform Plan Hook Service Item (Legacy)'),
        ),
    ]
