# Generated by Django 3.2.5 on 2021-10-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0092_remove_netscaler_actions'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourceaction',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='serveraction',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='triggerpoint',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
