# Generated by Django 2.2.16 on 2021-01-14 17:12

import common.fields
from django.db import migrations
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('vra', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vrapolicy',
            name='user_mappings',
        ),
        migrations.AddField(
            model_name='vrapolicy',
            name='user_mapping',
            field=common.fields.TemplatableField(default='', help_text='(Templatable) The User Mapping for this vRealize Automation Policy', max_length=65536, validators=[driven_apps.common.validators.StringFieldValidator(blank=False, field_name='userMapping', template=True)]),
        ),
    ]
