# Generated by Django 2.2.16 on 2021-01-15 21:21

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json
import driven_apps.common.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_userprofile_widgets_json'),
        ('naming', '0071_auto_20210112_1807'),
        ('vra', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='VraDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('deployment_info', django_extensions.db.fields.json.JSONField(default=dict)),
                ('blueprint_name', models.TextField(blank=True, null=True)),
                ('project_name', models.TextField(blank=True, null=True)),
                ('archived', models.BooleanField(default=False)),
                ('job_metadata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='naming.JobMetadata')),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vra.VraPolicy')),
                ('workspace', models.ForeignKey(help_text='Workspace URL', on_delete=django.db.models.deletion.PROTECT, to='accounts.Group')),
            ],
            options={
                'verbose_name_plural': 'vRealize Automation Deployments',
                'db_table': 'vra_deployments',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(models.Model, driven_apps.common.mixins.RoleBasedHalFilteringMixin),
        ),
    ]
