# Generated by Django 2.2.16 on 2021-01-15 19:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vra', '0002_auto_20210114_1712'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vrapolicy',
            name='user_mapping',
        ),
    ]
