# Generated by Django 2.2.16 on 2021-01-26 17:49

import common.fields
from django.db import migrations
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('vra', '0004_auto_20210120_1552'),
    ]

    operations = [
        migrations.AddField(
            model_name='vrapolicy',
            name='blueprint_id',
            field=common.fields.TemplatableField(blank=True, help_text='(Templatable) The Blueprint Id for this vRealize Automation Policy', max_length=65536, null=True, validators=[driven_apps.common.validators.StringFieldValidator(blank=True, field_name='cloudTemplateInputs', template=True), driven_apps.common.validators.RegexValidator(field_name='blueprintId', message='Must be a valid UUID.', regex='^[0-9A-fa-f-]*$', template=True)]),
        ),
        migrations.AddField(
            model_name='vrapolicy',
            name='project_name',
            field=common.fields.TemplatableField(blank=True, help_text='(Templatable) The Project Name for this vRealize Automation Policy', max_length=65536, null=True, validators=[driven_apps.common.validators.StringFieldValidator(blank=True, field_name='cloudTemplateInputs', template=True)]),
        ),
        migrations.AlterField(
            model_name='vrapolicy',
            name='cloud_template_inputs',
            field=common.fields.TemplatableField(blank=True, help_text='(Templatable) The Cloud Template Inputs for this vRealize Automation Policy', max_length=65536, null=True, validators=[driven_apps.common.validators.StringFieldValidator(blank=True, field_name='cloudTemplateInputs', template=True)]),
        ),
    ]
