# Generated by Django 2.2.16 on 2021-01-26 19:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vra', '0002_vradeployment'),
        ('vra', '0005_auto_20210126_1749'),
    ]

    operations = [
    ]
