# Generated by Django 2.2.16 on 2021-01-26 22:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vra', '0006_auto_20210126_2052'),
        ('vra', '0006_merge_20210126_1952'),
    ]

    operations = [
    ]
