# Generated by Django 2.2.16 on 2021-03-02 17:10

import common.fields
from django.db import migrations, models
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('vra', '0007_merge_20210126_2241'),
    ]

    operations = [
        migrations.AddField(
            model_name='vra8policy',
            name='user_mapping',
            field=common.fields.TemplatableField(blank=True, help_text='(Templatable) User mapping', max_length=65536, null=True, validators=[driven_apps.common.validators.StringFieldValidator(blank=True, field_name='userMappings', template=True)]),
        ),
        migrations.AddField(
            model_name='vra8policy',
            name='verify_new_deployment_owner',
            field=models.BooleanField(default=False, help_text='Verify new deployment owner', null=True, validators=[driven_apps.common.validators.BooleanFieldValidator(field_name='verifyNewDeploymentOwner')]),
        ),
    ]
