# Generated by Django 2.2.16 on 2021-03-02 18:37

import common.fields
from django.db import migrations, models
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('vra', '0008_auto_20210302_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vra8policy',
            name='user_mapping',
            field=common.fields.TemplatableField(default='{{ deploymentOwner | required }}', help_text='(Templatable) User mapping', max_length=65536, validators=[driven_apps.common.validators.StringFieldValidator(blank=True, field_name='userMappings', template=True), driven_apps.common.validators.RequiredFieldValidator(field_name='userMappings')]),
        ),
        migrations.AlterField(
            model_name='vra8policy',
            name='verify_new_deployment_owner',
            field=models.BooleanField(default=True, help_text='Verify new deployment owner', validators=[driven_apps.common.validators.BooleanFieldValidator(field_name='verifyNewDeploymentOwner'), driven_apps.common.validators.RequiredFieldValidator(field_name='verifyNewDeploymentOwner')]),
        ),
    ]
