# Generated by Django 2.2.16 on 2021-05-14 19:08

import common.fields
from django.db import migrations
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('vra', '0011_auto_20210309_2040'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vrapolicy',
            name='cloud_template_name',
            field=common.fields.TemplatableField(help_text='(Templatable) The Cloud Template Name for this vRealize Automation Policy (A.K.A) Blueprint Name', max_length=65536, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='cloudTemplateName')]),
        ),
        migrations.AlterField(
            model_name='vrapolicy',
            name='cloud_template_version_number',
            field=common.fields.TemplatableField(help_text='(Templatable) The Cloud Template Version Number for this vRealize Automation Policy', max_length=65536, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='cloudTemplateVersionNumber')]),
        ),
    ]
