# Generated by Django 2.2.10 on 2020-03-06 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='PropertySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('type', models.CharField(choices=[('static', 'static'), ('dynamic', 'dynamic')], max_length=255)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('properties', models.TextField(max_length=10485750)),
            ],
            options={
                'verbose_name_plural': 'Property Sets',
                'db_table': 'property_sets',
            },
        ),
    ]
