# Generated by Django 2.2.10 on 2020-03-09 21:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('property_sets', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyset',
            name='properties',
            field=models.TextField(),
        ),
    ]
