# Generated by Django 2.2.10 on 2020-03-11 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    replaces = [('property_sets', '0003_auto_20200311_1447'), ('property_sets', '0004_auto_20200311_1516')]

    dependencies = [
        ('property_sets', '0002_auto_20200309_2109'),
    ]

    operations = [
        migrations.RenameField(
            model_name='propertyset',
            old_name='properties',
            new_name='_properties',
        ),
        migrations.AlterField(
            model_name='propertyset',
            name='_properties',
            field=models.TextField(default='{}'),
        ),
    ]
