# Generated by Django 2.2.10 on 2020-05-06 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0051_auto_20200323_1456'),
        ('property_sets', '0004_auto_20200312_1814'),
    ]

    operations = [
        migrations.AddField(
            model_name='propertyset',
            name='workspace',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='accounts.Group'),
        ),
    ]
