# Generated by Django 2.2.10 on 2020-05-14 20:08

from django.db import migrations, models
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('property_sets', '0008_auto_20200508_1529'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyset',
            name='type',
            field=models.CharField(choices=[('static', 'static'), ('dynamic', 'dynamic')], max_length=255, validators=[driven_apps.common.validators.OneOfValidator(['dynamic', 'static'])]),
        ),
    ]
