# Generated by Django 2.2.12 on 2020-06-17 15:18

from django.db import migrations, models
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('property_sets', '0010_auto_20200602_2054'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyset',
            name='type',
            field=models.CharField(choices=[('static', 'static')], max_length=255, validators=[driven_apps.common.validators.EqualsValidator(field_name='type', required_value='static')]),
        ),
    ]
