# Generated by Django 2.2.16 on 2021-01-20 15:52

from django.db import migrations, models
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('property_sets', '0012_auto_20200619_1623'),
    ]

    operations = [
        migrations.AlterField(
            model_name='propertyset',
            name='name',
            field=models.CharField(max_length=255, unique=True, validators=[driven_apps.common.validators.NotBlankValidator(field_name='name', required=True), driven_apps.common.validators.MinLengthValidator(constraint=3, field_name='name', required=True), driven_apps.common.validators.RegexValidator(field_name='name', message='Must be alphanumeric characters and/or underscores.', regex='^[0-9A-Za-z_]*$', template=False)]),
        ),
    ]
