# Generated by Django 2.2.16 on 2021-06-04 17:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('property_sets', '0014_auto_20210126_1922'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='propertyset',
            name='type',
        ),
    ]
