# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 18:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_cloudbolttag_model_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudbolttag',
            name='name',
            field=models.CharField(max_length=100, verbose_name='Name'),
        ),
        migrations.AlterUniqueTogether(
            name='cloudbolttag',
            unique_together=set([('model_name', 'name')]),
        ),
    ]
