# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-23 19:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0004_initialize_model_name_20180201_2119'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudbolttag',
            name='parent',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='child_tags', to='tags.CloudBoltTag'),
        ),
    ]
