# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-23 19:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0005_cloudbolttag_parent'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudbolttag',
            name='sequence',
            field=models.IntegerField(default=0, help_text='Sequence specifies the order labels appear in the catalog. Lower-number sequence numbers will show up first. (default=0)', verbose_name='Sequence'),
        ),
    ]
