# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-17 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0010_set_bidirectional_sync_on_taggableattribute_20190419_2105'),
    ]

    operations = [
        migrations.AlterField(
            model_name='autocorrecttagvaluemapping',
            name='correct_value',
            field=models.CharField(max_length=255, verbose_name='correct value'),
        ),
        migrations.AlterField(
            model_name='autocorrecttagvaluemapping',
            name='misspelled_value',
            field=models.CharField(max_length=255, verbose_name='misspelled value'),
        ),
        migrations.AlterField(
            model_name='taggableattribute',
            name='attribute',
            field=models.CharField(help_text='Property of a CloudBolt server whose value will be assigned to the tag value', max_length=255, verbose_name='attribute'),
        ),
    ]
