# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-30 18:39
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("tags", "0011_auto_20191017_0101"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="autocorrecttagvaluemapping", name="resource_handler",
        ),
        migrations.DeleteModel(name="AutoCorrectTagValueMapping",),
    ]
