# Generated by Django 2.2.16 on 2021-03-26 16:54

import common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0012_auto_20191030_1839'),
    ]

    operations = [
        migrations.AddField(
            model_name='cloudbolttag',
            name='global_id',
            field=models.CharField(default=common.mixins.get_global_id_chars, help_text='Identifier that can be used to access this object through the API across instances.', max_length=16, verbose_name='Global ID'),
        ),
    ]
