# Generated by Django 3.2.3 on 2021-05-27 20:58

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
        ('tags', '0014_set_global_id_for_cloudbolttag'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cloudbolttag',
            name='slug',
            field=models.SlugField(max_length=100, unique=True, verbose_name='slug'),
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='content_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags_taggeditem_tagged_items', to='contenttypes.contenttype', verbose_name='content type'),
        ),
        migrations.AlterField(
            model_name='taggeditem',
            name='object_id',
            field=models.IntegerField(db_index=True, verbose_name='object ID'),
        ),
    ]
