# Generated by Django 3.2.5 on 2021-12-17 10:08

import common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0016_alter_taggableattribute_resource_handler'),
    ]

    operations = [
        migrations.AddField(
            model_name='taggableattribute',
            name='global_id',
            field=models.CharField(default=common.mixins.get_global_id_chars, help_text='Identifier that can be used to access this object through the API across instances.', max_length=16, verbose_name='Global ID'),
        ),
    ]
