# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-02 19:49
from __future__ import unicode_literals

import costs.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0003_disktypemultiplier'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrate',
            name='poweroff_rate',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Enter the rate to be used when the resource is powered OFF.', max_digits=65, null=True, validators=[costs.models.isOnlyDigits]),
        ),
        migrations.AddField(
            model_name='customfieldrate',
            name='poweroff_rate',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Enter the rate to be used when the resource is powered OFF.', max_digits=65, null=True, validators=[costs.models.isOnlyDigits]),
        ),
        migrations.AddField(
            model_name='licenserate',
            name='poweroff_rate',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Enter the rate to be used when the resource is powered OFF.', max_digits=65, null=True, validators=[costs.models.isOnlyDigits]),
        ),
        migrations.AddField(
            model_name='osbuildrate',
            name='poweroff_rate',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Enter the rate to be used when the resource is powered OFF.', max_digits=65, null=True, validators=[costs.models.isOnlyDigits]),
        ),
        migrations.AlterField(
            model_name='applicationrate',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Enter the rate to be used when the resource is powered ON.', max_digits=65, null=True, validators=[costs.models.isOnlyDigits]),
        ),
        migrations.AlterField(
            model_name='customfieldrate',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Enter the rate to be used when the resource is powered ON.', max_digits=65, null=True, validators=[costs.models.isOnlyDigits]),
        ),
        migrations.AlterField(
            model_name='licenserate',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Enter the rate to be used when the resource is powered ON.', max_digits=65, null=True, validators=[costs.models.isOnlyDigits]),
        ),
        migrations.AlterField(
            model_name='osbuildrate',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=10, help_text='Enter the rate to be used when the resource is powered ON.', max_digits=65, null=True, validators=[costs.models.isOnlyDigits]),
        ),
    ]
