# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 21:21
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0038_auto_20180625_2145'),
        ('costs', '0005_auto_20170605_1711'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingLineItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('quantity', models.IntegerField()),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('cost', models.DecimalField(decimal_places=10, max_digits=20)),
                ('resource_id', models.CharField(help_text='The ID of the external resource from the cloud provider.', max_length=255)),
                ('server', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='infrastructure.Server')),
            ],
        ),
    ]
