# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-03 01:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0006_billinglineitem'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='billinglineitem',
            name='end_date',
        ),
        migrations.RemoveField(
            model_name='billinglineitem',
            name='start_date',
        ),
        migrations.AddField(
            model_name='billinglineitem',
            name='date',
            field=models.DateField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
