# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-06 00:08
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourcehandlers', '0011_resourcehandler_enable_terminal_feature'),
        ('costs', '0007_auto_20190103_0142'),
    ]

    operations = [
        migrations.CreateModel(
            name='BillingSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=10, max_digits=20)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
                ('cost', models.DecimalField(decimal_places=10, max_digits=20)),
                ('category', models.CharField(max_length=255)),
                ('start_date', models.DateTimeField()),
                ('end_date', models.DateTimeField()),
                ('column', models.CharField(blank=True, help_text='Enter the column name if this summary data is the result of a groupby summary on a specific column in the original bill.', max_length=255, null=True)),
                ('resource_handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='resourcehandlers.ResourceHandler')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='billinglineitem',
            name='quantity',
            field=models.DecimalField(decimal_places=10, max_digits=20),
        ),
    ]
