# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-06 18:12
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0003_auto_20190806_1812'),
        ('costs', '0008_auto_20190206_0008'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCPBillingSummary',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(max_length=255)),
                ('invoice_date', models.DateField()),
                ('cost', models.DecimalField(decimal_places=10, max_digits=20)),
                ('project', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='gcp.GCPProject')),
            ],
        ),
    ]
