# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-16 22:57
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0009_gcpbillingsummary'),
    ]

    operations = [
        migrations.CreateModel(
            name='CurrencyConversionRate',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('symbol', models.CharField(help_text='Ex. ¥, €, £, SEK, CHF, R$, $, etc', max_length=10)),
                ('rate', models.DecimalField(decimal_places=10, max_digits=20)),
            ],
        ),
    ]
