# Generated by Django 2.2.16 on 2021-05-20 23:28

import common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('costs', '0011_auto_20191021_2342'),
    ]

    operations = [
        migrations.AddField(
            model_name='applicationrate',
            name='global_id',
            field=models.CharField(default=common.mixins.get_global_id_chars, help_text='Identifier that can be used to access this object through the API across instances.', max_length=16, verbose_name='Global ID'),
        ),
        migrations.AddField(
            model_name='customfieldrate',
            name='global_id',
            field=models.CharField(default=common.mixins.get_global_id_chars, help_text='Identifier that can be used to access this object through the API across instances.', max_length=16, verbose_name='Global ID'),
        ),
        migrations.AddField(
            model_name='osbuildrate',
            name='global_id',
            field=models.CharField(default=common.mixins.get_global_id_chars, help_text='Identifier that can be used to access this object through the API across instances.', max_length=16, verbose_name='Global ID'),
        ),
    ]
