# Generated by Django 2.2.16 on 2021-05-18 23:42

from django.db import migrations

from common.mixins import get_global_id_chars


def set_ids_for_model(Model):
    prefix = "RTE"
    for row in Model.objects.all():
        chars = get_global_id_chars()
        row.global_id = f"{prefix}-{chars}"
        row.save()


class Migration(migrations.Migration):

    def set_global_ids(apps, schema_editor):
        ApplicationRate = apps.get_model("costs", "ApplicationRate")
        set_ids_for_model(ApplicationRate)
        CustomFieldRate = apps.get_model("costs", "CustomFieldRate")
        set_ids_for_model(CustomFieldRate)
        OSBuildRate = apps.get_model("costs", "OSBuildRate")
        set_ids_for_model(OSBuildRate)

    dependencies = [
        ('costs', '0012_rates_global_ids'),
    ]

    operations = [
        migrations.RunPython(set_global_ids, migrations.RunPython.noop)
    ]
