# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-03 22:59
from __future__ import unicode_literals

import common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('aws', '0003_auto_20161004_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='AWSPrivateConnectionInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('endpoint', models.CharField(max_length=1024)),
                ('is_secure', models.BooleanField(default=True)),
                ('port', models.IntegerField(blank=True, null=True, validators=[common.validators.is_only_digits])),
                ('path', models.CharField(blank=True, max_length=1024)),
            ],
        ),
        migrations.CreateModel(
            name='AWSPrivateHandler',
            fields=[
                ('awshandler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='aws.AWSHandler')),
                ('ec2_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ec2_handlers', to='aws_private.AWSPrivateConnectionInfo')),
                ('elb_connection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='elb_handlers', to='aws_private.AWSPrivateConnectionInfo')),
            ],
            options={
                'verbose_name': 'AWS Private resource handler',
            },
            bases=('aws.awshandler',),
        ),
        migrations.AlterField(
            model_name='awsprivateconnectioninfo',
            name='is_secure',
            field=models.BooleanField(default=True, verbose_name='Connect over SSL'),
        ),
    ]
