# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-27 03:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontent', '0012_duplicate_osbas_in_multiple_rhs'),
        ('tags', '0006_cloudbolttag_sequence'),
        ('behavior_mapping', '0009_auto_20180119_1931'),
        ('costs', '0008_auto_20190206_0008'),
        ('history', '0014_auto_20190111_0124'),
        ('infrastructure', '0038_auto_20180625_2145'),
        ('resourcehandlers', '0011_resourcehandler_enable_terminal_feature'),
        ('networks', '0005_auto_20180202_1944'),
        ('jobs', '0031_recurringjob_last_run'),
        ('resources', '0008_fontawesome_4to5'),
        ('aws_private', '0002_auto_20190227_0101'),
    ]

    operations = [
        migrations.DeleteModel(
            name='AWSPrivateHandler',
        ),
        migrations.DeleteModel(
            name='AWSPrivateConnectionInfo',
        ),
    ]
