# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 20:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_auto_20160829_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serverhistory',
            name='custom_field_values',
        ),
    ]
