# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-01 20:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0015_auto_20170505_0022'),
        ('accounts', '0018_rename_server_owners'),
        ('externalcontent', '0005_auto_20170325_1506'),
        ('orders', '0011_installpodorderitem_custom_field_values'),
        ('resourcehandlers', '0003_resourcetechnology_slug'),
        ('history', '0003_remove_serverhistory_custom_field_values'),
    ]

    operations = [
        migrations.AddField(
            model_name='serverhistory',
            name='applications',
            field=models.ManyToManyField(blank=True, to='externalcontent.Application'),
        ),
        migrations.AddField(
            model_name='serverhistory',
            name='custom_field_values',
            field=models.ManyToManyField(blank=True, to='orders.CustomFieldValue'),
        ),
        migrations.AddField(
            model_name='serverhistory',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.Environment'),
        ),
        migrations.AddField(
            model_name='serverhistory',
            name='extra_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=65, null=True, verbose_name='Extra Rate'),
        ),
        migrations.AddField(
            model_name='serverhistory',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.Group'),
        ),
        migrations.AddField(
            model_name='serverhistory',
            name='hostname',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='serverhistory',
            name='hw_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=65, null=True, verbose_name='Hardware Rate'),
        ),
        migrations.AddField(
            model_name='serverhistory',
            name='ip',
            field=models.CharField(blank=True, max_length=200, verbose_name='IP'),
        ),
        migrations.AddField(
            model_name='serverhistory',
            name='mac',
            field=models.CharField(blank=True, max_length=200),
        ),
        migrations.AddField(
            model_name='serverhistory',
            name='os_build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='externalcontent.OSBuild', verbose_name='OS Build'),
        ),
        migrations.AddField(
            model_name='serverhistory',
            name='resource_handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resourcehandlers.ResourceHandler'),
        ),
        migrations.AddField(
            model_name='serverhistory',
            name='sw_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=65, null=True, verbose_name='Software Rate'),
        ),
        migrations.AddField(
            model_name='serverhistory',
            name='total_rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=65, null=True, verbose_name='Total Rate'),
        ),
        migrations.AlterField(
            model_name='serverhistory',
            name='cpu_cnt',
            field=models.IntegerField(blank=True, null=True, verbose_name='Number of CPUs'),
        ),
        migrations.AlterField(
            model_name='serverhistory',
            name='disk_size',
            field=models.IntegerField(blank=True, null=True, verbose_name='Disk size (GB)'),
        ),
        migrations.AlterField(
            model_name='serverhistory',
            name='mem_size',
            field=models.DecimalField(blank=True, decimal_places=4, max_digits=10, null=True, verbose_name='Memory size (GB)'),
        ),
    ]
