# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-07 22:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0004_auto_20170601_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverhistory',
            name='environment',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='infrastructure.Environment'),
        ),
        migrations.AlterField(
            model_name='serverhistory',
            name='group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.Group'),
        ),
    ]
