# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 18:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0005_auto_20170607_2259'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serverhistory',
            name='applications',
            field=models.ManyToManyField(blank=True, to='externalcontent.Application', verbose_name='Applications'),
        ),
    ]
