# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 18:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0006_auto_20171012_1842'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceHistory',
            new_name='ResourceHistory',
        ),
    ]
