# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-14 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0008_auto_20171214_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resourcehistory',
            name='_resource',
            field=models.TextField(help_text='JSON representation of the dictionary serialization of the resource at a given time (event_time)'),
        ),
    ]
