# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-16 21:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0011_resourcehandlerhistory'),
        ('history', '0011_resourcehistory_misc_rate'),
    ]

    operations = [
    ]
