# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-18 23:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0021_auto_20180202_1944'),
        ('history', '0011_resourcehistory_misc_rate'),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderHistory',
            fields=[
                ('historymodel_ptr', models.OneToOneField(auto_created=True, parent_link=True, primary_key=True, serialize=False, to='history.HistoryModel', on_delete=models.CASCADE)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='orders.Order')),
            ],
            options={
                'abstract': False,
            },
            bases=('history.historymodel',),
        ),
    ]
