# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-01 20:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0012_orderhistory'),
        ('history', '0012_merge_20180416_2159'),
    ]

    operations = [
    ]
