# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-16 15:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0015_alerthistory'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alerthistory',
            name='message',
            field=models.TextField(default='', help_text='The message provided for the alert', verbose_name="Alert's Message"),
        ),
    ]
