# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-04 11:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0064_auto_20191118_2305'),
        ('history', '0017_historymodel_rate_change'),
    ]

    operations = [
        migrations.CreateModel(
            name='ActionHistory',
            fields=[
                ('historymodel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='history.HistoryModel')),
                ('base_action', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbhooks.OrchestrationHook')),
                ('orchestration_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbhooks.HookPointAction')),
                ('resource_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbhooks.ResourceAction')),
                ('server_action', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbhooks.ServerAction')),
            ],
            options={
                'abstract': False,
            },
            bases=('history.historymodel',),
        ),
    ]
