# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-20 18:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('externalcontent', '0005_auto_20170325_1506'),
        ('resourcehandlers', '0003_resourcetechnology_slug'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcropolisImage',
            fields=[
                ('osbuildattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='externalcontent.OSBuildAttribute')),
                ('template_name', models.CharField(max_length=1024)),
                ('description', models.CharField(max_length=1024)),
                ('total_disk_size', models.DecimalField(blank=True, decimal_places=4, help_text='Total size of all disks on this image in GB', max_digits=10, null=True)),
                ('uuid', models.CharField(max_length=100)),
            ],
            options={
                'verbose_name': 'Image',
            },
            bases=('externalcontent.osbuildattribute',),
        ),
        migrations.CreateModel(
            name='AcropolisResourceHandler',
            fields=[
                ('resourcehandler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resourcehandlers.ResourceHandler')),
                ('networks', models.ManyToManyField(blank=True, to='resourcehandlers.ResourceNetwork')),
                ('os_build_attributes', models.ManyToManyField(blank=True, to='acropolis.AcropolisImage')),
            ],
            options={
                'verbose_name': 'Acropolis resource handler',
            },
            bases=('resourcehandlers.resourcehandler',),
        ),
    ]
