# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-16 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0033_auto_20180508_1222'),
        ('acropolis', '0004_acropolisdisk'),
    ]

    operations = [
        migrations.CreateModel(
            name='AcropolisServerInfo',
            fields=[
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='infrastructure.Server')),
                ('sockets', models.IntegerField(blank=True, null=True)),
                ('vcpus_per_socket', models.IntegerField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
