# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-18 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0038_auto_20180625_2145'),
        ('acropolis', '0005_acropolisserverinfo'),
    ]

    operations = [
        migrations.AddField(
            model_name='acropolisserverinfo',
            name='snapshots',
            field=models.ManyToManyField(blank=True, to='infrastructure.ServerSnapshot'),
        ),
    ]
