# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-03 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('acropolis', '0006_acropolisserverinfo_snapshots'),
    ]

    operations = [
        migrations.AddField(
            model_name='acropolisresourcehandler',
            name='nutanix_api_version',
            field=models.CharField(choices=[('v2', 'v2'), ('v3', 'v3')], default='v3', help_text="The version of the Nutanix Acropolis API you're connecting to.", max_length=20),
        ),
    ]
