# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-02 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('acropolis', '0007_acropolisresourcehandler_nutanix_api_version'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='acropolisimage',
            name='old_template_name',
        ),
        migrations.RemoveField(
            model_name='acropolisresourcehandler',
            name='old_os_build_attributes',
        ),
    ]
