# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-06-14 18:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('resourcehandlers', '0012_auto_20190501_1815'),
        ('externalcontent', '0012_duplicate_osbas_in_multiple_rhs'),
        ('infrastructure', '0039_auto_20190503_2313'),
        ('utilities', '0062_merge_20190423_2120'),
    ]

    operations = [
        migrations.CreateModel(
            name='OCIImage',
            fields=[
                ('osbuildattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='externalcontent.OSBuildAttribute')),
                ('uuid', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
            bases=('externalcontent.osbuildattribute',),
        ),
        migrations.CreateModel(
            name='OCIResourceHandler',
            fields=[
                ('resourcehandler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resourcehandlers.ResourceHandler')),
                ('region', models.CharField(max_length=20)),
                ('user', models.CharField(max_length=200)),
                ('fingerprint', models.CharField(max_length=47)),
                ('key_file', models.CharField(max_length=4096)),
                ('pass_phrase', models.CharField(max_length=100)),
                ('tenancy', models.CharField(max_length=200)),
                ('compartment', models.CharField(max_length=200)),
                ('connection_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.ConnectionInfo')),
            ],
            options={
                'verbose_name': 'Oracle Cloud Infrastructure resource handler',
                'abstract': False,
            },
            bases=('resourcehandlers.resourcehandler',),
        ),
        migrations.CreateModel(
            name='OCIResourceNetwork',
            fields=[
                ('resourcenetwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resourcehandlers.ResourceNetwork')),
                ('uuid', models.CharField(max_length=256)),
                ('cidr_block', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Oracle Cloud Infrastructure Switch',
                'abstract': False,
            },
            bases=('resourcehandlers.resourcenetwork',),
        ),
        migrations.CreateModel(
            name='OCIServerInfo',
            fields=[
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='infrastructure.Server')),
                ('availability_domain', models.CharField(max_length=20)),
                ('shape', models.CharField(max_length=20)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='ociresourcehandler',
            name='networks',
            field=models.ManyToManyField(blank=True, to='oci.OCIResourceNetwork'),
        ),
    ]
