# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-07 10:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('oci', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ociserverinfo',
            name='availability_domain',
            field=models.CharField(max_length=255),
        ),
        migrations.AlterField(
            model_name='ociserverinfo',
            name='shape',
            field=models.CharField(max_length=255),
        ),
    ]
