# Generated by Django 2.2.10 on 2020-10-14 19:13

import common.fields
from django.db import migrations, models
import django.db.models.deletion
import driven_apps.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('credentials', '0003_modulecredential_connection_method'),
        ('accounts', '0053_encrypt_security_answers'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptingPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The user-specified name of this Scripting Policy.', max_length=255, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='name'), driven_apps.common.validators.MinLengthValidator(constraint=3, field_name='name', required=True), driven_apps.common.validators.RegexValidator(field_name='name', message='Must be alphanumeric characters and/or underscores.', regex='^[0-9A-Za-z_]*$')])),
                ('description', models.TextField(blank=True, help_text='The description text for this Scripting Policy.', null=True)),
                ('target_host', common.fields.TemplatableField(help_text='The target host for this Scripting Policy.', max_length=65536, validators=[driven_apps.common.validators.StringFieldValidator(blank=False, field_name='target_host', template=True)])),
                ('provision_launch_command_template', common.fields.TemplatableField(help_text='The launch command template for this Scripting Policy.', max_length=65536, validators=[driven_apps.common.validators.StringFieldValidator(blank=False, field_name='provision_launch_command_template', template=True)])),
                ('provision_script', common.fields.TemplatableField(help_text='The script for this Scripting Policy.', max_length=65536, validators=[driven_apps.common.validators.StringFieldValidator(blank=False, field_name='provision_script', template=True)])),
                ('provision_success_exit_codes', common.fields.TemplatableField(help_text='The success exit codes for this Scripting Policy.', max_length=65536, validators=[driven_apps.common.validators.StringFieldValidator(blank=False, field_name='provision_success_exit_codes', template=True)])),
                ('credential', models.ForeignKey(help_text='Credential for this Scripting Policy.', on_delete=django.db.models.deletion.PROTECT, to='credentials.ModuleCredential')),
                ('workspace', models.ForeignKey(help_text='Workspace URL', on_delete=django.db.models.deletion.PROTECT, to='accounts.Group')),
            ],
            options={
                'verbose_name_plural': 'Scripting Policies',
                'db_table': 'scripting_policies',
            },
        ),
    ]
