# Generated by Django 2.2.10 on 2020-10-20 17:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_scripting', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scriptingpolicy',
            options={'ordering': ['-id'], 'verbose_name': 'Scripting policy', 'verbose_name_plural': 'Scripting Policies'},
        ),
        migrations.AddConstraint(
            model_name='scriptingpolicy',
            constraint=models.UniqueConstraint(fields=('name',), name='scripting_policy_name_unique'),
        ),
    ]
