# Generated by Django 2.2.10 on 2020-10-26 19:16

from django.db import migrations, models
import django.db.models.deletion
import driven_apps.common.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0066_merge_20201023_1725'),
        ('accounts', '0054_auto_20201019_1709'),
        ('fuse_scripting', '0003_auto_20201022_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='ScriptingDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('hostname', models.CharField(blank='True', max_length=256, null='False')),
                ('details', models.TextField(blank='true', null='true')),
                ('job_metadata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='naming.JobMetadata')),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuse_scripting.ScriptingPolicy')),
                ('workspace', models.ForeignKey(help_text='Workspace URL', on_delete=django.db.models.deletion.PROTECT, to='accounts.Group')),
            ],
            options={
                'verbose_name_plural': 'Scripting Deployments',
                'db_table': 'scripting_deployments',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(models.Model, driven_apps.common.mixins.RoleBasedHalFilteringMixin),
        ),
    ]
