# Generated by Django 2.2.10 on 2020-11-18 16:58

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_scripting', '0004_scriptingdeployment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptingdeployment',
            name='details',
            field=django_extensions.db.fields.json.JSONField(blank='true', default=dict, null='true'),
        ),
    ]
