# Generated by Django 2.2.16 on 2020-11-19 15:00

from django.db import migrations, models
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_scripting', '0005_auto_20201118_1658'),
    ]

    operations = [
        migrations.AlterField(
            model_name='scriptingdeployment',
            name='details',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, null=True),
        ),
        migrations.AlterField(
            model_name='scriptingdeployment',
            name='hostname',
            field=models.CharField(blank=True, default='', max_length=256),
        ),
    ]
