# Generated by Django 2.2.16 on 2020-11-20 16:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_scripting', '0006_auto_20201119_1500'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptingdeployment',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
