# Generated by Django 2.2.16 on 2020-11-23 20:40

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_scripting', '0007_scriptingdeployment_archived'),
    ]

    operations = [
        migrations.AddField(
            model_name='scriptingpolicy',
            name='deprovision_launch_command_template',
            field=common.fields.TemplatableField(blank=True, help_text='The deprovisioning launch command template for this Scripting Policy.', max_length=65536, null=True),
        ),
        migrations.AddField(
            model_name='scriptingpolicy',
            name='deprovision_script',
            field=common.fields.TemplatableField(blank=True, help_text='The deprovisioning script for this Scripting Policy.', max_length=65536, null=True),
        ),
        migrations.AddField(
            model_name='scriptingpolicy',
            name='deprovision_success_exit_codes',
            field=common.fields.TemplatableField(blank=True, help_text='The deprovisioning success exit codes for this Scripting Policy.', max_length=65536, null=True),
        ),
        migrations.AlterField(
            model_name='scriptingpolicy',
            name='provision_launch_command_template',
            field=common.fields.TemplatableField(help_text='The provisioning launch command template for this Scripting Policy.', max_length=65536),
        ),
        migrations.AlterField(
            model_name='scriptingpolicy',
            name='provision_script',
            field=common.fields.TemplatableField(help_text='The provisioning script for this Scripting Policy.', max_length=65536),
        ),
        migrations.AlterField(
            model_name='scriptingpolicy',
            name='provision_success_exit_codes',
            field=common.fields.TemplatableField(help_text='The provisioning success exit codes for this Scripting Policy.', max_length=65536),
        ),
    ]
