# Generated by Django 2.2.16 on 2020-11-25 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_scripting', '0008_auto_20201124_1324'),
        ('fuse_scripting', '0008_auto_20201123_2040'),
    ]

    operations = [
    ]
