# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-24 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phpipam', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='phpipam',
            name='app_id',
            field=models.CharField(default='phpipam', help_text='App ID of the phpIPAM instance', max_length=50),
            preserve_default=False,
        ),
    ]
