# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-30 18:31
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0005_auto_20190710_1848'),
        ('phpipam', '0002_phpipam_app_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='PhpIPAMNetwork',
            fields=[
                ('ipamnetwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='ipam.IPAMNetwork')),
                ('phpipam_id', models.IntegerField()),
                ('section_id', models.IntegerField()),
            ],
            options={
                'abstract': False,
            },
            bases=('ipam.ipamnetwork',),
        ),
    ]
