# Generated by Django 3.2.3 on 2021-09-03 18:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('phpipam', '0003_phpipamnetwork'),
    ]

    operations = [
        migrations.AddField(
            model_name='phpipamnetwork',
            name='section_name',
            field=models.CharField(max_length=128, null=True),
        ),
    ]
