# Generated by Django 2.2.16 on 2021-04-14 16:18

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='IngestEvent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(max_length=256)),
                ('_ingest_date', models.DateTimeField(auto_now_add=True, null=True)),
                ('_managed_object_href', models.TextField()),
            ],
            options={
                'verbose_name': 'Ingest Events',
                'verbose_name_plural': 'Ingest Events',
                'db_table': 'ingest_events',
                'ordering': ['id'],
            },
        ),
    ]
