# Generated by Django 3.2.3 on 2021-06-29 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ingest', '0001_initial'),
    ]

    operations = [
        migrations.DeleteModel(
            name='IngestEvent',
        ),
    ]
