# Generated by Django 2.2.12 on 2020-06-23 13:50

import cb_secrets.fields
from django.db import migrations, models
import django.db.models.deletion
import driven_apps.common.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0052_auto_20200526_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModuleCredential',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('description', models.CharField(blank=True, max_length=1024, null=True)),
                ('username', models.CharField(blank=True, max_length=255, null=True)),
                ('password', cb_secrets.fields.EncryptedTextField(blank=True, max_length=255, null=True)),
                ('endpoint_type', models.CharField(blank=True, max_length=255, null=True)),
                ('workspace', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='accounts.Group')),
            ],
            options={
                'verbose_name_plural': 'Module Credentials',
                'db_table': 'module_credentials',
            },
            bases=(models.Model, driven_apps.common.mixins.RoleBasedHalFilteringMixin),
        ),
        migrations.AddConstraint(
            model_name='modulecredential',
            constraint=models.UniqueConstraint(fields=('endpoint_type', 'name'), name='credential_endpoint_type_name_unique'),
        ),
    ]
