# Generated by Django 2.2.10 on 2020-09-02 16:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('credentials', '0002_auto_20200626_2246'),
    ]

    operations = [
        migrations.AddField(
            model_name='modulecredential',
            name='connection_method',
            field=models.CharField(default='basic', max_length=12),
        ),
    ]
