# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-19 16:51
from __future__ import unicode_literals

from django.db import migrations


"""
With the 9.0 release, CloudBolt began the migration to support multiple IPAM Technologies OOTB instead of just Infoblox.
Part of this migration includes refactoring the ipam app to be more extensible and consistent with the rest of our
codebase. Included in this refactor is renaming the tech-specific module of the infoblox technology to be
`infoblox_wrapper` similar to how our RH wrappers are named. The reason for this change is to make it easier for future
consumers of the CB codebase to understand the relationship between the wrapper and models for the different
IPAMTechnology instances.
"""


def rename_existing_infoblox_modules(apps, schema_editor):
    IPAMTechnology = apps.get_model('ipam', 'IPAMTechnology')

    for tech in IPAMTechnology.objects.all():
        if tech.name == 'Infoblox':
            tech.modulename = 'ipam.infoblox.infoblox_wrapper'
            tech.save()


class Migration(migrations.Migration):

    dependencies = [
        ('infoblox', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(rename_existing_infoblox_modules, migrations.RunPython.noop)
    ]
