# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-04 22:59
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0009_remove_globalpreferences_enable_google_authentication'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalpreferences',
            name='main_list_per_page',
        ),
        migrations.RemoveField(
            model_name='globalpreferences',
            name='sub_list_per_page',
        ),
    ]
