# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-06 23:10
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0010_auto_20170104_2210'),
        ('utilities', '0010_auto_20170104_2259'),
    ]

    operations = [
    ]
