# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-20 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0012_catalogredirect_20170118_2124'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='a_la_carte_servers',
            field=models.BooleanField(default=True, help_text="If disabled, the 'New Server' button will not be shown (except to CB admins). This is useful if you want normal users to only order through the Catalog.", verbose_name='New Server button'),
        ),
    ]
