# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-01 19:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0013_auto_20170120_1845'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalpreferences',
            name='allow_approver_to_edit_pending_orders',
        ),
    ]
