# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-25 01:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0014_remove_globalpreferences_allow_approver_to_edit_pending_orders'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='restrict_job_logs_to_admins',
            field=models.BooleanField(default=False, help_text='Only CB admins can access job logs.'),
        ),
    ]
