# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-27 22:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0015_globalpreferences_restrict_job_logs_to_admins'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='restrict_job_logs_to_admins',
            field=models.BooleanField(default=False, help_text="When disabled, anyone who can see a job's details can also access the job's log. When enabled, only CB admins can see job logs."),
        ),
        migrations.AlterField(
            model_name='globalpreferences',
            name='security_message',
            field=models.CharField(blank=True, help_text='Shown under the nav bar on all pages. HTML tags ok, up to 1000 chars', max_length=1000, null=True),
        ),
    ]
