# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-05 20:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0012_create_job_owners_without_logs'),
        ('utilities', '0018_auto_20170407_1949'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalpreferences',
            name='powerful_requestors',
        ),
        migrations.RemoveField(
            model_name='globalpreferences',
            name='restrict_job_logs_to_admins',
        ),
    ]
