# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-09 14:34
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0019_remove_perm_related_booleans'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='enable_notebook_feature',
            field=models.BooleanField(default=False, help_text="Enables admins to access a Jupyter Notebook with Django's shell_plus for support and testing.", verbose_name='Notebook feature'),
        ),
    ]
