# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-15 18:13
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0019_add_power_schedule_perms'),
        ('utilities', '0019_remove_perm_related_booleans'),
    ]

    operations = [
        migrations.CreateModel(
            name='LDAPMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ldap_ou_dn', models.CharField(blank=True, help_text="Full distinguished name of the organizational unit. If blank, this mapping will apply regardless of the user's OU.", max_length=1024)),
                ('ldap_group_dn', models.CharField(blank=True, help_text='Full distinguished name of the group. If blank, this mapping will apply regardless of which groups the user belongs to.', max_length=1024)),
                ('ldap_utility', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.LDAPUtility')),
            ],
        ),
        migrations.CreateModel(
            name='LDAPMappingGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Group')),
                ('mapping', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='utilities.LDAPMapping')),
                ('roles', models.ManyToManyField(to='accounts.Role')),
            ],
        ),
    ]
