# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-17 19:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0020_globalpreferences_enable_notebook_feature'),
        ('utilities', '0020_ldapmapping_ldapmappinggroup'),
    ]

    operations = [
    ]
