# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 19:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0023_auto_20171003_1703'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='show_user_avatars',
            field=models.BooleanField(default=True, help_text='Show avatar images provided by external third party service hosted at gravatar.com. Users must create a Gravatar profile and associate an image with their email address. If disabled, user initials are shown instead.', verbose_name='Avatars'),
        ),
    ]
