# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-09 19:13
from __future__ import unicode_literals

from django.db import migrations
from django.conf import settings


def convert_setting_to_db_field(apps, schema_editor):
    GlobalPreferences = apps.get_model('utilities', 'GlobalPreferences')

    gp = GlobalPreferences.objects.first()
    # Skip if GP singleton does not exist at this time, possible during CB install
    if gp:
        # Also, tolerate a missing ENABLE_AVATARS setting
        gp.show_user_avatars = getattr(settings, 'ENABLE_AVATARS', True)
        gp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0024_globalpreferences_show_user_avatars'),
    ]

    operations = [
        migrations.RunPython(convert_setting_to_db_field),
    ]
