# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 16:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0025_convert_gravatars_setting_to_gp'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='cbadmin_email',
            field=models.CharField(blank=True, help_text='Send failure reports to these e-mail addresses. Can be a single email address or a comma-separated list.', max_length=1024, null=True, verbose_name='CB Admin E-mail'),
        ),
    ]
