# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-30 18:07
from __future__ import unicode_literals

from django.db import migrations


def server_cols_service_tier_to_resource_tier(apps, schema_editor):
    """
    In the set of possible server table columns defined in ServerTableConfig,
    'Service Tier' has been changed to 'Resource Tier' as part of the XaaS
    transition of what BPs create. If a customer has selected that column and
    therefore had it included in their GlobalPreferences.server_table_columns,
    it must be updated to the new name to work correctly.
    """
    GlobalPreferences = apps.get_model('utilities', 'GlobalPreferences')
    # There should only be 1, but let's be extra safe
    for gp in GlobalPreferences.objects.all():
        if gp.server_table_columns and 'Service Tier' in gp.server_table_columns:
            gp.server_table_columns = gp.server_table_columns.replace('Service Tier', 'Resource Tier')
            gp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0027_globalpreferences_job_timeout'),
    ]

    operations = [
        migrations.RunPython(server_cols_service_tier_to_resource_tier,
                             migrations.RunPython.noop),
    ]
