# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0027_globalpreferences_job_timeout'),
        # include to avoid this GP field being deleted before being used in the RH data migration.
        ('resourcehandlers', '0008_auto_20171212_1718'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalpreferences',
            name='enable_console_feature',
        ),
    ]
