# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 12:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0027_globalpreferences_job_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='rate_currency_unit',
            field=models.CharField(default='$', help_text='Ex. \xa5, \u20ac, \xa3, SEK, CHF, R$, $, etc', max_length=10),
        ),
    ]
