# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 18:55
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0028_remove_globalpreferences_enable_console_feature'),
        ('utilities', '0028_auto_20171211_1242'),
    ]

    operations = [
    ]
