# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 17:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0028_remove_globalpreferences_enable_console_feature'),
        ('utilities', '0028_change_gp_server_cols_service_tier_20171130_1807'),
    ]

    operations = [
    ]
