# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-29 14:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0029_merge_20171219_1725'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='default_redirect',
            field=models.CharField(blank=True, default='/dashboard/', help_text="\n            URL to redirect users users to when they navigate to / on the CB\n            server.  Common examples are '/dashboard/' (the default),\n            '/catalog/', and '/servers/'.\n        ", max_length=255, verbose_name='Default redirect (web server needs to be restarted for this to take effect)'),
        ),
    ]
