# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-02 14:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0030_auto_20171229_1408'),
        ('utilities', '0029_merge_20171219_1855'),
    ]

    operations = [
    ]
