# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-10 20:01
from __future__ import unicode_literals
import re

from django.db import migrations


def update_redirect_for_services_urls(apps, schema_editor):
    """
    Sinces the URLs that formerly included references to services have been
    changed to the new resources structure, if the "default redirect"
    miscellaneous setting is set to a URL that has changed, update it
    accordingly.
    Most of the time, just replace services with resources. However, the
    services list is a special case.
    """
    GlobalPreferences = apps.get_model("utilities", "GlobalPreferences")
    gp = GlobalPreferences.objects.first()  # There should only be 1, if any
    if gp:
        gp.default_redirect = gp.default_redirect.replace(
            '/services/', '/resources/')
        # If the URL was just /services/, for the services list, it will now be
        # just /resources/ and needs to become /resources/service/list/
        gp.default_redirect = re.sub(
            '^/resources/$', '/resources/service/list/', gp.default_redirect
        )
        gp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0031_merge_20180102_1448'),
    ]

    operations = [
        migrations.RunPython(update_redirect_for_services_urls, migrations.RunPython.noop),
    ]
