# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-15 16:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0033_change_default_redirect_for_service_actions_urls_20180115_1424'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapmapping',
            name='is_cbadmin',
            field=models.BooleanField(default=False, verbose_name="Grant CB Admin"),
        ),
        migrations.AddField(
            model_name='ldapmapping',
            name='is_super_admin',
            field=models.BooleanField(default=False, verbose_name="Grant Super Admin"),
        ),
    ]
