# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-16 20:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0030_merge_20180321_1947'),
        ('utilities', '0034_ldap_mapping_admin_fields'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='cit_default_owner',
            field=models.ForeignKey(blank=True, help_text='The default owner for all CIT orders and jobs, including sub-jobs', null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.UserProfile', verbose_name='Default CIT Owner'),
        ),
    ]
