# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-27 06:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0035_globalpreferences_cit_default_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='enable_password_toggle',
            field=models.BooleanField(default=False, help_text='When enabled users will be able to unmask passwords in any form field, if they have the appropriate rights to do so.', verbose_name='Password Toggle'),
        ),
    ]
