# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-25 14:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0035_globalpreferences_cit_default_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='inherit_group_permissions',
            field=models.BooleanField(default=False, help_text='If enabled, all Users and the Roles they have in parent groups will be inherited down to all their subgroups.', verbose_name='Inherit Group Permissions'),
        ),
    ]
