# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-04-29 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0035_globalpreferences_cit_default_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='enable_cost_preview_per_env',
            field=models.BooleanField(default=True, help_text='When disabled, cost preview per environment will not be shown in the order form.', verbose_name='Enable cost preview per environment'),
        ),
    ]
