# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-04 15:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0035_globalpreferences_cit_default_owner'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='hostname_case_sensitivity',
            field=models.BooleanField(default=False, help_text='Allows the use of same hostname with differing case. ie. server01 and SERVER01', verbose_name='Hostnames case sensitive'),
        ),
    ]
