# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-07 22:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0036_globalpreferences_hostname_case_sensitivity'),
        ('utilities', '0037_auto_20180507_1547'),
    ]

    operations = [
    ]
