# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 13:32
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0036_globalpreferences_inherit_group_permissions'),
        ('utilities', '0038_merge_20180507_2244'),
    ]

    operations = [
    ]
