# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-11 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0038_merge_20180507_2244'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='remote_script_dir_unix',
            field=models.CharField(blank=True, help_text='The directory that will be used when writing remote scripts to *nix VMs',
                                   max_length=1000, null=True, verbose_name='Remote script *nix directory'),),
        migrations.AddField(
            model_name='globalpreferences',
            name='remote_script_dir_windows',
            field=models.CharField(blank=True, help_text='The directory that will be used when writing remote scripts to Windows VMs via VMWare Tools',
                                   max_length=1000, null=True, verbose_name='Remote script Windows directory'),

        ),
    ]
