# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-12 00:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0039_auto_20180511_1855'),
        ('utilities', '0039_merge_20180509_2017'),
    ]

    operations = [
    ]
