# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-15 19:57
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0039_merge_20180508_1332'),
        ('utilities', '0040_merge_20180512_0048'),
    ]

    operations = [
    ]
