# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-06 23:41
from __future__ import unicode_literals

from django.db import migrations, models
import utilities.models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0042_globalpreferences_inherit_group_parameters'),
    ]

    operations = [
        migrations.CreateModel(
            name='DBLock',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=255, unique=True)),
                ('value', models.CharField(max_length=255)),
                ('expires', models.DateTimeField(blank=True, default=utilities.models.default_lock_expiration)),
            ],
        ),
    ]
