# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-16 00:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0044_fontawesome_4to5'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='admin_only_mode',
            field=models.BooleanField(default=False, help_text='Log non-CB admin users out and disallow them from logging in until this is disabled.'),
        ),
    ]
