# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-05 18:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0045_globalpreferences_admin_only_mode'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='job_timeout',
            field=models.IntegerField(default=86400, help_text='The maximum number of seconds that all jobs are limited to.', verbose_name='Default job timeout'),
        ),
    ]
