# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-05 19:06
from __future__ import unicode_literals

from django.db import migrations


def change_job_timeout(apps, schema_editor):
    """
    8.5 begins enforcement of a global job timeout. Previously, this global preference was set
    to 1 hour, which is not sufficient and would cause problems for customers if all jobs > 1
    hour started failing after they upgrade. Therefore, change this value to 24 hours in all CBs
    when upgrading. Customers can change this to meet their needs later, on the Misc Settings page.
    """
    GlobalPreferences = apps.get_model("utilities", "GlobalPreferences")
    gp = GlobalPreferences.objects.first()  # There should only be 1, if any
    if gp:
        gp.job_timeout = 3600 * 24
        gp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0046_auto_20181205_1813'),
    ]

    operations = [
        migrations.RunPython(change_job_timeout, migrations.RunPython.noop),
    ]
