# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-18 22:32
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0047_change_job_timeout_to_24hrs'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='security_message',
            field=models.CharField(blank=True, help_text="Shown under the nav bar on all pages. Some HTML tags ok ('a', 'b', 'i', 'span'), up to 1000 chars", max_length=1000, null=True),
        ),
    ]
