# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-19 18:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0048_auto_20181218_2232'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='enable_notebook_feature',
            field=models.BooleanField(default=True, help_text="Enables admins to access a Jupyter Notebook with Django's shell_plus for support and testing.", verbose_name='Notebook feature'),
        ),
    ]
