# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 14:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0048_auto_20181218_2232'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldapmapping',
            name='has_api_access',
            field=models.BooleanField(default=True, verbose_name='Grant API Access'),
        ),
        migrations.AddField(
            model_name='ldapmapping',
            name='is_devops_admin',
            field=models.BooleanField(default=False, verbose_name='Grant Devops Admin'),
        ),
        migrations.AddField(
            model_name='ldapmapping',
            name='is_global_viewer',
            field=models.BooleanField(default=False, verbose_name='Grant Global Viewer'),
        ),
    ]
