# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2018-12-27 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0049_auto_20181227_1440'),
        ('utilities', '0049_auto_20181219_1850'),
    ]

    operations = [
    ]
