# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-27 20:04
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0049_auto_20181219_1850'),
        ('resourcehandlers', '0011_resourcehandler_enable_terminal_feature'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalpreferences',
            name='enable_remote_feature',
        ),
    ]
