# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-02 19:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0050_merge_20181227_1826'),
        ('utilities', '0050_remove_globalpreferences_enable_remote_feature'),
    ]

    operations = [
    ]
