# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-06 21:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0052_globalpreferences_disabled_reports_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='disabled_reports_list',
            field=models.TextField(blank=True, help_text='Choose out-of-the-box reports to disable for all users.', null=True, verbose_name='Disabled out-of-the-box reports'),
        ),
    ]
