# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-07 17:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0053_auto_20190206_2147'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='disabled_reports_list',
            field=models.TextField(blank=True, default='""', help_text='Choose out-of-the-box reports to disable for all users.', verbose_name='Disabled out-of-the-box reports'),
        ),
    ]
