# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-11 20:31
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0054_auto_20190207_1751'),
        ('utilities', '0052_auto_20190205_1915'),
    ]

    operations = [
    ]
