# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-27 22:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0055_merge_20190211_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='disabled_recent_activity_categories',
            field=models.TextField(blank=True, help_text='Choose recent activity history categories to disable for all users.', verbose_name='Disabled Recent Activity (dashboard item) categories'),
        ),
    ]
