# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-20 17:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0055_merge_20190211_2031'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldaputility',
            name='email_format',
            field=models.CharField(blank=True, help_text='Define an email format if email is not part of the AD/LDAP. Example: <code>{ first }.{ last }@{ domain }</code>.  Possible references are first, last, username, and domain.', max_length=100, null=True),
        ),
    ]
