# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-06 11:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0055_merge_20190211_2031'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='enable_bulk_orders',
            field=models.BooleanField(default=False, help_text='Enable the ability to order a blueprint for more than one user.', verbose_name='Enable bulk ordering'),
        ),
    ]
