# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-29 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0055_merge_20190211_2031'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='globalpreferences',
            name='enable_notebook_feature',
        ),
    ]
