# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-04 20:23
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0056_auto_20190320_1754'),
        ('utilities', '0056_remove_globalpreferences_enable_notebook_feature'),
    ]

    operations = [
    ]
