# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-21 23:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0049_globalpreferences_default_addressing_scheme'),
        ('utilities', '0056_globalpreferences_disabled_recent_activity_categories'),
    ]

    operations = [
    ]
