# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-04 19:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0057_merge_20190404_2023'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ldaputility',
            name='email_format',
            field=models.CharField(blank=True, help_text='Define an email format if email is not part of the AD/LDAP. Example: <code>{{ first }}.{{ last }}@{{ domain }}</code>.  Possible references are first, last, username, and domain.', max_length=100, null=True),
        ),
    ]
