# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-17 09:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0058_auto_20190404_1904'),
        ('utilities', '0056_globalpreferences_enable_bulk_orders'),
    ]

    operations = [
    ]
