# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-29 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0058_auto_20190325_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='enable_social_feature',
            field=models.BooleanField(default=False, help_text='Enables CB users to post to social websites.', verbose_name='Social'),
        ),
    ]
