# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-03 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0059_auto_20190329_0045'),
        ('utilities', '0056_remove_globalpreferences_enable_notebook_feature'),
    ]

    operations = [
    ]
