# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-04-10 19:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0060_merge_20190403_0036'),
        ('utilities', '0058_auto_20190404_1904'),
    ]

    operations = [
    ]
