# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-23 21:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0061_merge_20190410_1924'),
        ('utilities', '0059_merge_20190417_0928'),
    ]

    operations = [
    ]
