# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-04 22:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0062_merge_20190423_2120'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='default_user_display_scheme',
            field=models.CharField(choices=[('username', 'Username'), ('full_name', 'Full Name')], default='username', help_text='This controls how user information is displayed in dropdowns.', max_length=10, verbose_name='Default User Display Scheme'),
        ),
    ]
