# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-05 00:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0063_globalpreferences_default_user_display_scheme'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='default_user_display_scheme',
            field=models.CharField(choices=[('username', 'Username'), ('full_name', 'Full Name'), ('last_first', 'Last Name, First Name'), ('first_initial_last', 'First Initial Last Name')], default='username', help_text='This controls how user information is displayed when changing owner on a resource.', max_length=20, verbose_name='Default User Display Scheme'),
        ),
    ]
