# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-07 13:54
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0067_connectioninfo_labels'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectioninfo',
            name='labels',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='tags.TaggedItem', to='tags.CloudBoltTag', verbose_name='Labels'),
        ),
    ]
