# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-08 16:17
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0068_auto_20190807_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='show_video_tips',
            field=models.BooleanField(default=True, help_text='Display video tip icons in the user interface that pop up a dialog with a short video explaining that feature or part of the user interface.'),
        ),
    ]
