# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-15 20:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0069_globalpreferences_show_video_tips'),
        ('utilities', '0069_globalpreferences_catalog_viewing_mode'),
    ]

    operations = [
    ]
