# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-21 23:42
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0070_merge_20190815_2030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='rate_currency_unit',
            field=models.CharField(default='$', help_text='Ex. JPY, EUR, GBP, SEK, CHF, BRL, USD, etc', max_length=10),
        ),
    ]
