# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-20 19:18
from __future__ import unicode_literals

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0070_merge_20190815_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='cit_default_retry_wait',
            field=models.IntegerField(default=600, help_text='Number of seconds to wait to retry tests after they fail.', validators=[common.validators.is_only_digits], verbose_name='CIT Retry Wait'),
        ),
    ]
