# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-20 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0070_merge_20190815_2030'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='show_recipient_field_on_order_form',
            field=models.CharField(choices=[('always', 'When Allowed'), ('never', 'Never'), ('only_enabled_bps', 'Only Enabled Blueprints')], default='never', help_text='Controls when the "Recipient" field is shown to permitted users on the order form. If set to "Only Enabled Blueprints", Blueprint managers can access the per-Blueprint setting using the Edit button on the Blueprint\'s Overview tab. If the field is not shown, the user ordering the Blueprint will be the sole recipient.', max_length=16, verbose_name='Show "Recipient" field on order form'),
        ),
    ]
