# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-20 18:36
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0071_auto_20190919_1646'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='inactivity_timeout_minutes',
            field=models.IntegerField(default=20, help_text='If set, log user out after this many minutes of inactivity. Note that a value of 0 means no timeout.'),
        ),
    ]
