# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-23 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0071_globalpreferences_cit_default_retry_wait'),
        ('utilities', '0072_auto_20190920_1836'),
    ]

    operations = [
    ]
