# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-25 23:29
from __future__ import unicode_literals

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0073_merge_20190923_2353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='inactivity_timeout_minutes',
            field=models.IntegerField(default=20, help_text='If set, log user out after this many minutes of inactivity. Note that a value of 0 means no timeout.', validators=[common.validators.is_only_digits]),
        ),
    ]
