# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-01 03:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0074_auto_20190925_2329'),
        ('utilities', '0071_globalpreferences_show_recipient_field_on_order_form'),
    ]

    operations = [
    ]
