# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-17 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0076_globalpreferences_enable_email_verification'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='email_default_from_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Email default from address'),
        ),
        migrations.AlterField(
            model_name='rootcertificate',
            name='active',
            field=models.BooleanField(default=True, verbose_name='Active'),
        ),
        migrations.AlterField(
            model_name='rootcertificate',
            name='certificate',
            field=models.TextField(verbose_name='Certificate'),
        ),
    ]
