# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-28 14:40
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0071_auto_20191021_2342'),
        ('utilities', '0077_auto_20191017_0101'),
    ]

    operations = [
    ]
