# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-06 21:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0078_merge_20191028_1440'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='catalog_viewing_mode',
            field=models.CharField(choices=[('tiles', 'Tiles'), ('table', 'Table'), ('categories', 'Categories')], default='tiles', help_text='This controls how blueprints will be organized and styled when browsing the Catalog page.', max_length=255, verbose_name='Default Catalog Viewing Mode'),
        ),
    ]
