# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-19 21:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ('utilities', '0079_auto_20191106_2133'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='external_url_whitelist',
            field=models.TextField(default='.*',
                                   help_text=r"A semicolon-separated list of the domains to which WebHooks and CloudBolt Actions using source code from an external URL are allowed to connect. These domain names are regular expressions and could also be represented as ipv4 IP addresses. Ex. '.*\.internal\.loc;192\.168\..*;my\.domain\.com'. Defaults to allowing everything: '.*'"),
        ),
    ]
