# Generated by Django 2.2.10 on 2020-02-14 09:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0080_globalpreferences_external_url_whitelist'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='security_message',
            field=models.CharField(blank=True, help_text="Shown under the nav bar on all pages. Some HTML tags ok ('a', 'b', 'i', 'span', 'br', 'h1', 'h2', 'h3', 'h4', 'h5', 'h6'), up to 1000 chars", max_length=1000, null=True),
        ),
    ]
