# Generated by Django 2.2.10 on 2020-03-10 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0081_auto_20200214_0920'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='auto_login_sso',
            field=models.BooleanField(default=True, help_text='If there is an SSO Provider configured for the portal, automatically redirect users there for login.', verbose_name='Automatically login to SSO'),
        ),
    ]
