# Generated by Django 2.2.10 on 2020-04-09 03:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0082_globalpreferences_auto_login_sso'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectioninfo',
            name='transport',
            field=models.CharField(default=None, max_length=30, null=True),
        ),
    ]
