# Generated by Django 2.2.10 on 2020-04-30 21:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0082_globalpreferences_auto_login_sso'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='auto_login_sso',
            field=models.BooleanField(default=False, help_text='If there is an SSO Provider configured for the portal, automatically redirect users there for login.', verbose_name='Automatically login to SSO'),
        ),
    ]
