# Generated by Django 2.2.10 on 2020-04-15 23:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0083_connectioninfo_transport'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectioninfo',
            name='transport',
            field=models.CharField(default='', max_length=30, null=True),
        ),
    ]
