# Generated by Django 2.2.10 on 2020-04-17 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0084_auto_20200415_2351'),
    ]

    operations = [
        migrations.AlterField(
            model_name='connectioninfo',
            name='transport',
            field=models.CharField(default='', max_length=30),
        ),
    ]
