# Generated by Django 2.2.12 on 2020-05-13 23:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0085_auto_20200417_0041'),
        ('utilities', '0083_auto_20200430_2124'),
    ]

    operations = [
    ]
