# Generated by Django 2.2.12 on 2020-05-20 16:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0086_merge_20200513_2334'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='personality',
            field=models.CharField(blank=True, choices=[('CMP', 'CloudBolt CMP'), ('Fuse', 'Sovlabs Fuse')], help_text='This attribute is set by internal processes and serves as the final validation that a license based personality was applied.', max_length=5, null=True, verbose_name='Appliance Personality'),
        ),
    ]
