# Generated by Django 2.2.12 on 2020-07-27 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0088_set_personality_from_license_20200521_1143'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='run_guided_setup',
            field=models.BooleanField(default=False, editable=False, help_text='If True, directs user to Guided Setup wizard.  After completing or skipping Guided Setup, this setting is set to False.'),
        ),
        migrations.AlterField(
            model_name='globalpreferences',
            name='run_quick_setup',
            field=models.BooleanField(default=True, editable=False, help_text='If True, directs user to Quick Setup wizard.  After completing or skipping QS, this setting is set to False.'),
        ),
    ]
