# Generated by Django 2.2.10 on 2020-09-30 16:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0090_remove_globalpreferences_run_guided_setup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='cbadmin_email',
            field=models.CharField(blank=True, help_text='Can be a single email address or a comma-separated list.', max_length=1024, null=True, verbose_name='CB Admin E-mail'),
        ),
    ]
