# Generated by Django 2.2.10 on 2020-11-18 19:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0091_auto_20200930_1617'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='enable_set_challenge_question',
            field=models.BooleanField(default=True, help_text='When enabled, new users will be asked to set a challenge question and answer.', verbose_name='Password Reset Question'),
        ),
    ]
