# Generated by Django 2.2.10 on 2020-12-03 00:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0092_globalpreferences_enable_set_challenge_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='embedded_mode',
            field=models.BooleanField(default=False, help_text="When enabled, non-admin users can only access with the URL param '?frame=true' which hides nav menus. If you are nesting CloudBolt in an IFRAME, you will also need to set Embed URLs with the parent site URLs.", verbose_name='Embedded Mode'),
        ),
        migrations.AddField(
            model_name='globalpreferences',
            name='frame_ancestors',
            field=models.TextField(default='', help_text='A space separated list of domains or URLs that are allowed to frame the cloudbolt UI. This is used to populate the frame-ancestors of the Content-Security-Policy sent by the appliance. If you intend to nest the CloudBolt UI into an IFRAME on a company portal or  other site you will need to add the hostname of the parent site here.  This list can use a mixture of different formats "example.com" / "*.example.com" / "https://*.example.com:12/path/to/file.js" '),
        ),
    ]
