# Generated by Django 2.2.16 on 2020-11-25 18:32

import common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0092_globalpreferences_enable_set_challenge_question'),
    ]

    operations = [
        migrations.AddField(
            model_name='ldaputility',
            name='global_id',
            field=models.CharField(default=common.mixins.get_global_id_chars, help_text='Identifier that can be used to access this object through the API across instances.', max_length=16, verbose_name='Global ID'),
        ),
    ]
