# Generated by Django 2.2.16 on 2021-01-26 23:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0096_auto_20210105_0050'),
        ('utilities', '0093_auto_20201203_0051'),
    ]

    operations = [
    ]
