# Generated by Django 2.2.16 on 2021-03-02 23:32
from django.db import migrations

from common.mixins import get_global_id_chars


class Migration(migrations.Migration):
    def set_global_ids(apps, schema_editor):
        ConnectionInfo = apps.get_model("utilities", "ConnectionInfo")
        prefix = "CON"
        for row in ConnectionInfo.objects.all():
            chars = get_global_id_chars()
            row.global_id = f"{prefix}-{chars}"
            row.save()

    dependencies = [
        ("utilities", "0098_connectioninfo_global_id"),
    ]

    operations = [
        migrations.RunPython(set_global_ids, migrations.RunPython.noop),
    ]
