# Generated by Django 2.2.16 on 2021-03-03 16:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0098_auto_20210302_1922'),
        ('utilities', '0099_set_global_id_for_connectioninfo'),
    ]

    operations = [
    ]
