# Generated by Django 2.2.16 on 2021-04-05 13:58

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0102_sshkey_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='default_user_display_scheme',
            field=models.CharField(choices=[('username', 'Username'), ('full_name', 'Full Name'), ('last_first', 'Last Name, First Name'), ('first_initial_last', 'First Initial Last Name')], default='username', help_text='Controls how User information is displayed when selecting Users in certain places in the UI.', max_length=20, verbose_name='Default User Display Scheme'),
        ),
    ]
