# Generated by Django 2.2.16 on 2021-04-08 18:49

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0003_tenant_portal'),
        ('utilities', '0102_sshkey_data'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshkey',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant'),
        ),
    ]
