# Generated by Django 2.2.16 on 2021-05-03 13:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0103_auto_20210405_1358'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='legal_notice_every_login',
            field=models.BooleanField(default=True, help_text='When enabled, if there is Legal Notice Text configured above then display it every single time a User logs in. If disabled, the Legal Notice Text is only displayed once per User.', verbose_name='Display Legal Notice on Every Login'),
        ),
        migrations.AddField(
            model_name='globalpreferences',
            name='legal_notice_text',
            field=models.CharField(blank=True, default='', help_text='To enable a legal notice that displays to Users upon login, enter the text to be displayed here. To disable the feature, leave this field blank.', max_length=1024, verbose_name='Legal Notice Text'),
        ),
    ]
