# Generated by Django 2.2.16 on 2021-05-07 10:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0104_auto_20210503_1352'),
    ]

    operations = [
        migrations.AlterField(
            model_name='globalpreferences',
            name='legal_notice_text',
            field=models.CharField(blank=True, default='', help_text='To enable a legal notice that displays to Users upon login, enter the text to be displayed here. To disable the feature, leave this field blank.<br>Note: There is a maximum length of 1024 characters.', max_length=1024, verbose_name='Legal Notice Text'),
        ),
    ]
