# Generated by Django 2.2.16 on 2021-05-20 13:37

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0039_orderitem_global_id'),
        ('utilities', '0105_auto_20210507_1056'),
    ]

    operations = [
        migrations.AddField(
            model_name='sshkey',
            name='key_reference',
            field=models.ForeignKey(help_text='The CustomFieldValue used internally to store the reference to the SSHKey that appears on the order form and elsewhere in the UI. For RH-specific keys, matches the name that comes from the Resource Handler.', null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sshkey', to='orders.CustomFieldValue'),
        ),
    ]
