# Generated by Django 2.2.16 on 2021-05-27 17:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0103_sshkey_tenant'),
        ('utilities', '0108_auto_20210520_1405'),
    ]

    operations = [
    ]
