# Generated by Django 3.2.3 on 2021-06-18 21:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0109_merge_20210527_1726'),
    ]

    operations = [
        migrations.AddField(
            model_name='cbreleaseinfo',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
