# Generated by Django 2.2.16 on 2021-07-02 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0110_cbreleaseinfo_updated_at'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='sshkey',
            name='name',
        ),
    ]
