# Generated by Django 3.2.3 on 2021-07-30 23:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0112_connectioninfo_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='InstanceMetadata',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('instance_uuid', models.CharField(help_text='Permanent unique UUID for this instance.', max_length=64)),
            ],
            options={
                'verbose_name': 'Instance metadata',
                'verbose_name_plural': 'Instance metadata',
                'db_table': 'instance_metadata',
            },
        ),
    ]
