# Generated by Django 3.2.3 on 2021-07-16 18:26

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0112_connectioninfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='auto_generate_user_passwords',
            field=models.BooleanField(default=False, help_text='When creating a new user, they will receive an email to reset their password automatically.', verbose_name='Require New Users to Self-Assign Passwords'),
        ),
    ]
