# Generated by Django 2.2.16 on 2021-08-02 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0112_connectioninfo_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='globalpreferences',
            name='allowed_roles_in_embedded_mode',
            field=models.TextField(default='is_cbadmin', help_text='Choose which Global Role(s) can access CloudBolt directly when Embedded Mode is enabled. Must always include at least Super Admins.', verbose_name='Allowed Global Roles in Embedded Mode'),
        ),
        migrations.AlterField(
            model_name='globalpreferences',
            name='embedded_mode',
            field=models.BooleanField(default=False, help_text="When enabled, most users can only access with the URL param '?frame=true' which hides nav menus. If you are nesting CloudBolt in an IFRAME, you will also need to set Embed URLs with the parent site URLs. Only users with certain Global Role(s), Super Admins by default, can access CloudBolt directly when Embedded Mode is enabled.", verbose_name='Embedded Mode'),
        ),
    ]
