# Generated by Django 3.2.3 on 2021-08-06 00:44

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0113_auto_20210802_1337'),
        ('utilities', '0113_instancemetadata'),
    ]

    operations = [
    ]
