# Generated by Django 3.2.3 on 2021-08-10 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('utilities', '0113_globalpreferences_auto_generate_user_passwords'),
        ('utilities', '0114_merge_0113_auto_20210802_1337_0113_instancemetadata'),
    ]

    operations = [
    ]
