# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-10-11 21:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobengine', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='jobengineworker',
            name='max_concurrency',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
