# Generated by Django 2.2.16 on 2020-10-19 04:25

from django.db import migrations, models
import django.db.models.deletion
import driven_apps.common.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('naming', '0064_auto_20201015_2233'),
        ('jobs', '0046_auto_20201017_0204'),
    ]

    operations = [
        migrations.CreateModel(
            name='PolicyJobParameters',
            fields=[
                ('jobparameters_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jobs.JobParameters')),
                ('job_metadata', models.ForeignKey(help_text='Job metadata for tracking job progress and logging', null=True, on_delete=django.db.models.deletion.SET_NULL, to='naming.JobMetadata')),
            ],
            options={
                'verbose_name_plural': 'Policy Job Parameters',
                'db_table': 'policyjobparameters',
                'ordering': ['id'],
                'abstract': False,
            },
            bases=('jobs.jobparameters', models.Model, driven_apps.common.mixins.RoleBasedHalFilteringMixin),
        ),
    ]
