# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-14 14:53
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone
import files.models
import model_utils.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigurationFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created', model_utils.fields.AutoCreatedField(default=django.utils.timezone.now, editable=False, verbose_name='created')),
                ('modified', model_utils.fields.AutoLastModifiedField(default=django.utils.timezone.now, editable=False, verbose_name='modified')),
                ('location_type', models.CharField(choices=[('upload', 'Upload file'), ('url', 'Fetch from URL')], default='upload', max_length=20)),
                ('upload_file', models.FileField(blank=True, max_length=255, null=True, upload_to='config_files')),
                ('source_url', models.TextField(blank=True, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=(files.models.ExternalSourceCodeMixin, models.Model),
        ),
    ]
