# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-22 23:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0014_remove_customfield_hide_single_value'),
        ('files', '0002_update_location_type_choices'),
    ]

    operations = [
        migrations.CreateModel(
            name='FileInput',
            fields=[
                ('customfield_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infrastructure.CustomField')),
                ('hide_if_default_value', models.BooleanField(default=False)),
                ('config_file', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='input_fields', to='files.ConfigurationFile')),
            ],
            bases=('infrastructure.customfield',),
        ),
    ]
