# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-01 23:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_fileinputmapping'),
    ]

    operations = [
        migrations.RenameField(
            model_name='configurationfile',
            old_name='upload_file',
            new_name='module_file',
        ),
        migrations.RenameField(
            model_name='configurationfile',
            old_name='source_url',
            new_name='source_code_url',
        ),
    ]
