# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('qemu', '0003_auto_20161004_2121'),
    ]

    operations = [
        migrations.AlterField(
            model_name='qemuresourcehandler',
            name='clone_tmpl_timeout',
            field=models.IntegerField(default=60, help_text='Used to adjust the timeout for provisioning a VM from a template', verbose_name='Clone Template Timeout'),
        ),
    ]
