# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-06 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('qemu', '0007_auto_20190102_1747'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='qemuresourcehandler',
            name='clone_tmpl_timeout',
        ),
    ]
