# Generated by Django 2.2.12 on 2020-05-26 16:40

from django.db import migrations, models
import driven_apps.common.mixins
import multiselectfield.db.fields


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProductLicense',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('license_id', models.UUIDField()),
                ('company', models.CharField(max_length=1024)),
                ('registered_to_email', models.CharField(max_length=255)),
                ('registered_to_user', models.CharField(max_length=255)),
                ('_issue_date', models.DateTimeField(blank=True, null=True)),
                ('_installed_date', models.DateTimeField(blank=True, null=True)),
                ('_expiration_date', models.DateTimeField(blank=True, null=True)),
                ('product_type', models.CharField(choices=[('CMP', 'CMP'), ('FUSE', 'Fuse')], max_length=16)),
                ('license_type', models.CharField(choices=[('TRIAL', 'trial'), ('PURCHASE', 'purchase'), ('NFR', 'nfr')], max_length=16)),
                ('quantity', models.IntegerField()),
                ('quantity_type', models.CharField(choices=[('NODE', 'NODE'), ('CPU_SOCKET', 'CPU_SOCKET'), ('MANAGED_OBJECT', 'MANAGED_OBJECT'), ('MODULE', 'MODULE')], max_length=32)),
                ('modules', multiselectfield.db.fields.MultiSelectField(choices=[('NAMING', 'naming')], max_length=6)),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
            bases=(models.Model, driven_apps.common.mixins.RoleBasedHalFilteringMixin),
        ),
    ]
