# Generated by Django 2.2.12 on 2020-05-29 22:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('product_license', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlicense',
            name='_expiration_date',
        ),
        migrations.RemoveField(
            model_name='productlicense',
            name='_installed_date',
        ),
        migrations.RemoveField(
            model_name='productlicense',
            name='_issue_date',
        ),
        migrations.AddField(
            model_name='productlicense',
            name='expiration_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productlicense',
            name='installed_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='productlicense',
            name='issue_date',
            field=models.DateField(blank=True, null=True),
        ),
    ]
