# Generated by Django 2.2.10 on 2020-08-31 16:32

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product_license', '0002_auto_20200529_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlicense',
            name='modules',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NAMING', 'naming'), ('BLUECAT_IPAM', 'bluecat ipam')], max_length=19),
        ),
    ]
