# Generated by Django 2.2.10 on 2020-09-02 18:35

from django.db import migrations
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product_license', '0003_auto_20200831_1632'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlicense',
            name='modules',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('NAMING', 'naming'), ('BLUECAT_IPAM', 'bluecat ipam'), ('INFOBLOX_IPAM', 'infoblox ipam')], max_length=33),
        ),
    ]
