# Generated by Django 2.2.10 on 2020-09-23 21:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_license', '0007_auto_20200922_1809'),
        ('product_license', '0007_auto_20200917_1901'),
    ]

    operations = [
    ]
