# Generated by Django 2.2.10 on 2020-09-25 17:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_license', '0009_auto_20200923_2232'),
        ('product_license', '0006_auto_20200914_2103'),
    ]

    operations = [
    ]
