# Generated by Django 2.2.16 on 2021-01-13 19:07

from django.db import migrations, models
import multiselectfield.db.fields


class Migration(migrations.Migration):

    dependencies = [
        ('product_license', '0013_auto_20201113_1724'),
    ]

    operations = [
        migrations.AlterField(
            model_name='productlicense',
            name='modules',
            field=multiselectfield.db.fields.MultiSelectField(choices=[('BLUECAT_DNS', 'bluecat dns'), ('BLUECAT_IPAM', 'bluecat ipam'), ('INFOBLOX_DNS', 'infoblox dns'), ('INFOBLOX_IPAM', 'infoblox ipam'), ('MICROSOFT_ACTIVE_DIRECTORY', 'microsoft active directory'), ('MICROSOFT_DNS', 'microsoft dns'), ('MEN_AND_MICE_DNS', 'men and mice dns'), ('MEN_AND_MICE_IPAM', 'men and mice ipam'), ('NAMING', 'naming'), ('SCRIPTING', 'scripting'), ('ANSIBLE_TOWER', 'ansible tower'), ('CONNECTOR', 'connector'), ('SERVICE_CATALOG', 'service catalog'), ('SDN', 'software defined network'), ('ORCHESTRATION', 'orchestration'), ('PROVISIONING_ENGINE', 'provisioning engine'), ('REPORT', 'report')], max_length=229),
        ),
        migrations.AlterField(
            model_name='productlicense',
            name='quantity_type',
            field=models.CharField(choices=[('NODE', 'NODE'), ('CPU_SOCKET', 'CPU_SOCKET'), ('MANAGED_OBJECT', 'MANAGED_OBJECT'), ('MODULE', 'MODULE'), ('SERVER', 'SERVER')], max_length=32),
        ),
    ]
