# Generated by Django 2.2.16 on 2021-02-08 21:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_license', '0015_auto_20210208_1602'),
        ('product_license', '0017_auto_20210202_2251'),
    ]

    operations = [
    ]
