# Generated by Django 2.2.16 on 2021-02-22 10:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_license', '0019_auto_20210211_1551'),
        ('product_license', '0020_auto_20210217_2106'),
    ]

    operations = [
    ]
