# Generated by Django 2.2.16 on 2021-05-20 13:57

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('product_license', '0024_auto_20210402_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='productlicense',
            name='_modules',
            field=django_extensions.db.fields.json.JSONField(default=dict),
        ),
    ]
