# Generated by Django 2.2.16 on 2021-05-20 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('product_license', '0026_auto_20210519_1902'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='productlicense',
            name='modules',
        )
    ]
