# Generated by Django 3.2.3 on 2021-09-23 21:32
from os import rename
import os.path
import settings

from django.db import migrations

from product_license.license_service import LicenseService


FILENAME = os.path.join(settings.VARDIR, "opt", "cloudbolt", "license.bin")


class Migration(migrations.Migration):

    def store_license_in_db(apps, schema_editor):
        if os.path.exists(FILENAME):
            ciphertext = open(FILENAME, "rb").read()
            LicenseService().add_license(ciphertext)
            rename(FILENAME, f"{FILENAME}.bak")

    def restore_license_file(apps, schema_editor):
        if os.path.exists(f"{FILENAME}.bak") and not os.path.exists(FILENAME):
            rename(f"{FILENAME}.bak", FILENAME)

    dependencies = [
        ('product_license', '0028_auto_20210520_1736'),
    ]

    operations = [
        migrations.RunPython(store_license_in_db, reverse_code=restore_license_file)
    ]
