# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-06 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0004_auto_20161103_2150'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='chefconf',
            options={'verbose_name': 'Chef'},
        ),
    ]
