# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-23 00:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0005_auto_20170106_0100'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefconf',
            name='knife_bootstrap_additional_args',
            field=models.TextField(blank=True, help_text="Additional command line arguments to pass when installing Chef agents with knife bootstrap. Supports the use of templatized values. Ex. '-N {{server.hostname}} -r chef-client,apt', '{% if server.is_windows %} -p 5985{% endif %}'"),
        ),
    ]
