# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-07 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0007_remove_knife_bootstrap_additional_args_param'),
    ]

    operations = [
        migrations.AlterField(
            model_name='chefnode',
            name='conf',
            field=models.ForeignKey(help_text='The Chef Conf that manages this Chef Node.', on_delete=django.db.models.deletion.CASCADE, related_name='nodes', to='chef.ChefConf'),
        ),
    ]
