# Generated by Django 2.2.12 on 2020-06-04 01:45

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('chef', '0008_auto_20191107_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='chefconf',
            name='delete_node_if_exists',
            field=models.BooleanField(default=False, help_text='During provisioning, CB can first delete a chef node if it already exists.'),
        ),
    ]
