# Generated by Django 3.2.3 on 2021-07-20 18:49

from django.db import migrations

from common.mixins import get_global_id_chars

class Migration(migrations.Migration):

    def set_global_ids(apps, schema_editor):
        ChefRole = apps.get_model("chef", "ChefRole")
        prefix = "CRL"
        for row in ChefRole.objects.all():
            chars = get_global_id_chars()
            row.global_id = f"{prefix}-{chars}"
            row.save()

    dependencies = [
        ('chef', '0010_global_id_for_chef_role_and_cookbook'),
    ]

    operations = [
        migrations.RunPython(set_global_ids, migrations.RunPython.noop),
    ]
