# Generated by Django 3.2.3 on 2021-07-20 18:49

from django.db import migrations

from common.mixins import get_global_id_chars

class Migration(migrations.Migration):

    def set_global_ids(apps, schema_editor):
        ChefCookbook = apps.get_model("chef", "ChefCookbook")
        prefix = "CCB"
        for row in ChefCookbook.objects.all():
            chars = get_global_id_chars()
            row.global_id = f"{prefix}-{chars}"
            row.save()

    dependencies = [
        ('chef', '0011_set_global_id_for_chef_role'),
    ]

    operations = [
        migrations.RunPython(set_global_ids, migrations.RunPython.noop),
    ]
