"""
Generates the PEM file to be used for HTTPS requests by the Requests library.
The resulting file is written to disk and returned by the get_ssl_verification()
method if SSL Verification is activated in settings.

This management command is available so the PEM file can be re-generated by
the upgrader in case the Certifi library is upgraded and the base set of certs
has changed. The other inputs are active RootCertificate instances, and those
should trigger a re-generation because of post-save and post-delete signals
in the utilties.helpers file.
"""
from __future__ import unicode_literals

from django.core.management.base import BaseCommand

from utilities.helpers import generate_pem


class Command(BaseCommand):
    def handle(self, *args, **options):
        generate_pem()
