# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-29 23:02
from __future__ import unicode_literals

from django.db import migrations


def security_groups_allow_multiple(apps, schema_editor):
    """
    One-time migration for existing customers to set allow_multiple = True on
    the AWS security group parameter, which used to only allow a single value.
    """
    CustomField = apps.get_model('infrastructure', 'CustomField')
    try:
        cf = CustomField.objects.get(name='sec_groups')
    except CustomField.DoesNotExist:
        # CF doesn't exist and will be created by cb_minimal
        return
    cf.allow_multiple = True
    cf.save()


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0004_auto_20180503_0036'),
        ('infrastructure', '0034_auto_20180516_2007')
    ]

    operations = [
        migrations.RunPython(
            security_groups_allow_multiple, migrations.RunPython.noop
        )
    ]
