# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-04 22:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0005_security_groups_allow_multiple'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebsdisk',
            name='volume_type',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
