# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-02 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0007_ebs_volume_type_options_and_more_20180606_1654'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='amazonmachineimage',
            name='name',
        ),
        migrations.RemoveField(
            model_name='awshandler',
            name='old_os_build_attributes',
        ),
    ]
