# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 19:52
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0008_awsbillinglineitem'),
        ('aws', '0008_auto_20190102_1747'),
    ]

    operations = [
    ]
