# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-10 22:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0009_merge_20190110_1952'),
    ]

    operations = [
        migrations.AddField(
            model_name='awshandler',
            name='s3_billing_bucket',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
