# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-02-27 22:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0010_awshandler_s3_billing_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='awsbillinglineitem',
            name='reserved_instance',
            field=models.BooleanField(default=False),
        ),
    ]
