# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-06 22:41
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0010_awshandler_s3_billing_bucket'),
    ]

    operations = [
        migrations.AddField(
            model_name='ebsdisk',
            name='encrypted',
            field=models.BooleanField(default=False),
        ),
    ]
