# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-03-15 22:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0011_awsbillinglineitem_reserved_instance'),
        ('aws', '0011_ebsdisk_encrypted'),
    ]

    operations = [
    ]
