# Generated by Django 2.2.10 on 2020-02-03 13:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0013_awshandler_ssm_arn'),
    ]

    operations = [
        migrations.AddField(
            model_name='awshandler',
            name='enable_SSM',
            field=models.BooleanField(default=False),
        ),
    ]
