# Generated by Django 2.2.10 on 2020-03-24 21:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0014_awshandler_enable_ssm'),
        ('aws', '0013_awshandler_role_arn'),
    ]

    operations = [
    ]
