# Generated by Django 2.2.10 on 2020-04-07 19:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0015_merge_20200324_2107'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awshandler',
            name='SSM_ARN',
        ),
        migrations.RemoveField(
            model_name='awshandler',
            name='enable_SSM',
        ),
    ]
