# Generated by Django 2.2.10 on 2020-04-24 23:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0016_auto_20200407_1927'),
    ]

    operations = [
        migrations.AddField(
            model_name='awshandler',
            name='SSM_ARN',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='awshandler',
            name='enable_SSM',
            field=models.BooleanField(default=False),
        ),
    ]
