# Generated by Django 2.2.10 on 2020-11-04 04:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0017_auto_20200424_2337'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='awshandler',
            name='enable_SSM',
        ),
    ]
