# Generated by Django 2.2.16 on 2021-03-04 17:46

import cb_secrets.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0018_remove_awshandler_enable_ssm'),
    ]

    operations = [
        migrations.AddField(
            model_name='awshandler',
            name='billingaccount',
            field=models.CharField(blank=True, help_text='Username of commercial AWS account that holds billing information for this account', max_length=250, verbose_name='Billing Account username'),
        ),
        migrations.AddField(
            model_name='awshandler',
            name='billingpasswd',
            field=cb_secrets.fields.EncryptedPasswordField(blank=True, verbose_name='Billing Account password'),
        ),
    ]
