# Generated by Django 2.2.16 on 2021-03-19 15:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0019_auto_20210304_1746'),
        ('aws', '0019_awshandler_account_id'),
    ]

    operations = [
    ]
