# Generated by Django 3.2.3 on 2021-09-22 23:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0020_merge_20210319_1539'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2serverinfo',
            name='profile_arn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
