# Generated by Django 3.2.3 on 2021-09-28 14:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0021_ec2serverinfo_profile_arn'),
    ]

    operations = [
        migrations.AlterField(
            model_name='awshandler',
            name='SSM_ARN',
            field=models.CharField(blank=True, db_column='ssm_arn', default='', max_length=255, null=True),
        ),
    ]
