# Generated by Django 3.2.5 on 2021-10-26 21:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('aws', '0023_new_aws_params_20211022_2124'),
    ]

    operations = [
        migrations.AddField(
            model_name='ec2serverinfo',
            name='host_group_arn',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
        migrations.AddField(
            model_name='ec2serverinfo',
            name='host_id',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
