# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-30 16:56
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscv', '0006_cittest_max_retries'),
    ]

    operations = [
        migrations.AddField(
            model_name='cittest',
            name='timeout_limit',
            field=models.IntegerField(blank=True, help_text='Maximum wait time before failing the test due to timeout.', null=True, validators=[django.core.validators.MinValueValidator(0)]),
        ),
    ]
