# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-19 18:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscv', '0009_auto_20190814_1416'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cittest',
            name='name',
            field=models.CharField(max_length=255),
        ),
    ]
