# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-30 18:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscv', '0010_auto_20190919_1804'),
    ]

    operations = [
        migrations.AddField(
            model_name='cittest',
            name='last_retry_count',
            field=models.IntegerField(default=0),
        ),
    ]
