# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-17 01:01
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscv', '0011_cittest_last_retry_count'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cittest',
            name='expected_output',
            field=models.TextField(blank=True, help_text='Expected output will search for matching job results. Leaving blank will search for any result found.', verbose_name='Expected output'),
        ),
        migrations.AlterField(
            model_name='cittest',
            name='expected_status',
            field=models.CharField(choices=[('SUCCESS', 'complete with success'), ('WARNING', 'complete with warnings'), ('FAILURE', 'complete with errors')], max_length=25, verbose_name='Expected status'),
        ),
        migrations.AlterField(
            model_name='cittest',
            name='max_retries',
            field=models.IntegerField(default=0, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Max retries'),
        ),
        migrations.AlterField(
            model_name='cittest',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='cittest',
            name='notes',
            field=models.TextField(blank=True, help_text='Notes to identify the purpose of the CITTest', verbose_name='Notes'),
        ),
        migrations.AlterField(
            model_name='cittest',
            name='timeout_limit',
            field=models.IntegerField(blank=True, help_text='Maximum wait time before failing the test due to timeout.', null=True, validators=[django.core.validators.MinValueValidator(0)], verbose_name='Timeout limit'),
        ),
    ]
