# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-18 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cscv', '0012_auto_20191017_0101'),
    ]

    operations = [
        migrations.AlterField(
            model_name='actioncittest',
            name='hook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbhooks.OrchestrationHook'),
        ),
    ]
