# Generated by Django 2.2.10 on 2020-01-24 17:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('cscv', '0013_auto_20191118_2305'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cittest',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
