# Generated by Django 2.2.12 on 2020-06-30 07:20

import cb_secrets.fields
import common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkVirtualizationTechnology',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Name of the network virtualization technology')),
                ('version', models.CharField(max_length=20, verbose_name='Version of the network virtualization technology')),
                ('modulename', models.CharField(blank=1, max_length=50, verbose_name='Python module for interacting with this version of the network virtualization technology.')),
            ],
            options={
                'verbose_name_plural': 'network virtualization technologies',
            },
        ),
        migrations.CreateModel(
            name='NetworkVirtualization',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ip', models.CharField(max_length=50, verbose_name='IP address')),
                ('port', models.IntegerField(default=443, help_text='Port used to connect to this network virtualization service', validators=[common.validators.is_only_digits])),
                ('protocol', models.CharField(choices=[('http', 'http'), ('https', 'https')], default='https', help_text='Protocol used to connect to this network virtualization service', max_length=10)),
                ('serviceaccount', models.CharField(help_text='Username of account authorized to run commands on this network virtualization service', max_length=250, verbose_name='Account username')),
                ('servicepasswd', cb_secrets.fields.EncryptedPasswordField(verbose_name='Account password')),
                ('name', models.CharField(blank=True, max_length=50, null=True)),
                ('network_virtualization_technology', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_virtualization.NetworkVirtualizationTechnology')),
                ('real_type', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, to='contenttypes.ContentType')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
