# Generated by Django 2.2.12 on 2020-07-01 20:06

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_virtualization', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='networkvirtualizationtechnology',
            options={'verbose_name': 'network virtualization platform', 'verbose_name_plural': 'network virtualization platforms'},
        ),
        migrations.AlterField(
            model_name='networkvirtualization',
            name='ip',
            field=models.CharField(help_text='Hostname or IP of the network virtualization platform to connect to', max_length=50, validators=[common.validators.validate_domain_or_ip], verbose_name='IP address'),
        ),
        migrations.AlterField(
            model_name='networkvirtualization',
            name='port',
            field=models.IntegerField(default=443, help_text='Port used to connect to this network virtualization platform', validators=[common.validators.is_only_digits]),
        ),
        migrations.AlterField(
            model_name='networkvirtualization',
            name='protocol',
            field=models.CharField(choices=[('http', 'http'), ('https', 'https')], default='https', help_text='Protocol used to connect to this network virtualization platform', max_length=10),
        ),
        migrations.AlterField(
            model_name='networkvirtualization',
            name='serviceaccount',
            field=models.CharField(help_text='Username of account authorized to run commands on this network virtualization platform', max_length=250, verbose_name='Account username'),
        ),
        migrations.AlterField(
            model_name='networkvirtualizationtechnology',
            name='modulename',
            field=models.CharField(blank=1, max_length=50, verbose_name='Python module for interacting with this version of the network virtualization platform'),
        ),
        migrations.AlterField(
            model_name='networkvirtualizationtechnology',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Name of the network virtualization platform'),
        ),
        migrations.AlterField(
            model_name='networkvirtualizationtechnology',
            name='version',
            field=models.CharField(max_length=20, verbose_name='Version of the network virtualization platform'),
        ),
    ]
