# Generated by Django 2.2.12 on 2020-07-02 20:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('network_virtualization', '0002_update_help_text'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkvirtualization',
            name='enable_ssl_verification',
            field=models.BooleanField(default=True, help_text='When disabled, SSL certificates will not be verified when connecting to this network virtualization platform.', verbose_name='SSL Verification'),
        ),
    ]
