# Generated by Django 2.2.12 on 2020-07-08 20:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourcehandlers', '0018_resourcehandler_include_vm_tags'),
        ('network_virtualization', '0003_networkvirtualization_enable_ssl_verification'),
    ]

    operations = [
        migrations.CreateModel(
            name='NetworkVirtualizationResourceHandlerMapping',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('_raw_json_representation', models.TextField(help_text='JSON representation of the dictionary of name/value pairs returned by the 3rd party API.')),
                ('display_name', models.CharField(max_length=100)),
                ('uuid', models.CharField(editable=False, max_length=100)),
                ('network_virtualization', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='network_virtualization.NetworkVirtualization')),
                ('resource_handler', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='resourcehandlers.ResourceHandler')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
