# Generated by Django 2.2.10 on 2020-07-15 15:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_virtualization', '0004_networkvirtualizationresourcehandlermapping'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkvirtualizationresourcehandlermapping',
            name='slug',
            field=models.SlugField(blank=1, max_length=100, verbose_name='Slugified name of the resource technology filter (ex. vmware)'),
        ),
        migrations.AlterField(
            model_name='networkvirtualizationresourcehandlermapping',
            name='network_virtualization',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='mappings', to='network_virtualization.NetworkVirtualization'),
        ),
    ]
