# Generated by Django 2.2.10 on 2020-07-29 21:22

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('network_virtualization', '0005_auto_20200715_1514'),
    ]

    operations = [
        migrations.AlterField(
            model_name='networkvirtualizationresourcehandlermapping',
            name='resource_handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sdn_mapping', to='resourcehandlers.ResourceHandler'),
        ),
    ]
