# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-18 17:48
from __future__ import unicode_literals

import cb_secrets.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('contenttypes', '0002_remove_content_type_name'),
    ]

    operations = [
        migrations.CreateModel(
            name='SIEMProvider',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Label for this SIEM provider', max_length=80)),
                ('ip', models.CharField(max_length=50, verbose_name='IP/Hostname')),
                ('username', models.CharField(blank=True, max_length=250)),
                ('password', cb_secrets.fields.EncryptedPasswordField(blank=True)),
                ('real_type', models.ForeignKey(editable=False, null=True, on_delete=django.db.models.deletion.CASCADE, to='contenttypes.ContentType')),
            ],
            options={
                'ordering': ['name'],
                'abstract': False,
            },
        ),
    ]
