# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-18 22:27
from __future__ import unicode_literals

import cb_secrets.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siem', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='siemprovider',
            name='ip',
        ),
        migrations.AddField(
            model_name='siemprovider',
            name='hostname',
            field=models.CharField(default='', max_length=255, verbose_name='Hostname / IP Address'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='siemprovider',
            name='password',
            field=cb_secrets.fields.EncryptedPasswordField(),
        ),
        migrations.AlterField(
            model_name='siemprovider',
            name='username',
            field=models.CharField(max_length=50),
        ),
    ]
