# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-19 16:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siem', '0003_auto_20190718_2313'),
    ]

    operations = [
        migrations.AddField(
            model_name='siemprovider',
            name='_loggers',
            field=models.CharField(default='""', help_text='JSON field of configured loggers.', max_length=120),
        ),
    ]
