# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-23 23:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('siem', '0004_siemprovider__loggers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='siemprovider',
            name='_loggers',
            field=models.CharField(blank=True, default='""', help_text='JSON field of configured loggers.', max_length=120),
        ),
    ]
