# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-06 19:54
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_parent_service'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResourceType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('label', models.CharField(max_length=255)),
                ('lifecycle', models.CharField(choices=[('ACTIVE', 'Active'), ('HISTORICAL', 'Historical')], default='ACTIVE', max_length=10)),
            ],
        ),
    ]
