# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 14:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0003_service_parent_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='accounts.Group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='service',
            name='lifecycle',
            field=models.CharField(choices=[('ACTIVE', 'Active'), ('HISTORICAL', 'Historical'), ('PROV', 'Provisioning'), ('PROVFAILED', 'Provision Failed')], default='PROV', max_length=10, verbose_name='Lifecycle'),
        ),
        migrations.AlterField(
            model_name='service',
            name='name',
            field=models.CharField(max_length=75, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='service',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='accounts.UserProfile', verbose_name='Owner'),
        ),
    ]
