# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 13:47
from __future__ import unicode_literals

from django.db import migrations


def create_ootb_service_resourcetype(apps, schema_editor):
    """
    Make the OOTB ResourceType called "Service", which will eventually be used
    to replace our current Service model with a Resource of type "Service".
    Doing this here rather than in cb_minimal partially because we can't think
    of a reason to do it there, and largely because this object will need to be
    referenced by the data migration that translates create_service on the BP to
    resource_type.
    """
    ResourceType = apps.get_model('services', 'ResourceType')
    ResourceType.objects.create(
        name='service',
        label='Service',
    )


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0004_resourcetype'),
    ]

    operations = [
        migrations.RunPython(create_ootb_service_resourcetype),
    ]
