# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 15:28
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_ootb_service_resourcetype_20171108_1347'),
    ]

    operations = [
        migrations.AddField(
            model_name='service',
            name='resource_type',
            field=models.ForeignKey(blank=True, help_text='The type of resource that this object represents.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.ResourceType', verbose_name='Resource Type'),
        ),
    ]
