# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-13 20:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0007_set_services_resource_type_20171113_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='service',
            name='resource_type',
            field=models.ForeignKey(help_text='The type of resource that this object represents.', on_delete=django.db.models.deletion.PROTECT, to='services.ResourceType', verbose_name='Resource Type'),
        ),
    ]
