# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-16 18:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0008_auto_20171113_2033'),
        ('services', '0004_auto_20171114_1444'),
    ]

    operations = [
    ]
