# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-27 19:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0010_resourcetype_plural_label'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='resourcetype',
            options={'ordering': ['label']},
        ),
    ]
