# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-13 15:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0013_auto_20171208_1747'),
    ]

    operations = [
        migrations.RenameField(
            model_name='resource',
            old_name='parent_service',
            new_name='parent_resource',
        ),
        migrations.AlterField(
            model_name='servicenetwork',
            name='appliance_identifier',
            field=models.CharField(help_text='Indentifier to tell external API what unique appliance id to look for. Appliances can be used to configure routing, firewall, load balancers and other services', max_length=255, null=True),
        ),
    ]
