# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 14:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0014_auto_20171213_1518'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ServiceNetwork',
            new_name='SoftwareDefinedNetwork',
        ),
        migrations.RenameModel(
            old_name='ServiceAppliance',
            new_name='SoftwareDefinedNetworkAppliance',
        ),
    ]
