# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-22 14:51
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0015_auto_20171222_1447'),
    ]

    operations = [
        migrations.RenameField(
            model_name='softwaredefinednetwork',
            old_name='service',
            new_name='resource',
        ),
        migrations.RenameField(
            model_name='softwaredefinednetworkappliance',
            old_name='service',
            new_name='resource',
        ),
    ]
