# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-01 18:41
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0016_auto_20171222_1451'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resource',
            name='attributes',
            field=models.ManyToManyField(blank=True, related_name='oldresource_set', to='orders.CustomFieldValue'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='blueprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oldresource_set', to='servicecatalog.ServiceBlueprint'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oldresource_set', to='accounts.Group', verbose_name='Group'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='jobs',
            field=models.ManyToManyField(blank=True, related_name='oldresource_set', to='jobs.Job'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='owner',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='oldresource_set', to='accounts.UserProfile', verbose_name='Owner'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='parent_resource',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='oldresource_sub_components', to='services.Resource'),
        ),
        migrations.AlterField(
            model_name='resource',
            name='resource_type',
            field=models.ForeignKey(help_text='The type of resource that this object represents.', on_delete=django.db.models.deletion.PROTECT, related_name='oldresource_set', to='services.ResourceType', verbose_name='Resource Type'),
        ),
        migrations.AlterField(
            model_name='softwaredefinednetwork',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oldsoftwaredefinednetwork_set', to='infrastructure.Environment'),
        ),
        migrations.AlterField(
            model_name='softwaredefinednetwork',
            name='network',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oldsoftwaredefinednetwork_set', to='resourcehandlers.ResourceNetwork'),
        ),
        migrations.AlterField(
            model_name='softwaredefinednetwork',
            name='resource_handler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oldsoftwaredefinednetwork_set', to='resourcehandlers.ResourceHandler'),
        ),
        migrations.AlterField(
            model_name='softwaredefinednetwork',
            name='service_item',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='oldsoftwaredefinednetwork_set', to='servicecatalog.ServiceItem'),
        ),
        migrations.AlterField(
            model_name='softwaredefinednetworkappliance',
            name='environment',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oldsoftwaredefinednetworkappliance_set', to='infrastructure.Environment'),
        ),
        migrations.AlterField(
            model_name='softwaredefinednetworkappliance',
            name='resource_handler',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='oldsoftwaredefinednetworkappliance_set', to='resourcehandlers.ResourceHandler'),
        ),
    ]
