# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-02 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0006_auto_20180503_0036'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='openstackhandler',
            name='old_os_build_attributes',
        ),
    ]
