# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-06 12:02
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("externalcontent", "0012_duplicate_osbas_in_multiple_rhs"),
        ("openstack", "0007_remove_openstackhandler_old_os_build_attributes"),
    ]

    operations = [
        migrations.CreateModel(
            name="OpenStackImage",
            fields=[
                (
                    "osbuildattribute_ptr",
                    models.OneToOneField(
                        auto_created=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        parent_link=True,
                        primary_key=True,
                        serialize=False,
                        to="externalcontent.OSBuildAttribute",
                    ),
                ),
                ("uuid", models.CharField(blank=True, max_length=100, null=True)),
                (
                    "external_id",
                    models.CharField(blank=True, max_length=100, null=True),
                ),
                (
                    "total_disk_size",
                    models.DecimalField(
                        blank=True,
                        decimal_places=4,
                        help_text="Total size of all disks on this image in GB",
                        max_digits=10,
                        null=True,
                    ),
                ),
            ],
            options={"verbose_name": "Image", "abstract": False,},
            bases=("externalcontent.osbuildattribute",),
        ),
    ]
