# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-30 12:49
from __future__ import unicode_literals

from django.db import migrations


def move_libclouldimages_to_openstackimages(apps, schema_editor):
    LibcloudImage = apps.get_model("libcloudhandler", "libcloudimage")
    OpenStackImage = apps.get_model("openstack", "openstackimage")
    OSBuild = apps.get_model("externalcontent", "OSBuild")
    OpenStackHandler = apps.get_model("openstack", "OpenStackHandler")
    ResourceHandler = apps.get_model("resourcehandlers", "resourcehandler")
    rhs = OpenStackHandler.objects.all()
    if rhs:
        for rh in rhs.all():
            images = LibcloudImage.objects.filter(resourcehandler=rh).values()
            for image in images.all():
                new_image, created = OpenStackImage.objects.get_or_create(
                    os_build=OSBuild.objects.get(id=image["os_build_id"]),
                    template_name=image["template_name"],
                    resourcehandler=ResourceHandler.objects.filter(id=rh.id).first(),
                )
                if created:
                    # Set the openstack specific Attributes to the new osbuild
                    new_image.project_name = None
                    new_image.is_bootable = False
                    new_image.external_id = image["external_id"]
                    new_image.save()
                    rh.os_build_attributes.add(new_image)
                    LibcloudImage.objects.filter(resourcehandler=rh).delete()


class Migration(migrations.Migration):

    dependencies = [
        ("openstack", "0010_openstackimage_project_name"),
    ]

    operations = [
        migrations.RunPython(
            move_libclouldimages_to_openstackimages, migrations.RunPython.noop
        )
    ]
