# Generated by Django 2.2.10 on 2020-04-10 07:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('openstack', '0011_auto_20190930_1249'),
        ('openstack', '0008_security_groups_allow_multiple'),
    ]

    operations = [
    ]
