# Generated by Django 2.2.12 on 2020-08-14 13:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libcloudhandler', '0006_remove_libcloudimage_old_template_name'),
        ('openstack', '0013_auto_20200428_1414'),
    ]

    operations = [
        migrations.CreateModel(
            name='OpenStackServerInfo',
            fields=[
                ('libcloudserverinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='libcloudhandler.LibcloudServerInfo')),
                ('availability_zone', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
            bases=('libcloudhandler.libcloudserverinfo',),
        ),
    ]
