# Generated by Django 2.2.10 on 2020-04-24 19:40

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import driven_apps.common.custom_fields
import driven_apps.common.mixins
import driven_apps.common.validators


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('naming', '0010_endpoint'),
    ]

    operations = [
        migrations.CreateModel(
            name='Validator',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The user-specified name of this validator.', max_length=255, unique=True, validators=[driven_apps.common.validators.not_blank, driven_apps.common.validators.MinLengthValidator(3, True), django.core.validators.RegexValidator('^[0-9A-Za-z_-]*$', 'Must match ^[0-9A-Za-z_-]*$')])),
                ('description', models.TextField(blank=True, default='', help_text='The description text for this validator.')),
                ('type', driven_apps.common.custom_fields.LowerCaseCharField(choices=[('dns', 'dns')], help_text='The type of this validator.', max_length=64, validators=[driven_apps.common.validators.OneOfValidator(('dns',))])),
                ('endpoint', models.ForeignKey(help_text='The name of the endpoint this validator will use.', on_delete=django.db.models.deletion.DO_NOTHING, to='naming.Endpoint')),
            ],
            options={
                'verbose_name': 'validator',
                'verbose_name_plural': 'validators',
                'db_table': 'validator',
                'ordering': ['id'],
                'abstract': False,
            },
            bases=(models.Model, driven_apps.common.mixins.RoleBasedHalFilteringMixin),
        ),
    ]
