# Generated by Django 2.2.10 on 2020-04-28 15:56

import django.core.validators
from django.db import migrations, models
import django.db.models.deletion
import driven_apps.common.custom_fields
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validator',
            name='endpoint',
            field=models.ForeignKey(help_text='The name of the endpoint this validator will use.', on_delete=django.db.models.deletion.DO_NOTHING, to='naming.Endpoint', validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='endpoint'), driven_apps.common.validators.not_blank]),
        ),
        migrations.AlterField(
            model_name='validator',
            name='name',
            field=models.CharField(help_text='The user-specified name of this validator.', max_length=255, unique=True, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='name'), driven_apps.common.validators.not_blank, driven_apps.common.validators.MinLengthValidator(3, True), django.core.validators.RegexValidator('^[0-9A-Za-z_-]*$', 'Must match ^[0-9A-Za-z_-]*$')]),
        ),
        migrations.AlterField(
            model_name='validator',
            name='type',
            field=driven_apps.common.custom_fields.LowerCaseCharField(help_text='The type of this validator.', max_length=64, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='type'), driven_apps.common.validators.OneOfValidator(['dns'])]),
        ),
    ]
