# Generated by Django 2.2.12 on 2020-05-11 20:11

import django.core.validators
from django.db import migrations, models
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0005_auto_20200506_2203'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validator',
            name='name',
            field=models.CharField(help_text='The user-specified name of this validator.', max_length=255, unique=True, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='name'), driven_apps.common.validators.not_blank, driven_apps.common.validators.MinLengthValidator(3, True), django.core.validators.RegexValidator('^[0-9A-Za-z_]*$', 'Must be alphanumeric characters and/or underscores.')]),
        ),
    ]
