# Generated by Django 2.2.12 on 2020-06-29 19:59

from django.db import migrations, models
import django.db.models.deletion
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0008_auto_20200619_1623'),
        ('naming', '0028_endpoint_data'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validator',
            name='endpoint',
            field=models.ForeignKey(help_text='The name of the endpoint this validator will use.', on_delete=django.db.models.deletion.DO_NOTHING, to='naming.Endpoint', validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='endpoint'), driven_apps.common.validators.NotBlankValidator(field_name='endpoint', required=True)]),
        ),
    ]
