# Generated by Django 2.2.12 on 2020-07-06 18:59

from django.db import migrations
import driven_apps.common.custom_fields
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('validators', '0009_auto_20200629_1959'),
    ]

    operations = [
        migrations.AlterField(
            model_name='validator',
            name='type',
            field=driven_apps.common.custom_fields.LowerCaseCharField(help_text='The type of this validator.', max_length=64, validators=[driven_apps.common.validators.RequiredFieldValidator(field_name='type'), driven_apps.common.validators.OneOfValidator(allowed_values=['dns', 'vra8'], field_name='type')]),
        ),
    ]
