# Generated by Django 2.2.16 on 2021-01-06 22:08

from django.db import migrations, models
import django.db.models.deletion
import driven_apps.common.mixins


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('naming', '0069_servicenowendpoint'),
        ('accounts', '0055_userprofile_widgets_json'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNowCMDBPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The user-specified name of this ServiceNow CMDB Policy.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='The description text for this ServiceNow CMDB Policy.', null=True)),
                ('endpoint', models.ForeignKey(help_text='ServiceNow provider endpoint for this ServiceNow CMDB policy.', on_delete=django.db.models.deletion.PROTECT, to='naming.Endpoint')),
                ('workspace', models.ForeignKey(help_text='Workspace URL', on_delete=django.db.models.deletion.PROTECT, to='accounts.Group')),
            ],
            options={
                'verbose_name': 'ServiceNow CMDB Policy',
                'verbose_name_plural': 'ServiceNow CMDB Policies',
                'db_table': 'servicenow_cmdb_policies',
                'ordering': ['-id'],
            },
            bases=(models.Model, driven_apps.common.mixins.RoleBasedHalFilteringMixin),
        ),
        migrations.AddConstraint(
            model_name='servicenowcmdbpolicy',
            constraint=models.UniqueConstraint(fields=('name',), name='servicenow_cmdb_policy_name_unique'),
        ),
    ]
