# Generated by Django 2.2.16 on 2021-01-07 17:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_servicenow', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenowcmdbpolicy',
            name='endpoint',
            field=models.ForeignKey(help_text='ServiceNow provider endpoint for this ServiceNow CMDB policy.', on_delete=django.db.models.deletion.PROTECT, to='naming.ServiceNowEndpoint'),
        ),
    ]
