# Generated by Django 2.2.16 on 2021-01-13 14:35

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_servicenow', '0002_auto_20210107_1732'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenowcmdbpolicy',
            name='provision_template',
            field=common.fields.TemplatableField(default='default template', help_text='The template to be sent to the ServiceNow Identification and Reconciliation Engine (IRE) when provisioning.', max_length=65536),
            preserve_default=False,
        ),
    ]
