# Generated by Django 2.2.16 on 2021-01-14 18:52

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json
import driven_apps.common.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0055_userprofile_widgets_json'),
        ('naming', '0071_auto_20210112_1807'),
        ('fuse_servicenow', '0003_servicenowcmdbpolicy_provision_template'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServicenowDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_item_names', models.CharField(help_text='The ServiceNow CI Names', max_length=256)),
                ('activity', models.CharField(help_text='Link to history of deployment results', max_length=256)),
                ('provisioning_details', django_extensions.db.fields.json.JSONField(default=dict, help_text='ServiceNow provisioning details')),
                ('job_metadata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='naming.JobMetadata')),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuse_servicenow.ServiceNowCMDBPolicy')),
                ('workspace', models.ForeignKey(help_text='Workspace URL', on_delete=django.db.models.deletion.PROTECT, to='accounts.Group')),
            ],
            options={
                'verbose_name_plural': 'ServiceNow Deployments',
                'db_table': 'servicenow_deployments',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(models.Model, driven_apps.common.mixins.RoleBasedHalFilteringMixin),
        ),
    ]
