# Generated by Django 2.2.16 on 2021-01-21 16:16

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_servicenow', '0004_servicenowdeployment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenowdeployment',
            name='configuration_item_names',
            field=django_extensions.db.fields.json.JSONField(default=dict, help_text='A list of ServiceNow CI Names'),
        ),
    ]
