# Generated by Django 2.2.16 on 2021-02-02 00:56

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_servicenow', '0005_auto_20210121_1616'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicenowdeployment',
            name='configuration_item_names',
        ),
        migrations.RemoveField(
            model_name='servicenowdeployment',
            name='provisioning_details',
        ),
        migrations.AddField(
            model_name='servicenowdeployment',
            name='configuration_items_info',
            field=django_extensions.db.fields.json.JSONField(default=dict, help_text='A list of ServiceNow CI information (JSON)'),
        ),
        migrations.AddField(
            model_name='servicenowdeployment',
            name='execution_details',
            field=django_extensions.db.fields.json.JSONField(default=dict, help_text='ServiceNow execution details'),
        ),
    ]
