# Generated by Django 2.2.16 on 2021-02-10 14:31

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_servicenow', '0006_auto_20210202_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenowcmdbpolicy',
            name='update_template',
            field=common.fields.TemplatableField(default='{"items":[{"className":"cmdb_ci_linux_server","values":{"os":"Linux Red Hat","discovery_source":"onefuse","sys_class_name":"cmdb_ci_linux_server","name":"{{name}}","host_name":"{{host_name}}","ip_address":"{{nic0_ip}}","os_version":"2.6.9-22.0.1.fi.smp","disk_space":"{{disk_size}}","state":"ON"}},{"className":"cmdb_ci_linux_server","values":{"os":"Linux Red Hat","discovery_source":"onefuse","sys_class_name":"cmdb_ci_linux_server","name":"{{name2}}","host_name":"{{host_name2}}","ip_address":"{{nic0_ip2}}","os_version":"2.6.9-22.0.1.fi.smp","disk_space":"{{disk_size2}}","state":"ON"}}]}', help_text='The template to be sent to the ServiceNow Identification and Reconciliation Engine (IRE) when updating.', max_length=65536),
            preserve_default=False,
        ),
    ]
