# Generated by Django 2.2.16 on 2021-02-12 14:15

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_servicenow', '0007_servicenowcmdbpolicy_update_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenowcmdbpolicy',
            name='deprovision_template',
            field=common.fields.TemplatableField(default={}, help_text='The template to be sent to the ServiceNow Identification and Reconciliation Engine (IRE) when deprovisioning.', max_length=65536),
            preserve_default=False,
        ),
    ]
