# Generated by Django 2.2.16 on 2021-02-12 17:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_servicenow', '0008_servicenowcmdbpolicy_deprovision_template'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenowdeployment',
            name='archived',
            field=models.BooleanField(default=False),
        ),
    ]
