# Generated by Django 2.2.16 on 2021-02-17 13:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_servicenow', '0008_remove_servicenowdeployment_activity'),
        ('fuse_servicenow', '0009_servicenowdeployment_archived'),
    ]

    operations = [
    ]
