# Generated by Django 2.2.16 on 2021-03-01 18:29

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json
import driven_apps.common.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0075_jobmetadata__rendered_templates'),
        ('accounts', '0056_auto_20210207_1142'),
        ('fuse_servicenow', '0010_merge_20210217_1351'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNowCMDBDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('configuration_items_info', django_extensions.db.fields.json.JSONField(default=dict, help_text='A list of ServiceNow CMDB CI information (JSON)')),
                ('execution_details', django_extensions.db.fields.json.JSONField(default=dict, help_text='ServiceNow CMDB execution details')),
                ('archived', models.BooleanField(default=False)),
                ('job_metadata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='naming.JobMetadata')),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuse_servicenow.ServiceNowCMDBPolicy')),
                ('workspace', models.ForeignKey(help_text='Workspace URL', on_delete=django.db.models.deletion.PROTECT, to='accounts.Group')),
            ],
            options={
                'verbose_name_plural': 'ServiceNow CMDB Deployments',
                'db_table': 'servicenow_cmdb_deployments',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(models.Model, driven_apps.common.mixins.RoleBasedHalFilteringMixin),
        ),
        migrations.DeleteModel(
            name='ServicenowDeployment',
        ),
    ]
