# Generated by Django 2.2.16 on 2021-03-18 18:53

from django.db import migrations, models
import django.db.models.deletion
import driven_apps.common.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('naming', '0077_auto_20210311_1506'),
        ('accounts', '0059_set_global_id_for_userprofile'),
        ('fuse_servicenow', '0011_auto_20210301_1829'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNowConnectorPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='The user-specified name of this ServiceNow Connector Policy.', max_length=255)),
                ('description', models.TextField(blank=True, help_text='The description text for this ServiceNow Connector Policy.', null=True)),
                ('endpoint', models.ForeignKey(help_text='ServiceNow provider endpoint for this ServiceNow Connector policy.', on_delete=django.db.models.deletion.PROTECT, to='naming.ServiceNowEndpoint')),
                ('workspace', models.ForeignKey(help_text='Workspace URL', on_delete=django.db.models.deletion.PROTECT, to='accounts.Group')),
            ],
            options={
                'verbose_name': 'ServiceNow Connector Policy',
                'verbose_name_plural': 'ServiceNow Connector Policies',
                'db_table': 'servicenow_connector_policies',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(models.Model, driven_apps.common.mixins.RoleBasedHalFilteringMixin),
        ),
        migrations.AddConstraint(
            model_name='servicenowconnectorpolicy',
            constraint=models.UniqueConstraint(fields=('name',), name='servicenow_connector_policy_name_unique'),
        ),
    ]
