# Generated by Django 2.2.16 on 2021-03-24 15:04

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_servicenow', '0012_auto_20210318_1853'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenowconnectorpolicy',
            name='inputs',
            field=django_extensions.db.fields.json.JSONField(default=dict, help_text='A list of ServiceNow Connector Policy inputs {"name": <string>, "required": <boolean>} to be passed to OneFuse Policies during execution.'),
        ),
    ]
