# Generated by Django 2.2.16 on 2021-04-14 19:44

from django.db import migrations, models
import django.db.models.deletion
import driven_apps.common.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0060_role_group_types'),
        ('naming', '0079_rename_solarwinds_version'),
        ('fuse_servicenow', '0014_servicenowconnectorcatalogitem'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNowConnectorDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('job_metadata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='naming.JobMetadata')),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='fuse_servicenow.ServiceNowConnectorPolicy')),
                ('workspace', models.ForeignKey(help_text='Workspace URL', on_delete=django.db.models.deletion.PROTECT, to='accounts.Group')),
            ],
            options={
                'verbose_name_plural': 'ServiceNow Connector Deployments',
                'db_table': 'servicenow_connector_deployments',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(models.Model, driven_apps.common.mixins.RoleBasedHalFilteringMixin),
        ),
    ]
