# Generated by Django 2.2.16 on 2021-04-22 11:18

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_servicenow', '0015_servicenowconnectordeployment'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenowconnectorpolicy',
            name='sub_policies',
            field=django_extensions.db.fields.json.JSONField(default=dict, help_text='A JSON array of the required parameters for each policy type.'),
        ),
    ]
