# Generated by Django 2.2.16 on 2021-04-26 20:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_servicenow', '0016_servicenowconnectorpolicy_sub_policies'),
        ('fuse_servicenow', '0016_servicenowconnectorcatalogitem_job_metadata'),
    ]

    operations = [
    ]
