# Generated by Django 2.2.16 on 2021-04-28 14:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_servicenow', '0017_merge_20210426_2004'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenowconnectorcatalogitem',
            name='servicenow_sys_id',
            field=models.CharField(blank=True, help_text='The sys_id of the linked catalog item in ServiceNow.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicenowconnectorcatalogitem',
            name='catalog',
            field=models.TextField(help_text='The catalog name in ServiceNow for this ServiceNow Connector Catalog Item.'),
        ),
        migrations.AlterField(
            model_name='servicenowconnectorcatalogitem',
            name='category',
            field=models.TextField(help_text='The category name from the specified catalog in ServiceNow for this ServiceNow Connector Catalog Item.'),
        ),
    ]
