# Generated by Django 2.2.16 on 2021-04-28 17:20

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vra', '0011_auto_20210309_2040'),
        ('fuse_servicenow', '0017_merge_20210428_1720'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenowconnectordeployment',
            name='vra_policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='vra.VraPolicy'),
        ),
    ]
