# Generated by Django 2.2.16 on 2021-04-28 21:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_servicenow', '0018_auto_20210428_1408'),
        ('fuse_servicenow', '0018_servicenowconnectordeployment_vra_policy'),
    ]

    operations = [
    ]
