# Generated by Django 2.2.16 on 2021-04-28 21:22

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_servicenow', '0019_merge_20210428_2115'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenowconnectorcatalogitem',
            name='inputs',
            field=django_extensions.db.fields.json.JSONField(default=dict, help_text='A list of ServiceNow Connector Catalog Item inputs {"name": <string>, "label": <string>, "policyInput": <string>, "required": <boolean>} to be created on the catalog item in ServiceNow.'),
        ),
    ]
