# Generated by Django 2.2.16 on 2021-05-25 18:31

from django.db import migrations, models
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_servicenow', '0020_auto_20210428_2122'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servicenowconnectorpolicy',
            name='sub_policies',
        ),
        migrations.AddField(
            model_name='servicenowconnectorpolicy',
            name='catalog',
            field=models.TextField(default='Service Catalog', help_text='The catalog name in ServiceNow for this ServiceNow Connector Catalog Item.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicenowconnectorpolicy',
            name='category',
            field=models.TextField(default='Virtual Resources', help_text='The category name from the specified catalog in ServiceNow for this ServiceNow Connector Catalog Item.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicenowconnectorpolicy',
            name='servicenow_sys_id',
            field=models.CharField(blank=True, help_text='The sys_id of the linked catalog item in ServiceNow.', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='servicenowconnectorpolicy',
            name='inputs',
            field=django_extensions.db.fields.json.JSONField(default=dict, help_text='A list of ServiceNow Connector Catalog Item inputs {"name": <string>, "label": <string>, "policyInput": <string>, "required": <boolean>} to be created on the catalog item in ServiceNow.'),
        ),
        migrations.DeleteModel(
            name='ServiceNowConnectorCatalogItem',
        ),
    ]
