# Generated by Django 2.2.16 on 2021-06-03 20:16

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_servicenow', '0021_auto_20210525_1831'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenowconnectorpolicy',
            name='child_policy_link',
            field=models.TextField(default='a', help_text='Link to the OneFuse Child Policy to be invoked by ServiceNow Connector Policy.'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicenowconnectorpolicy',
            name='child_policy_template',
            field=common.fields.TemplatableField(default='a', help_text='Template for executing the OneFuse Child Policy to be invoked by ServiceNow Connector Policy.', max_length=65536),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='servicenowconnectorpolicy',
            name='child_policy_type',
            field=models.TextField(default='a', help_text='Type of the OneFuse Child Policy to be invoked by ServiceNow Connector Policy.'),
            preserve_default=False,
        ),
    ]
