# Generated by Django 2.2.16 on 2021-06-15 15:08

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_servicenow', '0022_auto_20210603_2016'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenowconnectorpolicy',
            name='child_policy_template',
            field=django_extensions.db.fields.json.JSONField(default=dict, help_text='Template for executing the OneFuse Child Policy to be invoked by ServiceNow Connector Policy.'),
        ),
    ]
