# Generated by Django 3.2.3 on 2021-07-02 15:16

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_servicenow', '0025_auto_20210701_2032'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenowconnectordeployment',
            name='_child_policy_href',
            field=models.TextField(blank=True, null=True),
        ),
    ]
