# Generated by Django 3.2.3 on 2021-07-14 22:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_servicenow', '0026_alter_servicenowconnectordeployment__child_policy_href'),
    ]

    operations = [
        migrations.AddField(
            model_name='servicenowconnectordeployment',
            name='_child_managed_object_href',
            field=models.TextField(blank=True, null=True),
        ),
    ]
