# Generated by Django 3.2.3 on 2021-08-02 22:30

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('fuse_servicenow', '0027_servicenowconnectordeployment__child_managed_object_href'),
    ]

    operations = [
        migrations.AlterField(
            model_name='servicenowconnectorpolicy',
            name='child_policy_template',
            field=common.fields.TemplatableField(help_text='Template for executing the OneFuse Child Policy to be invoked by ServiceNow Connector Policy.', max_length=65536),
        ),
    ]
