# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-10 22:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alibaba', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='alibabavswitch',
            options={'verbose_name': 'Alibaba VSwitch'},
        ),
    ]
