# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-20 16:30
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alibaba', '0002_auto_20190610_2229'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alibabaresourcehandler',
            name='access_key',
            field=models.CharField(max_length=100),
        ),
    ]
