# Generated by Django 3.2.3 on 2021-08-12 21:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alibaba', '0003_auto_20191120_1630'),
    ]

    operations = [
        migrations.AddField(
            model_name='alibabaserverinfo',
            name='disk_category',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
