# Generated by Django 3.2.5 on 2021-12-15 19:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alibaba', '0005_alibabaserverinfo_tags_json'),
    ]

    operations = [
        migrations.AddField(
            model_name='alibabaserverinfo',
            name='resource_group',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
    ]
