# Generated by Django 3.2.5 on 2021-12-21 08:16

from django.db import migrations


class Migration(migrations.Migration):
    def add_alibaba_sshkey_password_fields(apps, schema_editor):
        """
        In order to smooth the transition of adding the new (required) Alibaba
        Tech-Specific Parameters Credential Type and Password, we want to add the new field and
        current options to any existing Alibaba Environment. Otherwise, things would behave poorly
        until users went to each of those Environments and re-imported all their Tech-specific Parameters.
        This allows everything to function immediately, and they can still import
        the Parameter's options at any time in the future to make sure they're current
        """
        AlibabaResourceHandler = apps.get_model("alibaba", "AlibabaResourceHandler")
        CustomField = apps.get_model("infrastructure", "CustomField")
        CustomFieldValue = apps.get_model("orders", "CustomFieldValue")

        # Copied from alibaba_minimal since this will run first
        alibaba_cfs = [
            {
                "name": "login_credential_type_alibaba",
                "cf_dict": {
                    "label": "Alibaba Credential Type",
                    "type": "STR",
                    "required": True,
                    "description": "Alibaba requires a login credential for orders; the credential must be either an existing Key Pair or Password.",
                },
                "options": ["Key Pair", "Password"],
            },
            {
                "name": "password_alibaba",
                "cf_dict": {
                    "label": "Alibaba Login Password",
                    "type": "PWD",
                    "required": True,
                    "description": (
                        "Alibaba requires a password for orders. It must be at 8 to 31 characters in length and contain at least three types of the following characters: uppercase letter, lowercase letters, digits, and special characters."
                        "Special characters include the following ones: ()`~!@#$%^&*_-+=|{}[]:;'<>,.?/. The logon password for a Windows instance cannot start with a forward slash (/)."
                    ),
                },
            },
        ]

        envs = []
        for handler in AlibabaResourceHandler.objects.all():
            envs.extend(handler.environment_set.all())

        if envs:
            for cf_field in alibaba_cfs:
                cf, __ = CustomField.objects.get_or_create(name=cf_field["name"], defaults=cf_field["cf_dict"])
                cfvs = []

                # Create Options if defined.
                options = cf_field.get("options", [])
                for opt in options:
                    cfv, __ = CustomFieldValue.objects.get_or_create(field=cf, str_value=opt)
                    cfvs.append(cfv)

                # Add Field and options to Environment.
                for env in envs:
                    env.custom_fields.add(cf)

                    if cfvs and not env.custom_field_options.filter(field=cf).exists():
                        env.custom_field_options.add(*cfvs)

    dependencies = [
        ('alibaba', '0006_alibabaserverinfo_resource_group'),
        ('infrastructure', '0062_update_internet_max_bandwidth_out_20211213_1835'),
        ('orders', '0041_alter_customfieldvalue_url_value'),
    ]

    operations = [
        migrations.RunPython(add_alibaba_sshkey_password_fields, migrations.RunPython.noop),
    ]
