# Generated by Django 3.2.5 on 2021-12-22 17:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alibaba', '0006_alibabaserverinfo_resource_group'),
        ('alibaba', '0006_alter_alibabaserverinfo_instance_type'),
    ]

    operations = [
    ]
