# Generated by Django 3.2.5 on 2022-01-03 16:13

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alibaba', '0006_alter_alibabaserverinfo_instance_type'),
        ('alibaba', '0007_alibaba_sshkey_password_support'),
    ]

    operations = [
    ]
