# Generated by Django 3.2.5 on 2022-01-06 21:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('alibaba', '0007_merge_20211222_1753'),
        ('alibaba', '0008_merge_20220103_1613'),
    ]

    operations = [
    ]
