# Generated by Django 2.2.12 on 2020-05-21 17:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eula', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='eula',
            name='eulaText',
            field=models.TextField(default='', help_text='EULA Text'),
        ),
    ]
