# Generated by Django 2.2.12 on 2020-05-22 14:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eula', '0002_eula_eulatext'),
    ]

    operations = [
        migrations.AlterField(
            model_name='eula',
            name='acceptedOn',
            field=models.DateTimeField(blank=True, help_text='Timestamp of when the EULA was accepted by the user.', null=True),
        ),
    ]
