# Generated by Django 2.2.12 on 2020-05-27 13:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eula', '0003_auto_20200522_1413'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='eula',
            options={'ordering': ['id'], 'verbose_name': 'EULA', 'verbose_name_plural': 'EULA'},
        ),
        migrations.AlterModelTable(
            name='eula',
            table='eula',
        ),
    ]
