# Generated by Django 2.2.10 on 2020-07-20 20:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eula', '0004_auto_20200527_1358'),
    ]

    operations = [
        migrations.RenameField(
            model_name='eula',
            old_name='acceptedOn',
            new_name='accepted_on',
        ),
        migrations.RenameField(
            model_name='eula',
            old_name='eulaText',
            new_name='eula_text',
        ),
        migrations.AddField(
            model_name='eula',
            name='product',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
