# Generated by Django 2.2.10 on 2020-07-20 20:26
from django.db import migrations


def set_eula_product(apps, schema_editor):
    try:
        from product_license.cb_license import CloudBoltLicense
    except Exception:
        # If this class no longer exists we can safely skip the migration.
        # The EULA records for both products are created in create_objects instead.
        return

    product = "cmp"
    if CloudBoltLicense().license_is_for_fuse():
        product = "onefuse"

    EULA = apps.get_model('eula', 'EULA')
    for eula in EULA.objects.all():
        eula.product = product
        eula.save()


class Migration(migrations.Migration):

    dependencies = [
        ('eula', '0005_auto_20200720_2024'),
    ]

    operations = [
        migrations.RunPython(set_eula_product, migrations.RunPython.noop)
    ]
