# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-26 18:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmware', '0011_auto_20170104_2307'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vsphereresourcehandler',
            name='clone_tmpl_timeout',
            field=models.IntegerField(default=60, help_text='Used to adjust the timeout for provisioning a VM from a template', verbose_name='Clone Template Timeout'),
        ),
    ]
