# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-07 17:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmware', '0015_auto_20190102_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='vsphereosbuildattribute',
            name='uuid',
            field=models.UUIDField(blank=True, null=True, verbose_name='UUID in VMware'),
        ),
    ]
