# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-05 17:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmware', '0016_vsphereosbuildattribute_uuid'),
    ]

    operations = [
        migrations.AddField(
            model_name='vmwareserverinfo',
            name='moid',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
