# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-06 15:22
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vmware', '0017_vmwareserverinfo_moid'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='vsphereresourcehandler',
            name='clone_tmpl_timeout',
        ),
    ]
