# Generated by Django 3.2.3 on 2021-09-21 16:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vmware', '0018_remove_vsphereresourcehandler_clone_tmpl_timeout'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vmwarenetwork',
            name='adapterType',
            field=models.CharField(choices=[('E1000', 'E 1000'), ('VMXN3', 'VMX NET 3')], db_column='adaptertype', default='E1000', max_length=6),
        ),
        migrations.AlterField(
            model_name='vmwarenetwork',
            name='dvSwitch',
            field=models.CharField(blank=True, db_column='dvswitch', max_length=100),
        ),
        migrations.AlterField(
            model_name='vsphereresourcehandler',
            name='clusterName',
            field=models.CharField(db_column='clustername', max_length=100),
        ),
    ]
