# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-16 10:28
from __future__ import unicode_literals

import cb_secrets.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ExportPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', cb_secrets.fields.EncryptedPasswordField(help_text="Optionally, you may provide a password for encrypting and decrypting any secrets contained in the item being exported. This is useful for sharing exported objects across different CloudBolt instances or when configuring a remote source blueprint. If no password is specified, then a default key will be used for this CloudBolt instance, and the exported object's secrets can only be decrypted when imported into the same CloudBolt instance it was exported from. ")),
            ],
        ),
    ]
