# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-23 17:04
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0011_orchestrationhook_max_retries'),
        ('jobs', '0010_auto_20170130_2012'),
    ]

    operations = [
        migrations.AddField(
            model_name='runflowparameters',
            name='hook',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbhooks.OrchestrationHook'),
        ),
    ]
