# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-27 21:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0011_auto_20170223_0150'),
        ('jobs', '0011_runflowparameters_hook'),
    ]

    operations = [
    ]
