# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 18:51
from __future__ import unicode_literals

from django.db import migrations


def update_description(apps, schema_editor):
    """
    Checks for an existing RecurringJob for 'Auto-power control servers' and, if
    it exists, updates its description to match the new way that things work
    (and what new CBs will get from cb_minimal).
    """
    RecurringJob = apps.get_model('jobs', 'RecurringJob')

    rj = RecurringJob.objects.filter(name='Auto-power control servers').first()
    if rj:
        # copied from cb_minimal
        rj.description = (
            "This recurring job enables auto-powering off of servers for periods of the day. This can be useful for "
            "servers that do not need to run at night, to save on public cloud costs/resource consumption at "
            "those times of the day. "

            "To use this feature, go to a server's details page and configure a power "
            "schedule on the tab or use the Power Schedule parameter at order time. "
            "When the action runs it will look for the ScheduledTime models "
            "created by you setting the power schedule, and use them to determine which "
            "servers should be powered on or off at the current time. "

            "CloudBolt will use its own server time to judge whether it is the right time to power on and "
            "off VMs, so make sure you know what time it is on the CB server and that the timezone is right. "

            "Also note that this recurring job is expected to be run "
            "every hour on the hour. If it is run on a different schedule, that will impact "
            "when servers are powered on or off. The power change will only happen if the job runs "
            "during the hour on the day when a power change is scheduled."
        )
        rj.save()


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0012_merge'),
    ]

    operations = [
        migrations.RunPython(update_description),
    ]
