# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-07 18:55
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0013_update_power_control_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='label',
            field=models.CharField(blank=True, max_length=256),
        ),
    ]
