# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-04 19:29
from __future__ import unicode_literals

from django.db import migrations


def install_service_to_deploy_blueprint(apps, schema_editor):
    """
    Change the type of existing Jobs from install_service to deploy_blueprint,
    since that is more accurate now that a job from a BlueprintOrderItem does
    not necessarily install a service. Needed so those existing jobs will work
    correctly with changes to icon names and such.
    """
    Job = apps.get_model('jobs', 'Job')
    for job in Job.objects.filter(type='install_service'):
        job.type = 'deploy_blueprint'
        job.save()


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0016_auto_20170823_1641'),
    ]

    operations = [
        migrations.RunPython(install_service_to_deploy_blueprint),
    ]
