# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-17 13:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_auto_20171011_1654'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='job',
            options={'get_latest_by': 'start_date', 'ordering': ['id']},
        ),
    ]
