# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-05 12:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0018_auto_20171011_1654'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hookparameters',
            old_name='services',
            new_name='resources',
        ),
    ]
