# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-25 18:30
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0019_auto_20180117_1327'),
        ('jobs', '0019_auto_20180105_1228'),
    ]

    operations = [
    ]
