# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-02 19:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0020_merge_20180125_1830'),
        ('resources',
         '0002_move_services_app_objs_to_resources_app_20180201_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hookparameters',
            name='resources',
            field=models.ManyToManyField(to='resources.Resource'),
        ),
    ]
