# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 04:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0021_auto_20180202_1944'),
    ]

    operations = [
        migrations.AlterField(
            model_name='jobparameters',
            name='failure_email_address',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='If the job fails, send an e-mail to this address'),
        ),
    ]
