# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 23:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0022_jobparameters_fix_verbose_name_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringjob',
            name='allow_parallel_jobs',
            field=models.BooleanField(default=False),
        ),
    ]
