# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-05 23:49
from __future__ import unicode_literals

from django.db import migrations


def allow_parallel_power_control_jobs(apps, schema_editor):
    """
    Now that RecurringJob.allow_parallel_jobs exists, ensure it's set to True for
    two OOTB recurring jobs: "Auto-power control [servers|resources]".
    """
    RecurringJob = apps.get_model('jobs', 'RecurringJob')
    for job in RecurringJob.objects.filter(name__startswith='Auto-power control'):
        job.allow_parallel_jobs = True
        job.save()


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0023_recurringjob_allow_parallel_jobs'),
    ]

    operations = [
        migrations.RunPython(allow_parallel_power_control_jobs, reverse_code=migrations.RunPython.noop)
    ]