# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-03 23:50
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0024_allow_parallel_power_control_jobs'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='created_date',
            field=models.DateTimeField(auto_now_add=True, null=True, verbose_name='Time created'),
        ),
    ]
