# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-04 00:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0025_job_created_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='worker_pid',
            field=models.PositiveIntegerField(blank=True, null=True),
        ),
    ]
