# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-04 16:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0026_job_worker_pid'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='can_be_requeued',
            field=models.BooleanField(default=True),
        ),
    ]
