# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-01 03:16
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0027_job_can_be_requeued'),
    ]

    operations = [
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('SUCCESS', 'Completed successfully'), ('WARNING', 'Completed with warnings'), ('FAILURE', 'Completed with errors'), ('TO_CANCEL', 'In cancellation process'), ('CANCELED', 'Canceled by user'), ('INIT', 'Initializing')], db_index=True, default='PENDING', max_length=10, verbose_name='Job status'),
        ),
    ]
