# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-08 23:51
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0028_add_INIT_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='updated_date',
            field=models.DateTimeField(auto_now=True, null=True, verbose_name='Time updated'),
        ),
    ]
