# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-09 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0029_job_updated_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='worker_hostname',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
    ]
