# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-26 23:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0030_job_worker_hostname'),
    ]

    operations = [
        migrations.AddField(
            model_name='recurringjob',
            name='last_run',
            field=models.DateTimeField(blank=True, editable=False, null=True, verbose_name='Last time a job was spawned'),
        ),
    ]
