# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-20 19:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0031_recurringjob_last_run'),
    ]

    operations = [
        migrations.AddField(
            model_name='job',
            name='execution_state',
            field=models.TextField(blank=1),
        ),
        migrations.AlterField(
            model_name='job',
            name='status',
            field=models.CharField(choices=[('INIT', 'Initializing'), ('PENDING', 'Pending'), ('QUEUED', 'Queued'), ('RUNNING', 'Running'), ('PAUSED', 'Paused'), ('STEP', 'Step'), ('NEXT', 'Next'), ('RETURN', 'Run until return'), ('SUCCESS', 'Completed successfully'), ('WARNING', 'Completed with warnings'), ('FAILURE', 'Completed with errors'), ('TO_CANCEL', 'In cancellation process'), ('CANCELED', 'Canceled by user')], db_index=True, default='PENDING', max_length=10, verbose_name='Job status'),
        ),
    ]
