# Generated by Django 2.2.10 on 2020-03-06 14:24

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0036_auto_20200204_0052'),
        ('jobs', '0035_auto_20200213_1443'),
    ]

    operations = [
    ]
