# Generated by Django 2.2.12 on 2020-05-14 17:44

from django.db import migrations

def fix_recurring_jobs_due_to_missing_type(apps, schema_editor):
    RecurringJob = apps.get_model('jobs', 'RecurringJob')

    # loop thu any sub-type recurring action job in the db that is missing the type and set it
    for recurring_action_job in RecurringJob.objects.filter(type="", recurringactionjob__isnull=False):
        recurring_action_job.type == "orchestration_hook"
        recurring_action_job.save()

    # loop thru any recurring_job that is NOT of sub-type recurring_action_job and has no
    # job parameters -- this should only happened by importing bad content, probably from
    # the content library. Since these RecurringJobs can not be fixed and will only break
    # the job engine we'll delete them.
    RecurringJob.objects.filter(recurringactionjob=None, parameters=None).delete()

class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0040_auto_20200427_1821'),
    ]

    operations = [
        migrations.RunPython(fix_recurring_jobs_due_to_missing_type, migrations.RunPython.noop)
    ]
