# Generated by Django 2.2.16 on 2020-12-22 17:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0049_set_global_id_for_recurring_jobs'),
        ('jobs', '0048_job_global_id'),
    ]

    operations = [
    ]
