# Generated by Django 2.2.16 on 2021-03-02 22:43

import json

import cb_secrets.fields
from django.db import migrations


def encrypt_arguments(apps, schema_editor):
    HookParameters = apps.get_model("jobs", "HookParameters")
    TriggerActionParameters = apps.get_model("jobs", "TriggerActionParameters")
    TriggerParameters = apps.get_model("jobs", "TriggerParameters")
    for Model in (HookParameters, TriggerActionParameters, TriggerParameters):
        for row in Model.objects.all():
            row._encrypted_arguments = row._arguments
            row.save()


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0050_merge_20201222_1737"),
    ]

    operations = [
        migrations.AddField(
            model_name="hookparameters",
            name="_encrypted_arguments",
            field=cb_secrets.fields.EncryptedTextField(
                blank=True,
                help_text="JSON representation of the dictionary of name/value pairs to be passed to this action.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="triggeractionparameters",
            name="_encrypted_arguments",
            field=cb_secrets.fields.EncryptedTextField(
                blank=True,
                help_text="JSON representation of the dictionary of name/value pairs to be passed to this action.",
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="triggerparameters",
            name="_encrypted_arguments",
            field=cb_secrets.fields.EncryptedTextField(
                blank=True,
                help_text="JSON representation of the dictionary of name/value pairs to be passed to this action.",
                null=True,
            ),
        ),
        migrations.RunPython(encrypt_arguments, migrations.RunPython.noop),
    ]
