# Generated by Django 2.2.16 on 2021-03-03 00:08

from django.db import migrations


def decrypt_arguments(apps, schema_editor):
    HookParameters = apps.get_model("jobs", "HookParameters")
    TriggerActionParameters = apps.get_model("jobs", "TriggerActionParameters")
    TriggerParameters = apps.get_model("jobs", "TriggerParameters")
    for Model in (HookParameters, TriggerActionParameters, TriggerParameters):
        for row in Model.objects.all():
            row._arguments = row._encrypted_arguments
            row.save()


class Migration(migrations.Migration):

    dependencies = [
        ("jobs", "0051_encrypted_arguments"),
    ]

    operations = [
        migrations.RunPython(migrations.RunPython.noop, decrypt_arguments),
        migrations.RemoveField(model_name="hookparameters", name="_arguments",),
        migrations.RemoveField(
            model_name="triggeractionparameters", name="_arguments",
        ),
        migrations.RemoveField(model_name="triggerparameters", name="_arguments",),
    ]
