# Generated by Django 3.2.5 on 2021-10-21 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0052_remove_unencrypted_arguments'),
    ]

    operations = [
        migrations.AlterField(
            model_name='recurringjob',
            name='enabled',
            field=models.BooleanField(default=False),
        ),
    ]
