# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-10 18:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0003_ipamnetwork__network_ref'),
    ]

    operations = [
        migrations.AddField(
            model_name='ipam',
            name='name',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
    ]
