# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-10 18:48
from __future__ import unicode_literals

from django.db import migrations


def name_existing_ipams(apps, schema_editor):
    IPAM = apps.get_model('ipam', 'IPAM')

    for ipam in IPAM.objects.all():
        ipam.name = 'Infoblox'
        ipam.save()


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0004_ipam_name'),
    ]

    operations = [
        migrations.RunPython(name_existing_ipams, migrations.RunPython.noop)
    ]
