# Generated by Django 3.2.3 on 2021-09-21 16:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ipam', '0010_set_global_id_for_ipam'),
    ]

    operations = [
        migrations.AlterField(
            model_name='availableipamnetwork',
            name='CIDR',
            field=models.CharField(db_column='cidr', max_length=43),
        ),
        migrations.AlterField(
            model_name='ipamnetwork',
            name='CIDR',
            field=models.CharField(db_column='cidr', max_length=43),
        ),
    ]
