# Generated by Django 2.2.16 on 2021-05-19 15:38

from django.db import migrations, models
import django.db.models.deletion
import django_extensions.db.fields.json
import driven_apps.common.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0061_userprofile_legal_notice_seen'),
        ('naming', '0080_auto_20210414_1450'),
        ('resources', '0012_set_global_id_for_resource_type'),
        ('blueprint_based_modules', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='BlueprintModuleDeployment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=256, null=True)),
                ('provisioning_job_results', django_extensions.db.fields.json.JSONField(default=dict, help_text='Provisioning Job Results')),
                ('deprovisioning_job_results', django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text='Deprovisioning Job Results', null=True)),
                ('archived', models.BooleanField(default=False)),
                ('job_metadata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='naming.JobMetadata')),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='blueprint_based_modules.BlueprintBasedModulePolicy')),
                ('resource', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.Resource')),
                ('workspace', models.ForeignKey(help_text='Workspace URL', on_delete=django.db.models.deletion.PROTECT, to='accounts.Group')),
            ],
            options={
                'verbose_name_plural': 'Module Managed Objects',
                'db_table': 'module_managed_objects',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(models.Model, driven_apps.common.mixins.RoleBasedHalFilteringMixin),
        ),
    ]
