# Generated by Django 3.2.3 on 2021-07-09 13:45

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('blueprint_based_modules', '0003_blueprintmoduledeployment_update_job_results'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='blueprintmoduledeployment',
            options={'ordering': ['-id'], 'verbose_name': 'Module Managed Object', 'verbose_name_plural': 'Module Managed Objects'},
        ),
        migrations.AddField(
            model_name='blueprintbasedmodulepolicy',
            name='action_payloads',
            field=common.fields.TemplatableField(blank=True, help_text='The field is used to map Day2 action labels and their payloads.', max_length=65536, null=True),
        ),
    ]
