# Generated by Django 3.2.3 on 2021-07-15 17:23

from django.db import migrations
import django_extensions.db.fields.json


class Migration(migrations.Migration):

    dependencies = [
        ('blueprint_based_modules', '0004_auto_20210709_1345'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprintmoduledeployment',
            name='display_details',
            field=django_extensions.db.fields.json.JSONField(blank=True, default=dict, help_text='Used to display the results in the UI', null=True),
        ),
    ]
