# Generated by Django 2.2.12 on 2020-07-10 20:00

from django.db import migrations, models
import django.db.models.deletion
import driven_apps.common.mixins
import driven_apps.common.validators
import driven_apps.policies.classes


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('naming', '0033_microsoftendpoint'),
        ('accounts', '0052_auto_20200526_0144'),
    ]

    operations = [
        migrations.CreateModel(
            name='MicrosoftActiveDirectoryPolicy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=254, unique=True, validators=[driven_apps.common.validators.NotBlankValidator(field_name='name', required=True), driven_apps.common.validators.MinLengthValidator(constraint=3, field_name='name', required=True), driven_apps.common.validators.RegexValidator(field_name='name', message='Must be alphanumeric characters and/or underscores.', regex='^[0-9A-Za-z_]*$')])),
                ('description', models.CharField(blank=True, default='', max_length=1024)),
                ('computer_name_letter_case', models.CharField(choices=[('Lowercase', 'LOWER'), ('Uppercase', 'UPPER')], max_length=255)),
                ('ou', models.CharField(max_length=1024, validators=[driven_apps.common.validators.NotBlankValidator(field_name='ou', required=True)], verbose_name='Organizational Unit')),
                ('microsoft_endpoint', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='naming.MicrosoftEndpoint')),
                ('workspace', models.ForeignKey(help_text='Workspace URL', on_delete=django.db.models.deletion.PROTECT, to='accounts.Group')),
            ],
            options={
                'ordering': ['id'],
                'abstract': False,
            },
            bases=(driven_apps.policies.classes.GenericPolicy, models.Model, driven_apps.common.mixins.RoleBasedHalFilteringMixin),
        ),
    ]
