# Generated by Django 2.2.10 on 2020-07-14 21:14

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_active_directory', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsoftactivedirectorypolicy',
            name='microsoft_endpoint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='naming.MicrosoftEndpoint'),
        ),
    ]
