# Generated by Django 2.2.10 on 2020-08-07 19:09

from django.db import migrations, models
import django.db.models.deletion
import driven_apps.common.mixins


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0052_auto_20200526_0144'),
        ('microsoft_active_directory', '0002_auto_20200714_2114'),
        ('naming', '0039_auto_20200727_1624'),
        ('jobs', '0043_auto_20200805_0130'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='MicrosoftActiveDirectoryPolicy',
            new_name='MicrosoftADPolicy',
        ),
        migrations.CreateModel(
            name='MicrosoftADComputerJobParameters',
            fields=[
                ('jobparameters_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='jobs.JobParameters')),
                ('json_payload', models.TextField()),
                ('template_properties', models.TextField(default='{}')),
                ('result', models.TextField(default='{}')),
                ('errors', models.TextField(default='{}')),
                ('job_metadata', models.ForeignKey(help_text='Naming job metadata for tracking job progress and logging', null=True, on_delete=django.db.models.deletion.SET_NULL, to='naming.JobMetadata')),
                ('policy', models.ForeignKey(help_text='Microsoft Active Directory Policy', null=True, on_delete=django.db.models.deletion.SET_NULL, to='microsoft_active_directory.MicrosoftADPolicy')),
                ('workspace', models.ForeignKey(help_text='Workspace URL', on_delete=django.db.models.deletion.PROTECT, to='accounts.Group')),
            ],
            options={
                'verbose_name_plural': 'Active Directory Computer Job Parameters',
                'db_table': 'microsoft_ad_computer_job_parameters',
                'ordering': ['id'],
                'abstract': False,
            },
            bases=('jobs.jobparameters', models.Model, driven_apps.common.mixins.RoleBasedHalFilteringMixin),
        ),
        migrations.CreateModel(
            name='MicrosoftADComputerAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=256)),
                ('job_metadata', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='naming.JobMetadata')),
                ('policy', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='microsoft_active_directory.MicrosoftADPolicy')),
                ('workspace', models.ForeignKey(help_text='Workspace URL', on_delete=django.db.models.deletion.PROTECT, to='accounts.Group')),
            ],
            options={
                'verbose_name_plural': 'Microsoft Active Directory Computer Names',
                'db_table': 'microsoft_active_directory_computer_names',
                'ordering': ['-id'],
                'abstract': False,
            },
            bases=(models.Model, driven_apps.common.mixins.RoleBasedHalFilteringMixin),
        ),
    ]
