# Generated by Django 2.2.10 on 2020-08-11 05:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_active_directory', '0003_microsoftactivedirectorycomputername_squashed_0006_merge_20200807_1851'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='microsoftadcomputeraccount',
            options={'ordering': ['-id'], 'verbose_name_plural': 'Microsoft Active Directory Computer Accounts'},
        ),
        migrations.AlterModelTable(
            name='microsoftadcomputeraccount',
            table='microsoft_active_directory_computer_accounts',
        ),
    ]
