# Generated by Django 2.2.10 on 2020-08-13 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_active_directory', '0004_auto_20200811_0526'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoftadpolicy',
            name='create_organizational_unit',
            field=models.BooleanField(default=False),
        ),
    ]
