# Generated by Django 2.2.10 on 2020-08-13 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_active_directory', '0006_microsoftadpolicy_remove_organizational_unit'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoftadpolicy',
            name='_security_groups',
            field=models.TextField(default='{}'),
        ),
    ]
