# Generated by Django 2.2.10 on 2020-08-18 18:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_active_directory', '0007_microsoftadpolicy__security_groups'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsoftadcomputeraccount',
            name='policy',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='microsoft_active_directory.MicrosoftADPolicy'),
        ),
    ]
