# Generated by Django 2.2.10 on 2020-08-20 00:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_active_directory', '0008_auto_20200818_1825'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsoftadpolicy',
            name='_security_groups',
            field=models.TextField(default='[]'),
        ),
    ]
