# Generated by Django 2.2.10 on 2020-08-24 17:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_active_directory', '0009_auto_20200820_0041'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoftadpolicy',
            name='build_ou',
            field=models.CharField(default='', max_length=1024, verbose_name='Build Organizational Unit'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='microsoftadpolicy',
            name='create_build_ou',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='microsoftadpolicy',
            name='remove_build_ou',
            field=models.BooleanField(default=False),
        ),
    ]
