# Generated by Django 2.2.10 on 2020-08-27 18:57

import common.fields
from django.db import migrations
import driven_apps.common.validators


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_active_directory', '0010_auto_20200824_1723'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsoftadpolicy',
            name='build_ou',
            field=common.fields.TemplatableField(max_length=65536, verbose_name='Build Organizational Unit'),
        ),
        migrations.AlterField(
            model_name='microsoftadpolicy',
            name='ou',
            field=common.fields.TemplatableField(max_length=65536, validators=[driven_apps.common.validators.NotBlankValidator(field_name='ou', required=True)], verbose_name='Organizational Unit'),
        ),
    ]
