# Generated by Django 2.2.10 on 2020-08-28 19:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_active_directory', '0011_microsoftadpolicy_delete_computer_accounts_by_name'),
        ('microsoft_active_directory', '0011_auto_20200827_1857'),
    ]

    operations = [
    ]
