# Generated by Django 2.2.10 on 2020-08-31 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_active_directory', '0012_merge_20200828_1953'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsoftadpolicy',
            name='delete_computer_accounts_by_name',
            field=models.BooleanField(default=False),
        ),
    ]
