# Generated by Django 2.2.10 on 2020-09-01 23:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_active_directory', '0012_microsoftadcomputeraccount_state'),
        ('microsoft_active_directory', '0013_auto_20200831_2117'),
    ]

    operations = [
    ]
