# Generated by Django 2.2.10 on 2020-09-04 18:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_active_directory', '0014_merge_20200901_2319'),
    ]

    operations = [
        migrations.AlterField(
            model_name='microsoftadpolicy',
            name='delete_computer_accounts_by_name',
            field=models.BooleanField(default=True),
        ),
    ]
