# Generated by Django 2.2.10 on 2020-09-11 22:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_active_directory', '0015_auto_20200904_1819'),
    ]

    operations = [
        migrations.RenameField(
            model_name='microsoftadcomputerjobparameters',
            old_name='template_properties',
            new_name='script_template',
        ),
    ]
