# Generated by Django 2.2.10 on 2020-09-15 20:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('microsoft_active_directory', '0016_auto_20200911_2251'),
    ]

    operations = [
        migrations.AddField(
            model_name='microsoftadcomputeraccount',
            name='_security_groups',
            field=models.TextField(default='[]'),
        ),
        migrations.AddField(
            model_name='microsoftadcomputeraccount',
            name='build_ou',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
        migrations.AddField(
            model_name='microsoftadcomputeraccount',
            name='final_ou',
            field=models.CharField(blank=True, default='', max_length=1024),
        ),
        migrations.AddField(
            model_name='microsoftadcomputerjobparameters',
            name='computer_account_data',
            field=models.TextField(default='{}'),
        ),
    ]
