# Generated by Django 2.2.16 on 2020-11-20 07:10

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0046_auto_20201017_0204'),
        ('microsoft_active_directory', '0017_auto_20200915_2035'),
    ]

    operations = [
        migrations.DeleteModel(
            name='MicrosoftADComputerJobParameters',
        ),
    ]
