# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-30 20:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hyperv', '0011_auto_20190102_1747'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hypervresourcehandler',
            name='images_dir',
            field=models.CharField(default='C:\\\\exports', help_text='Directory on the Hyper-V server where VM images are stored.', max_length=1024, verbose_name='Images Directory'),
        ),
    ]
