# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-18 19:42
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('azure_arm', '0015_auto_20170619_2221'),
    ]

    operations = [
        migrations.CreateModel(
            name='AzureStackHandler',
            fields=[
                ('azurearmhandler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='azure_arm.AzureARMHandler')),
                ('resource_manager_endpoint', models.CharField(max_length=1024)),
            ],
            options={
                'verbose_name': 'Azure Stack resource handler',
            },
            bases=('azure_arm.azurearmhandler',),
        ),
    ]
