# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-22 15:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azure_stack', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='azurestackhandler',
            old_name='resource_manager_endpoint',
            new_name='metadata_endpoint',
        ),
    ]
