# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 15:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0014_remove_customfield_hide_single_value'),
        ('libcloudhandler', '0002_libcloudimage_total_disk_size'),
    ]

    operations = [
        migrations.AddField(
            model_name='libcloudserverinfo',
            name='snapshots',
            field=models.ManyToManyField(blank=True, to='infrastructure.ServerSnapshot'),
        ),
    ]
