# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-31 19:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0005_azurearmextension'),
    ]

    operations = [
        migrations.AddField(
            model_name='azurearmserverinfo',
            name='storage_account',
            field=models.CharField(blank=True, max_length=1024),
        ),
    ]
