# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-11 22:32
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0008_auto_20170417_2256'),
    ]

    operations = [
        migrations.CreateModel(
            name='ARMResourceGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('region', models.CharField(max_length=1024)),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azure_arm.AzureARMHandler')),
            ],
            options={
                'verbose_name': 'Azure Resource Group',
            },
        ),
        migrations.CreateModel(
            name='ARMStorageAccount',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=1024)),
                ('region', models.CharField(max_length=1024)),
                ('handler', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='azure_arm.AzureARMHandler')),
            ],
            options={
                'verbose_name': 'Azure Storage Account',
            },
        ),
    ]
