# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 00:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0014_remove_customfield_hide_single_value'),
        ('azure_arm', '0009_armresourcegroup_armstorageaccount'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='armresourcegroup',
            name='region',
        ),
        migrations.RemoveField(
            model_name='armstorageaccount',
            name='region',
        ),
        migrations.AddField(
            model_name='armresourcegroup',
            name='environment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.Environment'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='armstorageaccount',
            name='environment',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='infrastructure.Environment'),
            preserve_default=False,
        ),
    ]
