# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0010_auto_20170512_0040'),
    ]

    operations = [
        migrations.AddField(
            model_name='armresourcegroup',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='armstorageaccount',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
