# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-12 18:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0011_auto_20170512_1556'),
    ]

    operations = [
        migrations.AddField(
            model_name='armstorageaccount',
            name='resource_group',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='azure_arm.ARMResourceGroup'),
        ),
    ]
