# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-10 00:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0012_armstorageaccount_resource_group'),
    ]

    operations = [
        migrations.AlterField(
            model_name='armresourcegroup',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable or disable this resource in CloudBolt'),
        ),
        migrations.AlterField(
            model_name='armstorageaccount',
            name='is_active',
            field=models.BooleanField(default=True, help_text='Enable or disable this resource in CloudBolt'),
        ),
    ]
