# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 22:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0013_auto_20170610_0044'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='azurearmservernetworkcard',
            options={'verbose_name': 'Azure Resource Manager NIC'},
        ),
    ]
