# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-19 22:21
from __future__ import unicode_literals

from django.db import migrations


def update_arm_restech(apps, schema_editor):
    """
    The ARM restech has been renamed in cb_minimal, so any existing records need to be updated,
    else create_objects will create a new one and the old one will stick around.
    """
    ResourceTechnology = apps.get_model("resourcehandlers", "ResourceTechnology")
    ResourceTechnology.objects.filter(name="Azure ARM").update(name="Azure Resource Manager")


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0014_auto_20170619_2221'),
    ]

    operations = [
        migrations.RunPython(update_arm_restech),
    ]
