# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-08-16 14:44
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0015_auto_20170619_2221'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='armresourcegroup',
            options={'ordering': ['name'], 'verbose_name': 'Azure Resource Group'},
        ),
        migrations.AlterModelOptions(
            name='armstorageaccount',
            options={'ordering': ['name'], 'verbose_name': 'Azure Storage Account'},
        ),
    ]
