# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-11 13:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0017_auto_20170908_1848'),
    ]

    operations = [
        migrations.AddField(
            model_name='azurearmhandler',
            name='cloud_environment',
            field=models.CharField(choices=[('PUBLIC', 'Public (Default)'), ('GERMAN', 'Germany'), ('CHINA', 'China'), ('US_GOV', 'US Gov')], default='PUBLIC', max_length=128),
        ),
    ]
