# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-22 19:53
from __future__ import unicode_literals

from django.db import migrations


def rename_azure_arm(apps, schema_editor):
    """
    Renames the 'Azure Resource Manager' Resource Technology to 'Azure'
    by looking up it's module.
    """
    ResourceTechnology = apps.get_model('resourcehandlers', 'ResourceTechnology')

    ResourceTechnology.objects.filter(
        modulename='resourcehandlers.azure_arm.azure_wrapper'
    ).update(
        name='Azure'
    )


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0018_azurearmhandler_cloud_environment'),
    ]

    operations = [
        migrations.RunPython(
            rename_azure_arm,
            migrations.RunPython.noop
        )
    ]
