# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-27 18:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0019_rename_azure_arm_20180222_1953'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='azurearmservernetworkcard',
            options={'verbose_name': 'Azure NIC'},
        ),
    ]
