# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-20 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0020_auto_20180227_1824'),
    ]

    operations = [
        migrations.AddField(
            model_name='azurearmavailableimage',
            name='blob_uri',
            field=models.CharField(blank=True, max_length=1028),
        ),
        migrations.AddField(
            model_name='azurearmavailableimage',
            name='resource_group',
            field=models.CharField(blank=True, max_length=255),
        ),
        migrations.AddField(
            model_name='azurearmimage',
            name='blob_uri',
            field=models.CharField(blank=True, max_length=1028),
        ),
        migrations.AddField(
            model_name='azurearmimage',
            name='resource_group',
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
