# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-13 18:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0021_auto_20180320_1948'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azurearmavailableimage',
            name='blob_uri',
            field=models.CharField(blank=True, default='', max_length=1028),
        ),
        migrations.AlterField(
            model_name='azurearmavailableimage',
            name='resource_group',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='azurearmimage',
            name='blob_uri',
            field=models.CharField(blank=True, default='', max_length=1028),
        ),
        migrations.AlterField(
            model_name='azurearmimage',
            name='resource_group',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
