# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-27 19:25
from __future__ import unicode_literals

from django.db import migrations

def set_default(apps, schema_editor):
    """
    Checks if there are any azure ARM images. If not, sets the default value for the action input
    on the 'Fetch and Cache Available Images' action to True. (setting the CFV value to True)
    :return:
    """
    AzureARMImage = apps.get_model('azure_arm', 'AzureARMImage')
    HookPointAction = apps.get_model('cbhooks', 'HookPointAction')
    CustomFieldValue = apps.get_model('orders', 'CustomFieldValue')
    RunHookInputMapping = apps.get_model('cbhooks', 'RunHookInputMapping')

    # if the user has no images, then we will use the whitelist
    if AzureARMImage.objects.count() == 0:
        # get the default value for use_whitelist (which is a CFV object) and set the default to True
        action = HookPointAction.objects.filter(name='Fetch and Cache available Azure images').first()
        if action:
            old_mapping = action.input_mappings.filter(hook_input__name__icontains='use_whitelist').first()
            if old_mapping and old_mapping.default_value.boolean_value is False:
                new_value, created = CustomFieldValue.objects.get_or_create(
                    field=old_mapping.default_value.field,
                    boolean_value=True
                )
                new_mapping = RunHookInputMapping.objects.create(
                    hook_input=old_mapping.hook_input,
                    default_value=new_value
                )
                action.input_mappings.add(new_mapping)
                action.input_mappings.remove(old_mapping)
    # else, the user has images and the use of a whitelist would delete existing images that are not in the whitelist,
    # since we wouldn't have a way to check that those images in CB still exist in Azure, so we will keep the default
    # as False (which is already set by cb_minimal)


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0022_auto_20180413_1815'),
    ]

    operations = [
        migrations.RunPython(set_default,
                             migrations.RunPython.noop),
    ]
