# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-30 19:21
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0023_set_use_whitelist_default_value_20180427_1925'),
        ('azure_arm', '0023_set_up_managed_disks_ux'),
    ]

    operations = [
    ]
