# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-08 20:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0026_auto_20180503_1800'),
    ]

    operations = [
        migrations.AddField(
            model_name='azurearmimage',
            name='region',
            field=models.CharField(default='', max_length=255),
        ),
    ]
