# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-16 00:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0025_set_up_storage_account_type'),
        ('azure_arm', '0026_auto_20180503_1800'),
    ]

    operations = [
    ]
