# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-17 23:34
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0028_auto_20180508_2025'),
        ('azure_arm', '0027_merge_20180516_0029'),
    ]

    operations = [
    ]
