# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-23 13:58
from __future__ import unicode_literals

from django.db import migrations


def remove_duplicate_mapping(apps, schema_editor):
    """
    Checks if there are any azure ARM images. If not, sets the default value for the action input
    on the 'Fetch and Cache Available Images' action to True. (setting the CFV value to True)
    :return:
    """
    AzureARMAvailableImage = apps.get_model('azure_arm', 'AzureARMAvailableImage')
    HookPointAction = apps.get_model('cbhooks', 'HookPointAction')

    action = HookPointAction.objects.filter(name='Fetch and Cache available Azure images').first()
    if not action:
        return

    mappings = action.input_mappings.filter(hook_input__name__icontains='use_whitelist')
    if mappings and mappings.count() > 1:
        if AzureARMAvailableImage.objects.exists():
            # in this case, the user already has fetched cached images and we should not use a whitelist so they don't
            # lose any images. Remove the True mapping.
            true_mapping = mappings.filter(
                default_value__boolean_value=True).first()
            if true_mapping:
                true_mapping.delete()
        else:
            # remove the False mapping
            false_mapping = mappings.filter(
                default_value__boolean_value=False).first()
            if false_mapping:
                false_mapping.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0029_merge_20180517_2334'),
    ]

    operations = [
        migrations.RunPython(remove_duplicate_mapping,
                             migrations.RunPython.noop),
    ]
