# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-23 16:26
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0030_remove_dup_input_mappings_for_use_whitelist_20180523_1358'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azurearmsubnet',
            name='parent_network',
            field=models.CharField(max_length=256),
        ),
    ]
