# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-22 00:10
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0031_auto_20180523_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='azurearmserverinfo',
            name='availability_set',
            field=models.CharField(blank=True, max_length=1024, null=True),
        ),
    ]
