# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-25 18:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0031_auto_20180523_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='azurearmavailableimage',
            name='image_id',
            field=models.CharField(blank=True, default='', max_length=1028),
        ),
        migrations.AddField(
            model_name='azurearmimage',
            name='image_id',
            field=models.CharField(blank=True, default='', max_length=1028),
        ),
    ]
