# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-06-06 21:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0031_auto_20180523_1626'),
    ]

    operations = [
        migrations.AddField(
            model_name='azurearmhandler',
            name='auth_type',
            field=models.CharField(choices=[('SERVICE', 'Service Principal'), ('ADAL', 'Active Directory')], default='SERVICE', max_length=128),
        ),
    ]
