# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-03 18:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0032_auto_20180625_1812'),
        ('azure_arm', '0032_azurearmserverinfo_availability_set'),
    ]

    operations = [
    ]
