# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-07-06 20:25
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0033_merge_20180703_1811'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azurearmimage',
            name='offer',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='azurearmimage',
            name='publisher',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='azurearmimage',
            name='sku',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
        migrations.AlterField(
            model_name='azurearmimage',
            name='version',
            field=models.CharField(blank=True, default='', max_length=255),
        ),
    ]
