# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-14 20:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0032_azurearmhandler_auth_type'),
        ('azure_arm', '0034_auto_20180706_2025'),
    ]

    operations = [
    ]
