# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-11-29 18:29
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0036_azurearmdisk_host_caching'),
    ]

    operations = [
        migrations.AddField(
            model_name='azurearmavailableimage',
            name='resource_handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='available_images', to='azure_arm.AzureARMHandler'),
        ),
    ]
