# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-12-01 01:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0037_azurearmavailableimage_resource_handler'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azurearmavailableimage',
            name='resource_handler',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='azure_arm.AzureARMHandler'),
        ),
    ]
