# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-02 17:47
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0038_auto_20181201_0126'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='azurearmhandler',
            name='old_os_build_attributes',
        ),
        migrations.RemoveField(
            model_name='azurearmimage',
            name='old_template_name',
        ),
    ]
