# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-01 15:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0039_auto_20190102_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='azurearmserverinfo',
            name='node_size',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
