# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-09 13:43
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0040_azurearmserverinfo_node_size'),
        ('azure_arm', '0041_auto_20190703_2326'),
    ]

    operations = [
    ]
