# Generated by Django 2.2.10 on 2020-04-29 23:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0046_auto_20200211_1928'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azurearmhandler',
            name='networks',
            field=models.ManyToManyField(blank=True, related_name='resource_handlers', to='azure_arm.AzureARMSubnet'),
        ),
    ]
