# Generated by Django 2.2.12 on 2020-06-30 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0048_auto_20200629_2223'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azurearmavailableimage',
            name='os_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='azurearmimage',
            name='os_type',
            field=models.CharField(blank=True, default='', max_length=255, null=True),
        ),
    ]
