# Generated by Django 2.2.12 on 2020-09-01 14:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0050_update_arm_shared_images_20200707_2050'),
    ]

    operations = [
        migrations.AlterField(
            model_name='azurearmimage',
            name='location_availability',
            field=models.CharField(max_length=1024),
        ),
    ]
