# Generated by Django 2.2.16 on 2021-02-19 14:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('azure_arm', '0051_auto_20200901_1448'),
    ]

    operations = [
        migrations.RenameField(
            model_name='azurearmhandler',
            old_name='tenant_id',
            new_name='azure_tenant_id',
        ),
    ]
