# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-08-06 18:12
from __future__ import unicode_literals

import cb_secrets.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0002_gcpnetwork_project'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcpproject',
            name='billing_account_key',
            field=cb_secrets.fields.EncryptedTextField(blank=True, null=True, verbose_name='BigQuery Billing Export Service Account Key JSON'),
        ),
        migrations.AddField(
            model_name='gcpproject',
            name='billing_table_name',
            field=models.CharField(blank=True, max_length=250, null=True),
        ),
    ]
