# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-07 00:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0003_auto_20190806_1812'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gcpnetwork',
            name='project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='networks', to='gcp.GCPProject'),
        ),
        migrations.AlterField(
            model_name='gcpproject',
            name='handler',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcp_projects', to='gcp.GCPHandler'),
        ),
        migrations.AlterField(
            model_name='gcpserverinfo',
            name='gcp_project',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='servers', to='gcp.GCPProject'),
        ),
        migrations.AlterField(
            model_name='gcpsubnetwork',
            name='parent_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='subnetworks', to='gcp.GCPNetwork'),
        ),
    ]
