# Generated by Django 2.2.10 on 2020-01-27 16:55

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0004_auto_20191107_0049'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcpsubnetwork',
            name='service_projects',
            field=models.ManyToManyField(related_name='usable_subnets', to='gcp.GCPProject'),
        ),
        migrations.AlterField(
            model_name='gcpsubnetwork',
            name='parent_network',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='subnetworks', to='gcp.GCPNetwork'),
        ),
    ]
