# Generated by Django 2.2.10 on 2020-03-03 22:50

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0006_auto_20200219_2248'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gcpproject',
            old_name='service_account_key',
            new_name='service_account_info',
        ),
        migrations.RemoveField(
            model_name='gcpproject',
            name='service_account_email',
        ),
    ]
