# Generated by Django 2.2.16 on 2020-12-09 10:58

import common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0007_auto_20200303_2250'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcphandler',
            name='global_id',
            field=models.CharField(default=common.mixins.get_global_id_chars, help_text='Identifier that can be used to access this object through the API across instances.', max_length=16, verbose_name='Global ID'),
        ),
    ]
