# Generated by Django 2.2.16 on 2020-12-10 08:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0009_set_global_id_for_gcphandler'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='gcphandler',
            options={'verbose_name': 'GCP Resource Handler', 'verbose_name_plural': "GCP Resource Handler's"},
        ),
        migrations.AddField(
            model_name='gcphandler',
            name='service_account_info',
            field=models.TextField(blank=True, null=True),
        ),
    ]
