# Generated by Django 2.2.16 on 2021-02-09 12:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0010_gcphandler_service_account_info'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gcphandler',
            name='global_id',
        ),
    ]
