# Generated by Django 3.2.3 on 2021-06-22 14:02

from django.db import migrations


class Migration(migrations.Migration):
    def set_network_for_shared_vpc(apps, schema_editor):
        """
        We need to maintain the original name of the GCP Network for shared VPC's since customers have the ability to
        update the name field of a GCPNetwork through the CloudBolt UI. This migration is part of a fix for
        Bug: https://cloudbolt.atlassian.net/browse/DEV-18839
        """
        GCPSubnetwork = apps.get_model('gcp', 'GCPSubnetwork')

        parent_networks = set()
        for vpc_subnet in GCPSubnetwork.objects.filter(service_projects__isnull=False).all():
            if not vpc_subnet.network:
                vpc_subnet.network = vpc_subnet.parent_network.name
                vpc_subnet.save()

            parent_networks.add(vpc_subnet.parent_network)

        for parent_network in parent_networks:
            if not parent_network.network:
                parent_network.network = parent_network.name
                parent_network.save()

    dependencies = [
        ('gcp', '0011_gcphandler_remove_global_id'),
    ]

    operations = [
        migrations.RunPython(set_network_for_shared_vpc, migrations.RunPython.noop),
    ]
