# Generated by Django 3.2.3 on 2021-07-16 22:03

import cb_secrets.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0012_gcpnetwork_set_network_for_sharedvpc'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcphandler',
            name='gcp_api_credentials',
            field=cb_secrets.fields.EncryptedTextField(blank=True, null=True, verbose_name='Credentials returned from OAuth for the GCP API'),
        ),
    ]
