# Generated by Django 3.2.3 on 2021-07-20 18:52

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libcloudhandler', '0006_remove_libcloudimage_old_template_name'),
        ('gcp', '0013_gcphandler_gcp_api_credentials'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCPImage',
            fields=[
                ('libcloudimage_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='libcloudhandler.libcloudimage')),
                ('self_link', models.CharField(blank=True, max_length=256, null=True)),
            ],
            options={
                'abstract': False,
            },
            bases=('libcloudhandler.libcloudimage',),
        ),
    ]
