# Generated by Django 3.2.3 on 2021-08-03 00:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0013_gcpserverinfo_tags_json'),
        ('gcp', '0014_gcpimage'),
    ]

    operations = [
    ]
