# Generated by Django 3.2.3 on 2021-08-10 00:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0059_replace_global_key_name_with_key_name_20210630_1352'),
        ('gcp', '0015_merge_0013_gcpserverinfo_tags_json_0014_gcpimage'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCPDisk',
            fields=[
                ('disk_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infrastructure.disk')),
                ('disk_type', models.CharField(default='', max_length=124, verbose_name='GCP Disk Type')),
            ],
            options={
                'abstract': False,
            },
            bases=('infrastructure.disk',),
        ),
    ]
