# Generated by Django 3.2.3 on 2021-08-04 19:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0015_merge_0013_gcpserverinfo_tags_json_0014_gcpimage'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcpproject',
            name='gcp_id',
            field=models.CharField(max_length=50, null=True),
        ),
    ]
