# Generated by Django 3.2.3 on 2021-08-10 17:38

from django.db import migrations


class Migration(migrations.Migration):
    def gcpdisks_from_disks(apps, schema_editor):
        """
        For each Disk associated with a GCP Server, convert it to the new GCPDisk submodel
        (let the new field default for now; will be updated on next sync)
        """
        GCPHandler = apps.get_model("gcp", "GCPHandler")
        GCPDisk = apps.get_model("gcp", "GCPDisk")
        ContentType = apps.get_model('contenttypes', 'ContentType')
        gcpdisk_ct = ContentType.objects.get_for_model(GCPDisk)

        for handler in GCPHandler.objects.all():
            for server in handler.server_set.all():
                for disk in server.disks.all():
                    new_gcpdisk = GCPDisk(disk_ptr_id=disk.id)
                    new_gcpdisk.__dict__.update(disk.__dict__)
                    new_gcpdisk.real_type = gcpdisk_ct
                    new_gcpdisk.save()

    dependencies = [
        ('gcp', '0016_gcpdisk'),
    ]

    operations = [
        migrations.RunPython(gcpdisks_from_disks, migrations.RunPython.noop),
    ]
