# Generated by Django 3.2.3 on 2021-08-05 20:59
# Created by deleting our custom id field definition from the GCPProject model.
# This migration also changes the field type for any foreign ids in other model tables
# or other m2m ids, so it may take a while.

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gcp", "0017_gcpproject_data_copy_id_to_gcp_id"),
    ]

    # Remove the explicit id field from the model definition, which makes Django
    # create the magic id field definition on it.
    # migrations.AlterField(
    #     model_name="gcpproject",
    #     name="id",
    #     field=models.AutoField(
    #         auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
    #     ),
    # ),


    ## The above django migration was causing an error on certain sets of data. When converting the key columns from Strings to Integers, any
    ## values set as None are converted to 0.  When Django tries to re-setup the FK constraint (now using the integer), it fails because it cannot find
    ## PK record with id=0.  To solve this, we need set the 0 values to NULL.  Below are the SQL statements generated by [./manage.py sqlmigrate] command
    ## with 2 additional statements noted by the comments.

    if "postgresql" in settings.DATABASES["default"]["ENGINE"]:
        operations = [
            migrations.RunSQL(
                sql=['ALTER TABLE gcp_gcpnetwork DROP CONSTRAINT gcp_gcpnetwork_project_id_50a56b91_fk_gcp_gcpproject_id;'],
                reverse_sql=["""
                    ALTER TABLE gcp_gcpnetwork ADD
                    CONSTRAINT gcp_gcpnetwork_project_id_50a56b91_fk_gcp_gcpproject_id
                    FOREIGN KEY (project_id) REFERENCES gcp_gcpproject (id);
                """],
            ),

            migrations.RunSQL(
                sql=['ALTER TABLE gcp_gcpproject_groups DROP CONSTRAINT gcp_gcpproject_group_gcpproject_id_58335e28_fk_gcp_gcppr;'],
                reverse_sql=["""
                    ALTER TABLE gcp_gcpproject_groups ADD
                    CONSTRAINT gcp_gcpproject_group_gcpproject_id_58335e28_fk_gcp_gcppr
                    FOREIGN KEY (gcpproject_id) REFERENCES gcp_gcpproject (id);
                """],
            ),

            migrations.RunSQL(
                sql=['ALTER TABLE gcp_gcpserverinfo DROP CONSTRAINT gcp_gcpserverinfo_gcp_project_id_518e0408_fk_gcp_gcpproject_id;'],
                reverse_sql=["""
                    ALTER TABLE gcp_gcpserverinfo ADD
                    CONSTRAINT gcp_gcpserverinfo_gcp_project_id_518e0408_fk_gcp_gcpproject_id
                    FOREIGN KEY (gcp_project_id) REFERENCES gcp_gcpproject (id);
                """],
            ),

            migrations.RunSQL(
                sql=['ALTER TABLE gcp_gcpsubnetwork_service_projects DROP CONSTRAINT gcp_gcpsubnetwork_se_gcpproject_id_37ff6e5a_fk_gcp_gcppr;'],
                reverse_sql=["""
                    ALTER TABLE gcp_gcpsubnetwork_service_projects ADD
                    CONSTRAINT gcp_gcpsubnetwork_se_gcpproject_id_37ff6e5a_fk_gcp_gcppr
                    FOREIGN KEY (gcpproject_id) REFERENCES gcp_gcpproject (id);
                """],
            ),

            migrations.RunSQL(
                sql=['ALTER TABLE costs_gcpbillingsummary DROP CONSTRAINT costs_gcpbillingsumm_project_id_fe20b886_fk_gcp_gcppr;'],
                reverse_sql=["""
                    ALTER TABLE costs_gcpbillingsummary ADD
                    CONSTRAINT costs_gcpbillingsumm_project_id_fe20b886_fk_gcp_gcppr
                    FOREIGN KEY (project_id) REFERENCES gcp_gcpproject (id);
                """],
            ),

            migrations.RunSQL(
                sql=[
                    "DROP INDEX gcp_gcpproject_id_4e60299b_like;"
                    "ALTER TABLE gcp_gcpproject ALTER COLUMN id TYPE integer USING (id::integer);",
                    "CREATE SEQUENCE gcp_gcpproject_id_seq OWNED BY gcp_gcpproject.id;",
                    "ALTER TABLE gcp_gcpproject ALTER COLUMN id SET DEFAULT nextval('gcp_gcpproject_id_seq');",
                ],
                reverse_sql=[
                    "DROP SEQUENCE gcp_gcpproject_id_seq CASCADE;",
                    "ALTER TABLE gcp_gcpproject ALTER COLUMN id TYPE varchar(50);",
                    "CREATE INDEX gcp_gcpproject_id_4e60299b_like ON public.gcp_gcpproject USING btree (id varchar_pattern_ops);",
                ],
                state_operations=[
                    migrations.AlterField(
                        model_name="gcpproject",
                        name="id",
                        field=models.AutoField(
                            auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                        ),
                    )
                ]
            ),

            migrations.RunSQL(
                sql=[
                    "DROP INDEX gcp_gcpnetwork_project_id_50a56b91_like;",
                    "ALTER TABLE gcp_gcpnetwork ALTER COLUMN project_id TYPE integer USING (project_id::integer);",
                ],
                reverse_sql=[
                    "ALTER TABLE gcp_gcpnetwork ALTER COLUMN project_id TYPE varchar(50);",
                    "CREATE INDEX gcp_gcpnetwork_project_id_50a56b91_like ON public.gcp_gcpnetwork USING btree (project_id varchar_pattern_ops);",
                ],
            ),

            migrations.RunSQL(
                sql=[
                    "DROP INDEX gcp_gcpproject_groups_gcpproject_id_58335e28_like;",
                    "ALTER TABLE gcp_gcpproject_groups ALTER COLUMN gcpproject_id TYPE integer USING (gcpproject_id::integer);",
                ],
                reverse_sql=[
                    "ALTER TABLE gcp_gcpproject_groups ALTER COLUMN gcpproject_id TYPE varchar(50);",
                    "CREATE INDEX gcp_gcpproject_groups_gcpproject_id_58335e28_like ON public.gcp_gcpproject_groups USING btree (gcpproject_id varchar_pattern_ops);",
                ],
            ),

            migrations.RunSQL(
                sql=[
                    "DROP INDEX gcp_gcpserverinfo_gcp_project_id_518e0408_like;",
                    "ALTER TABLE gcp_gcpserverinfo ALTER COLUMN gcp_project_id TYPE integer USING (gcp_project_id::integer);",
                ],
                reverse_sql=[
                    "ALTER TABLE gcp_gcpserverinfo ALTER COLUMN gcp_project_id TYPE varchar(50);",
                    "CREATE INDEX gcp_gcpserverinfo_gcp_project_id_518e0408_like ON public.gcp_gcpserverinfo USING btree (gcp_project_id varchar_pattern_ops);",
                ],
            ),

            migrations.RunSQL(
                sql=[
                    "DROP INDEX gcp_gcpsubnetwork_service_projects_gcpproject_id_37ff6e5a_like;",
                    "ALTER TABLE gcp_gcpsubnetwork_service_projects ALTER COLUMN gcpproject_id TYPE integer USING (gcpproject_id::integer);",
                ],
                reverse_sql=[
                    "ALTER TABLE gcp_gcpsubnetwork_service_projects ALTER COLUMN gcpproject_id TYPE varchar(50);",
                    "CREATE INDEX gcp_gcpsubnetwork_service_projects_gcpproject_id_37ff6e5a_like ON public.gcp_gcpsubnetwork_service_projects USING btree (gcpproject_id varchar_pattern_ops);",
                ]
            ),

            migrations.RunSQL(
                sql=[
                    "DROP INDEX costs_gcpbillingsummary_project_id_fe20b886_like;",
                    "ALTER TABLE costs_gcpbillingsummary ALTER COLUMN project_id TYPE integer USING (project_id::integer);",
                    "ALTER TABLE costs_gcpbillingsummary ALTER COLUMN project_id DROP NOT NULL;",
                ],
                reverse_sql=[
                    "ALTER TABLE costs_gcpbillingsummary ALTER COLUMN project_id TYPE varchar(50)",
                    "CREATE INDEX costs_gcpbillingsummary_project_id_fe20b886_like ON public.costs_gcpbillingsummary USING btree (project_id varchar_pattern_ops);",
                ]
            ),

            # This RunSQL command fixes a casting issue, where string None is cast to int 0.  This command sets those 0 values to NULL
            migrations.RunSQL(
                sql=['UPDATE gcp_gcpnetwork SET project_id = NULL WHERE project_id = 0;'],
                reverse_sql=["UPDATE gcp_gcpnetwork SET project_id = 0 WHERE project_id IS NULL;"],
            ),

            # This RunSQL command fixes a casting issue, where string None is cast to int 0.  This command sets those 0 values to NULL
            migrations.RunSQL(
                sql=['UPDATE gcp_gcpserverinfo SET gcp_project_id = NULL WHERE gcp_project_id = 0;'],
                reverse_sql=["UPDATE gcp_gcpserverinfo SET gcp_project_id = 0 WHERE gcp_project_id IS NULL;"],
            ),

            migrations.RunSQL(
                sql=['ALTER TABLE gcp_gcpnetwork ADD CONSTRAINT gcp_gcpnetwork_project_id_50a56b91_fk FOREIGN KEY (project_id) REFERENCES gcp_gcpproject (id);'],
                reverse_sql=['ALTER TABLE gcp_gcpnetwork DROP CONSTRAINT gcp_gcpnetwork_project_id_50a56b91_fk'],
            ),

            migrations.RunSQL(
                sql=['ALTER TABLE gcp_gcpserverinfo ADD CONSTRAINT gcp_gcpserverinfo_gcp_project_id_518e0408_fk FOREIGN KEY (gcp_project_id) REFERENCES gcp_gcpproject (id);'],
                reverse_sql=['ALTER TABLE gcp_gcpserverinfo DROP CONSTRAINT gcp_gcpserverinfo_gcp_project_id_518e0408_fk']
            ),

            migrations.RunSQL(
                sql=['ALTER TABLE costs_gcpbillingsummary ADD CONSTRAINT costs_gcpbillingsumm_project_id_fe20b886_fk_gcp_gcppr FOREIGN KEY (project_id) REFERENCES gcp_gcpproject (id);'],
                reverse_sql=['ALTER TABLE costs_gcpbillingsummary DROP CONSTRAINT costs_gcpbillingsumm_project_id_fe20b886_fk_gcp_gcppr']
            ),

            # Make gcp_id non-nullable
            migrations.AlterField(
                model_name="gcpproject",
                name="gcp_id",
                field=models.CharField(max_length=50),
            ),
        ]
    else:
        operations = [
            migrations.RunSQL(
                sql=['ALTER TABLE gcp_gcpnetwork DROP FOREIGN KEY gcp_gcpnetwork_project_id_50a56b91_fk_gcp_gcpproject_id;'],
                reverse_sql=["""
                    ALTER TABLE gcp_gcpnetwork ADD
                    CONSTRAINT gcp_gcpnetwork_project_id_50a56b91_fk_gcp_gcpproject_id
                    FOREIGN KEY (project_id) REFERENCES gcp_gcpproject (id);
                """],
            ),

            migrations.RunSQL(
                sql=['ALTER TABLE gcp_gcpproject_groups DROP FOREIGN KEY gcp_gcpproject_group_gcpproject_id_58335e28_fk_gcp_gcppr;'],
                reverse_sql=["""
                    ALTER TABLE gcp_gcpproject_groups ADD
                    CONSTRAINT gcp_gcpproject_group_gcpproject_id_58335e28_fk_gcp_gcppr
                    FOREIGN KEY (gcpproject_id) REFERENCES gcp_gcpproject (id);
                """],
            ),

            migrations.RunSQL(
                sql=['ALTER TABLE gcp_gcpserverinfo DROP FOREIGN KEY gcp_gcpserverinfo_gcp_project_id_518e0408_fk_gcp_gcpproject_id;'],
                reverse_sql=["""
                    ALTER TABLE gcp_gcpserverinfo ADD
                    CONSTRAINT gcp_gcpserverinfo_gcp_project_id_518e0408_fk_gcp_gcpproject_id
                    FOREIGN KEY (gcp_project_id) REFERENCES gcp_gcpproject (id);
                """],
            ),

            migrations.RunSQL(
                sql=['ALTER TABLE gcp_gcpsubnetwork_service_projects DROP FOREIGN KEY gcp_gcpsubnetwork_se_gcpproject_id_37ff6e5a_fk_gcp_gcppr;'],
                reverse_sql= ["""
                    ALTER TABLE gcp_gcpsubnetwork_service_projects ADD
                    CONSTRAINT gcp_gcpsubnetwork_se_gcpproject_id_37ff6e5a_fk_gcp_gcppr
                    FOREIGN KEY (gcpproject_id) REFERENCES gcp_gcpproject (id);
                """],
            ),

            migrations.RunSQL(
                sql=['ALTER TABLE costs_gcpbillingsummary DROP FOREIGN KEY costs_gcpbillingsummary_project_id_fe20b886_fk_gcp_gcpproject_id;'],
                reverse_sql= ["""
                    ALTER TABLE costs_gcpbillingsummary ADD
                    CONSTRAINT costs_gcpbillingsummary_project_id_fe20b886_fk_gcp_gcpproject_id
                    FOREIGN KEY (project_id) REFERENCES gcp_gcpproject (id);
                """],
            ),

            migrations.RunSQL(
                sql=['ALTER TABLE gcp_gcpproject MODIFY id integer AUTO_INCREMENT NOT NULL;'],
                reverse_sql=['ALTER TABLE gcp_gcpproject MODIFY id varchar(50) NOT NULL;'],
                state_operations=[
                    migrations.AlterField(
                        model_name="gcpproject",
                        name="id",
                        field=models.AutoField(
                            auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                        ),
                    )
                ]
            ),

            migrations.RunSQL(
                sql=['ALTER TABLE gcp_gcpnetwork MODIFY project_id integer NULL;'],
                reverse_sql=['ALTER TABLE gcp_gcpnetwork MODIFY project_id varchar(50) NULL;'],
            ),

            migrations.RunSQL(
                sql=['ALTER TABLE gcp_gcpproject_groups MODIFY gcpproject_id integer NOT NULL;'],
                reverse_sql=['ALTER TABLE gcp_gcpproject_groups MODIFY gcpproject_id varchar(50) NOT NULL;'],
            ),

            migrations.RunSQL(
                sql=['ALTER TABLE gcp_gcpserverinfo MODIFY gcp_project_id integer NULL;'],
                reverse_sql=['ALTER TABLE gcp_gcpserverinfo MODIFY gcp_project_id varchar(50) NULL;'],
            ),

            migrations.RunSQL(
                sql=['ALTER TABLE gcp_gcpsubnetwork_service_projects MODIFY gcpproject_id integer NOT NULL;'],
                reverse_sql=['ALTER TABLE gcp_gcpsubnetwork_service_projects MODIFY gcpproject_id varchar(50) NOT NULL;'],
            ),

            migrations.RunSQL(
                sql=['ALTER TABLE costs_gcpbillingsummary MODIFY project_id integer NOT NULL;'],
                reverse_sql=['ALTER TABLE costs_gcpbillingsummary MODIFY project_id varchar(50) NOT NULL;'],
            ),

            # This RunSQL command fixes a casting issue, where string None is cast to int 0.  This command sets those 0 values to NULL
            migrations.RunSQL(
                sql=['UPDATE gcp_gcpnetwork SET project_id = NULL WHERE project_id = 0;'],
                reverse_sql=["UPDATE gcp_gcpnetwork SET project_id = 0 WHERE project_id = NULL;"],
            ),

            # This RunSQL command fixes a casting issue, where string None is cast to int 0.  This command sets those 0 values to NULL
            migrations.RunSQL(
                sql=['UPDATE gcp_gcpserverinfo SET gcp_project_id = NULL WHERE gcp_project_id = 0;'],
                reverse_sql=["UPDATE gcp_gcpserverinfo SET gcp_project_id = 0 WHERE gcp_project_id = NULL;"],
            ),

            migrations.RunSQL(
                sql=['ALTER TABLE gcp_gcpnetwork ADD CONSTRAINT gcp_gcpnetwork_project_id_50a56b91_fk FOREIGN KEY (project_id) REFERENCES gcp_gcpproject (id);'],
                reverse_sql=["""
                    ALTER TABLE gcp_gcpnetwork
                    DROP FOREIGN KEY gcp_gcpnetwork_project_id_50a56b91_fk,
                    DROP KEY gcp_gcpnetwork_project_id_50a56b91_fk;
                """]
            ),

            migrations.RunSQL(
                sql=['ALTER TABLE gcp_gcpserverinfo ADD CONSTRAINT gcp_gcpserverinfo_gcp_project_id_518e0408_fk FOREIGN KEY (gcp_project_id) REFERENCES gcp_gcpproject (id);'],
                reverse_sql=["""
                    ALTER TABLE gcp_gcpserverinfo
                    DROP FOREIGN KEY gcp_gcpserverinfo_gcp_project_id_518e0408_fk,
                    DROP KEY gcp_gcpserverinfo_gcp_project_id_518e0408_fk;
                """]
            ),

            migrations.RunSQL(
                sql=['ALTER TABLE costs_gcpbillingsummary ADD CONSTRAINT costs_gcpbillingsummary_project_id_fe20b886_fk_gcp_gcpproject_id FOREIGN KEY (project_id) REFERENCES gcp_gcpproject (id);'],
                reverse_sql=["""
                    ALTER TABLE costs_gcpbillingsummary
                    DROP FOREIGN KEY costs_gcpbillingsummary_project_id_fe20b886_fk_gcp_gcpproject_id,
                    DROP KEY costs_gcpbillingsummary_project_id_fe20b886_fk_gcp_gcpproject_id;
                """]
            ),



            # Make gcp_id non-nullable
            migrations.AlterField(
                model_name="gcpproject",
                name="gcp_id",
                field=models.CharField(max_length=50),
            ),
        ]
