# Generated by Django 3.2.3 on 2021-08-18 22:20

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0017_disk_to_gcpdisk_20210810_1738'),
        ('gcp', '0018_alter_gcpproject_id'),
    ]

    operations = [
    ]
