# Generated by Django 3.2.3 on 2021-09-08 16:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0018_alter_gcpproject_id'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCPPublicImageProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('project_name', models.CharField(max_length=50)),
                ('handler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='gcp_public_images', to='gcp.gcphandler')),
            ],
        ),
    ]
