# Generated by Django 3.2.3 on 2021-09-08 17:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gcp', '0019_gcppublicimageproject'),
        ('gcp', '0020_initial_disk_type_options_20210826_2210'),
    ]

    operations = [
    ]
