# Generated by Django 3.2.5 on 2021-12-16 15:35

from django.db import migrations


class Migration(migrations.Migration):

    def gcpdisks_set_realtype(apps, schema_editor):
        """
        Assign a correct real_type to any GCPDisk that has none, due to a ContentType
        bug (since fixed) in the 0017 migration.
        Since no model inherits from GCPDisk, there is no question what real_type should be.
        """
        GCPDisk = apps.get_model("gcp", "GCPDisk")
        ContentType = apps.get_model('contenttypes', 'ContentType')
        gcpdisk_ct = ContentType.objects.get_for_model(GCPDisk)

        for disk in GCPDisk.objects.filter(real_type=None):
            disk.real_type = gcpdisk_ct
            disk.save()


    dependencies = [
        ('gcp', '0021_merge_20210908_1751'),
    ]


    operations = [
        migrations.RunPython(gcpdisks_set_realtype, migrations.RunPython.noop),
    ]
