# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-12 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='EmailAlertChannel',
            fields=[
                ('alertchannel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alerts.AlertChannel')),
                ('_recipients', models.CharField(default='', help_text='Comma-separated list of the recipient email addresses you wish to send to.', max_length=1024, verbose_name='Recipient(s)')),
                ('subject', models.CharField(default='', help_text='Subject line for the email. If blank, the body of the email will be truncated and used as the subject.', max_length=512, verbose_name='Subject')),
            ],
            options={
                'abstract': False,
            },
            bases=('alerts.alertchannel',),
        ),
    ]
