# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-13 22:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0002_emailalertchannel'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailalertchannel',
            name='_recipients',
            field=models.CharField(blank=True, default='', help_text='Comma-separated list of the recipient email addresses you wish to send to.', max_length=1024, verbose_name='Recipient(s)'),
        ),
        migrations.AlterField(
            model_name='emailalertchannel',
            name='subject',
            field=models.CharField(blank=True, default='', help_text='Subject line for the email. If blank, the body of the email will be truncated and used as the subject.', max_length=512, verbose_name='Subject'),
        ),
    ]
