# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-13 22:20
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0003_auto_20190813_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertchannel',
            name='_alert_categories',
            field=models.CharField(blank=True, default='""', help_text='Comma-separated list of alert categories that should be sent to this channel.', max_length=512),
        ),
        migrations.AlterField(
            model_name='emailalertchannel',
            name='_recipients',
            field=models.CharField(blank=True, default='""', help_text='Comma-separated list of the recipient email addresses you wish to send to.', max_length=1024, verbose_name='Recipient(s)'),
        ),
        migrations.AlterField(
            model_name='slackalertchannel',
            name='_slack_channels',
            field=models.CharField(default='""', help_text='Comma-separated list of the Slack Channel(s) you wish to send to, by name or ID', max_length=512, verbose_name='Slack Channel(s)'),
        ),
    ]
