# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-14 18:08
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0004_auto_20190813_2220'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailalertchannel',
            name='_recipients',
            field=models.CharField(default='""', help_text='Comma-separated list of the recipient email addresses you wish to send to.', max_length=1024, verbose_name='Recipient(s)'),
        ),
    ]
