# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-15 20:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0005_auto_20190814_1808'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='emailalertchannel',
            options={'verbose_name': 'Email Alert Channel'},
        ),
        migrations.AlterModelOptions(
            name='slackalertchannel',
            options={'verbose_name': 'Slack Alert Channel'},
        ),
        migrations.AlterField(
            model_name='alertchannel',
            name='_alert_categories',
            field=models.CharField(blank=True, default='""', help_text='Comma-separated list of alert categories that should be sent to this channel. These can be categories that have been configured in the alerts sent by your custom code or those that are sent out-of-the-box by the product. The out-of-the-box alert categories are `cloudbolt.security` and `cloudbolt.admin`.', max_length=512, verbose_name='Alert Categories'),
        ),
        migrations.AlterField(
            model_name='slackalertchannel',
            name='_slack_channels',
            field=models.CharField(default='""', help_text='Comma-separated list of the Slack Channel(s) you wish to send to, by name or ID.', max_length=512, verbose_name='Slack Channel(s)'),
        ),
    ]
