# Generated by Django 2.2.16 on 2021-03-10 21:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('alerts', '0010_set_global_id_for_alerts'),
    ]

    operations = [
        migrations.CreateModel(
            name='TeamsAlertChannel',
            fields=[
                ('alertchannel_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='alerts.AlertChannel')),
                ('incoming_webhook_url', models.CharField(default='""', help_text='The Incoming Webhook URL that is associated with the Teams channel to which alerts will be routed.', max_length=255, verbose_name='Incoming Webhook URL')),
            ],
            options={
                'verbose_name': 'Microsoft Teams',
            },
            bases=('alerts.alertchannel',),
        ),
    ]
