# Generated by Django 3.2.3 on 2021-09-15 16:09

from django.db import migrations


class Migration(migrations.Migration):

    def set_global_ids(apps, schema_editor):
        """
        The previous prefix for alerts was over the 3-character limit. This
        migration regenerates the ids by replacing the prefix for any existing
        records with the new one. The characters after the prefix are retained.
        """
        model = apps.get_model('alerts', 'AlertChannel')
        prefix = 'ALT'
        for row in model.objects.all():
            old_id = row.global_id
            chars = old_id.split("-")[1]
            row.global_id = f'{prefix}-{chars}'
            row.save()

    dependencies = [
        ('alerts', '0011_teamsalertchannel'),
    ]

    operations = [
        migrations.RunPython(set_global_ids, migrations.RunPython.noop),
    ]
