# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-09 21:03
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0006_auto_20170104_2209'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceblueprint',
            name='sequence',
            field=models.IntegerField(default=0, help_text='Sequence specifies the order (followed by blueprint name) that blueprints appear in the catalog. Lower-number sequence numbers will show up first. (default=0)'),
        ),
    ]
