# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-19 18:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0006_auto_20161223_1423'),
        ('servicecatalog', '0007_auto_20170109_2103'),
    ]

    operations = [
    ]
