# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-03 18:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0008_merge'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='serviceblueprint',
            name='is_sub_blueprint',
        ),
        migrations.AddField(
            model_name='serviceblueprint',
            name='is_orderable',
            field=models.BooleanField(default=True, help_text='Specify whether this catalog item should be available for ordering directly or if it should be available only for inclusion in other blueprints.'),
        ),
    ]
