# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-16 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0010_installpodserviceitem_config_file'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installpodserviceitem',
            name='images',
            field=models.TextField(blank=True, default='', help_text='Comma-separated list of images of containers to install as part of this pod'),
        ),
    ]
