# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 19:14
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('files', '0004_fileinputmapping'),
        ('servicecatalog', '0011_installpod_allow_blank_images'),
    ]

    operations = [
        migrations.AddField(
            model_name='installpodserviceitem',
            name='input_mappings',
            field=models.ManyToManyField(to='files.FileInputMapping'),
        ),
    ]
