# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-05 18:18
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0012_installpodserviceitem_input_mappings'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='serviceblueprint',
            options={'verbose_name': 'Blueprint'},
        ),
    ]
