# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-05-15 22:35
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0014_provisionserverserviceitem_allowable_os_families'),
    ]

    operations = [
        migrations.AlterField(
            model_name='provisionserverserviceitem',
            name='allowable_os_families',
            field=models.ManyToManyField(blank=True, help_text='When users choose an OS Build, only show options for these families. This applies when ordering the blueprint (if the tier is set to allow the user to choose an OS Build), and when the blueprint admin predefines an OS Build for the tier.', to='externalcontent.OSFamily', verbose_name='Allowable OS Families'),
        ),
    ]
