# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-06-20 19:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0015_auto_20170515_2235'),
    ]

    operations = [
        migrations.AddField(
            model_name='networkserviceitem',
            name='provide_nat_for_servers',
            field=models.BooleanField(default=False, help_text="Provide NAT'ed addresses for servers in all targeted server tiers", verbose_name='Provide NAT for servers'),
        ),
    ]
