# -*- coding: utf-8 -*-
# Generated by Django 1.11.3 on 2017-07-27 15:24
from __future__ import unicode_literals

import common.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0016_networkserviceitem_provide_nat_for_servers'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceblueprint',
            name='list_image',
            field=common.fields.PreviewImageField(blank=True, default='', help_text='Any size. All standard image formats work, though PNGs with alpha transparency look best.', null=True, upload_to='services/'),
        ),
    ]
