# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-08 13:56
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('services', '0005_ootb_service_resourcetype_20171108_1347'),
        ('servicecatalog', '0019_auto_20170929_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceblueprint',
            name='resource_type',
            field=models.ForeignKey(blank=True, help_text='Specify what type of overall resource the Blueprint should create when ordered (beyond what is defined on the Build tab). If None, will simply provision any included servers and/or run any included actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='services.ResourceType', verbose_name='Resource Type'),
        ),
    ]
