# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-23 18:40
from __future__ import unicode_literals

from django.db import migrations
import taggit.managers


class Migration(migrations.Migration):

    dependencies = [
        ('tags', '0002_cloudbolttag_model_name'),
        ('servicecatalog', '0019_auto_20170929_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceblueprint',
            name='tags',
            field=taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='tags.TaggedItem', to='tags.CloudBoltTag', verbose_name='Tags'),
        ),
    ]
