# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-21 10:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0024_orchestrationhook_sequenced_action_inputs'),
        ('servicecatalog', '0019_auto_20170929_1737'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionserverserviceitem',
            name='environment_selection_hook',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='cbhooks.CloudBoltHook', verbose_name='Environment Selection Orchestration'),
        ),
    ]
