# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-11-14 17:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0022_remove_serviceblueprint_create_service'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceblueprint',
            name='service_name_template',
            field=models.CharField(blank=True, help_text='Specify a template for generating deployed resource names', max_length=255, null=True, verbose_name='Resource Name Template'),
        ),
    ]
