# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 18:27
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0023_auto_20171114_1711'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceblueprint',
            old_name='custom_fields_for_sis',
            new_name='custom_fields_for_items',
        ),
        migrations.RenameField(
            model_name='serviceblueprint',
            old_name='custom_fields_for_service',
            new_name='custom_fields_for_resource',
        ),
    ]
