# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-19 18:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0024_auto_20171219_1827'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceblueprint',
            name='custom_fields_for_items',
            field=models.ManyToManyField(blank=True, related_name='serviceblueprint_set_for_items', to='infrastructure.CustomField'),
        ),
        migrations.AlterField(
            model_name='serviceblueprint',
            name='custom_fields_for_resource',
            field=models.ManyToManyField(blank=True, related_name='serviceblueprint_set_for_resource', to='infrastructure.CustomField'),
        ),
    ]
