# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-12-20 17:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0025_auto_20171219_1827'),
    ]

    operations = [
        migrations.RenameField(
            model_name='serviceblueprint',
            old_name='service_name_template',
            new_name='resource_name_template',
        ),
        migrations.AlterField(
            model_name='serviceblueprint',
            name='groups',
            field=models.ManyToManyField(related_name='editable_blueprints', through='servicecatalog.ServiceBlueprintGroupPermissions', to='accounts.Group'),
        ),
        migrations.AlterField(
            model_name='serviceitem',
            name='deploy_seq',
            field=models.IntegerField(blank=True, help_text='Order in which build items of a blueprint will be deployed.', null=True, verbose_name='Deploy Sequence'),
        ),
    ]
