# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 19:17
from __future__ import unicode_literals

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0026_auto_20171220_1718'),
    ]

    operations = [
        migrations.AlterField(
            model_name='loadbalancerserviceitem',
            name='servers',
            field=models.ManyToManyField(blank=True, help_text='Servers to load balance. If left blank, will load balance all servers built up to this point in the resource.', related_name='load_balancers', to='servicecatalog.ProvisionServerServiceItem'),
        ),
        migrations.AlterField(
            model_name='serviceblueprint',
            name='list_image',
            field=common.fields.PreviewImageField(blank=True, default='', help_text='Any size. All standard image formats work, though PNGs with alpha transparency look best.', null=True, upload_to='blueprints/', verbose_name='List Image'),
        ),
    ]
