# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-18 19:17
from __future__ import unicode_literals

from django.db import migrations


def update_bp_list_images(apps, schema_editor):
    """
    I changed the upload_to of the list_image attribute on Blueprints to be
    blueprints rather than services. This means new uploaded BP images will be
    stored in /var/www/html/cloudbolt/static/uploads/blueprints. We want to
    change all existing BP images to live in that folder as well. The
    10-cloudbolt step of the upgrader takes care of creating the new folder,
    moving existing files over, and deleting the old folder. Here we update the
    BPs to reference the file in the new folder.
    """
    ServiceBlueprint = apps.get_model("servicecatalog", "ServiceBlueprint")

    for bp in ServiceBlueprint.objects.all():
        bp.list_image = bp.list_image.name.replace('services/', 'blueprints/')
        bp.save()


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0027_auto_20180118_1917'),
    ]

    operations = [
        migrations.RunPython(update_bp_list_images,
                             migrations.RunPython.noop),
    ]
