# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 18:12
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0028_change_bp_image_paths_20180118_1917'),
        ('servicecatalog', '0021_auto_20180202_1902'),
    ]

    operations = [
    ]
