# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-02 19:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0028_change_bp_image_paths_20180118_1917'),
        ('resources',
         '0002_move_services_app_objs_to_resources_app_20180201_1903'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceblueprint',
            name='resource_type',
            field=models.ForeignKey(blank=True, help_text='Specify what type of overall resource the Blueprint should create when ordered (beyond what is defined on the Build tab). If None, will simply provision any included servers and/or run any included actions.', null=True, on_delete=django.db.models.deletion.SET_NULL, to='resources.ResourceType', verbose_name='Resource Type'),
        ),
    ]
