# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-07 18:16
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0029_merge_20180207_1812'),
        ('servicecatalog', '0029_auto_20180202_1944'),
    ]

    operations = [
    ]
