# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-23 11:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0030_merge_20180207_1816'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceitem',
            name='rate',
            field=models.DecimalField(blank=True, decimal_places=10, max_digits=65, null=True),
        ),
    ]
