# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-01 20:25
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0020_provisionserverserviceitem_environment_selection_hook'),
        ('servicecatalog', '0030_merge_20180207_1816'),
    ]

    operations = [
    ]
