# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-03-02 13:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0031_merge_20180301_2025'),
        ('servicecatalog', '0031_serviceitem_rate'),
    ]

    operations = [
    ]
