# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2018-06-07 12:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0032_merge_20180302_1348'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceblueprint',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
    ]
