# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-09-21 18:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0035_serviceblueprint_discovery_plugin'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceblueprint',
            name='auto_historical_resources',
            field=models.BooleanField(default=False, help_text="When selected, any Resource associated with this Blueprint that is not returned by the Discovery Plug-in will be automatically marked Historical because it is presumed to no longer exist. A Resource will be considered not found by the Discovery Plug-in if none of its returned dictionaries contain a valid value for the specified Resource identifier that matches the Resource's value for that identifier.", verbose_name='Automatically Mark Resources Historical'),
        ),
    ]
