# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-01-07 20:27
from __future__ import unicode_literals

from django.db import migrations, models


def set_restrict_applications(apps, schema_editor):
    PSSI = apps.get_model('servicecatalog', 'ProvisionServerServiceItem')
    for pssi in PSSI.objects.all():
        if pssi.applications.exists():
            pssi.restrict_applications = True
            pssi.save()


def reverse_restrict_applications(apps, schema_editor):
    """Does nothing, deleting the restrict_applications field will undo the data migration"""
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0036_serviceblueprint_auto_historical_resources'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionserverserviceitem',
            name='restrict_applications',
            field=models.BooleanField(default=False),
        ),
        migrations.RunPython(set_restrict_applications, reverse_restrict_applications)
    ]
