# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-11 18:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0037_provisionserverserviceitem_restrict_applications'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceblueprint',
            name='last_cached',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='serviceblueprint',
            name='remote_source_url',
            field=models.TextField(blank=True, help_text='A reference to a remote source location where the Blueprint is populated from.', null=True, verbose_name='Remote Source URL'),
        ),
    ]
