# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-16 19:38
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0038_auto_20190411_1800'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceblueprint',
            name='remote_source_url',
            field=models.TextField(blank=True, help_text='A reference to a remote source location where the Blueprint is populated from. When set, this Blueprint will become read-only.', null=True, verbose_name='Remote Source URL'),
        ),
    ]
