# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-05-31 20:16
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0042_copyfileaction'),
        ('servicecatalog', '0041_auto_20190517_1854'),
    ]

    operations = [
        migrations.CreateModel(
            name='CopyFileActionServiceItem',
            fields=[
                ('serviceitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicecatalog.ServiceItem')),
                ('continue_on_failure', models.BooleanField(default=False)),
                ('run_on_scale_up', models.BooleanField(default=True)),
                ('hook', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='cbhooks.OrchestrationHook')),
                ('input_mappings', models.ManyToManyField(to='cbhooks.RunHookInputMapping')),
            ],
            options={
                'abstract': False,
            },
            bases=('servicecatalog.serviceitem', models.Model),
        ),
    ]
