# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-24 16:24
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0042_copyfileactionserviceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceblueprint',
            name='remote_source_url',
            field=models.TextField(blank=True, help_text='A reference to a remote source location where the Blueprint is populated from. When set, this Blueprint will refresh from that location and become read-only.<br>This is a beta feature, please \n\n\n\n\n\n<a href="/static/docs/catalog/index.html#blueprints-from-remote-source"\n    target="help"\n    class="no-tooltip-affordance"\n    data-toggle="tooltip"\n    data-html="true"\n    title="Learn more in the docs <p>(new window)</p>">\n     see the docs \n    <i class="icon-help"></i>\n</a>\n for details and limitations.', verbose_name='Remote Source URL'),
        ),
    ]
