# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-27 23:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0043_auto_20190624_1624'),
        ('servicecatalog', '0043_auto_20190621_1657'),
    ]

    operations = [
    ]
