# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-28 22:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0043_auto_20190624_1624'),
        ('servicecatalog', '0043_merge_20190614_2135'),
    ]

    operations = [
    ]
