# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-02 23:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0044_merge_20190628_2213'),
        ('servicecatalog', '0044_merge_20190627_2353'),
    ]

    operations = [
    ]
