# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-08 23:15
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0045_merge_20190702_2324'),
    ]

    operations = [
        migrations.AddField(
            model_name='runterraformplanhookserviceitem',
            name='minimum_version_required',
            field=models.CharField(default='8.6', help_text='This setting will be used to filter components during exports.', max_length=20),
        ),
    ]
