# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-16 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0046_runterraformplanhookserviceitem_minimum_version_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyfileactionserviceitem',
            name='targets',
            field=models.ManyToManyField(blank=True, help_text='This action will run on all servers created by the specified blueprint item.If no targets are selected, action will be run on all servers created by this blueprint (at the time when the action runs)', related_name='copy_file_actions_to_run', to='servicecatalog.ProvisionServerServiceItem'),
        ),
    ]
