# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-19 18:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0044_environment_container_orchestrator'),
        ('servicecatalog', '0046_runterraformplanhookserviceitem_minimum_version_required'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='installpodserviceitem',
            name='container_orchestrator',
        ),
        migrations.AddField(
            model_name='installpodserviceitem',
            name='environment',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='infrastructure.Environment', verbose_name='environment'),
        ),
    ]
