# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-30 20:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0047_auto_20190719_1810'),
        ('servicecatalog', '0047_copyfileactionserviceitem_targets'),
    ]

    operations = [
    ]
