# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-14 14:16
from __future__ import unicode_literals

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0049_auto_20190806_1730'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyfileactionserviceitem',
            name='last_updated',
            field=models.DateField(blank=True, null=True, verbose_name='Last Updated Date'),
        ),
        migrations.AddField(
            model_name='copyfileactionserviceitem',
            name='library_list_image',
            field=common.fields.PreviewImageField(blank=True, default='', help_text='Any size. All standard image formats work, though PNGs with alpha transparency look best.', null=True, upload_to='content_library/', verbose_name='Library List Image'),
        ),
        migrations.AddField(
            model_name='runcloudbolthookserviceitem',
            name='last_updated',
            field=models.DateField(blank=True, null=True, verbose_name='Last Updated Date'),
        ),
        migrations.AddField(
            model_name='runcloudbolthookserviceitem',
            name='library_list_image',
            field=common.fields.PreviewImageField(blank=True, default='', help_text='Any size. All standard image formats work, though PNGs with alpha transparency look best.', null=True, upload_to='content_library/', verbose_name='Library List Image'),
        ),
        migrations.AddField(
            model_name='runemailhookserviceitem',
            name='last_updated',
            field=models.DateField(blank=True, null=True, verbose_name='Last Updated Date'),
        ),
        migrations.AddField(
            model_name='runemailhookserviceitem',
            name='library_list_image',
            field=common.fields.PreviewImageField(blank=True, default='', help_text='Any size. All standard image formats work, though PNGs with alpha transparency look best.', null=True, upload_to='content_library/', verbose_name='Library List Image'),
        ),
        migrations.AddField(
            model_name='runflowhookserviceitem',
            name='last_updated',
            field=models.DateField(blank=True, null=True, verbose_name='Last Updated Date'),
        ),
        migrations.AddField(
            model_name='runflowhookserviceitem',
            name='library_list_image',
            field=common.fields.PreviewImageField(blank=True, default='', help_text='Any size. All standard image formats work, though PNGs with alpha transparency look best.', null=True, upload_to='content_library/', verbose_name='Library List Image'),
        ),
        migrations.AddField(
            model_name='runremotescripthookserviceitem',
            name='last_updated',
            field=models.DateField(blank=True, null=True, verbose_name='Last Updated Date'),
        ),
        migrations.AddField(
            model_name='runremotescripthookserviceitem',
            name='library_list_image',
            field=common.fields.PreviewImageField(blank=True, default='', help_text='Any size. All standard image formats work, though PNGs with alpha transparency look best.', null=True, upload_to='content_library/', verbose_name='Library List Image'),
        ),
        migrations.AddField(
            model_name='runterraformplanhookserviceitem',
            name='last_updated',
            field=models.DateField(blank=True, null=True, verbose_name='Last Updated Date'),
        ),
        migrations.AddField(
            model_name='runterraformplanhookserviceitem',
            name='library_list_image',
            field=common.fields.PreviewImageField(blank=True, default='', help_text='Any size. All standard image formats work, though PNGs with alpha transparency look best.', null=True, upload_to='content_library/', verbose_name='Library List Image'),
        ),
        migrations.AddField(
            model_name='runwebhookserviceitem',
            name='last_updated',
            field=models.DateField(blank=True, null=True, verbose_name='Last Updated Date'),
        ),
        migrations.AddField(
            model_name='runwebhookserviceitem',
            name='library_list_image',
            field=common.fields.PreviewImageField(blank=True, default='', help_text='Any size. All standard image formats work, though PNGs with alpha transparency look best.', null=True, upload_to='content_library/', verbose_name='Library List Image'),
        ),
        migrations.AddField(
            model_name='serviceblueprint',
            name='last_updated',
            field=models.DateField(blank=True, null=True, verbose_name='Last Updated Date'),
        ),
        migrations.AddField(
            model_name='serviceblueprint',
            name='library_list_image',
            field=common.fields.PreviewImageField(blank=True, default='', help_text='Any size. All standard image formats work, though PNGs with alpha transparency look best.', null=True, upload_to='content_library/', verbose_name='Library List Image'),
        ),
        migrations.AddField(
            model_name='teardownserviceitem',
            name='last_updated',
            field=models.DateField(blank=True, null=True, verbose_name='Last Updated Date'),
        ),
        migrations.AddField(
            model_name='teardownserviceitem',
            name='library_list_image',
            field=common.fields.PreviewImageField(blank=True, default='', help_text='Any size. All standard image formats work, though PNGs with alpha transparency look best.', null=True, upload_to='content_library/', verbose_name='Library List Image'),
        ),
    ]
