# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-15 14:35
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0050_auto_20190812_1854'),
        ('servicecatalog', '0050_auto_20190814_1416'),
    ]

    operations = [
    ]
