# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-20 19:48
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0053_set_bp_global_ids_20190913_1747'),
    ]

    operations = [
        migrations.AddField(
            model_name='serviceblueprint',
            name='show_recipient_field_on_order_form',
            field=models.BooleanField(default=False, help_text='Specify whether the "Recipient" field should be shown to permitted users on the order form for this Blueprint. If the field is not shown, the user ordering the Blueprint will be the sole recipient. This setting is only applicable when the Miscellaneous Setting \'Show "Recipient" field on order form\' is set to "Only Enabled Blueprints".', verbose_name='Show "Recipient" field on order form'),
        ),
    ]
