# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-09-18 00:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0053_set_bp_global_ids_20190913_1747'),
        ('servicecatalog', '0052_auto_20190830_2125'),
    ]

    operations = [
    ]
