# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-01 03:53
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0054_merge_20190918_0036'),
        ('servicecatalog', '0054_serviceblueprint_show_recipient_field_on_order_form'),
    ]

    operations = [
    ]
