# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-18 23:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0055_merge_20191001_0353'),
    ]

    operations = [
        migrations.AlterField(
            model_name='copyfileactionserviceitem',
            name='hook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbhooks.OrchestrationHook'),
        ),
        migrations.AlterField(
            model_name='runcloudbolthookserviceitem',
            name='hook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbhooks.OrchestrationHook'),
        ),
        migrations.AlterField(
            model_name='runemailhookserviceitem',
            name='hook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbhooks.OrchestrationHook'),
        ),
        migrations.AlterField(
            model_name='runflowhookserviceitem',
            name='hook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbhooks.OrchestrationHook'),
        ),
        migrations.AlterField(
            model_name='runremotescripthookserviceitem',
            name='hook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbhooks.OrchestrationHook'),
        ),
        migrations.AlterField(
            model_name='runterraformplanhookserviceitem',
            name='hook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbhooks.OrchestrationHook'),
        ),
        migrations.AlterField(
            model_name='runwebhookserviceitem',
            name='hook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbhooks.OrchestrationHook'),
        ),
        migrations.AlterField(
            model_name='teardownserviceitem',
            name='hook',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='cbhooks.OrchestrationHook'),
        ),
    ]
