# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-25 23:59
from __future__ import unicode_literals

import cb_secrets.fields
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0056_auto_20191118_2305'),
    ]

    operations = [
        migrations.CreateModel(
            name='ExportPassword',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('password', cb_secrets.fields.EncryptedPasswordField(help_text="Optionally, you may create a password for encrypting and decrypting any secrets contained in the item being exported. This is useful for sharing exported objects across different CloudBolt instances or when configuring a remote source blueprint. If no password is specified, then a default key will be used for this CloudBolt instance, and the exported object's secrets can only be decrypted when imported onto the same CloudBolt instanceit was exported from. ")),
            ],
        ),
        migrations.AddField(
            model_name='serviceblueprint',
            name='remote_source_password',
            field=cb_secrets.fields.EncryptedPasswordField(blank=True, help_text='Password used to decrypt encrypted secrets in the JSON being imported.', null=True, verbose_name='Remote Source Import Password'),
        ),
        migrations.AddField(
            model_name='exportpassword',
            name='blueprint',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servicecatalog.ServiceBlueprint'),
        ),
    ]
