# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-27 23:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0056_auto_20191118_2305'),
    ]

    operations = [
        migrations.AddField(
            model_name='installpodserviceitem',
            name='deploy_new_cluster',
            field=models.BooleanField(default=True),
        ),
    ]
