# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-04 22:18
from __future__ import unicode_literals

import cb_secrets.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0057_auto_20191125_2359'),
    ]

    operations = [
        migrations.AlterField(
            model_name='exportpassword',
            name='password',
            field=cb_secrets.fields.EncryptedPasswordField(help_text="Optionally, you may provide a password for encrypting and decrypting any secrets contained in the item being exported. This is useful for sharing exported objects across different CloudBolt instances or when configuring a remote source blueprint. If no password is specified, then a default key will be used for this CloudBolt instance, and the exported object's secrets can only be decrypted when imported into the same CloudBolt instance it was exported from. "),
        ),
        migrations.AlterField(
            model_name='serviceblueprint',
            name='remote_source_password',
            field=cb_secrets.fields.EncryptedPasswordField(blank=True, help_text='Password used to decrypt encrypted secrets in the Remote Source Blueprint definition on refresh', null=True, verbose_name='Remote Source Password'),
        ),
    ]
