# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-09 17:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0057_installpodserviceitem_deploy_new_cluster'),
    ]

    operations = [
        migrations.AlterField(
            model_name='installpodserviceitem',
            name='deploy_new_cluster',
            field=models.BooleanField(default=False),
        ),
    ]
