# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-11 17:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0058_auto_20191204_2218'),
        ('servicecatalog', '0058_auto_20191209_1702'),
    ]

    operations = [
    ]
