# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-16 10:28
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0059_merge_20191211_1700'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='exportpassword',
            name='blueprint',
        ),
        migrations.DeleteModel(
            name='ExportPassword',
        ),
    ]
