# Generated by Django 2.2.12 on 2020-06-02 23:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0060_auto_20191216_1028'),
    ]

    operations = [
        migrations.AlterField(
            model_name='serviceblueprint',
            name='remote_source_url',
            field=models.TextField(blank=True, help_text='A reference to a remote source location where the Blueprint is populated from. When set, this Blueprint will refresh from that location and become read-only.<br>', verbose_name='Remote Source URL'),
        ),
    ]
