# Generated by Django 2.2.16 on 2020-12-08 21:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0060_auto_20191216_1028'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprintserviceitem',
            name='restrict_sub_blueprint_scope',
            field=models.BooleanField(default=True, verbose_name='Execution Scope'),
        ),
    ]
