# Generated by Django 2.2.12 on 2020-06-23 05:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('externalcontent', '0016_set_app_ids_20190923_1137'),
        ('servicecatalog', '0061_auto_20200602_2309'),
    ]

    operations = [
        migrations.AddField(
            model_name='provisionserverserviceitem',
            name='initial_os_build',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='initial_os_build', to='externalcontent.OSBuild', verbose_name='Initial OS Build'),
        ),
    ]
