# Generated by Django 2.2.12 on 2020-07-09 11:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0062_provisionserverserviceitem_initial_os_build'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprintserviceitem',
            name='continue_on_failure',
            field=models.BooleanField(default=False),
        ),
    ]
