# Generated by Django 2.2.16 on 2021-01-26 23:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0064_auto_20201019_1709'),
        ('servicecatalog', '0061_blueprintserviceitem_restrict_sub_blueprint_scope'),
    ]

    operations = [
    ]
