# Generated by Django 2.2.16 on 2021-02-01 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0064_auto_20201019_1709'),
    ]

    operations = [
        migrations.AddField(
            model_name='copyfileactionserviceitem',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='runcloudbolthookserviceitem',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='runemailhookserviceitem',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='runflowhookserviceitem',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='runremotescripthookserviceitem',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='runterraformplanhookserviceitem',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='runwebhookserviceitem',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='teardownserviceitem',
            name='enabled',
            field=models.BooleanField(default=True),
        ),
    ]
