# Generated by Django 2.2.16 on 2021-02-02 16:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0065_auto_20210201_2004'),
        ('servicecatalog', '0065_merge_20210126_2337'),
    ]

    operations = [
    ]
