# Generated by Django 2.2.16 on 2021-03-01 17:59

import autoslug.fields
from django.db import migrations
import servicecatalog.models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0069_set_global_id_for_service_item'),
    ]

    operations = [
        migrations.AddField(
            model_name='blueprintserviceitem',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from=servicecatalog.models.BlueprintServiceItem.get_slug),
        ),
        migrations.AddField(
            model_name='copyfileactionserviceitem',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from=servicecatalog.models.CopyFileActionServiceItem.get_slug),
        ),
        migrations.AddField(
            model_name='installpodserviceitem',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from=servicecatalog.models.InstallPodServiceItem.get_slug),
        ),
        migrations.AddField(
            model_name='loadbalancerserviceitem',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from=servicecatalog.models.LoadBalancerServiceItem.get_slug),
        ),
        migrations.AddField(
            model_name='networkserviceitem',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from=servicecatalog.models.NetworkServiceItem.get_slug),
        ),
        migrations.AddField(
            model_name='provisionserverserviceitem',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from=servicecatalog.models.ProvisionServerServiceItem.get_slug),
        ),
        migrations.AddField(
            model_name='runcloudbolthookserviceitem',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from=servicecatalog.models.RunCloudBoltHookServiceItem.get_slug),
        ),
        migrations.AddField(
            model_name='runemailhookserviceitem',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from=servicecatalog.models.RunEmailHookServiceItem.get_slug),
        ),
        migrations.AddField(
            model_name='runflowhookserviceitem',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from=servicecatalog.models.RunFlowHookServiceItem.get_slug),
        ),
        migrations.AddField(
            model_name='runremotescripthookserviceitem',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from=servicecatalog.models.RunRemoteScriptHookServiceItem.get_slug),
        ),
        migrations.AddField(
            model_name='runterraformplanhookserviceitem',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from=servicecatalog.models.RunTerraformPlanHookServiceItem.get_slug),
        ),
        migrations.AddField(
            model_name='runwebhookserviceitem',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from=servicecatalog.models.RunWebHookServiceItem.get_slug),
        ),
        migrations.AddField(
            model_name='teardownserviceitem',
            name='slug',
            field=autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from=servicecatalog.models.TearDownServiceItem.get_slug),
        ),
    ]
