# Generated by Django 3.2.3 on 2021-08-20 20:54

import autoslug.fields
from django.db import migrations, models
import django.db.models.deletion
import files.models
import servicecatalog.models


class Migration(migrations.Migration):

    dependencies = [
        ('cbhooks', '0090_auto_20210820_2054'),
        ('accounts', '0061_userprofile_legal_notice_seen'),
        ('servicecatalog', '0071_set_slug_for_service_item'),
    ]

    operations = [
        migrations.CreateModel(
            name='TerraformConfigServiceItem',
            fields=[
                ('serviceitem_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='servicecatalog.serviceitem')),
                ('module_file', models.FileField(blank=True, help_text='A zip file containing Terraform configurations', max_length=255, null=True, upload_to='tf_configurations')),
                ('source_code_url', models.TextField(blank=True, help_text='Code will be fetched from here before action is run. E.g. URL (without any authentication tokens) to the raw file hosted on your github.com repository. For details \n\n\n\n\n\n<a href="/static-b0175/docs/HTML/actions-with-code.html#external-source-code"\n    id="docs-link"\n    target="help"\n    class="no-tooltip-affordance"\n    data-toggle="tooltip"\n    data-html="true"\n    title="Learn more in the docs <p>(new window)</p>">\n     see the docs \n    <i class="icon-help"></i>\n</a>\n.', null=True, verbose_name='URL for source code')),
                ('git_source_code_url', models.TextField(blank=True, help_text='Code will be fetched from here before action is run. E.g. URL (without any authentication tokens) to the raw file hosted on your github.com repository. For details \n\n\n\n\n\n<a href="/static-b0175/docs/HTML/actions-with-code.html#external-source-code"\n    id="docs-link"\n    target="help"\n    class="no-tooltip-affordance"\n    data-toggle="tooltip"\n    data-html="true"\n    title="Learn more in the docs <p>(new window)</p>">\n     see the docs \n    <i class="icon-help"></i>\n</a>\n.', null=True, verbose_name='URL for source code')),
                ('plan_directory', models.CharField(blank=True, help_text='Optional field to add a configuration directory if you are uploading a configuration inside a zip file that has multiple files in it.', max_length=255, null=True)),
                ('preserve_config_dir', models.BooleanField(default=False, help_text='Should the contents of the working directory be preserved across orders?')),
                ('branch', models.CharField(blank=True, help_text='Branch of the git repo to use.', max_length=255, null=True)),
                ('refresh_on_order', models.BooleanField(default=False, help_text='Refresh code from source on every order?')),
                ('local_path', models.CharField(blank=True, max_length=255, null=True)),
                ('default_tfvars', models.CharField(blank=True, default=None, max_length=4096, null=True)),
                ('slug', autoslug.fields.AutoSlugField(always_update=True, default=None, editable=False, null=True, populate_from=servicecatalog.models.TerraformConfigServiceItem.get_slug)),
                ('all_environments_enabled', models.BooleanField(default=False)),
                ('groups', models.ManyToManyField(blank=True, to='accounts.Group')),
                ('plan_hook_helper', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cbhooks.terraformplanhook')),
            ],
            options={
                'abstract': False,
            },
            bases=('servicecatalog.serviceitem', servicecatalog.models.ServiceItemWithEnvParametersMixin, files.models.ExternalSourceCodeMixin),
        ),
    ]
