# Generated by Django 3.2.3 on 2021-08-31 17:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servicecatalog', '0072_terraformconfigserviceitem'),
    ]

    operations = [
        migrations.AlterField(
            model_name='terraformconfigserviceitem',
            name='git_source_code_url',
            field=models.TextField(blank=True, help_text='Terraform Configuration Git URL', null=True, verbose_name='Terraform Configuration Git URL'),
        ),
        migrations.AlterField(
            model_name='terraformconfigserviceitem',
            name='source_code_url',
            field=models.TextField(blank=True, help_text='Terraform Configuration .zip URL', null=True, verbose_name='Terraform Configuration .zip URL'),
        ),
    ]
