# Generated by Django 2.2.10 on 2020-04-09 18:10

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilities', '0083_connectioninfo_transport'),
        ('resourcehandlers', '0017_auto_20191107_0049'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCVMMHandler',
            fields=[
                ('resourcehandler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resourcehandlers.ResourceHandler')),
                ('connection_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='utilities.ConnectionInfo')),
            ],
            options={
                'abstract': False,
            },
            bases=('resourcehandlers.resourcehandler',),
        ),
    ]
