# Generated by Django 2.2.12 on 2020-05-20 00:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('scvmm', '0003_scvmmtemplate'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='scvmmtemplate',
            options={'verbose_name': 'SCVMM Template'},
        ),
    ]
