# Generated by Django 2.2.12 on 2020-05-20 23:44

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourcehandlers', '0017_auto_20191107_0049'),
        ('scvmm', '0004_auto_20200520_0031'),
    ]

    operations = [
        migrations.CreateModel(
            name='SCVMMNetwork',
            fields=[
                ('resourcenetwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resourcehandlers.ResourceNetwork')),
            ],
            options={
                'verbose_name': 'SCVMM Network',
                'abstract': False,
            },
            bases=('resourcehandlers.resourcenetwork',),
        ),
        migrations.AddField(
            model_name='scvmmhandler',
            name='networks',
            field=models.ManyToManyField(blank=True, to='scvmm.SCVMMNetwork'),
        ),
    ]
