# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-09-28 15:10
from __future__ import unicode_literals

from django.db import migrations


base_templates = {
    'expired-server': {
        'name': 'Expired Server',
        'subject': """
            {% load helper_tags %}
            {% if servers|length == 1 %}
                [{% portal_label %}] Server {{ server.hostname }} is expired
            {% else %}
                [{% portal_label %}] Please take action on these {{ servers|length }} expired server{{ servers|pluralize}}
            {% endif %}
            """,
        'body': """
            {% load helper_tags %}

            Dear {{ owner.user.get_full_name }},

            You own {{ servers|length }} expired server{{ servers|pluralize }}.
            Please take a moment to delete or visit the {% portal_label %} interface to
            take care of {% if servers|length == 1 %}this resource{% else %}these resources{% endif %}.

            {% for server in servers %}
                Expired: {{ server.expiration_date|date:"SHORT_DATE_FORMAT" }}
                Hostname: {{ server.hostname }}
                IP: {% if server.ip == 'dhcp' %}DHCP{% else %}{{ server.ip }}{% endif %}
                Manage: {% site_link server %}
            {% endfor %}
            """,
    },
    'job-failure': {
        'name': 'Job failure',
        'subject': "{% load helper_tags %}[{% portal_label %}] {{subject}}",
        'body': """

            {% load helper_tags %}

            {{ message|safe }}

            {% if job %}
                ============

                View the job here:
                {% site_link job %}
            {% endif %}

            """,
    },
    'order-complete': {
        'name': 'Order Complete',
        'subject': """
            {{ order.status.capitalize }}: order #{{ order.id }} ({{ order.name|lower|default:"No name" }}) {{ order.status_display|lower }}
            """,
        'body': """
            {% load helper_tags %}
            Order #{{ order.id }} has completed.
            {% if order.name %}
                Short Description: {{ order.name }}
            {% endif %}
            {% if order.decom_server_list %}
                Decommissioned servers:
                {% for server in order.decom_server_list %}
                    * Hostname: {{ server.get_vm_name }}
                {% endfor%}
            {% endif %}
            {% if order.prov_server_list %}
                Provisioned servers:
                {% for server in order.prov_server_list %}
                    * Hostname: {{ server.get_vm_name }}{% if server.ip %}
                        Primary IP: {{ server.ip }} {% endif %}{% if server.rate %}
                        Rate: {{ server.rate_display }}{% endif %}
                {% endfor%}
            {% endif %}
            View the order here:
            {% site_link order %}
            """,
    },
    'order-created': {
        'name': 'Order Created',
        'subject': """
            {% load helper_tags %}[{% portal_label %}] An order has been submitted for your approval
            """,
        'body': """
            {% load helper_tags %}

            Order #{{ order.id }} has been submitted by user {{ order.owner.user.username }} for your approval.

            Review the order here:
            {% site_link order %}
            """,
    },
    'order-reminder': {
        'name': 'Order Reminder',
        'subject': """
            {% load helper_tags %}[{% portal_label %}] Reminder to review order #{{ order.id }}
            """,
        'body': """
            {% load helper_tags %}

            The requestor for order #{{ order.id }} sent you this reminder to review the order and approve or deny it:
            {% site_link order %}

            View requestor's profile:
            {% site_link order.owner %}
            """,
    },
    'aws-missing-tags': {
        'name': 'AWS Missing Tags',
        'subject': """
            {% load helper_tags %}
            {% portal_label %}: Warning - Server '{{ server.hostname }}' missing {{ missing_tags|length }} required tag{{ missing_tags|pluralize }}
            """,
        'body': """
            {% load helper_tags %}
            The Server '{{ server.hostname }}' is missing the following required tag{{ missing_tags|pluralize }}:
            {% if missing_tags %}
                {% for t in missing_tags %}
                * {{ t }}
                {% endfor %}
            {% endif %}
            """,
    },
    'attached-report': {
        'name': 'Attached Report',
        'subject': """
            {% load helper_tags %}{% portal_label %} Report: {{ report_name }}
            """,
        'body': """
            {% load helper_tags %}

            Here's your {{ report_name }} report from {% portal_label %}!
            Open the attached zip file and double-click the HTML file
            to view your report.
            """,
    },
    'cit-failure': {
        'name': 'Continuous Infrastructure Testing failure',
        'subject': """
            {% load helper_tags %}[{% portal_label %}] Continuous Infrastructure Testing failure
            """,
        'body': """
            {% load helper_tags %}

            {{ body_text|safe|linebreaks }}

            <hr />
            <p>
            View the full Continuous Infrastructure Testing job <a href="{{ job_link }}">here</a>.
            </p>
            <p>
            Sent from {% portal_label %}
            </p>
            """,
    },
    'export-servers-report': {
        'name': 'Export Servers Report',
        'subject': """
            {% load helper_tags %}[{% portal_label %}] Spreadsheet(s) of active server information
            """,
        'body': """
            Attached are CSV file(s) containing information about active servers.
            """,
    },
    'export-group-servers-report': {
        'name': 'Export Group Servers Report',
        'subject': """
            {% load helper_tags %}[{% portal_label %}] Spreadsheet of active {{ group }} server information
            """,
        'body': """
            {% load helper_tags %}

            Attached is a CSV file containing information about the active servers belonging to the {{ group }} group.

            View this group:
            {% site_link group %}
            """,
    },
    'group-quota-warning': {
        'name': 'Group Quota Warning',
        'subject': """
            {% load helper_tags %}
            {% portal_label %}: Warning - Group {{ group.name }} exceeded {{ threshold|stringformat:":.0%" }} threshold in {{ quotas|length }} quota{{ quotas|pluralize }}
            """,
        'body': """
            {% load helper_tags %}
            The Group '{{ group.name }}' has exceeded the {{ threshold|stringformat:":.0%" }} threshold for the following quota{{ quotas|pluralize }}:
            {% if quotas %}
                {% for q in quotas %}
                * {{ q.name }} at {{ q.usage }} (used={{ q.obj.used }}, limit={{ q.obj.limit }})
                {% endfor %}
            {% endif %}
            """,
    },
    'license-warning': {
        'name': 'License Warning',
        'subject': """
            {% load helper_tags %}
            {% portal_label %}: Warning - Product License Needs Attention
            """,
        'body': """
            {% load helper_tags %}
            Please review your {% portal_label %} Product License and resolve the following issue{{ warnings|pluralize }}:
            {% if warnings %}
              {% for warning in warnings %}
              * {{ warning }}
              {% endfor %}
            {% endif %}
            """,
    },
    'stale-job-report': {
        'name': 'Stale Job Report',
        'subject': """
            {% load helper_tags %}[{% portal_label %}] Stale job report
            """,
        'body': """
            {% load helper_tags %}

            {{ body_text|safe }}

            {% if jobs %}
            Jobs
            ============
            {% for j in jobs %}
                ID: {{ j.id }} || Type: {{ j.type_display }} || Running for {{ j.get_duration }} || {% site_link j %}
            {% endfor %}
            {% endif %}
            """,
    },
    'user-sync-failure': {
        'name': 'Error synchronizing user permissions',
        'subject': """
            {% load helper_tags %}[Attention Required] Error synchronizing user permissions in {% portal_label %}
            """,
        'body': """
            {% load helper_tags %}
            {% portal_label %} was unable to run the external_users_sync to update permissions
            and/or group memberships for user '{{userprofile}}' due to an orchestration error.

            Error: '{{error}}'

            Check the application log for more details on this error.
            """,
    },
}


def create_templates(apps, schema_editor):
    """
    For each of the template defined above, create or update on the slug
    and update the remaining fields. This will also default to not renamable,
    making the templates loaded through this migration un-deletable via the UI.
    """
    EmailTemplate = apps.get_model('emailtemplates', 'EmailTemplate')
    for slug, defaults in base_templates.items():
        EmailTemplate.objects.update_or_create(
            is_renamable=False,
            slug=slug,
            defaults=defaults
        )


class Migration(migrations.Migration):

    dependencies = [
        ('emailtemplates', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_templates),
    ]
