# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-12 20:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtemplates', '0002_auto_20170928_1510'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(default='', help_text='The HTML body, which will get rendered with context.'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(default='', help_text='The email subject, which will get rendered with context.', max_length=1024),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='text_body',
            field=models.TextField(blank=True, default='', help_text='The plain-text body of the email, which will get rendered with context. If no content is provided, the HTML body will be stripped of HTML tags and used instead.'),
        ),
    ]
