# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-10-17 01:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('emailtemplates', '0004_template_for_order_recipient_20180516_1652'),
    ]

    operations = [
        migrations.AlterField(
            model_name='emailtemplate',
            name='body',
            field=models.TextField(default='', help_text='The HTML body, which will get rendered with context.', verbose_name='Body'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='from_address',
            field=models.CharField(blank=True, help_text="Specify as: 'Full Name &lt;email@address>'<br/>Defaults to: 'no-reply@site.domain'", max_length=320, verbose_name='From address'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='name',
            field=models.CharField(max_length=255, verbose_name='Name'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='subject',
            field=models.CharField(default='', help_text='The email subject, which will get rendered with context.', max_length=1024, verbose_name='Subject'),
        ),
        migrations.AlterField(
            model_name='emailtemplate',
            name='text_body',
            field=models.TextField(blank=True, default='', help_text='The plain-text body of the email, which will get rendered with context. If no content is provided, the HTML body will be stripped of HTML tags and used instead.', verbose_name='Text body'),
        ),
    ]
