# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-10 15:33
from __future__ import unicode_literals

import common.validators
from django.db import migrations, models
import django.db.models.deletion
import taggit.managers


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('tags', '0010_set_bidirectional_sync_on_taggableattribute_20190419_2105'),
    ]

    operations = [
        migrations.CreateModel(
            name='UIExtension',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='Lowercase leters, with optional underscores.', max_length=255, unique=True, validators=[common.validators.is_valid_folder_name])),
                ('label', models.CharField(max_length=50)),
                ('description', models.TextField(blank=True, help_text='May be used to explain the purpose of a UI Extension and offer guidance to admins.', null=True)),
                ('filepath', models.CharField(max_length=255, unique=True)),
                ('labels', taggit.managers.TaggableManager(help_text='A comma-separated list of tags.', through='tags.TaggedItem', to='tags.CloudBoltTag', verbose_name='Labels')),
            ],
        ),
        migrations.CreateModel(
            name='UIExtensionComponent',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('description', models.TextField(blank=True, null=True, verbose_name='Description')),
                ('type', models.CharField(choices=[('dashboard', 'Dashboard'), ('report', 'Report'), ('tab', 'Detail View Tab'), ('admin', 'Admin Page')], max_length=10)),
                ('report_icon', models.ImageField(blank=True, help_text='a 32x16px thumbnail icon', upload_to='xui-icons')),
                ('report_category', models.CharField(blank=True, choices=[('costs', 'Costs'), ('servers', 'Servers'), ('usage', 'Usage')], max_length=10)),
                ('extension', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='extensions.UIExtension', verbose_name='UI Extension')),
            ],
        ),
    ]
