# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-08-14 14:16
from __future__ import unicode_literals

import common.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0002_uiextension_minimum_version_required'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiextension',
            name='last_updated',
            field=models.DateField(blank=True, null=True, verbose_name='Last Updated Date'),
        ),
        migrations.AddField(
            model_name='uiextension',
            name='library_list_image',
            field=common.fields.PreviewImageField(blank=True, default='', help_text='Any size. All standard image formats work, though PNGs with alpha transparency look best.', null=True, upload_to='content_library/', verbose_name='Library List Image'),
        ),
    ]
