# Generated by Django 3.2.3 on 2021-06-26 22:48
from django.db import migrations, models

from extensions.models import XUIIndexer


def index(*args, **kwargs):
    """
    Call the XUI Indexer to repopulate the table with information from installed XUIs.
    """
    XUIIndexer().index()


class Migration(migrations.Migration):
    dependencies = [
        ('extensions', '0006_uiextensioncomponent_global_id'),
    ]

    operations = [
        migrations.AddField(
            model_name='uiextensioncomponent',
            name='renderer',
            field=models.CharField(default=None, max_length=255, verbose_name='Render Function'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='uiextensioncomponent',
            name='view',
            field=models.CharField(default=None, max_length=255, verbose_name='View Class'),
            preserve_default=False,
        ),
        migrations.RunPython(index, migrations.RunPython.noop)
    ]
