# Generated by Django 3.2.3 on 2021-08-09 23:12

import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('extensions', '0007_component_render_and_view'),
    ]

    operations = [
        migrations.AlterField(
            model_name='uiextension',
            name='name',
            field=models.CharField(help_text='Lowercase letters, with optional underscores.', max_length=255, unique=True, validators=[common.validators.is_valid_folder_name]),
        ),
    ]
