# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-24 00:01
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behavior_mapping', '0004_auto_20161004_2121'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customfieldmapping',
            name='hide_single_value',
        ),
    ]
