# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-02-01 01:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('behavior_mapping', '0005_add_sequenceditem_for_applications'),
        ('behavior_mapping', '0005_remove_customfieldmapping_hide_single_value'),
    ]

    operations = [
    ]
