# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-19 21:09
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior_mapping', '0009_auto_20180119_1931'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfieldmapping',
            name='slider_increment',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='The amount that the slider for this parameter should increment by.', max_digits=10, null=True),
        ),
    ]
