# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-06-27 16:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior_mapping', '0010_customfieldmapping_slider_increment'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customfieldmapping',
            name='minimum',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='For string types, the min length. For integers & decimals, the minimum value.', max_digits=10, null=True),
        ),
    ]
