# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-06 00:29
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('behavior_mapping', '0011_auto_20190627_1627'),
    ]

    operations = [
        migrations.AddField(
            model_name='customfieldmapping',
            name='global_target',
            field=models.CharField(blank=True, choices=[('servers', 'servers'), ('resources', 'resources'), ('all', 'all')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='preconfigurationmapping',
            name='global_target',
            field=models.CharField(blank=True, choices=[('servers', 'servers'), ('resources', 'resources'), ('all', 'all')], max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='resourcepoolmapping',
            name='global_target',
            field=models.CharField(blank=True, choices=[('servers', 'servers'), ('resources', 'resources'), ('all', 'all')], max_length=255, null=True),
        ),
    ]
