# Generated by Django 3.2.3 on 2021-09-30 18:20

import behavior_mapping.models
from django.db import migrations
import django.db.models.manager


class Migration(migrations.Migration):

    dependencies = [
        ('behavior_mapping', '0012_auto_20191106_0029'),
    ]

    operations = [
        migrations.AlterModelManagers(
            name='customfieldmapping',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('global_mappings', behavior_mapping.models.GlobalMappingsManager()),
                ('global_mappings_not_defaults', behavior_mapping.models.GlobalMappingsNotDefaultsManager()),
                ('global_mappings_with_defaults', behavior_mapping.models.GlobalMappingsWithDefaultsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='preconfigurationmapping',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('global_mappings', behavior_mapping.models.GlobalMappingsManager()),
                ('global_mappings_not_defaults', behavior_mapping.models.GlobalMappingsNotDefaultsManager()),
                ('global_mappings_with_defaults', behavior_mapping.models.GlobalMappingsWithDefaultsManager()),
            ],
        ),
        migrations.AlterModelManagers(
            name='resourcepoolmapping',
            managers=[
                ('objects', django.db.models.manager.Manager()),
                ('global_mappings', behavior_mapping.models.GlobalMappingsManager()),
                ('global_mappings_not_defaults', behavior_mapping.models.GlobalMappingsNotDefaultsManager()),
                ('global_mappings_with_defaults', behavior_mapping.models.GlobalMappingsWithDefaultsManager()),
            ],
        ),
    ]
