# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-06 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puppet_ent', '0004_auto_20161214_0006'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='peconf',
            options={'verbose_name': 'Puppet Enterprise'},
        ),
    ]
