# Generated by Django 2.2.16 on 2021-03-29 05:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('infrastructure', '0054_auto_20210218_1007'),
        ('externalcontent', '0020_merge_20210226_1415'),
        ('resourcehandlers', '0022_auto_20210219_1515'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaasDisk',
            fields=[
                ('disk_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='infrastructure.Disk')),
                ('path', models.CharField(max_length=255)),
                ('model', models.CharField(max_length=255)),
            ],
            options={
                'abstract': False,
            },
            bases=('infrastructure.disk',),
        ),
        migrations.CreateModel(
            name='MaasImage',
            fields=[
                ('osbuildattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='externalcontent.OSBuildAttribute')),
                ('image_name', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
            bases=('externalcontent.osbuildattribute',),
        ),
        migrations.CreateModel(
            name='MaasServerInfo',
            fields=[
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='infrastructure.Server')),
                ('system_id', models.CharField(help_text='stores system_id, including after decom', max_length=200)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='MaasResourceHandler',
            fields=[
                ('resourcehandler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resourcehandlers.ResourceHandler')),
                ('networks', models.ManyToManyField(blank=True, to='resourcehandlers.ResourceNetwork')),
            ],
            options={
                'verbose_name': 'MAAS resource handler',
                'abstract': False,
            },
            bases=('resourcehandlers.resourcehandler',),
        ),
    ]
