# Generated by Django 2.2.16 on 2020-12-11 17:51

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('utilities', '0092_globalpreferences_enable_set_challenge_question'),
        ('externalcontent', '0017_auto_20201019_1709'),
        ('resourcehandlers', '0019_auto_20200925_1322'),
        ('infrastructure', '0052_auto_20201019_1709'),
    ]

    operations = [
        migrations.CreateModel(
            name='OutscaleImage',
            fields=[
                ('osbuildattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='externalcontent.OSBuildAttribute')),
                ('image_id', models.CharField(max_length=256)),
            ],
            options={
                'abstract': False,
            },
            bases=('externalcontent.osbuildattribute',),
        ),
        migrations.CreateModel(
            name='OutscaleServerInfo',
            fields=[
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='infrastructure.Server')),
                ('instance_id', models.CharField(max_length=255)),
                ('availability_zone', models.CharField(max_length=255)),
                ('keypair_name', models.CharField(blank=True, max_length=255)),
                ('instance_type', models.CharField(max_length=255)),
                ('security_group', models.CharField(blank=True, max_length=255)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='OutscaleSubnet',
            fields=[
                ('resourcenetwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resourcehandlers.ResourceNetwork')),
                ('subnet_id', models.CharField(max_length=256)),
                ('cidr_block', models.CharField(max_length=30)),
            ],
            options={
                'verbose_name': 'Outscale Subnet',
                'abstract': False,
            },
            bases=('resourcehandlers.resourcenetwork',),
        ),
        migrations.CreateModel(
            name='OutscaleResourceHandler',
            fields=[
                ('resourcehandler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resourcehandlers.ResourceHandler')),
                ('region', models.CharField(max_length=20)),
                ('access_key', models.CharField(max_length=100)),
                ('access_key_secret', models.CharField(max_length=100)),
                ('connection_info', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='utilities.ConnectionInfo')),
                ('networks', models.ManyToManyField(blank=True, to='outscale.OutscaleSubnet')),
            ],
            options={
                'verbose_name': 'Outscale resource handler',
                'abstract': False,
            },
            bases=('resourcehandlers.resourcehandler',),
        ),
    ]
