# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-13 00:46
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('resourcehandlers', '0002_auto_20161004_2121'),
        ('gce', '0002_auto_20161004_2121'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCENetwork',
            fields=[
                ('resourcenetwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resourcehandlers.ResourceNetwork')),
                ('cidr_block', models.CharField(blank=True, max_length=30)),
                ('mode', models.CharField(choices=[('legacy', 'Legacy'), ('custom', 'Custom'), ('auto', 'Auto')], max_length=12)),
            ],
            options={
                'verbose_name': 'GCE Network',
            },
            bases=('resourcehandlers.resourcenetwork',),
        ),
    ]
