# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-13 00:49
from __future__ import unicode_literals

from django.db import migrations


def create_gce_networks(apps, schema_editor):
    GCEHandler = apps.get_model("gce", "GCEHandler")
    GCENetwork = apps.get_model("gce", "GCENetwork")
    for handler in GCEHandler.objects.all():
        for network in handler.networks.all():
            new_gce_net = GCENetwork(resourcenetwork_ptr_id=network.id)
            new_gce_net.__dict__.update(network.__dict__)
            new_gce_net.save()


class Migration(migrations.Migration):

    dependencies = [
        ('gce', '0003_gcenetwork'),
    ]

    operations = [
        migrations.RunPython(create_gce_networks)
    ]
