# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-08 19:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('infrastructure', '0038_auto_20180625_2145'),
        ('accounts', '0036_extend_server_list_args'),
        ('gce', '0009_remove_gcehandler_old_os_build_attributes'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCPProject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50)),
                ('project_number', models.CharField(max_length=20)),
                ('project_id', models.CharField(max_length=50)),
                ('organization_id', models.CharField(max_length=50)),
                ('client_secrets', models.TextField()),
                ('environments', models.ManyToManyField(related_name='gcp_projects', to='infrastructure.Environment')),
                ('groups', models.ManyToManyField(related_name='gcp_projects', to='accounts.Group')),
                ('handler', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='gcp_projects', to='gce.GCEHandler')),
            ],
        ),
    ]
