# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-08 14:39
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('gce', '0010_gcpproject'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gcpproject',
            old_name='client_secrets',
            new_name='service_account_key',
        ),
        migrations.AddField(
            model_name='gcpproject',
            name='imported',
            field=models.BooleanField(default=False),
        ),
    ]
