# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-14 23:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('libcloudhandler', '0006_remove_libcloudimage_old_template_name'),
        ('gce', '0012_auto_20190313_2224'),
    ]

    operations = [
        migrations.CreateModel(
            name='GCPServerInfo',
            fields=[
                ('libcloudserverinfo_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='libcloudhandler.LibcloudServerInfo')),
                ('gcp_project', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='servers', to='gce.GCPProject')),
            ],
            options={
                'abstract': False,
            },
            bases=('libcloudhandler.libcloudserverinfo',),
        ),
    ]
