# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-18 20:51
from __future__ import unicode_literals

import cb_secrets.fields
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gce', '0014_auto_20190315_0145'),
    ]

    operations = [
        migrations.AddField(
            model_name='gcehandler',
            name='web_client_json',
            field=cb_secrets.fields.EncryptedTextField(blank=True, null=True, verbose_name='Web Application Client ID JSON'),
        ),
    ]
