# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 16:48
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gce', '0015_gcehandler_web_client_json'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GCPServerInfo',
        ),
    ]
