# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-08 16:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gce', '0016_auto_20190408_1648'),
    ]

    operations = [
        migrations.DeleteModel(
            name='GCPProject',
        ),
    ]
