# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-09 17:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('gce', '0017_auto_20190408_1650'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gcehandler',
            name='web_client_json',
        ),
    ]
