# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-03-23 13:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('containerorchestrators', '0002_containerresource'),
        ('kuberneteshandler', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='KubernetesResource',
            fields=[
                ('containerresource_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='containerorchestrators.ContainerResource')),
                ('name', models.CharField(max_length=253)),
                ('kind', models.CharField(max_length=40)),
                ('version', models.CharField(max_length=40)),
            ],
            options={
                'abstract': False,
            },
            bases=('containerorchestrators.containerresource',),
        ),
    ]
