# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-19 18:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('kuberneteshandler', '0002_kubernetesresource'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='KubernetesResource',
            new_name='KubernetesObject',
        ),
    ]
