# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-02-19 21:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuberneteshandler', '0004_kubernetesobject_namespace'),
    ]

    # the previous migration created the new namespace field and defaulted to
    # 'default'. This is correct because that was the only namespace we
    # previously handled. But now that we handle objects with no namespace, we
    # want the default namespace to be blank.
    operations = [
        migrations.AlterField(
            model_name='kubernetesobject',
            name='namespace',
            field=models.CharField(blank=True, default='', max_length=253),
        ),
    ]
