# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-17 16:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuberneteshandler', '0005_default_namespace_to_blank'),
    ]

    operations = [
        migrations.AddField(
            model_name='kubernetes',
            name='auth_type',
            field=models.CharField(choices=[('PASSWORD', 'Password'), ('TOKEN', 'Bearer Token')], default='PASSWORD', help_text='Authentication strategy to use when connecting to the Kubernetes API server', max_length=50, verbose_name='Authentication type'),
        ),
    ]
