# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-08-23 13:45
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuberneteshandler', '0006_kubernetes_auth_type'),
    ]

    operations = [
        migrations.AddField(
            model_name='kubernetes',
            name='url_path_prefix',
            field=models.CharField(blank=True, default='', help_text="If your Kubernetes endpoint uses a non-standard URL, use this field to prepend a component to the path that CB would normally use. This will be added after '&lt;protocol&gt;://&lt;host&gt;:&lt;port&gt;/' in the URL, and before 'api[s]/'.", max_length=255, verbose_name='URL Path Prefix'),
        ),
    ]
