# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-18 17:15
from __future__ import unicode_literals

import cb_secrets.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuberneteshandler', '0007_kubernetes_url_path_prefix'),
    ]

    operations = [
        migrations.AddField(
            model_name='kubernetes',
            name='ca_file_contents',
            field=cb_secrets.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kubernetes',
            name='cert_file_contents',
            field=cb_secrets.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='kubernetes',
            name='key_file_contents',
            field=cb_secrets.fields.EncryptedTextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='kubernetes',
            name='auth_type',
            field=models.CharField(choices=[('PASSWORD', 'Password'), ('TOKEN', 'Bearer Token'), ('CERTIFICATE', 'Certificate')], default='PASSWORD', help_text='Authentication strategy to use when connecting to the Kubernetes API server', max_length=50, verbose_name='Authentication type'),
        ),
    ]
