# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-12-04 22:19
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('kuberneteshandler', '0008_auto_20191118_1715'),
    ]

    operations = [
        migrations.AlterField(
            model_name='kubernetes',
            name='url_path_prefix',
            field=models.CharField(blank=True, default='', help_text="If your Kubernetes endpoint uses a non-standard URL, use this field to prepend a component to the path that CB would normally use. This will be added after '{protocol}://{host}:{port}/' in the URL, and before 'api[s]/'.", max_length=255, verbose_name='URL Path Prefix'),
        ),
    ]
