# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-03 23:27
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0007_ansibleconf_extra_vars'),
    ]

    operations = [
        migrations.AlterField(
            model_name='ansibleconf',
            name='inventory_path',
            field=models.CharField(default='/home/ansible/cloudbolt.ini', help_text='The path on the management server where an inventory file will be written.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ansiblegroup',
            name='available_playbooks',
            field=models.ManyToManyField(blank=True, help_text='Playbooks available to run on servers in this group.', related_name='groups_available', to='ansible.AnsiblePlaybook'),
        ),
        migrations.AlterField(
            model_name='ansiblegroup',
            name='initialization_playbooks',
            field=models.ManyToManyField(blank=True, help_text='Playbooks used to initialize servers in this group.', related_name='groups_initialized', to='ansible.AnsiblePlaybook'),
        ),
        migrations.AlterField(
            model_name='ansiblegroup',
            name='name',
            field=models.CharField(help_text='If group names are used in playbooks, this name should\n                  match one of them. Otherwise, any name can be entered here\n                  and it will be used for display purposes only.', max_length=255),
        ),
        migrations.AlterField(
            model_name='ansibleplaybook',
            name='name',
            field=models.CharField(help_text='A name for this playbook file, used for display purposes only.', max_length=255),
        ),
    ]
