# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-06 01:00
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0008_auto_20170103_2327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ansibleconf',
            options={'verbose_name': 'Ansible'},
        ),
        migrations.AlterModelOptions(
            name='ansiblegroup',
            options={'verbose_name': 'Ansible'},
        ),
    ]
