# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-03-15 00:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0009_auto_20170106_0100'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='ansiblegroup',
            options={'verbose_name': 'Ansible Group'},
        ),
    ]
