# -*- coding: utf-8 -*-
# Generated by Django 1.11.16 on 2019-03-09 22:04
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0010_auto_20170315_0009'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnsibleVariable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(help_text="The name of the variable to be passed to Ansible's '--extra-vars' flag.", max_length=1024)),
                ('value', models.CharField(max_length=1024)),
            ],
        ),
        migrations.AddField(
            model_name='ansibleconf',
            name='variables',
            field=models.ManyToManyField(related_name='ansibleconf_set', to='ansible.AnsibleVariable'),
        ),
        migrations.AddField(
            model_name='ansiblegroup',
            name='variables',
            field=models.ManyToManyField(related_name='ansiblegroup_set', to='ansible.AnsibleVariable'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='variables',
            field=models.ManyToManyField(related_name='ansibleplaybook_set', to='ansible.AnsibleVariable'),
        ),
    ]
