# Generated by Django 3.2.3 on 2021-08-12 20:22

import common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ansible', '0011_auto_20190309_2204'),
    ]

    operations = [
        migrations.AddField(
            model_name='ansiblegroup',
            name='global_id',
            field=models.CharField(default=common.mixins.get_global_id_chars, help_text='Identifier that can be used to access this object through the API across instances.', max_length=16, verbose_name='Global ID'),
        ),
        migrations.AddField(
            model_name='ansibleplaybook',
            name='global_id',
            field=models.CharField(default=common.mixins.get_global_id_chars, help_text='Identifier that can be used to access this object through the API across instances.', max_length=16, verbose_name='Global ID'),
        ),
    ]
