# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-04-14 19:12
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('nsx', '0002_auto_20160829_2059'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='nsxedgeconfiguration',
            name='datacenter_moid',
        ),
        migrations.RemoveField(
            model_name='nsxedgeconfiguration',
            name='datastore_moid',
        ),
        migrations.RemoveField(
            model_name='nsxedgeconfiguration',
            name='folder_moid',
        ),
        migrations.RemoveField(
            model_name='nsxedgeconfiguration',
            name='resource_pool_moid',
        ),
        migrations.AddField(
            model_name='nsxedgeconfiguration',
            name='cluster',
            field=models.CharField(default='', max_length=100, verbose_name='VMware Cluster'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nsxedgeconfiguration',
            name='datastore',
            field=models.CharField(default='', max_length=100, verbose_name='VMware Datastore'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='nsxedgeconfiguration',
            name='folder_path',
            field=models.CharField(blank=True, help_text='Location where new edge appliances will be deployed.', max_length=100, null=True, verbose_name='VMware Folder Path'),
        ),
        migrations.AddField(
            model_name='nsxedgeconfiguration',
            name='resource_pool',
            field=models.CharField(default='', max_length=100, verbose_name='VMware Resource Pool'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='nsxedgeconfiguration',
            name='cli_password',
            field=models.CharField(max_length=100, verbose_name='CLI Password'),
        ),
        migrations.AlterField(
            model_name='nsxedgeconfiguration',
            name='cli_username',
            field=models.CharField(default='cloudbolt', max_length=100, verbose_name='CLI Username'),
        ),
    ]
