# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-04-21 00:14
from __future__ import unicode_literals

from django.db import migrations


def remove_invalid_cfvs(apps, schema_editor):
    """
    Delete any CFVs that reference NSXEdge or NSXScope instances that no longer
    exist.
    """
    CustomFieldValue = apps.get_model('orders', 'CustomFieldValue')
    NSXEdge = apps.get_model('nsx', 'NSXEdge')
    NSXScope = apps.get_model('nsx', 'NSXScope')

    edge_cfvs = CustomFieldValue.objects.filter(field__type='NSXE')
    for cfv in edge_cfvs:
        if not NSXEdge.objects.filter(id=cfv.int_value).exists():
            cfv.delete()

    scope_cfvs = CustomFieldValue.objects.filter(field__type='NSXS')
    for cfv in scope_cfvs:
        if not NSXScope.objects.filter(id=cfv.int_value).exists():
            cfv.delete()


class Migration(migrations.Migration):

    dependencies = [
        ('nsx', '0004_auto_20180418_2222'),
    ]

    operations = [
        migrations.RunPython(remove_invalid_cfvs, migrations.RunPython.noop)
    ]
