# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-04-30 22:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('externalcontent', '0012_duplicate_osbas_in_multiple_rhs'),
        ('resourcehandlers', '0011_resourcehandler_enable_terminal_feature'),
        ('infrastructure', '0038_auto_20180625_2145'),
    ]

    operations = [
        migrations.CreateModel(
            name='DimensionDataNetworkDomainVlan',
            fields=[
                ('resourcenetwork_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resourcehandlers.ResourceNetwork')),
                ('network_domain_id', models.CharField(max_length=50)),
            ],
            options={
                'verbose_name': 'Dimension Data VLAN',
                'abstract': False,
            },
            bases=('resourcehandlers.resourcenetwork',),
        ),
        migrations.CreateModel(
            name='DimensionDataOSBuildAttribute',
            fields=[
                ('osbuildattribute_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='externalcontent.OSBuildAttribute')),
            ],
            options={
                'verbose_name': 'Dimension Data Build Attribute',
                'abstract': False,
            },
            bases=('externalcontent.osbuildattribute',),
        ),
        migrations.CreateModel(
            name='DimensionDataResourceHandler',
            fields=[
                ('resourcehandler_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='resourcehandlers.ResourceHandler')),
                ('org_id', models.CharField(blank=True, max_length=255, null=True)),
            ],
            options={
                'verbose_name': 'Dimension Data resource handler',
                'abstract': False,
            },
            bases=('resourcehandlers.resourcehandler',),
        ),
        migrations.CreateModel(
            name='DimensionDataServerInfo',
            fields=[
                ('server', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, primary_key=True, serialize=False, to='infrastructure.Server')),
                ('network_id', models.CharField(max_length=50)),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
