# -*- coding: utf-8 -*-
# Generated by Django 1.11.22 on 2019-11-07 18:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('waffle', '0003_update_strings_for_i18n'),
    ]

    operations = [
        migrations.CreateModel(
            name='Feature',
            fields=[
                ('switch_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='waffle.Switch')),
            ],
            options={
                'abstract': False,
            },
            bases=('waffle.switch',),
        ),
    ]
