# Generated by Django 2.2.12 on 2020-05-20 22:48

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('itsm', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ServiceNowITSM',
            fields=[
                ('itsm_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='itsm.ITSM')),
                ('app_id', models.CharField(help_text='App ID of the ServiceNowITSM instance', max_length=50)),
                ('created_at', models.DateTimeField(default=datetime.datetime.now)),
                ('updated_at', models.DateTimeField(default=datetime.datetime.now)),
            ],
            options={
                'abstract': False,
            },
            bases=('itsm.itsm',),
        ),
        migrations.CreateModel(
            name='CMDBData',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmdb_ci_field', models.CharField(max_length=255)),
                ('cloudbolt_ci_value', models.TextField(blank=True, null=True, verbose_name='Cloudbolt Object Value')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cmdb', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='itsm.CMDB')),
            ],
        ),
    ]
