# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-18 23:14
from __future__ import unicode_literals

import cb_secrets.fields
import common.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('siem', '0003_auto_20190718_2313'),
    ]

    operations = [
        migrations.CreateModel(
            name='SplunkConf',
            fields=[
                ('siemprovider_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='siem.SIEMProvider')),
                ('username', models.CharField(help_text='Administrator username for local SplunkForwarder instance.', max_length=50, verbose_name='Local Username')),
                ('password', cb_secrets.fields.EncryptedPasswordField(help_text='Administrator password for local SplunkForwarder instance.', verbose_name='Local Password')),
                ('installer_path', models.CharField(help_text='Path to SplunkForward tarball (.tgz) file on this server.', max_length=255, verbose_name='Installer Path')),
                ('indexer_hostname', models.CharField(help_text='Hostname / IP address of the Splunk receiving indexer (remote server).', max_length=255, verbose_name='Indexer Hostname / IP Address')),
                ('indexer_listen_port', models.IntegerField(null=True, validators=[common.validators.is_only_digits], verbose_name='Listening Port, Receiving Indexer')),
                ('deployment_hostname', models.CharField(help_text='Hostname / IP address of the Splunk deploymer server (remote server).', max_length=255, verbose_name='Deployment Server Hostname / IP Address')),
                ('deployment_management_port', models.IntegerField(null=True, validators=[common.validators.is_only_digits], verbose_name='Management Port, Deployment Server')),
                ('remote_username', models.CharField(help_text='Administrator username for Splunk receiving indexer (remote server).', max_length=255, verbose_name='Remote Username')),
                ('remote_password', cb_secrets.fields.EncryptedPasswordField(help_text='Administrator password for Splunk receiving indexer (remote server).', verbose_name='Remote Password')),
                ('timezone', models.CharField(default='UTC', max_length=50, verbose_name='Time Zone')),
                ('local_splunk_bin_path', models.CharField(max_length=255)),
                ('remote_splunk_bin_path', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': 'Splunk Universal Forwarder',
                'abstract': False,
            },
            bases=('siem.siemprovider',),
        ),
    ]
