# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-19 00:35
from __future__ import unicode_literals

import cb_secrets.fields
import common.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('splunk', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='splunkconf',
            name='deployment_hostname',
            field=models.CharField(help_text='Hostname / IP address of the Splunk Deployment Server (remote server).', max_length=255, verbose_name='Deployment Server Hostname / IP Address'),
        ),
        migrations.AlterField(
            model_name='splunkconf',
            name='deployment_management_port',
            field=models.IntegerField(help_text='Management Port on the Splunk Deployment Server (remote server).', null=True, validators=[common.validators.is_only_digits], verbose_name='Management Port'),
        ),
        migrations.AlterField(
            model_name='splunkconf',
            name='indexer_hostname',
            field=models.CharField(help_text='Hostname / IP address of the Splunk Receiving Indexer (remote server).', max_length=255, verbose_name='Indexer Hostname / IP Address'),
        ),
        migrations.AlterField(
            model_name='splunkconf',
            name='indexer_listen_port',
            field=models.IntegerField(help_text='Listening Port on the Splunk Receiving Indexer (remote server).', null=True, validators=[common.validators.is_only_digits], verbose_name='Listening Port'),
        ),
        migrations.AlterField(
            model_name='splunkconf',
            name='installer_path',
            field=models.CharField(help_text='Path to SplunkForwarder tarball (.tgz) file on this server.', max_length=255, verbose_name='Installer Path'),
        ),
        migrations.AlterField(
            model_name='splunkconf',
            name='remote_password',
            field=cb_secrets.fields.EncryptedPasswordField(help_text='Administrator password for Splunk Receiving Indexer (remote server).', verbose_name='Remote Password'),
        ),
        migrations.AlterField(
            model_name='splunkconf',
            name='remote_username',
            field=models.CharField(help_text='Administrator username for Splunk Receiving Indexer (remote server).', max_length=255, verbose_name='Remote Username'),
        ),
    ]
