# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-22 23:09
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splunk', '0003_remove_splunkconf_username'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='splunkconf',
            name='timezone',
        ),
    ]
