# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-07-25 16:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('splunk', '0005_auto_20190723_2247'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='SplunkConf',
            new_name='SplunkProvider',
        ),
    ]
