# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-06 01:02
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0003_auto_20161213_2338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puppetconf',
            options={'verbose_name': 'Puppet Open Source'},
        ),
    ]
