# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-20 23:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('puppet', '0004_auto_20170106_0102'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='puppetreport',
            options={'get_latest_by': 'time', 'ordering': ['time']},
        ),
    ]
