# Generated by Django 2.2.16 on 2021-02-07 11:42

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Tenant',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(max_length=255, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name='TenantPermission',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True, verbose_name='Name')),
                ('label', models.CharField(max_length=255, verbose_name='Label')),
                ('description', models.TextField(blank=True, help_text='Optional. Explain purpose or details about this permission.', null=True, verbose_name='Description')),
            ],
        ),
        migrations.CreateModel(
            name='TenantRole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('label', models.CharField(help_text="This is what users see. E.g. 'Tenant Admin'", max_length=255)),
                ('name', models.CharField(help_text="Internal identifier for this role. Names must be unique. E.g. 'tenant_admin'", max_length=255, unique=True)),
                ('description', models.TextField(blank=True, help_text='Optional. Explain purpose or details about this role.', null=True)),
                ('permissions', models.ManyToManyField(blank=True, to='tenants.TenantPermission')),
            ],
            options={
                'ordering': ('label',),
            },
        ),
    ]
