# -*- coding: utf-8 -*-
# Generated by Django 1.9.12 on 2017-01-06 00:56
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0002_auto_20160829_2059'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='connectorconf',
            options={'ordering': ['name']},
        ),
        migrations.RemoveField(
            model_name='connectorconf',
            name='connector',
        ),
        migrations.DeleteModel(
            name='Connector',
        ),
    ]
