# Generated by Django 2.2.16 on 2021-02-13 01:12

import common.mixins
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0003_auto_20170106_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectorconf',
            name='global_id',
            field=models.CharField(default=common.mixins.get_global_id_chars, help_text='Identifier that can be used to access this object through the API across instances.', max_length=16, verbose_name='Global ID'),
        ),
    ]
