# Generated by Django 2.2.16 on 2021-02-18 10:07

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('tenants', '0001_initial'),
        ('connectors', '0003_auto_20170106_0056'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectorconf',
            name='tenant',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='tenants.Tenant'),
        ),
    ]
