# Generated by Django 2.2.16 on 2021-02-26 14:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('connectors', '0004_connectorconf_tenant'),
        ('connectors', '0005_set_global_id_for_connectors'),
    ]

    operations = [
    ]
